### ISSUE TITLE
coverlet.msbuild is not accurate for .Net 5.0

### ISSUE THREAD

**Issue by dpomBF** [MicrosoftDocs/azure-devops-docs#10009]
It seems like coverlet.msbuild does not give correct Code Coverage results for .Net 5.0.
Please add that as a note after instructing the reader to reference coverlet.msbuild. It does work with coverlet.collector, but I haven't been able to get it to integrate smoothly with the dev-op pipeline. I still can't show the Code Coverage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@dpomBF I'll update the docs. For reference, this pipeline yaml worked for me. I had to use the `UseDotNet@2` and `DotNetCoreCLI@2` tasks. 

```yaml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
    publishTestResults: true
    projects: 'MyTestLibrary' # update with your test project directory

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

```
