### ISSUE TITLE
even if globbing returns single file task reports warning

### ISSUE THREAD

**Issue by cicorias** [MicrosoftDocs/azure-devops-docs#10030]
[Enter feedback here]

the warning that gets generated is invalid
`##[warning]Multiple file or directory matches were found. Using the first match:`

the globbing pattern used is 

```
    - task: PublishCodeCoverageResults@1
      name: 'coverage'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
        failIfCoverageEmpty: false
      displayName: 'publish code coverage'
```
I verify there is one file with:
```
    - task: CmdLine@2
      inputs:
        script: 'ls -alt $(Agent.TempDirectory)/**/coverage.cobertura.xml'
      displayName: 'list coverage xml files'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**
