### ISSUE TITLE
[Bug] Docker-compose up exception on v0.181.0

### ISSUE THREAD

**Issue by ming-tsai** [MicrosoftDocs/azure-devops-docs#10031]
Hi there,
I got an exception when I'm creating the new release on the new version of docker-compose but it works on version `0.175.0`, I couldn't find out any documentation about this issue.

**YAML file**
```yml
#Your build pipeline references a secret variable named ‘CONNECTION_STRING’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references a secret variable named ‘JWT_KEY’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘AZ_NUGET_PWD’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘AZ_NUGET_USR’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘AZ_NUGET_PWD’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

variables:
  JWT_ISSUER: 'http://120.0.0.1/issues'

steps:
- task: DockerCompose@0
  displayName: 'Build and Run Docker Image'
  inputs:
    dockerComposeFile: '$(System.DefaultWorkingDirectory)/Hydra/docker-compose.dev.yml'
    dockerComposeFileArgs: |
     API_CONTEXT=hydra-dev
     CONNECTION_STRING=$(CONNECTION_STRING)
     JWT_KEY=$(JWT_KEY)
     JWT_ISSUER=$(JWT_ISSUER)
     AZ_NUGET_PWD=$(AZ_NUGET_PWD)
    qualifyImageNames: false
    dockerComposeCommand: 'up --build --force-recreate --detach'
    arguments: '--build-arg AZ_NUGET_USR=$(AZ_NUGET_USR) --build-arg AZ_NUGET_PWD=$(AZ_NUGET_PWD)  --build-arg ASPNETCORE_ENVIRONMENT=Development'
```
**Logs:**
[v0.175.0.log](https://github.com/MicrosoftDocs/azure-devops-docs/files/5843541/v0.175.0.log)
[v0.180.0.log](https://github.com/MicrosoftDocs/azure-devops-docs/files/5843538/v0.180.0.log)
