### ISSUE TITLE
Loop through Azure Devops parameters. The script example is not valid

### ISSUE THREAD

**Issue by pecoult** [MicrosoftDocs/azure-devops-docs#10067]
Hi, 

I was using this doc to learn how to handle parameters and I found a small issue with one of the examples.

Chapter: Loop through parameters (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script#loop-through-parameters)

The script example is not correct.
```
...
steps: 
- ${{ each parameter in parameters }}:
  - script: echo ${{ parameters.Key }} 
  - script: echo ${{ parameters.Value }}
```
For both echos, the variable name should be 'parameter' instead of 'parameters'.

Cordially,

Romain P.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
This looks like it's been fixed. Here's the current text:

```
steps: 
- ${{ each parameter in parameters }}:
  - script: echo ${{ parameter.Key }} 
  - script: echo ${{ parameter.Value }}
```
