### ISSUE TITLE
Provided method for Linux is not working as per examples

### ISSUE THREAD

**Issue by JFolberth** [MicrosoftDocs/azure-devops-docs#10070]
Trying to run some az pipeline commands.  First tried using the AzureCLI task but that did not work due to authentication so found this.

This process also does not work with:
WARNING: Failed to store PAT using keyring; falling back to file storage.
WARNING: You can clear the stored credential by running az devops logout.
WARNING: Refer https://aka.ms/azure-devops-cli-auth to know more on sign in with PAT.

When taking the Linux code exactly as is.

Used `ubuntu-latest' and then tried ubuntu-16.04 like documentation stated same result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9480b69-ca1f-55bc-8505-49c51d9f205e
* Version Independent ID: 03df29bf-108d-6ffc-bb3e-b29fb8a1e46c
* Content: [Azure DevOps CLI in Azure Pipeline YAML - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops)
* Content Source: [docs/cli/azure-devops-cli-in-yaml.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/azure-devops-cli-in-yaml.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by JFolberth** [comment]
Any update on this?  I am trying to use this method as a way to lever az pipeline commands since it seems they are not natively working with the Azure CLI task https://github.com/Azure/azure-cli-extensions/issues/2935#issuecomment-770909291

**Comment by KathrynEE** [comment]
@JFolberth - I've contacted the product team to alert them to this issue. You might want to post your problem on  our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html). YOu may get a solution to your specific problem faster.

**Comment by KathrynEE** [comment]
@JFolberth - I'm going to close this issue for now. I will continue to work with the product team to update the article to clarify the problems you are having.

**Comment by JFolberth** [comment]
@KathrynEE  Please don't close this as it has been recognized as an issue in the community forums. https://developercommunity.visualstudio.com/t/Unable-to-run-az-pipeline-commands-withi/1329403

**Comment by KathrynEE** [comment]
@JFolberth - reopening.

**Comment by steved0x** [comment]
@JFolberth I am making some updates to the article, and I am reviewing your issue. I am able successfully run the provided pipeline using all 3 Linux hosted agent images, but I do get those same warnings, which I understand refer to storing the token, and that it is storing it in file storage as a fallback, and to clear it, you can run az devops logout at the conclusion of your az devops commands. However, the VM instances are single use per job and torn down when the job completes.

I am publishing an update today with a simplified pipeline (although it still has most of the same bits and the warnings you mention), so that won't resolve your issue.

Is that your issue, the warnings? Or does the pipeline fail when you attempt `az devops login`?

I will try and get more information on the warnings, and please let me know if it is the pipeline failing that is the issue, or the warnings combined with a successful execution of the az devops login step?

Thank you

Steve

**Comment by steved0x** [comment]
@JFolberth I found that I can eliminate the warnings by skipping `az devops login` and instead use the `AZURE_DEVOPS_EXT_PAT` environment variable, which is known to Azure DevOps CLI extension, like this:

```
- bash: |
    az pipelines build list
    git pr list
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
  displayName: 'Show build list and PRs'
```

I'm still gathering more information and will report back.

**Comment by steved0x** [comment]
#assign steved0x

**Comment by JFolberth** [comment]
Hey @steved0x  the issue it appears is azure devops commands won't work with ADO azure hosted agents. Here is a the community ticket I opened up.
https://developercommunity.visualstudio.com/t/Unable-to-run-az-pipeline-commands-withi/1329403

What I am trying to do in a pipeline is access ADO variable groups programmatically but both the CLI commands and native Powershell commands won't authenticate appropriately.

**Comment by JFolberth** [comment]
Hey @steved0x  Any luck or update on this one?

**Comment by steved0x** [comment]
@JFolberth I am updating the article to account for the latest hosted images (windows-2022 and macos-11), but I will run it using a matrix that uses all hosted agent images. I will try and add a step that access variable groups. I have found some cases where the Azure DevOps CLI doesn't have all the functionality of the REST API, for example I wanted to create a work item and link it to a pipeline run. I could do it in REST API but not Azure DevOps CLI. I filed an issue here: https://github.com/Azure/azure-devops-cli-extension/issues/1157. 

Have you investigated the repo before: https://github.com/Azure/azure-devops-cli-extension/issues

I did a brief search but didn't see anything reported about variable groups (but then it was a quick search) once I try to run my examples, I may have some better keywords for searching.

**Comment by steved0x** [comment]
I was able to run some variable groups commands (list) in my pipeline and I saw this note in the pipeline run details for that step:

> WARNING: Command group 'pipelines variable-group' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

If you are having trouble with Azure DevOps CLI and variable groups, it may be a result from this?

I have updated the article to show using the AZURE_DEVOPS_EXT_PAT approach which does not give any wanrings on Linux hosted agents, vs piping the PAT into az devops login. I believe the warnings are coming from the different ways that the linux agents are attempting to persist the context for the login across different steps, and I believe it falls back to an alternate storage mechanism. I get the same thing when running az devops commands in Azure Cloud Shell.

I was able to retrieve the variable group id of a variable group (in my example the group is named `Fabrikam-2021` by using the following. My approach is a little different, I embedded the name of the variable group vs retrieving it from a parameter, and since my query only returns 1 variable group, I can get the id using `[].id` vs using the name like in your example. If your command is running locally but not in the pipeline, you could change your variable assignment to use this syntax:

```
- bash: echo "##vso[task.setvariable variable=variableGroupId]$(az pipelines variable-group list --group-name Fabrikam-2021 --query [].id -o tsv)"
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
  displayName: 'Get Fabrikam-2021 variable group id'
```

```
variables:
- name: variableGroupId

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- bash: az --version
  displayName: 'Show Azure CLI version'

# Azure DevOps CLI extension call that does not require login or credentials
# since it configures the local environment
- bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
  displayName: 'Set default Azure DevOps organization and project'

- bash: az pipelines variable-group list --output table
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
  displayName: 'List variable groups'

- bash: echo "##vso[task.setvariable variable=variableGroupId]$(az pipelines variable-group list --group-name Fabrikam-2021 --query [].id -o tsv)"
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
  displayName: 'Get Fabrikam-2021 variable group id'

- bash: echo $(variableGroupId) 
  displayName: 'Display Fabrikam variable group id'
```
