### ISSUE TITLE
Runtime Params: FAQ question is not answered actually answered 

### ISSUE THREAD

**Issue by omzevall** [MicrosoftDocs/azure-devops-docs#10102]
The question in the FAQ is: Can parameters be set based on variables?

The answer begins, "There are times when it may be useful to set parameters to values based on variables." But then the rest of the answer briefly touches on predefined variables and gives an example used for pipeline templates. Additionally, the example does not contain any runtime parameters (or any parameters at all).

The question does not seem to be answered, but it would certainly be helpful to know how to set parameters based on variables (especially when triggering one pipeline by another).

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by nvaytet** [comment]
To add a little more information, I think we would like to know if/how we can do something like
```yaml
- jobs:
    template: build.yml
      parameters:
        image: 'ubuntu-20.04'
        ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          use_special_pr_flags: true
        ${{ if not(eq(variables['Build.Reason'], 'PullRequest')) }}:
          use_special_pr_flags: false
```
where `use_special_pr_flags` is a parameter in `build.yml`.

Of course this is a simplification, and this particular example can probably be achieved in some other way (by checking for `Build.Reason` inside `build.yml`) but the question is **can parameters for a template be set depending on the value of a user-defined or system variable**?

Something we also tried was use a dict to select params. For example, selecting different conda channels for a build environment depending on whether it is trying to merge into the `main` branch or into a `dev` branch:
```yaml
parameters:
- name: conda_channels
  type: object
  default:
    main: '--channel my/conda/project/main'
    dev: '--channel my/conda/project/dev'

trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: stages.yml
  parameters:
    conda_channels: ${{ parameters.conda_channels['System.PullRequest.TargetBranch'] }}
```

We tried many different syntaxes
- `${{ parameters.conda_channels[System.PullRequest.TargetBranch] }}`
- `${{ parameters.conda_channels[$(System.PullRequest.TargetBranch)] }}` -> does not parse
- `${{ parameters.conda_channels[${{ variables.System.PullRequest.TargetBranch}}] }}` -> does not parse

etc.. but no success.

Many thanks for any help.
