### ISSUE TITLE
How to reference these variables in pipelines?

### ISSUE THREAD

**Issue by edrandall** [MicrosoftDocs/azure-devops-docs#10176]
[Enter feedback here]
It's unclear how to reference these variables in pipelines.
Take for example Build.RequestedForId
If I use ${{ }} in a simple bash script:
```
          - task: Bash@3
            displayName: 'BuildInfo'
            inputs:
              targetType: 'inline'
              script: |
                echo "Build user: ${{ Build.RequestedForId }}"
```

This results in an error:  `Unrecognized value: 'Build'. Located at position nn within expression:...`
Page should make it clear exactly where and how they may be used, without the reader having to hunt for nuggets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#identity_values)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
