### ISSUE TITLE
Error in endpoints example code using a service connection on container jobs

### ISSUE THREAD

**Issue by brooke-hamilton** [MicrosoftDocs/azure-devops-docs#10181]
In this section of the [Container Jobs doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#endpoints), the example code for the `image` setting has an extra segment. The example is this: `image: myprivate/registry:ubuntu1604` but should be this: `image: registry:ubuntu1604`. The `myprivate/` part of the image does not correspond to anything and causes an exception when running. Below is the complete example:

The page currently shows this:
```YAML
container:
  image: myprivate/registry:ubuntu1604
  endpoint: private_dockerhub_connection
```

The corrected example should be this:
```YAML
container:
  image: registry:ubuntu1604
  endpoint: private_dockerhub_connection
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
