### ISSUE TITLE
Coverlet sample does not work with new versions of coverlet.collector

### ISSUE THREAD

**Issue by ErikWulms** [MicrosoftDocs/azure-devops-docs#10218]
When using newer versions of coverlet.collector it seems that the example code produces no code coverage. 
It requires the use of 
`dotnet test --collect:"XPlat Code Coverage"`
instead of
`dotnet test /p:CollectCoverage=true`

(https://github.com/coverlet-coverage/coverlet#usage)

I could not find whether it was still possible to specify a location for the coverlet output.
Anyways, in devops it put it in the temp folder by default.
For me this piece of code does the trick:

```
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
    publishTestResults: true
    projects: 'MyTestLibrary' # update with your test project directory

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
```

See also #10009 and #8644
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
