### ISSUE TITLE
checked out multi repositories in runOnce ->preDeploy can't be reused in deploy,postRouteTraffic,onSucess,OnFailure

### ISSUE THREAD

**Issue by cforce** [MicrosoftDocs/azure-devops-docs#10233]
I checkout scripts from two repositories which i use as well for building the docker image from in deploy in the second next stage. using below dedicated jobs. In the predeploy i am checking out (again) the two repositories needed. It seems like neither in the 
deploy,postRouteTraffic,on: failure:, on:success: jobs i can reuse this checkout repositories from the predeploy job.
It look like each of these jobs is getting a fresh new working directory and therfore the repo's checked out scripts are not localized on any other job of runOnce: afterwards. This behavior is completely unexpected and i would call it a bug.
Why shall i need to checkout the same repos out 5 times for jobs which are 100% serial executed and completly dependent on each. Also Doing that 5 times i could even get another revision of my branch, can't i? DO i need to manual preserve revisionsids?
How do i  even make sure i get the same revision i used from the first stage where i have built the container based on the very same repos as well?
```
  strategy:
      runOnce:
        ##################
        preDeploy:
          steps:
          - checkout: source
            clean: false
            persistCredentials: true
            displayName: checkout application source
            path: source
          - checkout: pipelinescripts
            clean: false
            displayName: checkout scripts
            path: pipelinescripts
  ...
```
