### ISSUE TITLE
Schedule pipeline using cron trigger on TAGS

### ISSUE THREAD

**Issue by kasdihacene** [MicrosoftDocs/azure-devops-docs#10247]
I want to schedule my pipeline to generate a new tag every day at 06:00.
I want to do something like:

````yaml
schedules:
- cron: '0 0 6 1/1 * ? *'
  displayName: 'Tag Automatic Deployment'
  branches:
    include:
      - refs/tags/APP-V1
  always: true
```

Is it possible to schedule a yaml pipeline using tags?
