### ISSUE TITLE
Example Script for Secure File Doesn't Work

### ISSUE THREAD

**Issue by jamsoft** [MicrosoftDocs/azure-devops-docs#10287]
I followed the example code to the letter and DevOps wouldn't even try to run the pipeline. Saying it was invalid. Here's that code:

```
- task: DownloadSecureFile@1
  name: downloadKeyStore
  displayName: 'Download Android Debug Key Store'
  inputs:
    secureFile: 'debugkeystoreFile'

- task: AndroidSigning@3
  displayName: 'Sign android binaries'
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: '$(downloadKeyStore.secureFilePath)'
    apksignerKeystorePassword: '$(keystorePassword)'
    apksignerKeystoreAlias: '$(keystorePassword)'
    apksignerKeyPassword: '$(keystorePassword)'
```

However, if I use this code, which disagrees with the docs, it all works.

```
- task: DownloadSecureFile@1
  name: downloadKeyStore
  displayName: 'Download Android Debug Key Store'
  inputs:
    secureFile: 'debugkeystoreFile'

- task: AndroidSigning@3
  displayName: 'Sign android binaries'
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'debugkeystoreFile'
    apksignerKeystorePassword: '$(keystorePassword)'
    apksignerKeystoreAlias: '$(keystorePassword)'
    apksignerKeyPassword: '$(keystorePassword)'
```
