### ISSUE TITLE
Warning when gathering python test coverage

### ISSUE THREAD

**Issue by fbjorn** [MicrosoftDocs/azure-devops-docs#10284]
I followed your example from "Publish code coverage results" and included this step to my pipeline:
```yaml
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
```

Then Azure Pipelines warned me with such message:
```
##[warning]Ignoring coverage report directory with Html content as we are auto-generating Html content
```

I tried to remove the line with `reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'` and the warning has gone 👍 
So I suppose you can remove it from the documentation
Also proposed change:
from:
```
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
```

to:
```
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
```
Cause no HTML generation required anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/python.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/python.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by juliakm** [comment]
@fbjorn Thank you for noting this. I'll push an update to the docs shortly. These are the updated tasks that worked for me. 

```yaml
- script: |
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
  displayName: 'pytest'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
```
