### ISSUE TITLE
Document the convertToJson function

### ISSUE THREAD

**Issue by hbuckle** [MicrosoftDocs/azure-devops-docs#10311]
Turns out there is a `convertToJson` function that converts a yaml object to a json string

```yaml
parameters:
  - name: complex
    type: object
    default:
      this_is:
        a_complex: object
        with:
          - complex
          - properties
stages:
  - stage: stage1
    jobs:
      - job: job1
        steps:
          - pwsh: |
              Write-Host "${{ convertToJson(parameters.complex) }}"
```

This should be documented (along with any other hidden functions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
