### ISSUE TITLE
Azure File Copy for Mac and Linux agent do not work

### ISSUE THREAD

**Issue by ankku** [MicrosoftDocs/azure-devops-docs#10327]
I have a task in my Yaml pipeline to upload artifacts in Blob Storage. I was able to do it for Windows agent using AZ File Copy task(shown below) but it failed for Linux and Mac agent. I was suggested to use Azure CLI task instead to make it work with Linux and Mac agent. Below is the Azure Cli task which I have written but it fails saying error as _"[error]Script failed with error: Error: Unable to locate executable file: 'powershell'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable. "_

I would like to know if this is a known bug or if formation of Azure Cli task is not proper and if Azure File Copy does not work for Mac and Linux. here are both tasks.

```
- task: AzureFileCopy@2
          displayName: 'Publish to Blob'
          inputs:
            SourcePath: '$(Build.SourcesDirectory)/ABC-$(osSuffix)'
            azureSubscription: 'Azure CICD'
            Destination: AzureBlob
            storage: '$(BlobStorageAccount)'
            ContainerName: '$(BlobContainer)'
            BlobPrefix: '$(BlobPrefix)/ABC/$(DeploymentVersion)/ABC-$(osSuffix)'
            AdditionalArgumentsForBlobCopy: '/V /S'
            outputStorageUri: BlobUri
            outputStorageContainerSasToken: BlobSASToken



-task: AzureCLI@2
          displayName: PublishToBlob
          inputs:
            azureSubscription: 'Azure CICD'
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: 'az storage blob upload -f '$(Build.SourcesDirectory)/ABC-$(osSuffix)' -c '$(BlobContainer)' -n '$(BlobPrefix)/ABC/$(DeploymentVersion)/ABC-$(osSuffix)'' 
```
