### ISSUE TITLE
document conditions for variables

### ISSUE THREAD

**Issue by burtonrodman** [MicrosoftDocs/azure-devops-docs#10336]
I am able to apply conditions to variables (using 2 syntax below) but can't find this in the official documentation:

(name: value syntax)
```
variables:
  MY_VARIABLE: VALUE
  ${{ if ne( parameters['ENVIRONMENT_OVERRIDE'], 'use_default' ) }}:
    ENVIRONMENT_NAME: ${{ parameters.ENVIRONMENT_OVERRIDE }}
```

(list syntax)
```
variables:
- group: 'my-variable-group'
- name: MY_VARIABLE
  value: VALUE
- ${{ if ne( parameters['ENVIRONMENT_OVERRIDE'], 'use_default' ) }}:
  - name: ENVIRONMENT_NAME
    value: ${{ parameters.ENVIRONMENT_OVERRIDE }}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
