### ISSUE TITLE
Custom npm command targetting script outside working dir fails.

### ISSUE THREAD

**Issue by mbelt** [MicrosoftDocs/azure-devops-docs#10377]
Regarding npm command tasks defined here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops

Directory structure of a repository with multiple NPM projects.
```
./ 
  ProjectA/
  ProjectB/
    package.json
      myCommand: node ../Common/script.js
  Common/
    script.js # uses yargs.
```
Projects in this repository use common node scripts for common tasks. Not conventional, but works fine locally.
```
- task: Npm@1
  displayName: 'xxx'
  inputs:
    command: custom
    workingDir: ProjectB
    verbose: false
    customCommand: 'run myCommand'
```

Results in
```
node ../script.js "--arg1" "***" "--arg2" "***" 
Error: Cannot find module 'yargs'
```
Error does not happen when script.js is somewhere under ProjectB/.
