### ISSUE TITLE
Need more documentation on parallel stages order

### ISSUE THREAD

**Issue by quasarea** [MicrosoftDocs/azure-devops-docs#10403]
In below example I want my Validate Security to be displayed first, then Validate Quality followed by Validate Coverage
![image](https://user-images.githubusercontent.com/10334982/112245372-a80eac80-8c48-11eb-8fc4-541c757be2c3.png)

Yaml is defined in exactly that order:
```
  - stage: ValidateSecurity
    displayName: Validate Security
    dependsOn:
      - Analyse
    jobs:
      - template: security-report.yml

  - stage: ValidateQuality
    displayName: Validate Quality
    dependsOn:
      - Analyse
      - Cover
      - Package
    jobs:
      - template: check-quality.yml

  - stage: ValidateCoverage
    displayName: Validate Coverage
    dependsOn: Cover
    jobs:
      - template: coverage.yml
```

But it still displays stages in not my designed order. Is there some other parameter or evaluation not documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322215c-8025-4f21-0700-7dfa7dc5c46e
* Version Independent ID: 141fcdbb-8394-525b-bb29-eff9a693a9c4
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
