### ISSUE TITLE
Documentation for tag references

### ISSUE THREAD

**Issue by paulaustin-automutatio** [MicrosoftDocs/azure-devops-docs#10460]
Can you provide examples of how to use git tag references or even full references as the ref for a repository?

```
variables:
  myRef: $[ variables['Build.SourceBranch'] ]
  
resources:
  repositories:
  - repository: repo1
    type: github
    endpoint: GitHubServiceConnection
    name: project/repo
    path: repo1
    ref: $(myRef)
````

If run with the master branch it gives the following error.

The pipeline is not valid. Could not get the latest source version for repository project/repo hosted on https://github.com/ using ref refs/heads/refs/heads/master.

Basically what I want to be able to do is have a if statement on the variable that says, if branch=master then use the Build.SourceBranch, else if it's a tag then use the ref with a prefix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@paulaustin-automutatio Thank you for your question. We'll look into the document, but in the meantime, consider these references: 

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by steved0x** [comment]
You could use a [template expression](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/template-expressions?view=azure-devops) since that variable is available in templates. Something like this:

```
variables:
  ${{ if eq(variables['Build.SourceBranch'], 'master') }}:
    myRef: ${{ variables['Build.SourceBranch'] }}
  ${{ else }}:
    myRef: 'something else'

  
resources:
  repositories:
  - repository: repo1
    type: github
    endpoint: GitHubServiceConnection
    name: project/repo
    path: repo1
    ref: $(myRef)
```
