### ISSUE TITLE
uses: keyword is not explained, does not work as described

### ISSUE THREAD

**Issue by jwefers** [MicrosoftDocs/azure-devops-docs#10461]
The article about Azure Repos Git mentions the `uses` Keyword (and only this page), as a way to state that i am gonna use that repo? But how?

My expectation from reading it, is that similar to a checkout step with `persistCredentials`, that an http auth extraheader gets put into the git config, without actually needing to do a checkout step.

However, the article does not into detail, nor does it work as described. The article says:

```yml
# Or you can reference it with a uses statement in the job
uses:
- FabrikamTools # Repository reference to FabrikamTools
```

so i tried
a)
```yml
job:
  uses:
    - OtherProject/OtherRepo
```
does not work, the pipeline expects an object for `uses`, contrary to the docs. Autocomplete tells me, `repositories` works.
```yml
resources:
  repositories:
    - repository: namedRepoReference
      type: git
      name: OtherDevOpsProject/SomeRepo
...
      - job: MyJob
        uses:
          repositories:
            - namedRepoReference
```

However, doing a git clone of `https://OurDevOps@dev.azure.com/OurDevOps/OtherDevOpsProject/_git/SomeRepo` fails, no auth.

So what exactly is this keyword doing? And how do i use it correctly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@jwefers Thanks for your question. We'll look into updating the article. In the mean time, consider these references:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by GaTechThomas** [comment]
We ran into this as well when we have terraform code that references git (via "git::" syntax).

Try doing the same thing you describe, but with this instead:

`git clone of https://$(System.AccessToken)@dev.azure.com/OurDevOps/OtherDevOpsProject/_git/SomeRepo`

**Comment by jwefers** [comment]
ding dong

**Comment by jwefers** [comment]
ping

**Comment by GaTechThomas** [comment]
Maybe a opening a new issue that just references this one would get a new set of eyes on it.

**Comment by jwefers** [comment]
in what kind of company would that make a difference 😑

**Comment by GaTechThomas** [comment]
Not looking to troll, just to get something done. May be that this got lost in the shuffle, which happens at every company unfortunately.

**Comment by jwefers** [comment]
I would say, "sort by oldest unsolved" is something i expect this cloud bememoth to be able to do. but then again, OMIGOD and cosmos let me question my career niche sometimes

**Comment by TimShererWithAquent** [comment]
@steved0x For awareness. Just to see where we are on this one.

**Comment by jwefers** [comment]
:/

**Comment by GaTechThomas** [comment]
> I would say, "sort by oldest unsolved" is something i expect this cloud bememoth to be able to do. but then again, OMIGOD and cosmos let me question my career niche sometimes

There will _always_ be something on the list no matter the size of the company. If nothing remains on the list then it's a dead product. Sort by oldest unsolved will trend towards showing the least important items first. It's just the nature of it. 

The way to get it solved is to raise its importance. That's what we're doing right now.

**Comment by jwefers** [comment]
i agree, thats why i would not create a new issue as suggested

**Comment by jwefers** [comment]
@steved0x

**Comment by davisnw** [comment]
Related I think: https://stackoverflow.com/questions/73550047/creating-a-yaml-build-template-with-access-to-all-repositories

**Comment by davisnw** [comment]
When using `uses:`, the referenced repositories must have already been declared as `resources:`.
When `uses:` is used instead of `checkout`, the repository won't be locally checked out by the agent, but the access token can still access the repository, e.g. via REST api or script.

When "Limit job authorization scope to referenced Azure DevOps repositories" / "Protect access to repositories in YAML pipeline" is enabled, there is a limit of 20 referenced repositories, see:
- https://stackoverflow.com/questions/73550047/creating-a-yaml-build-template-with-access-to-all-repositories
- https://developercommunity.visualstudio.com/t/checking-out-more-than-20-repositories-in-yaml-pip/1521492

Example:

```yaml
resources:
  repositories:
  - repository: R1
    type: git
    name: MyDevOpsProject/R1
  - repository: R2
    type: git
    name: MyDevOpsProject/R2
  - repository: R3
    type: git
    name: MyDevOpsProject/R3
  - repository: Rnnn
    type: git
    name: MyDevOpsProject/Rnnn

jobs:
- job:
  pool: 'swimming'
  uses:
    repositories:
    - R1
    - R2
    - R3
    - Rnnn
  steps: ...
```
