### ISSUE TITLE
filepath bash script outputting a variable

### ISSUE THREAD

**Issue by dpstratascale** [MicrosoftDocs/azure-devops-docs#10504]
All the examples on how to pass a variable between jobs and stages involve inline scripts, there are no examples on filePath scripts (E.g., a bash script) outputting a variable that can be processed in later stages.

Testing the vso method in an inline script does not output a variable to a different stage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@dpstratascale You can pass an environmental variable to your Bash task to have it available in a script. Here's an example. When the variable is referenced in the same job, the job value wins. When the variable is referenced in a stage without a job definition, the stage variable valued gets passed.  I'll work on making this clearer in the docs. 

```sh
#simple-script.sh

echo $VAR_A
```

```yaml
#azure-pipelines.yml

variables:
  a: 'pipeline yaml'

stages:
- stage: one
  displayName: one
  variables:
  - name: a
    value: 'stage yaml'

  jobs:
  - job: A
    variables:
    - name: a
      value: 'job yaml'
    steps:
    - bash: echo $(a)  #outputs job yaml
    - task: Bash@3
      inputs:
        filePath: 'simple-script.sh'
      env: 
        VAR_A: $(a) #outputs job yaml

  - job: C
    steps:
    - task: Bash@3
      inputs:
        filePath: 'simple-script.sh'
      env: 
        VAR_A: $(a) #outputs stage-yaml
```

**Comment by dpstratascale** [comment]
@juliakm Thank you very much for your reply, the problem I saw is slightly different, for example:

```
#script-a.sh
MYVAR=test
echo "##vso[task.setvariable variable=MYVAR;isSecret=false;isOutput=true;]$MYVAR"
```

```
#script-b.sh
echo "$MYVAR"
```

```
#azure-pipelines.yml

stages:
- stage: one
   jobs:
  - job: A
    steps:
    - task: Bash@3
      inputs:
        filePath: 'script-a.sh'

- stage: two
   jobs:
  - job: B
    steps:
    - task: Bash@3
      inputs:
        filePath: 'script-b.sh'
      env:
         MYVAR: $[ stageDependencies.one.A.outputs['printvar.MYVAR'] ]
```
I found that when inside of a script (that is sourced through a filePath) the variable is not managed properly and shared between stages.

The examples posted are all referencing inline scripts, while there is no example with a filePath script.

**Comment by juliakm** [comment]
@dpstratascale Thanks for the example. I ran your code and found the same issue. I wonder if calling a variable defined in one file from a second file is not supported. I will check with the product team and follow-up.

**Comment by juliakm** [comment]
@dpstratascale The challenge we ran into is that you cannot pass a variable with `[]` syntax directly to the `env:` input for a task. Instead, you need to define the variable for stage and then pass that variable with macro syntax to the task. Here's what works for me. I'll work on updating the article.

```sh
## script-a.sh
echo "##vso[task.setvariable variable=sauce;isOutput=true]crushed tomatoes"
```

```sh
## script-b.sh
echo 'Hello file version'
echo $skipMe
echo $StageSauce
```  

```yaml
## azure-pipelines.yml
stages:

- stage: one
  jobs:
  - job: A
    steps:
    - task: Bash@3
      inputs:
          filePath: 'script-a.sh'
      name: setvar
    - bash: |
       echo "##vso[task.setvariable variable=skipsubsequent;isOutput=true]true"
      name: skipstep
  
- stage: two
  jobs:
  - job: B
    variables:
      - name: StageSauce
        value: $[ stageDependencies.one.A.outputs['setvar.sauce'] ]
      - name: skipMe
        value: $[ stageDependencies.one.A.outputs['skipstep.skipsubsequent'] ]
    steps:
    - task: Bash@3
      inputs:
        filePath: 'script-b.sh'
      name: fileversion
      env:
        StageSauce: $(StageSauce) # We do not expand [] vars, we need to predefine above
        skipMe: $(skipMe)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Hello inline version'
          echo $(skipMe) 
          echo $(StageSauce) 


```
