### ISSUE TITLE
Pipelines caching example doesn't properly quote the static string

### ISSUE THREAD

**Issue by jefgen** [MicrosoftDocs/azure-devops-docs#10500]
In the example given for caching on the page [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#use-cache-task) it says that the key string "yarn" is supposed to be a static string:

```
variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
       yarn
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages

- script: yarn --frozen-lockfile
```

[emphasis added in the quote below]

> In this example, the cache key contains three parts: **a static string ("yarn")**, the OS the job is running on since this cache is unique per operating system, and the hash of the yarn.lock file that uniquely identifies the set of dependencies in the cache.

However, in the previous section on the it has this tip/warning that static strings need to be wrapped with double-quotes:

> To avoid a path-like string segment from being treated like a file path, wrap it with double quotes, for example: "my.key" | $(Agent.OS) | key.file

In order for "yarn" to not be treated as a file path, I think the example should be updated to use this instead:

```
    key: '"yarn" | "$(Agent.OS)" | yarn.lock'
```

FWIW, we ran into this issue here when trying to setup caching with Azure pipelines: https://github.com/unicode-org/icu/pull/1694 
(Thanks to @daniel-ju for finding this issue.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#use-cache-task)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by daniel-ju** [comment]
FWIW, the docs say that key segments are treated as file paths if they contain the `.` character:

> This file must exist at the time the task is run. Keep in mind that any key segment that "looks like a file path" will be treated like a file path. In particular, this includes segments containing a `.`. This could result in the task failing when this "file" does not exist.

However, does this mean that file names without a `.` would only be considered as a static string?

**Comment by ramiMSFT** [comment]
@jefgen Thank you for your feedback!

**Comment by jefgen** [comment]
Thanks for fixing this! 👍

**Comment by p-m-j** [comment]
Should this not have quotes for the restore keys also?

```yaml
key: 'yarn | "$(Agent.OS)" | yarn.lock'
  restoreKeys: |
    "yarn" | "$(Agent.OS)"
    "yarn"
```
