### ISSUE TITLE
Broken yml example in the Deployment jobs

### ISSUE THREAD

**Issue by VyacheslavPritykin** [MicrosoftDocs/azure-devops-docs#10569]
There is an incorrect yml example that:
- skips the execution of the StageB
- inserts an invalid value into the `myOutputVar` variable

Current non-working version:
```yml
stages:
- stage: StageA
  jobs:
  - deployment: A1
    pool:
      vmImage: 'ubuntu-16.04'
    environment: env1
    strategy:                  
      runOnce:
        deploy:
          steps:
          - bash: echo "##vso[task.setvariable variable=RunStageB;isOutput=true]true"
            name: setvarStep
          - bash: echo $(System.JobName)

- stage: StageB
  dependsOn: 
    - StageA
 
  # when referring to another stage, stage name is included in variable path
  condition: eq(dependencies.StageA.outputs['StageA.A1.setvarStep.RunStageB'], 'true')
  
  # Variables reference syntax differs slightly from inter-stage condition syntax
  variables:
    myOutputVar: stageDependencies.StageA.A1.outputs['A1.setvarStep.RunStageB']
  jobs:
  - deployment: B1
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:                  
      runOnce:
        deploy:
          steps:
          - bash: echo $(myOutputVar)
```

Updated working version:
```yml
stages:
- stage: StageA
  jobs:
  - deployment: A1
    pool:
      vmImage: 'ubuntu-16.04'
    environment: env1
    strategy:                  
      runOnce:
        deploy:
          steps:
          - bash: echo "##vso[task.setvariable variable=RunStageB;isOutput=true]true"
            name: setvarStep
          - bash: echo $(System.JobName)

- stage: StageB
  dependsOn: 
    - StageA
 
  # when referring to another stage, stage name is included in variable path
  condition: eq(dependencies.StageA.outputs['A1.setvarStep.RunStageB'], 'true') # <---- modified
  
  # Variables reference syntax differs slightly from inter-stage condition syntax
  variables:
    myOutputVar: $[stageDependencies.StageA.A1.outputs['setvarStep.RunStageB']] # <---- modified
  jobs:
  - deployment: B1
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:                  
      runOnce:
        deploy:
          steps:
          - bash: echo $(myOutputVar)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
