### ISSUE TITLE
Undocumented argument 'env'

### ISSUE THREAD

**Issue by rossdotpink** [MicrosoftDocs/azure-devops-docs#10575]
Hi!

Whilst `AzureCLI@0` does not, it seems `AzureCLI@1` and `AzureCLI@2` both support the use of an `env:` argument to define environment variables. For example:

```yaml
          - task: AzureCLI@2
            displayName: 'Call some script'
            inputs:
              azureSubscription: 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: scripts/my_script.sh
            env:
              EXAMPLE: 'some text'.     # this is available in the bash script as $EXAMPLE
              SAMPLE: 'some more text'  # also available in the bash script as $SAMPLE
```

While the docs for the [Bash task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops) _do_ document the `env` argument, the docs for the [AzureCLI task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops) _do not_.

What's the status of the `env` argument? Is the documentation simply lacking mention of it, or should this functionality not be used?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**
