### ISSUE TITLE
caching-docker.yml does not exist in example

### ISSUE THREAD

**Issue by XmlmXmlmX** [MicrosoftDocs/azure-devops-docs#10577]
At the section [`Docker images`](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#docker-images) is written:

> Replace caching-docker.yml with your own pipeline YAML file.

But htere is no `caching-docker.yml` in the given example:

```yaml
pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: Cache@2
    inputs:
      key: 'docker | cache'
      path: $(Pipeline.Workspace)/docker
      cacheHitVar: DOCKER_CACHE_HIT
    displayName: Cache Docker images
  - script: |
      docker load -i $(Pipeline.Workspace)/docker/cache.tar
    displayName: Restore Docker image
    condition: and(not(canceled()), eq(variables.DOCKER_CACHE_HIT, 'true'))
  - script: |
      mkdir -p $(Pipeline.Workspace)/docker
      docker save -o $(Pipeline.Workspace)/docker/cache.tar cache
    displayName: Save Docker image
    condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_HIT, 'true')))
```

Please clarify how to use the snippet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#docker-images)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
