### ISSUE TITLE
Environment seems to need resource type

### ISSUE THREAD

**Issue by marctalary** [MicrosoftDocs/azure-devops-docs#10589]
Hi,
the environment only seemed to work if specified with resource type.
e.g. in your examples it's
```
    environment: '$(envName).$(k8sNamespaceForPR)'
```
but only seems to work with...
```
  environment: 
    name: '$(envName).$(k8sNamespaceForPR)'
    resourceType: Kubernetes
```
otherwise I get `##[error]Unhandled: Input required: kubernetesServiceConnection`.
Please update the example if this is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vijayma** [comment]
Can you paste your entire YAML file? I believe this has to do with how you are using the environment in the steps later on.

**Comment by marctalary** [comment]
Sure, I've since moved to using pipeline templates.  This all works.
I don't specify the environment in later steps just once in the deployment job.
The template is invoked from a complete pipeline template per environment like so...

azure-pipelines-template.yml
```
stages:
- stage: Build
# .... left out call to build template
- stage: DeployToDev
  displayName: Dev Deployment
  dependsOn: Build  
  jobs:
  - template: deployment-jobs-template.yml
    parameters: 
      environment: dev
      siteDomainName: $(siteDomainName)
      kustomizeEnv: dev
```
deployment-jobs-template.yml
``` 
parameters:
- name: environment
- name: siteDomainName 
- name: kustomizeEnv

jobs:
- deployment: deployTo${{ parameters.environment }}
  displayName: Deploy to ${{ parameters.environment }} Environment
  pool:
    vmImage: $(vmImageName)

  variables:
    environment: ${{ parameters.environment }}
    environmentDomainName: ${{ parameters.siteDomainName }}

  environment:
    name: ${{ parameters.environment }}
    resourceType: Kubernetes

  strategy:
    runOnce:
      deploy:
        steps:

        - task: DownloadPipelineArtifact@2
          displayName: Download manifests artifact
          inputs:
            artifactName: 'manifests'
            downloadPath: '$(System.ArtifactsDirectory)/manifests'

        - task: PowerShell@2
          displayName: Set domain name for environment
          inputs:
            targetType: 'inline'
            script: |       
              if ('$(environment)' -eq 'live')
              {
                $domainName = '$(environmentDomainName)'
              }
              else
              {
                # Prefix root domain name with environment name when not live
                $domainName = '$(environment).$(environmentDomainName)'
                Write-Host "Updating deployment variable environmentDomainName with subdomain prefix"
                Write-Host "##vso[task.setvariable variable=environmentDomainName]$domainName"
              }
              Write-Host 'Domain name for $(environment):'
              Write-Host "$domainName"
            failOnStderr: true  

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: Replace vars in manifests
          inputs:
            targetFiles: '$(System.ArtifactsDirectory)/manifests/**/*.yml'
            encoding: 'auto'
            verbosity: detailed
            writeBOM: true
            actionOnMissing: 'fail'
            keepToken: false
            tokenPrefix: '#{'
            tokenSuffix: '}#'
            useLegacyPattern: false
            enableTelemetry: false

        - powershell: "Get-Content -Path $(System.ArtifactsDirectory)/manifests/app/deployment-env-vars.yml"
          displayName: Display Deployment Env Vars YAML
          enabled: false  # for debugging

        - task: KubernetesManifest@0
          displayName: Kustomize Manifests using env folder ${{ parameters.kustomizeEnv }}
          name: bake
          inputs:
            action: bake
            renderType: kustomize
            kustomizationPath: '$(System.ArtifactsDirectory)/manifests/env/${{ parameters.kustomizeEnv }}'

        - task: KubernetesManifest@0
          displayName: 'Deploy manifests'
          inputs:
            action: deploy
            manifests: '$(bake.manifestsBundle)'
            rolloutStatusTimeout: 1200
```
