### ISSUE TITLE
The example doesn't seem to update the Build.BuildNumber

### ISSUE THREAD

**Issue by MartijnCarolTREFF** [MicrosoftDocs/azure-devops-docs#10590]
I'm trying to create a nuget package numbering in a yaml file but whatever i try the build number is not chaning. Even the given example 

```

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

steps:
  - script: echo '$(Build.BuildNumber)' # outputs customized build number like project_def_master_20200828.1
```
Just returns the defauld YYYY.nn back = >  '20210425.44'

I've no cuw what I'm missing could you give me soe feedback? 

I just what to do:

```   
variables:  
  name: '1.0.0.$(Build.BuildId)'
  MyRunNumber: '1.0.0.$(Build.BuildId)'

steps:
  - script: echo '$(Build.BuildNumber)'            #is wrong
  - script: echo '$(MyRunNumber)'                  #is ok
  - script: echo '$(name)'                                  #is ok

.... some other stuff and not sure i need this

  - task: Assembly-Info-NetCore@2
    inputs:
          Path: 'scr/xxx/xxxx.csproj'
          FileNames: '**/*.csproj'
          InsertAttributes: true
          FileEncoding: 'auto'
          WriteBOM: false
          VersionNumber: $(name)
          FileVersionNumber: $(name)
          PackageVersion: $(name)
          
... than the  error command 

  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: 'scr/xxx/xxxx.csproj'
      versioningScheme: byBuildNumber

  #   versioningScheme: byEnvVar
  #   versionEnvVar: $(name)                          # not regonized 
      
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
