### ISSUE TITLE
Mounting the Docker Socket in the Kubernetes Deployment - Insecure?

### ISSUE THREAD

**Issue by HarleyB123** [MicrosoftDocs/azure-devops-docs#10621]
I've noticed that in the deployment for the ADO Runner, the docker socket is mounted. From my limited knowledge on the subject, this seems pretty insecure.

```
volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
volumes:
       - name: docker-volume
        hostPath:
            path: /var/run/docker.sock
```
Less of an issue and more of a question - why is this needed for the ADO runner to work? This doesn't look like a Docker-in-Docker use case, nor can I see a reason for the agent to manage other docker images

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
