### ISSUE TITLE
Gradle caching restoreKeys refer to Gemfile.lock

### ISSUE THREAD

**Issue by tschmidt01** [MicrosoftDocs/azure-devops-docs#10662]
The `restoreKeys` in [gradle caching documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#gradle) refer to a `Gemfile.lock`, which is clearly related to rails and not gradle, thus the example is not executable in a gradle based project:

```
Starting: Gradle caching
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.0.1
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - gradle [string]
 - Linux  [string]
Resolved to: gradle|Linux
Resolving restore key:
 - gradle       [string]
 - Linux        [string]
 - Gemfile.lock [file] (not found)
##[error]One or more errors occurred. (File not found: Gemfile.lock)
Finishing: Gradle caching
```

This would make more sense:
```
  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)" | **/build.gradle.kts'
      restoreKeys: |
        gradle | "$(Agent.OS)"
        gradle
      path: $(GRADLE_USER_HOME)
    displayName: Gradle caching
```

I'd also swap `script` for the `Gradle@2` task to make it more clear.

If you want, I can also open a PR for the proposed changes.
