### ISSUE TITLE
Looping over the same parameter twice

### ISSUE THREAD

**Issue by ArneKlein** [MicrosoftDocs/azure-devops-docs#10749]
According to the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#each-keyword) I can loop over a parameter like this:
```
steps:
- ${{ each value in parameters.listOfStrings }}:
  - script: echo ${{ value }}
```

however, no example shows how I can loop over the same parameter multiple times, e.g.:
```
steps:
- ${{ each value in parameters.listOfStrings }}:
  - script: echo ${{ value }}
- ${{ each value in parameters.listOfStrings }}:
  - script: echo ${{ value }}
```
exits with one of your not very helpful errors:

/pipelines/docker_build.yml@templates (Line: 25, Col: 3): Expected a mapping
/pipelines/docker_build.yml@templates (Line: 25, Col: 3): Expected a mapping
/pipelines/docker_build.yml@templates (Line: 24, Col: 3): Expected at least one key-value pair in the mapping
/pipelines/docker_build.yml@templates: Unexpected state while attempting to read the mapping end. State:

SequenceState:
  IsStart: False
  Index: 3
  IsEnd: True

MappingState:
  IsStart: False
  Index: 0
  IsKey: False
  IsEnd: False

Please extend the documentation how this can be done or that it can't be done

**Comment by juliakm** [comment]
@ArneKlein I checked with the product team and this should work. I'm able to loop through parameters without error in this YAML. If you're trying out a scenario and need some help, I'd recommend posting in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). 

```yaml
pool:
  vmImage: ubuntu-latest

parameters:
  - name: listOfStrings
    type: object
    default:
      - one
      - two
      - three

trigger: none

steps:
- ${{ each value in parameters.listOfStrings }}:
  - script: echo ${{ value }}
- ${{ each value in parameters.listOfStrings }}:
  - script: echo ${{ value }}
```
