### ISSUE TITLE
Pipelines YAML - Azure Function App task v1 - multiline appsettings example

### ISSUE THREAD

**Issue by mjhilton** [MicrosoftDocs/azure-devops-docs#10819]
## Problem
The example for the `appsettings` argument of the AzureFunctionApp@1 are fairly light-on. The argument example only uses the single-line string format:

> (Optional) Application settings. Use the syntax `-key value`. Enclose values that contain spaces in double quotation marks.
> For example, `-Port 5000 -RequestTimeout 5000 -WEBSITE_TIME_ZONE "Eastern Standard Time"`.

There is only one usage example for the YAML task, which doesn't include the `appsettings` argument at all:

```
variables:
  azureSubscription: Contoso
  # To ignore SSL error, uncomment the below variable
  # VSTS_ARM_REST_IGNORE_SSL_ERRORS: true

steps:
- task: AzureFunctionApp@1
  displayName: Azure Function App Deploy
  inputs:
    azureSubscription: $(azureSubscription)
    appName: samplefunctionapp
    package: $(System.DefaultWorkingDirectory)/**/*.zip
```

This documentation might lead someone with a large number of `appsettings` to write YAML like this:

```
steps:
- task: AzureFunctionApp@1
  displayName: Azure Function App Deploy
  inputs:
    azureSubscription: $(azureSubscription)
    appName: samplefunctionapp
    appsettings: -Port 5000 -RequestTimeout $(RequestTimeout) -WEBSITE_TIME_ZONE $(WebsiteTimezone) -Heirarchical:ConfigKey "WithAStaticValue" -ConnectionString $(StorageConnectionString)
    package: $(System.DefaultWorkingDirectory)/**/*.zip
```

The `appsettings` argument does not support multi-line input, but this single-line approach to providing the `appsettings` quickly becomes very difficult to read and maintain, especially with a large number of `appsettings` that need to vary per environment by way of variables.

## Documentation-based Solution
Using the [Block Folding YAML operator](https://yaml-multiline.info/), it's possible to have a much nicer multi-line format in your YAML, which gets stripped down to a single line on execution of the pipeline, maintaining compatibility with the task's single-line input requirement.

Changing the previous example to use the Block Folding operator, we instantly have a much cleaner, more maintainable YAML block:
```
steps:
- task: AzureFunctionApp@1
  displayName: Azure Function App Deploy
  inputs:
    azureSubscription: $(azureSubscription)
    appName: samplefunctionapp
    appsettings: >
      -Port 5000
      -RequestTimeout $(RequestTimeout)
      -WEBSITE_TIME_ZONE $(WebsiteTimezone)
      -Heirarchical:ConfigKey "WithAStaticValue"
      -ConnectionString $(StorageConnectionString)
    package: $(System.DefaultWorkingDirectory)/**/*.zip
```

It would be helpful if we could update the documentation with extra example(s) that includes the `appsettings` argument, and add a suggestion to the `appsettings` argument's description that the Block Folding operator can be used to split the settings across multiple lines.

## Code-based solution
An even better solution would be to update the task to support multiline JSON input for the app-settings, like the way the [Azure App Service Settings task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-settings?view=azure-devops) works, but that seems outside the scope of this repo and is probably better addressed on the YAML Tasks repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops#open-source)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**
