### ISSUE TITLE
Docs say to include azurepipelines-coverage.yml in root, but it is ignored

### ISSUE THREAD

**Issue by martimors** [MicrosoftDocs/azure-devops-docs#10812]
[Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops) say

> you must include a configuration YAML file named azurepipelines-coverage.yml at the root of your repo

however, this file is ignored by azure pipelines, which runs with default settings no matter the content of that file.

Pipeline:

```yml
  - job:
    displayName: "Unit Tests and Code Coverage"
    strategy:
      matrix:
        PipPython38:
          python.version: "3.8"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
        displayName: "Use Python $(python.version)"
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: 'my/feed'
          onlyAddExtraIndex: true
      - script: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev libssl-dev
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-azurepipelines pytest-cov wheel
          python -m pip install -r app/requirements.txt -r app/requirements-dev.txt
        workingDirectory: $(System.DefaultWorkingDirectory)/src
        displayName: "Install pytest and package requirements"
      - script: |
          python -m pytest -o junit_family=xunit2 --cov --cov-report html --cov-report xml --cov-fail-under=0 tests
        workingDirectory: $(System.DefaultWorkingDirectory)/src
        displayName: "Run unit tests"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa4f4c6-0a42-108e-79dd-5724e1049bd5
* Version Independent ID: f4a857d1-78bc-170b-b138-fcf490c85b38
* Content: [Code coverage for pull requests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops)
* Content Source: [docs/pipelines/test/codecoverage-for-pullrequests.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/codecoverage-for-pullrequests.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**
