### ISSUE TITLE
Inconsistent indentation in example

### ISSUE THREAD

**Issue by ArendSmit** [MicrosoftDocs/azure-devops-docs#10868]
On the https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops page there is a section:

You can also use conditional insertion for variables:
```
variables:
  - name: foo
    value: test

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "start"
- ${{ if eq(variables.foo, 'test') }}:
  - script: echo "this is a test"

```
in which the indentation is different than the rest of the indentations on this whole page.

It is not explained as either relevant or irrelevant. Introducing it there makes no sense.

Please fix this so it cannot create confusion.

There should either be an explanation for the space before the - sign before name: foo or it should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
