### ISSUE TITLE
Using Variables for Pipeline Resource Version

### ISSUE THREAD

**Issue by kfam98** [MicrosoftDocs/azure-devops-docs#10876]
I want to use a variable like so:

```
resources:
  pipelines:
  - pipeline: PipelineName
    source: Pipeline
    version: $(variable)
```

However, I read that variables cannot be passed in, and that we should use runtime parameters instead. 

References here: 
https://stackoverflow.com/questions/59184728/specifying-pipeline-resource-version-using-variable https://developercommunity.visualstudio.com/t/pipeline-resource-version-property-as-a-variable-1/845445
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#manual-version-picker-for-resources-in-the-create-run-dialogue

They state that I should use runtime parameters, so I tried it:
```
resources:
  pipelines:
  - pipeline: PipelineName
    source: Pipeline
    version: "${{ parameters.version }}"
```

When I attempt to run this build pipeline, I get `A template expression is not allowed in this context`. 

I think that this feature to use a variable in a resource should be supported. But, when trying to follow the aforementioned "runtime parameters", it doesn't work. Can anyone direct me to how I can make this work, or make it a feature?

Thanks :)
