### ISSUE TITLE
Incorrect behavior of require template check/policy

### ISSUE THREAD

**Issue by MoimHossain** [MicrosoftDocs/azure-devops-docs#10883]
The required template check feature doesn't work as it is described/documented.

## How to reproduce?
Let's consider this example scenario, where I have 2 Azure DevOps projects with following repositories:
- Platform (Project)
  - templates (Repository) 
- Product-A (project)
  - workload (Repository)
  - fake-templates (Repository)

The intention is **Platform team** provides some "secure/trusted" templates to the **product** teams and enforces the templates to be extended via [Required Template Check](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass#required-template) feature. 

With that in mind, I wanted to setup __approvals and check__ policy (based on **Required Template check**). Therefore, I navigate: 

> Product-A > Project settings > Agent Pools >  Azure Pipelines > Approvals and checks (from top-right menu)

Create a Required YAML template policy with following configurations:
- Repository Host: ```Azure Repos```
- Repository : ```Platform/templates```
- Ref: ```refs/heads/master```
- Path to template: ```template.yml```

Next, I create a pipeline for ```workload``` repository in ```Product-A``` project, here's the YAML:
```yaml
resources:
  repositories:
    - repository: templates
      type: git      
      name: Platform/templates
extends:
  template: template.yml@templates
  parameters:
      yesNo: false 
```

This works - as expected. 
However, if I now modify the YAML with the following:

```yaml
resources:
  repositories:
    - repository: templates
      type: git      
      name: Product-A/fake-templates  ## Notice, here I am pointing to a template that shouldn't be allowed
extends:
  template: unsafe-template.yml@templates
  parameters:
      yesNo: false 
```
This would work too - without any complaints. This must be a bug/fault. 

This behavior clearly not what is described in the documents. The approval checks on Agent pool serves no purposes if anybody can just avoid/bypass the required template check completely with an altered YAML file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f721e2df-f7e4-8db7-08cc-eab779477c99
* Version Independent ID: 95014030-e9eb-6425-2990-8f9fa2452e7e
* Content: [Security through templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/security/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/security/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/security/templates.md)
* Product: **devops**
* Technology: **devops-cicd-security**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
