### ISSUE TITLE
Coverlet.Cover .NET 5 Pipeline Collection Example Not Working

### ISSUE THREAD

**Issue by sam-mfb** [MicrosoftDocs/azure-devops-docs#10894]
Following the .Net 5 sample for collecting coverage statistics in a linux or mac devops pipeline with coverlet.collector does not work.

(https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive#collect-code-coverage-metrics-with-coverlet)

I believe this is because the `CoverletOutput` flag for specifying the output directory does not work in coverlet.cover as noted in this issue: (https://github.com/coverlet-coverage/coverlet/issues/500)

Statistics can be collected if the publish task is modified as follows:

```
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
```
That is the default location where results are stored.  This generates a warning that "Multiple file or directory matches were found." but the first is used and the coverage report is generated.  I haven't found anyway to work around this warning.

**Comment by sam-mfb** [comment]
On further review of the coverlet.cover documentation, I think the correct command line for the test run itself should actually be:

```
- task: DotNetCoreCLI@2
  displayName: "Run unit tests"
  inputs:
    command: 'test'
    projects: 'syz.api.unittest/syz.api.unittest.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
    publishTestResults: true
```

Note the different method for specifying the output format in `arguments:` as indicated by the documentation for coverlet.cover -- (https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#passing-runsettings-arguments-through-commandline)

I have tested this on my pipeline successfully.
