### ISSUE TITLE
Invalid YAML code

### ISSUE THREAD

**Issue by shrewmouse1** [MicrosoftDocs/azure-devops-docs#10988]
The example code provided isn't even valid.  Everything below `- deployment` should be indented one level.  The provided example gives 3 errors:

- /azure-pipelines.yml (Line: 9, Col: 1): Unexpected value 'displayName'
- /azure-pipelines.yml (Line: 10, Col: 1): Unexpected value 'environment'
- /azure-pipelines.yml (Line: 13, Col: 1): Unexpected value 'strategy'

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops#use-virtual-machine-in-pipelines

```yaml
trigger: 
- main

pool: 
   vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM

  environment: 
    name: ContosoDeploy
    resourceType: VirtualMachine

  strategy:
    runOnce:
      deploy:   
          steps:
          - script: echo "Hello world $(date)"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
