### ISSUE TITLE
Multiple pipeline triggers aren't mentioned

### ISSUE THREAD

**Issue by jemayn** [MicrosoftDocs/azure-devops-docs#11070]
Hey there!

Trying to set up a flow where one of two pipelines can trigger a third, it is not mentioned on this page whether this is possible or not.

Tried doing something like this:

```yaml
trigger: none 

resources:
  pipelines:
    - pipeline: BE-BuildPipeline
      source: 'BE Build'
      trigger: true 
    - pipeline: FE-BuildPipeline
      source: 'FE Build'
      trigger: true
```

Seems only the BE-BuildPipeline triggers this one, however if it is commented out the FE-BuildPipeline can also trigger it. Seems a bit strange, so if it's not intended to have more than one pipeline triggers in a pipeline I'd suggest a note or warning is added on this page 🙂

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?tabs=yaml&view=azure-devops#branch-considerations)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
