### ISSUE TITLE
CopyFiles@2 - Wrong casing regarding the schema json

### ISSUE THREAD

**Issue by dhcgn** [MicrosoftDocs/azure-devops-docs#11085]
### Wrong casing

```
# Copy files
# Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
- task: CopyFiles@2
  inputs:
    #sourceFolder: # Optional
    #contents: '**' 
    targetFolder: 
    #cleanTargetFolder: false # Optional
    #overWrite: false # Optional
    #flattenFolders: false # Optional
    #preserveTimestamp: false # Optional
```

### Should be

```
# Copy files
# Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
- task: CopyFiles@2
  inputs:
    #SourceFolder: # Optional
    #Contents: '**' 
    TargetFolder: 
    #CleanTargetFolder: false # Optional
    #OverWrite: false # Optional
    #FlattenFolders: false # Optional
    #PreserveTimestamp: false # Optional
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
