### ISSUE TITLE
Repository resource triggers for GitHub

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/azure-devops-docs#11083]
According to the following documents:
* [**Repository resource**](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#repository-resource)
* [**Multiple repositories - Triggers**](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#triggers)

In the YAML pipelines, repository resource triggers only work for Azure Repos Git repositories in the same organization at present. They do not work for GitHub or Bitbucket repository resources.
![document-01](https://user-images.githubusercontent.com/46307996/125924422-c063606c-3ac4-42da-947b-ae28dcb203cd.png)
![document-02](https://user-images.githubusercontent.com/46307996/125924437-c93775ef-8231-4e40-8e48-437c9edce708.png)

However, according to my test, see the YAML pipeline sample below:
```yaml
resources:
  repositories:
  - repository: GHRepo01
    type: github
    name: {GitHub Org}/GitHubRepo01
    endpoint: ConnectGitHub
    trigger:
     branches:
       include:
       - '*'
  - repository: GHRepo02
    type: github
    name: {GitHub Org}/GitHubRepo02
    endpoint: ConnectGitHub
    trigger:
     branches:
       include:
       - '*'

pool:
  vmImage: ubuntu-latest

steps:
- checkout: GHRepo01
- checkout: GHRepo02  
```
**GitHubRepo01** and **GitHubRepo02** are two Git repositories hosted on GitHub. Every time I push new changes to **GitHubRepo01** or **GitHubRepo02**, the YAML pipeline can be triggered. This behavior is obviously inconsistent with the statement in the document.
However, I checked the [**Release Notes**](https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-188-update) of Azure DevOps, I did not find any sprint mentioned that the repository resource triggers has been available to GitHub repository resource.

Another odd thing is that if I enable **`batch`** for the trigger, the trigger would no longer work unless I disable the **`batch`** again.
```yaml
resources:
  repositories:
  - repository: GHRepo01
    type: github
    name: {GitHub Org}/GitHubRepo01
    endpoint: ConnectGitHub
    trigger:
     batch: true  # enable batch
     branches:
       include:
       - '*'
  - repository: GHRepo02
    type: github
    name: {GitHub Org}/GitHubRepo02
    endpoint: ConnectGitHub
    trigger:
     batch: true  # enable batch
     branches:
       include:
       - '*'
```
