### ISSUE TITLE
Unclear `succeeded('previousJob')`, what `it` is it referring to and requirements of allowed job

### ISSUE THREAD

**Issue by rogerprz** [MicrosoftDocs/azure-devops-docs#11095]
The [succeeded](https://dev.azure.com/valet-testing/build-playground/_build/results?buildId=890&view=results) documentation is unclear on what it refers to. Is dependsOn still required? I tested with and without and it looks like it is still required even though documentation seems to state that if you want to run job only if  a specific job succeeds you do not need to declare `dependsOn`

This is valid
```
- job: C
     dependsOn:
     - B
    condition: succeeded('B')
    steps:
    - script: echo "Should still run"
```
but this is not valid (or should it be?) and it is not clear if it should be based on what `it` represents
```
- job: C
    # dependsOn:
    # - B
    condition: succeeded('B')
    steps:
    - script: echo "Should still run"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#succeeded)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
