### ISSUE TITLE
There is no section about action `Generate deployment manifest`

### ISSUE THREAD

**Issue by shoter** [MicrosoftDocs/azure-devops-docs#11105]
As title says: There is no section about action `Generate deployment manifest`

Example code:
```
    - task: AzureIoTEdge@2
      displayName: 'Generate deployment manifest - amd64'
      inputs:
        action: 'Generate deployment manifest'
        templateFilePath: '$(Build.SourcesDirectory)/deployment.template.json'
        defaultPlatform: 'amd64'
        deploymentManifestOutputPath: '$(Build.SourcesDirectory)/deployment.e2e.json'
        validateGeneratedDeploymentManifest: 'true'
  ```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93a0bac-faf1-3c5d-d358-487d3d0d4f9e
* Version Independent ID: 06d36475-d60d-067d-0c12-d5af0ff1d85c
* Content: [Azure IoT Edge task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/azure-iot-edge.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/azure-iot-edge.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
