### ISSUE TITLE
conditional variables based on stageDependencies

### ISSUE THREAD

**Issue by tehho** [MicrosoftDocs/azure-devops-docs#11145]
Im trying to set up a pipeline that switches environment based on a stageDependencies variable.
Is this possible or do i need to set up 2 stages, 1 apply_autoapprove and 1 apply_manual?

Below pipeline errors with `Unrecognized value: 'stageDependencies'. Located at position 4 within expression: eq(stageDependencies.Plan.Terraform_Plan.outputs['opa.opa_autoapprove'], 'true').`

```yaml
resources:
  repositories:
    - repository: templates
      type: git

stages:
  - stage: Plan
    jobs:
      - job: Terraform_Plan
        displayName: Terraform Plan - Publish a package if Infrastructure changes are identified
        continueOnError: false
        steps:
          - template: azure-devops/templates/steps/terraform.yaml@templates
            parameters:
              version: $(terraform_version)
              path: $(directory)
              package_name: $(product)
              terraform_init: true
              terraform_plan: true
              terraform_opa: true

  - stage: Apply
    dependsOn: Plan
    variables: 
      - name: opa_autoapprove
        value: $[stageDependencies.Plan.Terraform_Plan.outputs['opa.opa_autoapprove']]
      - name: deployment_environment
        ${{ if eq(variables['opa_autoapprove'], 'true')}}:
          value: Terraform_Apply_Autoapprove
        ${{ if ne(variables['opa_autoapprove'], 'true')}}:
          value: Terraform_Apply

    condition: |
      and(
        succeeded(), 
        ne(variables['Build.Reason'], 'PullRequest'), 
        eq(stageDependencies.Plan.outputs['Terraform_Plan.plan.plan_exitcode'], '2')
      )
    jobs:
      # track deployments on the environment
      - deployment: Terraform_Apply
        displayName: Terraform Apply - Resources creation
        environment: ${{variables['deployment_environment']}}
        strategy:
          # default deployment strategy
          runOnce:
            deploy:
              steps:
                - template: azure-devops/templates/steps/terraform.yaml@templates
                  parameters:
                    version: $(terraform_version)
                    package_name: $(product)
                    terraform_apply: true
          
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
