### ISSUE TITLE
Conditional if clause not consistent and poorly documented

### ISSUE THREAD

**Issue by sijucm** [MicrosoftDocs/azure-devops-docs#11172]
Microsoft documentation does not clearly mention how to use the if clause with multiple conditions and scarily enough logic cannot be applied when it comes to what Microsoft has implemented. 
If I use the following clause it does not use it as an OR condition. It just evaluate to false. But if I use the same in a 'task condition' it works. Microsoft, please, let me use some logic instead of pure randomness just like how it is in Microsoft VB. Could someone please let me know why it won't evaluate to true if the parameters.environment is 'production'. I just cannot figure it out how Microsoft evaluates it as false. If this is not the way Microsoft wants it, it will be great if Microsoft can document that in this page with an example. 

    - ${{ if or(eq('${{ parameters.environment }}', 'production'), eq('${{ parameters.environment }}', 'acceptance')) }}:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@sijucm Thanks for your question. While we look into the documentation, consider these additional resources: 

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by juliakm** [comment]
@sijucm I think that the problem you are running into is that you're using template syntax inside of template syntax. In this example, the first step evaluates as true. 

```yaml
parameters:
- name: environment
  type: string
  default: 'acceptance'

steps:
  - ${{ if or(eq(parameters.environment, 'production'), eq(parameters.environment, 'acceptance')) }}:
    - script: echo "Are you there param?"
  - ${{ if eq(parameters.environment, 'production') }}:
    - script: echo "Are you there param?" 
 ```

If you have suggestions for how the product should work or concerns about possible bugs, please reach out to the product team in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
