### ISSUE TITLE
npm publish external registry wrong casing

### ISSUE THREAD

**Issue by florianbader** [MicrosoftDocs/azure-devops-docs#11202]
The documentation states at the bottom that in order to publish to an external registry the following is needed:
```yaml
- task: Npm@1
  inputs:
    command: publish
    publishRegistry: UseExternalRegistry
    publishEndpoint: '<NAME_OF_YOUR_SERVICE_CONNECTION>'
```

If done the task will fail with an error message `Cannot read property 'url' of undefined`. This is because the publishRegistry parameter needs to be set to `useExternalRegistry` because the constant in the task is case sensitive (see [here](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/NpmV1/constants.ts#L11))

This is how the example should look like and works:
```yaml
- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useExternalRegistry
    publishEndpoint: '<NAME_OF_YOUR_SERVICE_CONNECTION>'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10c01b82-71e7-f21d-e7d3-88792e8aea84
* Version Independent ID: d8528b3d-6323-79bf-2663-f79431b66b2f
* Content: [Publishing npm packages using Azure Pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/npm?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/npm.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/npm.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
