### ISSUE TITLE
[Cache Task] docker cache seems not working

### ISSUE THREAD

**Issue by KagamiChan** [MicrosoftDocs/azure-devops-docs#11228]
Hi, I'm using the docker@2 task for building and pushing images. The example for docker says the path should be `$(Pipeline.Workspace)/docker`

However after I added the cache for docker, I got the error saying the folder does not exist, which sounds to me docker did not save anything into that location, here's a log

```
Resolving key:
 - docker  [string]
 - "Linux" [string]
 - cache   [string]
Resolved to: docker|"Linux"|cache
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session ###
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `docker|"Linux"|cache`
There is a cache miss.
tar: /home/vsts/work/1/docker: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

I noticed that in previous version we have more steps and configurations, is there any extra steps required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@KagamiChan - We'll look into whether we should update this article. Please be aware that we don't off product support on this board - rather, we maintain the documentation. If you're troubleshooting errors, please try the links I included in the previous issue:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by richardjharding** [comment]
I'm seeing the same error - either the documentation is wrong/incomplete or there is an issue with the task - I'm using hosted ubuntu-latest image - my docker build step completes but I get the same path error in the post job cache step

**Comment by ramiMSFT** [comment]
@KagamiChan Thank you for your feedback! You must mkdir that directory first. I'm updating the article shortly

```yaml
pool:
  vmImage: 'Ubuntu-16.04'
steps:
  - task: Cache@2
    displayName: Cache task
    inputs:
      key: 'docker | "$(Agent.OS)" | cache'
      path: $(Pipeline.Workspace)/docker
      cacheHitVar: CACHE_RESTORED                #Variable to set to 'true' when the cache is restored
    
  - script: |
      docker load -i $(Pipeline.Workspace)/docker/cache.tar
    displayName: Docker restore
    condition: and(not(canceled()), eq(variables.CACHE_RESTORED, 'true'))

  - script: |
      mkdir -p $(Pipeline.Workspace)/docker
      docker save -o $(Pipeline.Workspace)/docker/cache.tar cache
    displayName: Docker save
    condition: and(not(canceled()), or(failed(), ne(variables.CACHE_RESTORED, 'true')))
```

**Comment by kucher-neocles** [comment]
> @KagamiChan Thank you for your feedback! You must mkdir that directory first. I'm updating the article shortly
> 
> ```yaml
> pool:
>   vmImage: 'Ubuntu-16.04'
> steps:
>   - task: Cache@2
>     displayName: Cache task
>     inputs:
>       key: 'docker | "$(Agent.OS)" | cache'
>       path: $(Pipeline.Workspace)/docker
>       cacheHitVar: CACHE_RESTORED                #Variable to set to 'true' when the cache is restored
>     
>   - script: |
>       docker load -i $(Pipeline.Workspace)/docker/cache.tar
>     displayName: Docker restore
>     condition: and(not(canceled()), eq(variables.CACHE_RESTORED, 'true'))
> 
>   - script: |
>       mkdir -p $(Pipeline.Workspace)/docker
>       docker save -o $(Pipeline.Workspace)/docker/cache.tar cache
>     displayName: Docker save
>     condition: and(not(canceled()), or(failed(), ne(variables.CACHE_RESTORED, 'true')))
> ```

Does it work for someone? "Docker save" step fails for me with the error above:
`**##[debug]script=mkdir -p /home/vsts/work/1/docker
docker save -o /home/vsts/work/1/docker/cache.tar cache**
##[debug]workingDirectory=/home/vsts/work/1/s
##[debug]check path : /home/vsts/work/1/s
Generating script.
##[debug]Agent.Version=2.191.1
##[debug]agent.tempDirectory=/home/vsts/work/_temp
##[debug]check path : /home/vsts/work/_temp
========================== Starting Command Output ===========================
##[debug]which 'bash'
##[debug]found: '/bin/bash'
##[debug]which '/bin/bash'
##[debug]found: '/bin/bash'
##[debug]/bin/bash arg: --noprofile
##[debug]/bin/bash arg: --norc
##[debug]/bin/bash arg: /home/vsts/work/_temp/e17460e9-dd31-42e9-b75a-1e6fs54sddsdbc.sh
##[debug]exec tool: /bin/bash
##[debug]arguments:
##[debug]   --noprofile
##[debug]   --norc
##[debug]   /home/vsts/work/_temp/e17460e9-dd31-42e9-b75a-1e6cb319bdbc.sh
/bin/bash --noprofile --norc /home/vsts/work/_temp/e17460e9-dd31-42e9-b75a-1e6fs54sddsdbc.sh
**Error response from daemon: No such image: cache**
`

**Comment by richardjharding** [comment]
Yep I'm seeing the same - I tried wrapping the last element of the key in quotes to avoid it being treated as a path -but first this seems to be the wrong thing as it wouldn't create a correct hash value?

Even then I get another error with the docker save step as cache doesn't exist - I think this needs a more work on the documentation to explain what that example is doing and whether those tasks need to be wrapped around the docker build step?

**Comment by ramiMSFT** [comment]
I reached out to the product team about this and we need a little more information to debug this issue. Can you enable verbose logging and upload the logs?

**Comment by wsharp-ra** [comment]
I also ran into this issue and I was able to get the command to run. The save step needs to run after you build your docker image. However, it doesn't seem to be using the cached image. Still looking into that.

>Error response from daemon: No such image: cache

This is because it's looking for the name of the image you just built.

**Example**
```
- task: Cache@2
  displayName: Cache task
  inputs:
    key: 'docker | "$(Agent.OS)" | cache'
    path: $(Pipeline.Workspace)/docker
    cacheHitVar: CACHE_RESTORED
    
- script: |
    docker load -i $(Pipeline.Workspace)/docker/cache.tar
  displayName: Docker restore
  condition: and(not(canceled()), eq(variables.CACHE_RESTORED, 'true'))

- task: Docker@2
  displayName: 'Build Image'
  inputs:
    repository: 'myrepo'
    command: 'build'
    Dockerfile: 'Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: 'myimagename'

- script: |
    mkdir -p $(Pipeline.Workspace)/docker
    docker save -o $(Pipeline.Workspace)/docker/cache.tar myrepo:myimagename
  displayName: Docker save
  condition: and(not(canceled()), or(failed(), ne(variables.CACHE_RESTORED, 'true')))
```
