### ISSUE TITLE
Trigger pipeline from other pipeline does not work

### ISSUE THREAD

**Issue by Laetus** [MicrosoftDocs/azure-devops-docs#11232]
We've tried to configure to trigger the pipeline from another repository.  But it didn't work.

Observed behaviour:

when adding the snippet 

```yaml
# this is being defined in app-ci pipeline
resources:
  pipelines:
  - pipeline: securitylib   # Name of the pipeline resource
    source: security-lib-ci # Name of the pipeline referenced by the pipeline resource
    project: FabrikamProject # Required only if the source pipeline is in another project
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes
```

Into your pipeline, the resource was referenced (different builds could be selected, when using the "Run Pipeline" dialog. 

Expected behaviour:
Completion of `security-lib-ci` pipeline should automatically start the `app-ci` pipeline. 

We've managed to fix that behaviour, via "Edit" app-ci pipeline -> "Triggers" -> manually selecting `security-lib-ci`. However, this was not reflected in the yaml. 

We also didn't achieve this configuration via the terraform provider. 

Is there a way to configure that in an Everything as Code way (AzD Pipeline YAML or Terraform)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?tabs=yaml&view=azure-devops#branch-considerations)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
