### ISSUE TITLE
The final example should be explicit Copy-Paste

### ISSUE THREAD

**Issue by benjamimo1** [MicrosoftDocs/azure-devops-docs#11282]
A copy-paste example of the final Task form should be presented:

```
- task: ShellScript@2
  inputs:
    scriptPath:
    args: 'test.sh'. <------ Change here -------<
    #disableAutoCwd: false # Optional
    #cwd: '' # Optional
    #failOnStandardError: false
```

Not doing so assumes that the reader will successfully pass the argument (which we can't guarantee)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fff5ec-d766-b589-39ff-9c69ab26dd5b
* Version Independent ID: 12deb045-2511-b5bf-9e41-0d223bef516b
* Content: [Shell Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/shell-script.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/shell-script.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
