### ISSUE TITLE
Documentation of count function

### ISSUE THREAD

**Issue by aelray** [MicrosoftDocs/azure-devops-docs#11323]
Could you please add to the documentation of the counter function here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops-2020#counter

that the `prefix`, although being a string, may not contain certain special characters. I lost nearly two days figuring out, that the string may not contain `.` symbols.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @aelray! The article will be updated shortly.

**Comment by juliakm** [comment]
@aelray Can you give an example of the prefix value being filtered out? I've tried a number of variations with `.` characters that are still included. 

```yaml
pool:
  vmImage: ubuntu-latest

variables:
  major: 1
  minor: 0
  patch: $[ counter(format('{0}.{1}', variables.major, variables.minor), 0) ]

steps:
  - script: echo "Hello, World, version $(major).$(minor).$(patch)"
```

**Comment by gh-andre** [comment]
> The development team recommends using A-Za-z, integers, and _.

This would be disastrous. Why can't the dev team actually say what's being used today? Dots definitely work today and if the docs make it official that the don't, it becomes a major problem for anyone who uses a version pattern as a prefix, which is pretty common. I'm using it for a number of projects, for example, and I know others do to. Please, please, push the dev team to provide a more definitive answer. This function is far too important to just wing it with a safe subset of actual characters.

**Comment by gh-andre** [comment]
I also want to highlight a couple of practical uses of the `counter` function that are either impossible or far more complex to implement in other DevOps services.

The example where the patch version is automatically incremented is used only by teams that don't follow build maturity best practices and work around the lack of build numbers in other DevOps environments by usurping patch level as a build number, which is automatically incremented.

In projects where teams are working towards a specific release, the version of the next release is picked by the Product Owner and it cannot be auto-incremented at any level. The Product Owner may set up a schedule that follows, say, biweekly releases, but that doesn't quite replace using a build number, which is commonly missed. A build number shows build maturity towards the next release and it's auto-incremented within the pipeline until the most mature build is released.

So, for simple projects with multiple supported past releases (i.e. non-website apps), build number will be different for different release lineages, so one may have versions `4.1.0+27` and `5.0.0+78` produced by the same pipeline. In this example, there were 27 builds for version `4.1.0` and 78 builds for version `5.0.0`. Feature branches in this model wouldn't be contributing to build numbers and the pipeline on branch `4.1.x` might look like this:
```yaml
variables:
  VERSION: 4.1.0
  BUILD_NUMBER: $[counter(variables.VERSION, 1)]

name: $(VERSION)+$(BUILD_NUMBER)
```
On `master` the same chunk of configuration would just have `VERSION: 5.0.0` and everything else would work the same way. As an example, here's an Open Source project that uses this technique:

https://dev.azure.com/StoneSteps/Stone%20Steps%20Webalizer/_build?definitionId=6

For teams that run CI builds on feature branches, build numbers on those branches don't contribute to the product maturity until they are merged to their base branch, so it's useful to keep those builds visibly different from the base branch builds, which is possible via Azure DevOps conditional variable assignment and in a simplified form might look like this:
```yaml
variables:
  VERSION: 5.0.0
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    BUILD_NUMBER: $[ counter(variables.VERSION, 1) ]
    BUILD_METADATA: $[ format('{0}', variables.BUILD_NUMBER) ]
  ${{ else }}:
    BUILD_NUMBER: $[ counter(format('{0}+{1}', variables.VERSION, variables['Build.SourceBranchName']), 1) ]
    BUILD_METADATA: $[ format('{0}.{1}', variables['Build.SourceBranchName'], variables.BUILD_NUMBER) ]

name: $(VERSION)+$(BUILD_METADATA)
```
This makes it possible to use the same CI pipeline to build artifacts towards the next release, which typically would be used by QA (e.g. `myapp-5.0.0+47`), as well as artifacts for feature branches, which would be used either by developers or in automated testing (e.g. `myapp-5.0.0+ab-123.5`). In the latter version, `ab-123` would be the name of the feature branch and and `5` is the build number on that branch. What's even better that the build number generated this way can be used even in Release pipelines via `Build.BuildNumber`.

All this being said, at least characters that are valid for a semantic version should be documented, so it's possible to accommodate simple branch names with dashes in the last part of their name (e.g. `features/ab-123`). These patterns do currently work in Azure DevOps and it it apart from other DevOps services I used in this respect. It would be a sad day if the dev team would suddenly drop a bunch of these characters.
