### ISSUE TITLE
delayForMinutes: Step references task 'Delay' at version '1.1.10' which is not valid for the given job target

### ISSUE THREAD

**Issue by jigisha9** [MicrosoftDocs/azure-devops-docs#11395]
@lsegal @alex @bratsche @alloy @timheuer 

```
steps:
   - task: Delay@1
     inputs:
         delayForMinutes: '1'
```

**Step references task 'Delay' at version '1.1.10' which is not valid for the given job target**

still getting below error on azure pipeline. How to resolve?
