### ISSUE TITLE
A little more information on versionEnvVar

### ISSUE THREAD

**Issue by woter1832** [MicrosoftDocs/azure-devops-docs#11406]
It took me a while to realise that the format of `versionEnvVar` is in the format `BUILD_BUILDNUMBER`, not the usual `$(Build.BuildNumber)`.

I know you say:
> Enter the variable name without $, $env, or %
But this is very unusual and I fell foul of the unique syntax. If I have, I am sure others have too. May I suggest you highlight that we should use the raw AzDO env variable? Maybe an example wouldn't go amiss:

```
# Push pre-release NuGet packages from a build to internal organisation Feed
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.Tests.nupkg'
    feedPublish: 'FabrikamFeed'
    versionEnvVar: BUILD_BUILDNUMBER
    versioningScheme: 'byEnvVar'
```

Also, it may be worth noting that the `versioningScheme` value of `byBuildNumer` doesn't pick up the pre-release "tag" in the Build Number. i.e `mypackage-1.0.1-beta.nupkg`. It drops `-beta` from the package name, hence the above example uses `byEnvVar`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#yaml-snippet)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**
