### ISSUE TITLE
Variables support in pool demands of deployment job and lifecycle hooks

### ISSUE THREAD

**Issue by arkein** [MicrosoftDocs/azure-devops-docs#11403]
Hello,

I'm struggling to find the description of how exactly the calculation of pool demands work in deployment job and lifecycle hooks.

- The documentation clarifies that only global level variables work for defining a pool name. Stage/job level variables are not supported to define pool name. Are the stage/job level variables supported to define pool demands? E.g.

```yaml
# few previous regular jobs
jobs:
  - deployment: deployJob
     environment: dev
     pool:
        name: PrivatePool
        demands:
          - AzureRegion -equals $(AzureRegion) # a custom variable set in previous job/stage.
     # strategy and the rest of steps
```

- When I attempt to use the demand based on variables, the deployment job fails without any details at all.

![image](https://user-images.githubusercontent.com/4995531/134498683-25e18445-4757-442c-8a22-b76fcc1b90ac.png)

![image](https://user-images.githubusercontent.com/4995531/134501968-9d82b03a-362b-4bac-896c-fc30cd7aa01d.png)

Full repro pipeline:

```yaml
stages:
  - stage: setVariableStage
    displayName: "Set Variable"
    jobs:
      - job: setVariableJob
        timeoutInMinutes: 0
        pool:
          name: PrivatePool
        steps:
          - checkout: none
          - pwsh: |
              Write-Host "##vso[task.setvariable variable=AzureRegion;isOutput=true;]eastus2"
            displayName: Set vars
            name: setVariableStep
  - stage: Deploy
    displayName: "Deploy"
    dependsOn: setVariableStage
    variables:
      - name: AzureRegion
        value: $[ stageDependencies.setVariableStage.setVariableJob.outputs['setVariableStep.AzureRegion'] ]
    jobs:
      - deployment: deployJob
        environment: dev
        pool:
          name: PrivatePool
          demands:
            - AzureRegion -equals $(AzureRegion)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - pwsh: |
                    Write-Host "AzureRegion = $(AzureRegion)"
                  displayName: Output
```

- When `deploy` hook pool is configured in addition to the deployment job pool, demands seem to be ignored? Even if I set unrealistic demands which non of my agents can meet, the job runs successfully.

```yaml
jobs:
  - deployment: deployJob
     environment: dev
     pool:
        name: PrivatePool
     strategy:
       runOnce:
         deploy:
           pool:
             name: PrivatePool
             demands:
               - unrealisticDemand # ignored, deploy runs on the first available agent in the pool.
               - AzureRegion -equals $(AzureRegion) # a custom variable set in previous job/stage; ignored as well.
           steps:
             - checkout: none
              # rest of steps
```

- When a deployment job `pool` is omitted but `deploy` hook pool is configured, the hook pool seem to be completely ignored? The deployment of the below runs successfully on `Azure Pipelines` agent even though the hook is configured to use private agents.

```yaml
jobs:
  - deployment: deployJob
     environment: dev
     # pool not configured
     strategy:
       runOnce:
         deploy:
           pool:
             name: PrivatePool # pool is configured as override
           steps:
             - checkout: none
              # rest of steps
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
