### ISSUE TITLE
Add boolean parameter example to Bash task

### ISSUE THREAD

**Issue by jsuvanto** [MicrosoftDocs/azure-devops-docs#11417]
Please add an example of how to use boolean parameters with a bash task.

It may not be obvious that if a parameter is boolean type, in bash it is interpreted as "True" or "False" instead of "true" or "false".

Example:
```yaml
# azure-pipeline.yml
parameters:
  - name: isActivated
    type: boolean
    default: true

steps:
  - bash: |
      echo ${{parameters.isActivated}} # prints True
      if [ "${{parameters.isActivated}} == "true" ] ; then
        # This block is never reached!
      fi
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
