### ISSUE TITLE
HelmDeploy@0 chartName not used

### ISSUE THREAD

**Issue by FilBot3** [MicrosoftDocs/azure-devops-docs#11412]
# The issue

It seems that the given `HelmDeploy@0` task doesn't use the `chartName` value given to it. Then it tacks on the workspace location at the end of the command causing errors.

The YAML defintion

```yaml
---
jobs:
  - job: RenderTemplates
    displayName: Render Helm Chart Templates
    variables:
      - template: ../variables/proof-of-concept.yaml
    steps:
      - task: HelmDeploy@0
        displayName: Render Helm Chart
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: '${{ variables.AzDO_AKS_Svc_Conn }}'
          namespace: devops
          command: template
          arguments: >
            dryrun ./helm-generic-bluekc-deploy
            --values Developer.dudleyp.priorauth_gp_build/overrides/proof-of-concept.yaml
            --set "secrets_as_env[0].secret_name=app-secrets"
            --set "secrets_as_env[0].secret_type=Opaque"
            --set "secrets_as_env[0].secret_data.ProviderDataAccess__ConnectionString='$(ProviderDataAccess-ConnectionString)'"
            --set "secrets_as_env[0].secret_data.JwtAuth__HMAC256='$(JwtAuth-HMAC256)'"
            --set "secrets_as_env[0].secret_data.JwtAuth__ValidIssuer='$(JwtAuth-ValidIssuer)'"
            --set "secrets_as_env[0].secret_data.Serilog__WriteTo__0__Args__eventCollectorToken='$(Serilog-WriteTo-0-Args-eventCollectorToken)'"
            --set "secrets_as_env[0].secret_data.Serilog__WriteTo__0__Args__splunkHost='$(Serilog-WriteTo-0-Args-splunkHost)'"
      - task: HelmDeploy@0
        displayName: Install Helm Chart
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: '${{ variables.AzDO_AKS_Svc_Conn }}'
          namespace: devops
          command: install
          chartType: FilePath
          chartName: 'itdoesntreallymatterbecasuethistaskisnotworking'
          releaseName: priorauth
          valuesFile: './Developer.dudleyp.priorauth_gp_build/overrides/proof-of-concept.yaml'
          arguments: >
            ./helm-generic-bluekc-deploy
            --set "secrets_as_env[0].secret_name=app-secrets"
            --set "secrets_as_env[0].secret_type=Opaque"
            --set "secrets_as_env[0].secret_data.ProviderDataAccess__ConnectionString='$(ProviderDataAccess-ConnectionString)'"
            --set "secrets_as_env[0].secret_data.JwtAuth__HMAC256='$(JwtAuth-HMAC256)'"
            --set "secrets_as_env[0].secret_data.JwtAuth__ValidIssuer='$(JwtAuth-ValidIssuer)'"
            --set "secrets_as_env[0].secret_data.Serilog__WriteTo__0__Args__eventCollectorToken='$(Serilog-WriteTo-0-Args-eventCollectorToken)'"
            --set "secrets_as_env[0].secret_data.Serilog__WriteTo__0__Args__splunkHost='$(Serilog-WriteTo-0-Args-splunkHost)'"
```

The output. This has been trimed because it still shows the secrets even though they're "secret".

```plaintext
2021-09-24T19:43:20.2914498Z [command]/opt/hostedtoolcache/helm/3.7.0/x64/linux-amd64/helm install --debug --namespace devops priorauth --wait ./helm-generic-bluekc-deploy --set secrets_as_env[0].secret_name=app-secrets --set secrets_as_env[0].secret_type=Opaque --set secrets_as_env[0].secret_data.ProviderDataAccess__ConnectionString='***' --set secrets_as_env[0].secret_data.JwtAuth__HMAC256='***' --set secrets_as_env[0].secret_data.JwtAuth__ValidIssuer=BlueKC --set secrets_as_env[0].secret_data.Serilog__WriteTo__0__Args__eventCollectorToken='***' --set secrets_as_env[0].secret_data.Serilog__WriteTo__0__Args__splunkHost='***' /home/vsts/work/1/s
```

The method I am using which is what I used to do template, doesn't seem to work either because the task inserts things into different places than I normally do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
There's a stale issue about chartName: MicrosoftDocs/azure-devops-docs/issues/7318

**Comment by FilBot3** [comment]
Using this:

* https://stackoverflow.com/a/59586289/2009612

I was able to make a hacky work around.

**Comment by FilBot3** [comment]
```yaml
---
jobs:
  - job: RenderTemplates
    displayName: Render Helm Chart Templates
    variables:
      - template: ../variables/proof-of-concept.yaml
    steps:
      - task: Kubernetes@1
        displayName: Login to Kubernetes
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: '${{ variables.AzDO_AKS_Svc_Conn }}'
          command: 'login'
      - task: PythonScript@0
        displayName: Render Helm Chart
        inputs:
          scriptSource: inline
          script: |
            import logging
            import os
            import subprocess
            logging.basicConfig(level=logging.INFO)
            command_output = subprocess.run(['helm', 'template', 'priorauth', './helm-generic-bluekc-deploy',
              '--values=./Developer.dudleyp.priorauth_gp_build/overrides/proof-of-concept.yaml',
              '--set="secrets_as_env[0].secret_name=app-secrets"',
              '--set="secrets_as_env[0].secret_type=Opaque"',
              '--set="secrets_as_env[0].secret_data.ProviderDataAccess__ConnectionString=$(ProviderDataAccess-ConnectionString)"',
              '--set="secrets_as_env[0].secret_data.JwtAuth__HMAC256=$(JwtAuth-HMAC256)"',
              '--set="secrets_as_env[0].secret_data.JwtAuth__ValidIssuer=BlueKC"'
              '--set="secrets_as_env[0].secret_data.Serilog__WriteTo__0__Args__eventCollectorToken=$(Serilog-WriteTo-0-Args-eventCollectorToken)"'
              '--set="secrets_as_env[0].secret_data.Serilog__WriteTo__0__Args__splunkHost=$(Serilog-WriteTo-0-Args--splunkHost)"'], check=True)
            logging.info(command_output)
```
