### ISSUE TITLE
Set an output variable in deployment job in one stage (StageA) and use it in another deployment job in another stage (StageB)

### ISSUE THREAD

**Issue by bnchou** [MicrosoftDocs/azure-devops-docs#11426]
This case is not documented and normal syntax is not working.

```
trigger:
  paths:
    include:
      - build/stageVariablesDeployment/*

stages:
  - stage: StageA
    jobs:
    - deployment: A1
      environment: env1
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the deployment variable value"
              name: setvarStep
            - bash: echo $(System.JobName)

  - stage: StageB
    dependsOn: StageA
    variables:
      # myVarFromDeploymentJob: $[ stageDependencies.StageA.A1.outputs['setvarStep.myOutputVar'] ] # Normal syntax is not working
      myVarFromDeploymentJob: $[ stageDependencies.StageA.A1.outputs['A1.setvarStep.myOutputVar'] ]
    jobs:
    - deployment: B1
      environment: env1
      strategy:
        runOnce:
          deploy:
            steps:
            - script: "echo $(myVarFromDeploymentJob)"
              name: echovar
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#support-for-output-variables)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
