### ISSUE TITLE
Example given for environment actually runs on pool (at least with Server 2020)

### ISSUE THREAD

**Issue by pauloqueiroga** [MicrosoftDocs/azure-devops-docs#11492]
When I execute the example given in "Target an environment from a deployment job" using my Azure DevOps Server 2020, the script is actually executed in the agent from the pool, and not in the resource from the environment:

```
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'smarthotel-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
```

Through a lot of trial and error, I could only make it work in one of two ways:
1- Specify a resource in the environment
```
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'smarthotel-dev.linux-box-001'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
```

2- Specify tags and resource type:
```
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 
      name: 'smarthotel-dev'
      tags: my-tag
      resourceType: virtualmachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
```

I don't know if it's a bug with the product or not, but the documentation should reflect the actual behavior.

Thanks,
Paulo Queiroga

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Create target environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops-2020#environment-in-run-details)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
