### ISSUE TITLE
Note needed to one of examples, or possible bug (inconsistency)

### ISSUE THREAD

**Issue by quasarea** [MicrosoftDocs/azure-devops-docs#11544]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#conditionally-run-a-step

Below example works only because variable is defined in pipeline.:
```
variables:
  - name: foo
    value: fabrikam # triggers else condition

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "start"
- ${{ if eq(variables.foo, 'adaptum') }}:
  - script: echo "this is adaptum"
- ${{ elseif eq(variables.foo, 'contoso') }}:
  - script: echo "this is contoso"
- ${{ else }}:
  - script: echo "the value is not adaptum or contoso"
```
If its set in UI before pipeline runs (in variables section of run page) its not set due to being declared here (yaml declaration takes precedence over UI declaration as far as I can tell) 

If definition removed from here and defined in run time, it will have no value during conditions. This is because condition are expanded during compile time, and UI variable value is available only in runtime. This maybe bug because:
* its inconsistent with yaml declared variables - very misleading that one works and the other don't, 
* its inconsistent with parameters - those are available during compile time, and those are set in the same UI menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
