### ISSUE TITLE
UI Pipeline Variables not passed to Pipeline at Compile time

### ISSUE THREAD

**Issue by ackermann81** [MicrosoftDocs/azure-devops-docs#11557]
Hi,
I try to use a variable expression to get dynamic template for a template extend. 
When its based on a UI Pipeline variable the variable is empty at Pipeline Run. 
I created a pipeline variable in the UI and used it in the following yaml.

```
name: $(buildid)
trigger: none

extends:
  template: ${{ variables.APP }}_Template.yaml
```

When i start the pipeline he brings the error that he can´t find _Template.yaml. 
From the docs it says that ${{ variables.APP }} is processed on compile time. 
The interessting thing is that it works with parameters. 
If i use the following yaml and write the value in a parameter it works fine. 

```
name: $(buildid)
trigger: none
parameters:
  - name: APP
    displayName: APP
    type: string   

extends:
  template: ${{ parameters.APP }}_Template.yaml
```

The background is that we have more than 20 different applications and we want to standardize the pipelines. For this we want to use Extend from a template with resources but with dynamic templates.

Thanks for help.
Bye Robert
