### ISSUE TITLE
Artifact Name not being populated when parameterized in a Loop

### ISSUE THREAD

**Issue by JFolberth** [MicrosoftDocs/azure-devops-docs#11614]
Working on looping through a list of artifacts and publishing via the PublishPipelineArtfact and having it wrapped in a template. The loop value is being passed in for the targetPath; however the artifact value does not seem to get recognized.

I've tried both w/ and w/o single quotes, also with and with out the () surrounding the loop value. Can see the `dacpacName` value is used in target path and that piece is working.
task template:
```
parameters:
    targetPath: ''
    artifactName: ''
steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: ${{parameters.targetPath}}
    artifact:  ${{parameters.artifactName}}
```

Calling Loop
```
parameters:
- name: dacpacNames
  type: object
- name: solutionName
  type: string
- name: configurationName
  type: string
  default: 'Debug'

jobs:
- job: Build_Publish__dacpacs
  displayName: Build Publish dacpacs
  steps:
  - template: ../tasks/vs_build_task.yml@YAMLTemplates
  - ${{ each dacpacName in parameters.dacpacNames}}: 
    - template: ../tasks/ado_publish_pipeline_artifact.yml@YAMLTemplates
      parameters:
        artifact: '$({{ dacpacName }})'
        targetPath: '$(Pipeline.Workspace)\s\${{parameters.solutionName}}\bin\${{ parameters.configurationName }}\${{ dacpacName }}.dacpac'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and download artifacts in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
