### ISSUE TITLE
 Unexpected value 'container' when following documentation

### ISSUE THREAD

**Issue by martinisaksenprogleasing** [MicrosoftDocs/azure-devops-docs#11677]
I get `Unexpected value 'container'` when I try to use code similar to this:
```
- stage: 'Build'
  pool:
    name: Default
  container:
    registry: custom/image
    endpoint: custom
```

If I follow the linting hints from in VS Code and change it to this:
```
- stage: 'Build'
  pool:
    name: Default
    container:
      registry: custom/image
      endpoint: custom
```

Then the container is not run. The stage executes on the host.

How can I run the stage inside that custom container?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
