### ISSUE TITLE
conditional insertion does not work with variable group and expression variable

### ISSUE THREAD

**Issue by yehudamakarov** [MicrosoftDocs/azure-devops-docs#11728]
variables:
            - name: isQaRelease
              value: ${{ eq(variables['Build.SourceBranchName'], 'qa') }}
        
            - ${{ if eq(variables.isQaRelease, true) }}:
               - group: legacy-enterprise-sync-qa

The above does not bring in the variable group

            - ${{ if eq(variables['Build.SourceBranchName'], 'qa') }}:
               - group: legacy-enterprise-sync-qa

And this works. `- ${{ if eq(variables.isQaRelease, 'true') }}:` produces the same results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#conditional-insertion)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@yehudamakarov I don't think that you can conditionally insert an entire variable group but I will check with the product group to confirm. You can conditionally set the value of individual variables in a variable group. Here's an example.

```yaml
variables:
- group: myVarGroup
- name: env
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    value: a
  ${{ else }}:
    value: b

steps:
- script: | 
    echo '$(name)'
    echo '$(env)'
```

**Comment by Jokinen** [comment]
Here's an example where we considered using a similar pattern.

```yml
parameters:
  - name: environment
    type: string
    default: default
    values:
      - default
      - develop
      - staging
      - production

variables:
  - name: environment
    # Allow default logic to be overridden with a parameter
    ${{ if ne(parameters.environment, 'default') }}:
      value: ${{ parameters.environment }}
    # Otherwise use the default logic which choose environment based on source branch
    ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      value: staging
    ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      value: production
    ${{ else }}:
      value: develop
  # Map staging variable group into a stable variable value
  - ${{ if eq(variables.environment, 'staging') }}:
      - group: variable_group.staging
      - name: api_key
        value: $(staging-apikey)
  # Map production variable group into a stable variable value
  - ${{ if eq(variables.environment, 'production') }}:
      - group: variable_group.production
      - name: api_key
        value: $(production-apikey)
```

**Comment by damianobarbati** [comment]
@juliakm I have the same problem. I have defined 3 groups (development, staging and production).
I'm trying to use a specific group based on the branch, but it's not working:
```yml
variables:
  - group: test
  - name: pnpm_config_cache
    value: $(Pipeline.Workspace)/.pnpm-store
  # set variables for each branch that targets a specific environment deployment
  - name: isMainBranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isStagingBranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/staging')]
  - name: isProductionBranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/production')]
  # conditionally require a variable group
  - ${{ if eq(variables.isMainBranch, true) }}:
    - group: development
  - ${{ if eq(variables.isStagingBranch, true) }}:
    - group: staging
  - ${{ if eq(variables.isProductionBranch, true) }}:
    - group: production
```
