### ISSUE TITLE
YAML stage dependencies

### ISSUE THREAD

**Issue by WibblyDibbler** [MicrosoftDocs/azure-devops-docs#11732]
There are two related issues with documentation regarding dependencies when defined in YAML.  The document at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops states that "Stages can also use output variables from another stage. In this example, Stage B depends on a variable in Stage A."  The provided example is copied for discussion:

```
stages:
- stage: A
  jobs:
  - job: A1
    steps:
     - bash: echo "##vso[task.setvariable variable=shouldrun;isOutput=true]true"
     # or on Windows:
     # - script: echo ##vso[task.setvariable variable=shouldrun;isOutput=true]true
       name: printvar

- stage: B
  condition: and(succeeded(), eq(dependencies.A.outputs['A1.printvar.shouldrun'], 'true'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo hello from Stage B
```

The following are the issues:

1.  The example works for the bash task but not for the script task (on a Windows agent).
2.  This does not work when job A1 is a deployment job, and this is not evident anywhere in the MS docs.
