### ISSUE TITLE
How nuget packages are cached is not explained

### ISSUE THREAD

**Issue by mattiasnordqvist** [MicrosoftDocs/azure-devops-docs#11744]
It seems this article does not explain exactly how nuget packages get cached, only how they are restored from cache.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Version Independent ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Content: [Caching NuGet packages - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops#feedback)
* Content Source: [docs/pipelines/artifacts/caching-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/caching-nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
See the [Cache NuGet packages](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops#cache-nuget-packages) section. 

```yaml
variables:
  NUGET_PACKAGES: ''

- task: Cache@2
  displayName: Cache
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
    path: '$(NUGET_PACKAGES)'
    restoreKeys: |
      nuget | "$(Agent.OS)"
      nuget
    cacheHitVar: 'CACHE_RESTORED'
```
