### ISSUE TITLE
Problem with runtime expressions

### ISSUE THREAD

**Issue by quasarea** [MicrosoftDocs/azure-devops-docs#11752]
Hi, could you provide more documentation on using runtime expressions. I'm trying to influence job strategy by variable (as I cannot use parameters in `az pipeline run` nor in triggered/scheduled runs)

my working example is:
``` yaml
jobs:
  - job:
    variables:
      Configuration: Both # This works
      # Configuration: $[variables['VarConfiguration']] # Doesnt work: Building in Unknown mode, the Configuration is Release and the VarConfiguration is Release
    strategy:
      matrix:
        ${{ if in(variables['Configuration'], 'Release') }}:
          Release:
            BuildConfiguration: Release
        ${{ elseif in(variables['Configuration'], 'Debug') }}:
          Debug:
            BuildConfiguration: Debug
        ${{ elseif in(variables['Configuration'], 'Both') }}:
          Release:
            BuildConfiguration: Release
          Debug:
            BuildConfiguration: Debug
        ${{ else }}:
          Unknown:
            BuildConfiguration: Unknown
    steps:
      - checkout: none
      - pwsh: |
          Write-Output "Building in $(BuildConfiguration) mode, the Configuration is $(Configuration) and the VarConfiguration is $(VarConfiguration)"
        displayName: $(BuildConfiguration)
```

But it does not work if I set VarConfiguration neither in pipeline configuration, pipeline run configuration, or on az commad
```pwsh
az pipelines run --organization=$myOrg--project $myProj --id 6184 --branch develop --variables VarConfiguration=Release
```
Which makes sense, the VarConfiguration is set too late (during runtime) so it cannot affect compile time - ${{}} expression 

I tried multiple times and cannot make it work as runtime expression:
```yaml
jobs:
  - job:
    variables:
      Configuration: Both # This works
      # Configuration: $[variables['VarConfiguration']] # Doesnt work: Building in Unknown mode, the Configuration is Release and the VarConfiguration is Release
    strategy:
      matrix:
        $[ if in(variables['Configuration'], 'Release') ]:
          Release:
            BuildConfiguration: Release
        $[ elseif in(variables['Configuration'], 'Debug') ]:
          Debug:
            BuildConfiguration: Debug
        $[ elseif in(variables['Configuration'], 'Both') ]:
          Release:
            BuildConfiguration: Release
          Debug:
            BuildConfiguration: Debug
        $[ else ]:
          Unknown:
            BuildConfiguration: Unknown
    steps:
      - checkout: none
      - pwsh: |
          Write-Output "Building in $(BuildConfiguration) mode, the Configuration is $(Configuration) and the VarConfiguration is $(VarConfiguration)"
        displayName: $(BuildConfiguration)
```
brings back 
```yaml
/matrix-test.yml (Line: 10, Col: 13): A mapping was not expected
/matrix-test.yml (Line: 13, Col: 13): A mapping was not expected
/matrix-test.yml (Line: 16, Col: 13): A mapping was not expected
/matrix-test.yml (Line: 18, Col: 13): A mapping was not expected
/matrix-test.yml (Line: 21, Col: 13): A mapping was not expected
```

I would be grateful for an example of how to use runtime $[] expression in conditional context like above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
