### ISSUE TITLE
azurePowerShellVersion is required

### ISSUE THREAD

**Issue by ElectricLlama** [MicrosoftDocs/azure-devops-docs#11928]
I know that the doc indicates that **azurePowerShellVersion** is required.

But if you use this task and do not specify it, there is no validation warning, and you get a pretty cryptic error (below)

Can you somehow make it more obvious, perhaps with a couple of examples using

```

      - task: AzurePowerShell@5
        displayName: Get version
        inputs:
          azureSubscription: '<name of service connection>'
          ScriptType: InlineScript
          inline: $PSVersionTable
          azurePowerShellVersion: LatestVersion

```

This is the error message which stumped me for a while

```
Az version null not avaiable locally on the agent. Downloading dynamically.
Validate-VersionParameters: Cannot convert value 'null' to type 'System.Version'.

Exception: /home/vsts/work/_tasks/AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62/5.198.0/Utility.ps1:94
Line |
  94 |  …             throw ("Could not find the module path with given version …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find the module path with given version.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcda4373-62ae-e1ae-c15d-63f441179b47
* Version Independent ID: 305f78c0-2e89-78f2-d2d1-89471602610c
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**
