### ISSUE TITLE
DevOps Pipeline: submodules in the same project

### ISSUE THREAD

**Issue by sonyboy232** [MicrosoftDocs/azure-devops-docs#11939]
I have a DevOps project, and after adding a git submodule (in the same project) to my repo, I kept getting the following error during the checkout step in my DevOps pipeline:

>**remote: TF401019: The Git repository with name or identifier \<submodule\> does not exist or you do not have permissions for the operation you are attempting.**

It took me **DAYS** of googling, reading documentation, and fiddling to figure out how to get the submodule to clone without error, so it might be a good idea to put this information all in one place, where it can actually be found.

It seems that in order to get the submodule to clone as it should:

When the "**Protect access to repositories in YAML pipelines**" option in "Project Settings -> Pipelines -> Settings" is enabled as described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml#limit-job-authorization-scope-to-referenced-azure-devops-repositories) (updated link [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml#job-authorization-scope). Guess I should have quoted what _was_ there)
(**NOTE:** the name of the option in the above link is "Limit job authorization scope to referenced Azure DevOps repositories" which is **not** the title anymore):
![image](https://user-images.githubusercontent.com/4029235/152428140-45a1ef59-3690-4240-981e-59b4f1aab9ad.png)

1. If the submodule is in the same project as the pipeline, the url in `.gitmodules` must be relative as described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#checkout-submodules):
>The build pipeline will check out your Git submodules as long as they are:
>...
>**Authenticated:**
>
> - Contained in the same project, GitHub organization, or Bitbucket Cloud account as the Git repo specified above.
>
> - Added by using a URL relative to the main repository. For example, this one would be checked out: `git submodule add /../../submodule.git mymodule` This one would not be checked out: `git submodule add https://dev.azure.com/fabrikamfiber/_git/ConsoleApp mymodule`

2. The YAML must have a `checkout` step with the `submodules` key set to `true` as described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines).

3. The YAML must reference the submodule repository in `resources.repositories.repository` as described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-repositories-repository?view=azure-pipelines).

4. The YAML must reference the submodule repository **from** `resources.repositories.repository` **in** `stages.stage.jobs.job.uses.repositories` as described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#limit-job-authorization-scope-to-referenced-azure-devops-repositories) 
>When **Limit job authorization scope to referenced Azure DevOps repositories** is enabled, your YAML pipelines must explicitly reference any Azure Repos Git repositories you want to use in the pipeline as a [checkout step](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout) in the job that uses the repository. You won't be able to fetch code using scripting tasks and git commands for an Azure Repos Git repository unless that repo is first explicitly referenced.

  - `jobs.job.uses` described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job?view=azure-pipelines) and [here](https://github.com/MicrosoftDocs/azure-devops-docs/issues/10951)

**Putting it all together**

- Add the submodule to your git project: `git submodule add ../MySubmodule path/to/submodule`

- Your `.gitmodules` should now contain 
```
#.gitmodules

[submodule "path/to/submodule"]
        path = path/to/submodule        # The path where your submodule code will live
        url = ../MySubmodule            # The *relative* URL to the MySubmodule repo (this one is in the same project)
```
- And in your YAML: 
```yml
#my-pipeline.yml
...
resources:
  repositories:
  - repository: MySubmoduleID   #An ID to reference this resource
    type: git
    name: MySubmodule           #The name of the repository for my submodule

stages:
- stage: FirstStage
  displayName: 'Stage 1'
  jobs:
  - job: FirstJob
    displayName: 'Job 1'
    uses:                        #This section must be present
      repositories:
      - MySubmoduleID            #The value from resources.repositories.repository
    steps:
    - checkout: self             #Set to self in order for the parent repo to clone
      submodules: true           #This must be set to true
      persistCredentials: true   #I'm not sure if this line is needed or not
...
```

I hope this helps someone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by finaldzn** [comment]
Why is it this complicated to checkout submodules in the same project :(

**Comment by finaldzn** [comment]
Hello, it seems that azure devops downlaod the main branch of the submodule, do you know how to make it so it checkouts the good branch ? (the one that is actually used by the git submodule ?) 
Thank you

**Comment by adiun** [comment]
**Thank you** @sonyboy232 for taking the time to detail this and providing links. This really needs to be in the docs. 

Even the "Limit job authorization scope to referenced Azure DevOps repositories" option referenced everywhere in the MS docs (e.g. [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#limit-job-authorization-scope-to-referenced-azure-devops-repositories)) doesn't even exist anymore. I think it is renamed to `Protect access to repositories in YAML pipelines`. But more importantly, the approach given by @sonyboy232 is a better one since it avoids disabling that option.

**Comment by offbeatful** [comment]
This configuration with `uses` just does not make any sense except it complicates the whole thing.
I can specify the repository in the resources section and then use azure pipeline yaml template from it without any `uses`. So it gets checkout and yaml file is used from it. Then how it is different from submodules?

**Comment by sonyboy232** [comment]
> This configuration with `uses` just does not make any sense except it complicates the whole thing. I can specify the repository in the resources section and then use azure pipeline yaml template from it without any `uses`. So it gets checkout and yaml file is used from it. Then how it is different from submodules?

If your way is working for you then do that?

**Comment by offbeatful** [comment]
My current way is to duplicate a list of repositories that I specify in both resources/repository and jobs/uses/repository. I would like to avoid that. In my opinion this additional verbosity does not make sense as specifying yaml templates from another repository works without any additional fields.

That works without any uses:
```yaml
resources:
  repositories:
    - repository: pipelines
      type: git
      name: pipelines
      ref: refs/tags/v1.0.0

extends:
  template: .azure-pipelines/website.yml@pipelines
```

This should also work, right?

```yaml
resources:
  repositories:
    - repository: lib
      type: git
      name: lib
      ref: refs/tags/v1.0.0

jobs:
  - job: Build  
    steps:
      - checkout: self
        submodules: true
```

But it does not as I need to specify additional `uses`.  
```yaml
   uses:
      repositories:
        - lib
```
