### ISSUE TITLE
How to prevent creating a new _work folder at each stage?

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [MicrosoftDocs/azure-devops-docs#11989]
Hi everyone.
I have a problem with the azure pipeline stages.
the problem is azure pipeline stages will create a new folder for each stage and I will lose every source that I checkout before.

For example, I have these stages:
1. Checkout
2. Build
3. Tests
4. Deploy
5. etc

the problem is I checkout everything in stage 1 then when I want to build them in stage 2 it's getting the error because stage 1 is in _work\1 and stage 2 is in _work\2 and every resource is in _work\1 that's why I'm getting error in stage 2.

if I move all of them in one stage, everything is ok and every job runs successfully!

my example yml file:

```

trigger:
- Develop

resources:
  repositories:
  - repository: Libraries
    type: git
    name: Libraries
  - repository: Core2
    type: git
    name: Core2
stages:
  - stage: CheckProject
    displayName: Check out
    jobs:
     - job: Checkout
       steps:
        - checkout: self
          path: Projects/Cores/Core1
        - checkout: Core2
          path: Projects/Cores/Core2
        - checkout: Libraries
          path: Projects/Libraries
        
        - powershell: |
                      Remove-Item $(Pipeline.Workspace)/Github/SignalGo-full-net -Force -Recurse -ErrorAction SilentlyContinue
                      git clone --branch netstandard https://github.com/SignalGo/SignalGo-full-net.git Github/SignalGo-full-net
          name: PullSignalGo
          workingDirectory: $(Pipeline.Workspace)

        - task: UseDotNet@2
          displayName: Install .NET Core 6.x SDK
          inputs:
            packageType: 'sdk'
            version: '6.x'
            installationPath: $(Agent.ToolsDirectory)/dotnet
        - task: UseDotNet@2
          displayName: Install .NET Core 5.x SDK
          inputs:
            packageType: 'sdk'
            version: '5.x'
            installationPath: $(Agent.ToolsDirectory)/dotnet
  - stage: Build
    dependsOn: CheckProject
    displayName: Build
    jobs:
     - job: Build
       steps:
        - task: DotNetCoreCLI@2
          name: Build
          inputs:
            command: 'build'
            workingDirectory: $(Pipeline.Workspace)/Projects/Cores/Core1
            arguments: 'Core1.sln'
  - stage: Tests
    dependsOn: Build
    displayName: Tests
    jobs:
     - job: Tests
       steps:
        - task: DotNetCoreCLI@2
          name: Test
          inputs:
            command: 'test'
            workingDirectory: $(Pipeline.Workspace)/Projects/Cores/Core1
            arguments: 'Core1.sln --logger "console;verbosity=detailed"'
```

**Comment by WilliamAntonRohm** [comment]
@Ali-YousefiTelori -- Ali, thank you for your question.  Are you following a particular docs.microsoft.com article?  Meanwhile, please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by steved0x** [comment]
@Ali-YousefiTelori Are you using self-hosted agents or Microsoft-hosted agents? Each job is run on a new agent, and so on Microsoft-hosted agents you can't really access the work directory from a previous job, because that agent is released back to the agent pool and freshly re-imaged waiting for its next use. If you are using self-hosted agents, the agents are not wiped and re-imaged between each job, but there is no guarantee that you will get the same agent for each job in a multiple job/stage pipeline, unless you only have 1 agent, or you configure your agent with capabilities and your pipeline with matching demands.

If you move everything to a single stage, are you also moving them to a single job within the stage? If so, that would explain why it is working, because you have the same agent for the duration of your work, and so previous items are available.

If you do have multiple jobs, and you are on Microsoft-hosted agents, you can use [Pipeline artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml) to pass the outputs of the first job to the second job.

**Comment by Ali-YousefiTelori** [comment]
@steved0x Thank you for your explain,I have self hosted agent and pipeline has multiple jobs, Its working fine, but when I try to make them as multiple stage I will get that problem I said in the issue.
When I try to use multiple stages source will clone in folder 1 and second stage will create new folder, that's why it's not works.

**Comment by steved0x** [comment]
@Ali-YousefiTelori I will try and get more information about that for you.

**Comment by steved0x** [comment]
@Ali-YousefiTelori I tried to reproduce this but even with multiple stages, I get the same work directory when using my self-hosted agent, in my case `C:\agent\_work\3`. I asked and wasn't able to find out the internal rules for when a different number is picked under the _work folder.

I tried using a checkout path like `path: ../MyFolder` so I could pick my own folder (instead of 3 or some arbitrary digit) but it gave an error that I went outside the bounds of my specified work folder. I apologize that I don't have a better answer for you, my recommendation would be to file this issue under here.

https://developercommunity.visualstudio.com/search?space=21

The agent software is open source here:
https://github.com/microsoft/azure-pipelines-agent/issues

You could file an issue there as well.

Looking at this doc: https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/jobdirectories.md

It looks like each pipeline definition should get its own work number, so in your case, multiple stages in the same pipeline should get the same number. So you may be experiencing a bug, which can be reported at the first developer communities link.

```
trigger: none

pool: Default

stages:
- stage: stage1
  jobs:
  - job: s1j1
    steps:
    - script: echo $(Pipeline.Workspace)
  - job: s1j2
    steps:
    - script: echo $(Pipeline.Workspace)
- stage: stage2
  jobs:
  - job: s2j1
    steps:
    - script: echo $(Pipeline.Workspace)
  - job: s2j2
    steps:
    - script: echo $(Pipeline.Workspace)
```
