### ISSUE TITLE
Incorrect bash

### ISSUE THREAD

**Issue by TorokLev** [MicrosoftDocs/azure-devops-docs#11981]
[Enter feedback here]

Windows host cannot execute bash script.
cmd.exe will execute it, no matter if the title says bash.
It simply cannot find bash executor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e70665-a794-82fd-287b-65a747488efa
* Version Independent ID: 0c34f5c3-bc80-061d-cf7a-f30c224ce3b1
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@TorokLev Which hosted agent image were you using? Both of the Windows hosted agents have bash preinstalled:

https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#shells

and the following pipeline outputs the location of bash.exe:

```
trigger: none

strategy:
  matrix:
    windows2019:
      imageName: "windows-2019"
    windows2022:
      imageName: "windows-2022"
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
- bash: where bash
- bash: echo hello world
```

This produces the following output (the first bash command)

```
Generating script.
Script contents:
where bash
"C:\Program Files\Git\bin\bash.exe" -c pwd
/d/a/_temp
========================== Starting Command Output ===========================
"C:\Program Files\Git\bin\bash.exe" /d/a/_temp/d1a5aebd-53ee-4100-90c2-f3fa41d4d83c.sh
C:\Program Files\Git\usr\bin\bash.exe
C:\Program Files\Git\bin\bash.exe
C:\Windows\System32\bash.exe
Finishing: Bash
```

If you are using a self-hosted Windows agent you must install bash onto the VM image in order for it to be used.

I am closing this issue, but please reactivate it if I have misunderstood your question, and provide an example of bash that doesn't run on bash, and which agent image, and I will take a closer look.

Thank you
