### ISSUE TITLE
Missing information about output variable scope / example code is too small to showcase

### ISSUE THREAD

**Issue by Jathok-WSA** [MicrosoftDocs/azure-devops-docs#12005]
Section "Use outputs in a different stage" shows an example of just two stages which implicitly run in order.
Output variables from another stage are only available in the direct successor of a stage.
Without further explanation and testing the reader probably assumes that output variables are available for ALL following stages, which is not true.
You can however use output variables of a stage if the dependsOn: value is actively set like so (I am using the propagating dependsOn values to still force a linear run, as would have happened without using any dependsOn):

```
- stage: stage1 # sets outputVar
- stage: stage2 # uses stage1 outputVar
  dependsOn:
  - stage1 # as the direct successor, this could be omitted?!
- stage: stage3 # uses stage1 outputVar
  dependsOn:
  - stage1 # must be set to gain outputVar access
  - stage2 # used for linear order
- stage: stage4 # uses stage1 outputVar
  dependsOn:
  - stage1 # must be set to gain outputVar access
  - stage3 # used for linear order
```

I would add a remark in the text to explain this behavior:
"Output variables of a different stage are only available in the direct successor stage. If multiple stages should consume the same output variable, you must use a condition (dependsOn) on the stage that sets the outvariable"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
