### ISSUE TITLE
Better documentation for replacing PublishBuildArtifact with PublishPipelineArtifact

### ISSUE THREAD

**Issue by CasperWSchmidt** [MicrosoftDocs/azure-devops-docs#12007]
I'm trying to migrate our classic build pipelines and releases to YAML and came across [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#migrate-from-build-artifacts). Point 1 notes that it is no longer necessary to copy files to `$(Build.ArtifactStagingDirectory)` but it doesn't mention how it works without that step.

I have the following step to copy only the main project (without test projects) to the staging directory, but I can't find any documentation on how to achieve the same with `PublishPipelineArtifact@1`

```
    - task: DotNetCoreCLI@2
      displayName: dotnet publish
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        command: publish
        publishWebProjects: false
        projects: >-
          **/*.csproj
          !**/*test*.csproj
        arguments: '--configuration ${{parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false
        modifyOutputPath: false
```

How can I achieve the same with only `PublishPipelineArtifact@1`?

**Comment by WilliamAntonRohm** [comment]
@CasperWSchmidt -- Casper, thank you for your question.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@ramiMSFT -- Rami, please look into this issue.

**Comment by CasperWSchmidt** [comment]
@WilliamAntonRohm Can you be more specific on the first link? I already went through the documentation for the task with no luck. I also already searched the web (Google) with no luck and just tried SO directly - also with no luck. So either the info does not exist or my search-skills are lacking :)

**Comment by ramiMSFT** [comment]
Please refer to [PublishPipelineArtifact@1](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops), [conditions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml) and [expressions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops). See example below

```
- task: PublishPipelineArtifact@1
  displayName: 'Publish'
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)/**
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    artifactName: 'prod'
    ${{ else }}:
    artifactName: 'prod'
    artifactType: 'pipeline'
```
