### ISSUE TITLE
Summary Files don't get merged

### ISSUE THREAD

**Issue by sensslen** [MicrosoftDocs/azure-devops-docs#12021]
The documentation states that multiple matches to the "summaryFileLocation" will get merged. However when using the task as follows:
```
          - task: PublishCodeCoverageResults@1
            displayName: "Publish code coverage report"
            inputs:
              codeCoverageTool: "Cobertura"
              summaryFileLocation: "$(Agent.TempDirectory)/**/*cobertura.xml"
```
I get the following warning:
```
##[warning]Multiple file or directory matches were found. Using the first match: /opt/devops/_work/_temp/10e3af0c-7ecf-4409-8ed1-2a45eff8a466/coverage.cobertura.xml
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff16109-cc76-cea4-d41b-3fc9c4e9c534
* Version Independent ID: efd08832-ddbc-921a-f682-3ea68ecd27c3
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**
