### ISSUE TITLE
Stage variable condition syntax in multi-stage builds with deployment jobs

### ISSUE THREAD

**Issue by jaspreet-kakkar** [MicrosoftDocs/azure-devops-docs#12029]
The document does not cover the syntax for accessing stage variables from previous stages in conditions when the previous stage contains deployment jobs:

A sample pipeline below:
```
stages:
- stage: build
  displayName: build
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  dependsOn: []
  jobs:
  - deployment: build_job
    environment:
      name: "test"
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: "get commitMessage variable"
            name: getCommitMessage
            inputs:
              targetType: inline
              pwsh: true
              script: |
                $commitMessage = "abcd_import/"
                echo "setting commitMessage: $commitMessage"
                echo "##vso[task.setvariable variable=commitMessage;isOutput=true]$commitMessage"

- stage: lint
  displayName: lint
  dependsOn:
  - 'build'
  condition: contains(stageDependencies.build.build_job.outputs['build_job.getCommitMessage.commitMessage'], 'import/')
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  variables:
  - name: BUILD_STAGE_GET_COMMIT_MESSAGE
    value: $[stageDependencies.build.build_job.outputs['build_job.getCommitMessage.commitMessage']]
  jobs:
  - deployment: validate
    environment:
      name: "test"
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: "commitMessage is empty"
            name: fail
            inputs:
              targetType: inline
              pwsh: true
              script: "echo $(BUILD_STAGE_GET_COMMIT_MESSAGE)"

```
In the above sample pipeline, what should be the syntax to put a condition in the lint stage which uses a output variable from the build stage?
There are a number of variations here, some of which I have listed below and none of them works.

```
condition: contains(stageDependencies.build.outputs['build_job.getCommitMessage.commitMessage'], 'import/')
condition: contains(stageDependencies.build.build_job.outputs['build_job.getCommitMessage.commitMessage'], 'import/')
condition: contains(dependencies.build.outputs['build_job.getCommitMessage.commitMessage'], 'import/')
condition: contains(dependencies.build.build_job.outputs['build_job.getCommitMessage.commitMessage'], 'import/')
```

I had to raise a support case with the Azure DevOps team to find out the correct syntax to use here and it is:

`condition: contains(dependencies.build.outputs['build_job.build_job.getCommitMessage.commitMessage'], 'import/')
`

Which was really a surprise for me, I couldn't imagine putting the job name twice there.

Finally, I have some feedback on the variable expression syntax:
•	The syntax for using a stage variable is different for using it in a condition and using it to pass in as another variable.
•	Yet again, the syntax is different if the source stage is a job v/s if the source stage is a deployment job.
•	Most importantly, the correct syntax is missing in the MS documentation.
•	I couldn't find any way to diagnose the issue for example: it would be really helpful to see the stage output json in the build logs.

Finally, I believe Azure DevOps team has really messed this feature up. The syntax should be consistent across the jobs/deployment jobs, conditions and variables assignments. It's really a pain in this current state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?WT.mc_id=Portal-Microsoft_Azure_Support&view=azure-devops#dependencies)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
