### ISSUE TITLE
Mapping Values are not allowed in dependsOn:

### ISSUE THREAD

**Issue by CzernyJ** [MicrosoftDocs/azure-devops-docs#12032]
I´m trying to follow the sample in the fan-in strategy. However I do get the error Mapping Values are not allowed in this context.

```
  - stage: PROD
      dependsOn: 
      - Build
      - QS
      jobs:
```

My Pipeline is constisting of 3 Stages:
1. Build
2. QS
3. PROD

Prod should depend on Build and QS so that I can use the outputVariable of Build for referencing the artifact name.

How do you correctly specify lists in the dependsOn section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322215c-8025-4f21-0700-7dfa7dc5c46e
* Version Independent ID: 141fcdbb-8394-525b-bb29-eff9a693a9c4
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@CzernyJ -- Jürgen, thank you for your question.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- Julia, please look into this issue.

**Comment by CzernyJ** [comment]
Hi @WilliamAntonRohm,
yeah that was Step0 before I opened this issue. I wrote my sample as listed in the linked [MS Documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#specify-dependencies)
My reasoning is that either the documentation is not up to date to the currently accepted format. Or there is an error when parsing lists of values. I seem not to be able to provide lists in contexts of a variable or in the dependsOn section.

**Comment by juliakm** [comment]
@CzernyJ You should be able to specify multiple stages in the way you've described. I think your indentation may be off. Here's a working pipeline I just tested. 

```yaml
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs:
  - job: TestJob
    steps:      
    - script: echo "Hello from Test"
- stage: DeployUS1
  dependsOn: Test    # this stage runs after Test
  jobs:
  - job: DeployUS1Job
    steps:      
    - script: echo "Hello from US1Job"
- stage: DeployUS2
  dependsOn: Test    # this stage runs in parallel with DeployUS1, after Test
  jobs:
  - job: DeployUS2Job
    steps:      
    - script: echo "Hello from US2Job"

- stage: DeployEurope
  dependsOn:         # this stage runs after DeployUS1 and DeployUS2
  - DeployUS1
  - DeployUS2
  jobs:
  - job: MyJob
    steps:      
    - script: echo "Hello from DeployEurope"
```
![Screen Shot 2022-03-08 at 4 01 54 PM](https://user-images.githubusercontent.com/64906/157324429-b2de03f9-5bd1-490e-8ec6-f3ed02946f5b.png)
