### ISSUE TITLE
Coverage : RunSettings : Cobertura format is not working tough works with CLI

### ISSUE THREAD

**Issue by p00j4** [MicrosoftDocs/azure-devops-docs#12105]
[Enter feedback here]
I'm trying VSTest task to use my runsettings and generate a Cobertura report, which works fine on the CLI, however when same ran on ADO pipeline, generates .coverage file instead of *.cobertra.xml file 

**CodeCoverage.runsettings**
```

<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <DataCollectionRunSettings>
        
        <DataCollectors>
            <DataCollector friendlyName="Code Coverage">
                <Configuration>
                    <Format>Cobertura</Format>
                </Configuration>
            </DataCollector>
            
            
        </DataCollectors>
    </DataCollectionRunSettings>
</RunSettings>
```

**Task** 
```
      - task: VSTest@2
        displayName: Execute Unit Tests for $MySolution
        inputs:
          testAssemblyVer2: '**\*unittest*.dll'
          searchFolder: $(outputDirectory)  
          vsTestVersion: toolsInstaller
          runSettingsFile: Src\CodeCoverage.runsettings
          resultsFolder: '$(Agent.TempDirectory)\TestResults'
          diagnosticsEnabled: True
          codeCoverageEnabled: true
          collectDumpOn: Always
          testRunTitle: ""
          rerunFailedTests: true
          rerunMaxAttempts: 2
          condition: and(
                        succeeded() 
           )
```

**Cli run** 
vstest.console.exe MySolution.UnitTests.dll --EnableCodeCoverage --settings:$MyPath\Src\CodeCoverage.runsettings
![cmd_iTYSyi6tIZ](https://user-images.githubusercontent.com/6470509/159465153-7929f7ef-2a39-4769-98df-9851f063242c.png)

However, on ADO, the same config, generates a dot coverage file instead

![msedge_QenWERK0BI](https://user-images.githubusercontent.com/6470509/159466074-26302bb3-3b1b-44b2-a0c2-5ccea709b397.png)

What is the right way to achieve this. Please help with the document or please point me to right place to log this issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57dd4383-2206-3912-993e-773e8dc69c2d
* Version Independent ID: 537e5ce0-d483-2b56-5ec9-8bdef2d01635
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**
