### ISSUE TITLE
unvalidate bundle cache when lockfile changed

### ISSUE THREAD

**Issue by gsouf** [MicrosoftDocs/azure-devops-docs#12184]
Hi,

This is concerning bundler caching as documented here: https://github.com/MicrosoftDocs/azure-devops-docs/blob/63e80f516fa31d7472ae14ca756f386d321053cd/docs/pipelines/release/caching.md#bundler

I found that updating/adding deps won't invalidate the cache and thus these dependencies will keep being missed and will be installed again on every run until the cache is missed, wasting previous time for things we should be able to cache.

For example 

- you run your pipeline a first time
  - there is a cache miss, bundle folder is uploaded
- you add gem `x` to your gemfile
- you run pipeline
  - there is a cache hit
  - bundle folder does not contain gem `x` yet
  - it installs gem `x`
  - there is a cache hit because the key is the same, bundle folder is not uploaded
- you run pipeline
  - every cache hit won't have gem `x` so you will install it again and again

I I have done in my pipeline is to use a checksum of the lock file that way:

```yaml
  - bash: |
      echo "##vso[task.setvariable variable=gemLockChecksum;]$(sha1sum Gemfile.lock)"

  # Bundle cache
  - task: Cache@2
    displayName: Bundle Cache
    inputs:
      key: 'gems | "$(Agent.OS)" | "$(gemLockChecksum)"'
      restoreKeys: |
        gems | "$(Agent.OS)"
        gems
      path: $(Build.SourcesDirectory)/.ci/volumes/bundle
```

I think that could be added to the documentation instead of the current example.

Thanks
