### ISSUE TITLE
Multiple containers with services example throws psycopg2.OperationalError

### ISSUE THREAD

**Issue by MrCordeiro** [MicrosoftDocs/azure-devops-docs#12203]
The "Multiple containers with services example" section shows a Django Python web container connected to two database containers - PostgreSQL and MySQL. 

I tried running it and I couldn't make it to work.

I even simplified and removed the MySQL database, and still, the test doesn't start. It threw the following error:

```bash
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
```

The pipeline, without the MySQL and using a `.env`file:

```yaml
resources:
  containers:
    - container: db
      image: postgres
      volumes:
      - '/data/db:/var/lib/postgresql/data'
      env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
      - '5432:5432'
    - container: web
      image: python
      volumes:
      - '/code'
      ports:
      - '8000:8000'

pool:
  vmImage: 'ubuntu-latest'

container: web
services:
  db: db

steps:

- task: DownloadSecureFile@1
  name: dotEnv
  inputs:
    secureFile: '.env'

- task: CopyFiles@2
  displayName: 'Add .env file'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '.env'
    TargetFolder: '/__w/1/s/'

- script: |
    pip install -r requirements.txt
  displayName: 'Install requirements'

- script: |
    python /__w/1/s/manage.py test
  displayName: 'Run tests'
```

Is the example provided correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1c794c-d676-fc7e-758e-3464f16a1554
* Version Independent ID: 941de04a-2d34-ec82-8612-00e4070de673
* Content: [Service Containers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/service-containers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/service-containers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@MrCordeiro -- Fernando, thank you for your well-researched feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- Julia, please look into this issue.

**Comment by MrCordeiro** [comment]
Hi @juliakm and @WilliamAntonRohm, thanks for the replies.

As an aside, I am still unable to run the example. The way I "solved" my particular example was by switching to GitHub Actions. It used almost the same `.yaml` file, but I was able to get it running in a matter of minutes, not weeks.

Please let me know if you can replicate this issue.

**Comment by juliakm** [comment]
@MrCordeiro This pipeline just ran for me successfully, which matches our code example. 

```yaml
resources:
  containers:
    - container: db
      image: postgres
      volumes:
          - '/data/db:/var/lib/postgresql/data'
      env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    - container: mysql
      image: 'mysql:5.7'
      ports:
         - '3306:3306'
      env:
        MYSQL_DATABASE: users
        MYSQL_USER: mysql
        MYSQL_PASSWORD: mysql
        MYSQL_ROOT_PASSWORD: mysql
    - container: web
      image: python
      volumes:
      - '/code'
      ports:
        - '8000:8000'
     # options: 

pool:
  vmImage: 'ubuntu-latest'

container: web
services:
  db: db
  mysql: mysql

steps:

- script: |
        pip install django
        pip install psycopg2
        pip install mysqlclient
  displayName: set up django

- script: |
        python /__w/1/s/manage.py test
```

I was also able to run this pipeline without triggering an error after adding an `.env` secure file. 

```yaml
resources:
  containers:
    - container: db
      image: postgres
      volumes:
      - '/data/db:/var/lib/postgresql/data'
      env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
      - '5432:5432'
    - container: web
      image: python
      volumes:
      - '/code'
      ports:
      - '8000:8000'

pool:
  vmImage: 'ubuntu-latest'

container: web
services:
  db: db

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '.env'
    TargetFolder: '/__w/1/s/'
- script: |
        pip install django
        pip install psycopg2
        pip install mysqlclient
  displayName: set up django

- script: |
        python /__w/1/s/manage.py test
```

Closing this issue because I can't reproduce the error.
