### ISSUE TITLE
Problem with React and Vue build sample

### ISSUE THREAD

**Issue by VahidNaderi** [MicrosoftDocs/azure-devops-docs#12223]
I used the following sample in docs to build a docusaurus project which is based on react, using azure devops server 2020 

```yaml
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    Contents: 'build/**' # Pull the build directory (React)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
    ArtifactName: 'www' # output artifact named www
```

Running this got me this warning

```
##[warning]Directory 'C:\vsts-agent\_work\8\a' is empty. Nothing will be added to build artifact 'www'.
```

Leading me to suspect the build process and I checked the folder and I couldn't find the build folder. So I ran the `npm run build` on the vsts agent server locally and it built successfully.
Separting the npm install and build scripts like like the following to make the log more granular, resolved the issue.

```yaml
- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

```

I'm not sure if it's a bug in azure devops or documentation or something else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f617d-59c1-f3d4-d322-88ae5301d9b2
* Version Independent ID: df0db0d1-21da-ce6f-1f74-34b4be1d9ff3
* Content: [Build and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops&tabs=code)
* Content Source: [docs/pipelines/ecosystems/javascript.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/javascript.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
