### ISSUE TITLE
Variable Template Files with Dictionary 

### ISSUE THREAD

**Issue by josh-at-unisuper** [MicrosoftDocs/azure-devops-docs#12247]
I've looked into the variables definition pages; unable to find a working example of using a dictionary in a template file.

The following error is shown when pressing run pipeline: 

Encountered error(s) while parsing pipeline YAML:
/var.yaml (Line: 3, Col: 5): A mapping was not expected

This is what I'm looking to do.

```
# var.yaml file
variables:
  appServicePlanObj:
    planName: "name-goes-here"
    skuName: S1
    skuTier: Standard
    skuSize: S1
    skuFamily: S
    skuCapacity: 1

# pipeline.yaml file
stages:
  - stage: stage_Id
    displayName: Stage Name
    variables:
      - template: "var.yaml"
    jobs:
      - deployment: deploymentId
```
Ideally, I want to create more complex objects with nested arrays and objects.
