### ISSUE TITLE
Provide guidance on navigating to artifact

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/azure-devops-docs#12259]
We had quite a bit of difficulty finding where the artifact is downloaded to. Of course we could specify an absolute path and find it there but by default the artifact is downloaded to a directory above the current one.

Perhaps an example could be added:
```yaml
# Produce Artifact
      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: Artifact
# Consume
          - task: DownloadPipelineArtifact@2
          - script: |
              cd ../Artifact
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
