### ISSUE TITLE
Env variable in pom file cannot get picked from azure-pipeline.yaml

### ISSUE THREAD

**Issue by abhinav-jain09** [MicrosoftDocs/azure-devops-docs#12304]
I have pom.xml like follows 
```
	<properties>
                <functionResourceGroup>${env.functionResourceGroup}</functionResourceGroup>
		<functionAppName>${env.functionAppName}</functionAppName>
		<functionAppRegion>${env.functionAppName}</functionAppRegion>
	</properties>
```

and I want to set these varible from azure-pipline.yaml

```
variables:
  functionResourceGroup: 'RG20TOKENKLUIS100-D'
  functionAppName: 'FA20TKLSALLOW200-D'
  functionAppRegion: 'westeurope'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

```
when step run package goal it says appName not found. Meaning the variable from this file Is not getting set into pom.xml``
