### ISSUE TITLE
Iterative Insertion example doesn't validate when inserting dependsOn

### ISSUE THREAD

**Issue by cjwrk** [MicrosoftDocs/azure-devops-docs#12407]
Hi,

I have noticed using the iterative insertion example mentioned on this page to insert additional dependencies doesn't validate correctly:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#iterative-insertion

When validating the example it gives me the following message:
Job A depends on unknown job . Job B depends on job A which creates a cycle in the dependency graph.

Is this expected behavior when using the Iterative Insertion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#iterative-insertion)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@cjwrk -- thank you for your feedback and question.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- please look into this issue.

**Comment by cjwrk** [comment]
I have done some more investigation and it appears to be related to the YAML templates editor feature which is enabled on my account. If I disable that feature the validation returns OK. If I enable the feature it gives me the warning about the job dependencies.

![image](https://user-images.githubusercontent.com/99032473/174033688-6714b1be-23a0-435d-b82a-c47bfe2aed72.png)

**Comment by juliakm** [comment]
Thanks @cjwrk! I'm working on improving this example now. In the meantime, this interim one is working for me with the YAML editor. Notice that I'm using the `extends` keyword. 

```yaml
# job.yml
parameters:
- name: 'jobs'
  type: jobList
  default: []

jobs:
- ${{ each job in parameters.jobs }}: # Each job
  - ${{ each pair in job }}:          # Insert all properties other than "steps"
      ${{ if ne(pair.key, 'steps') }}:
        ${{ pair.key }}: ${{ pair.value }}
    steps:                            # Wrap the steps
    - script: echo "before"       # Pre steps
    - ${{ job.steps }}                # Users steps
    - script: echo "after"      # Post steps
      condition: always()
```

```yaml
# azure-pipelines.yml
pool:
  vmImage: ubuntu-latest 

extends:
  template: job.yml
  parameters:
    jobs:
    - job: A
      steps:
      - script: echo This will get sandwiched between two steps.
    - job: B
      steps:
      - script: echo So will this!
```
