### ISSUE TITLE
Using Maven@3 task's Code Coverage breaks Cache@2 task

### ISSUE THREAD

**Issue by ncgisudo** [MicrosoftDocs/azure-devops-docs#12403]
Admittedly this may be a bug with DevOps rather than the docs, but I feel that either way the docs could be changed to make the effects clearer,

Really simply - if you utilise the `Maven@3` task and set the `codeCoverageToolOption` input to `jaCoCo` then the `Cache@2` task cannot be used "as expected" (as per all the examples).

Essentially, setting the `codeCoverageToolOption` causes an injection of a <plugin> into the POM (i.e. before Maven actually runs the `Maven@3` task modifies the POM).  
This means that the post-build cache upload step will utilise a different cache key to the pre-build cache-fetch step, which means that subsequent builds won't download the previous build's cache.

An example azure-pipeline that exhibits this behaviour is:
```yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo
      
- task: Bash@3
  displayName: "Show any local diff"
  inputs:
    targetType: 'inline'
    script: |
      git diff

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'deploy site'
    codeCoverageToolOption: "jaCoCo"
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true
    findBugsRunAnalysis: false
      
- task: Bash@3
  displayName: "Show any local diff (post-build)"
  inputs:
    targetType: 'inline'
    script: |
      git diff
```

When the `codeCoverageToolOption` input is set to `jaCoCo`, it appears that the `Maven@3` task:
* Strips comments from the POM
* Adjusts whitespace in the POM
* Adds a jacoco-maven-plugin entry to the POM (regardless of if you already had one)

This was encountered and detected when I was attempting to configure other SCM plugins which checked for and enforced a clean SCM state, wherein it complained that `pom.xml` had been modified due to the above.

Whilst this itself may be a bug in the task, I think the docs could be clearer in describing what happens if `codeCoverageToolOption` is set.
