### ISSUE TITLE
Android Emulator example hangs indefinitely

### ISSUE THREAD

**Issue by PPartisan** [MicrosoftDocs/azure-devops-docs#12402]
The code sample under the [TEST](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#test) heading hangs indefinitely. This code is supposed to launch an Android emulator as a background process and then continue so Android connected tests can run. I noticed a problem on StackOverflow that describes the same issue [here](https://stackoverflow.com/questions/71478721/azure-devops-android-emulator-script-timeout). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f69815-b798-2328-7e55-c67865505623
* Version Independent ID: 2ece0f9a-c3f8-2a47-71ef-c9e22e2a02c9
* Content: [Build, test, and deploy Android apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/android.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/android.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by PPartisan** [comment]
For what it's worth, I resolved this by using:
```
$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
$ANDROID_HOME/cmdline-tools/latest/bin/avdmanager
```
Instead of what was given in example:
```
$ANDROID_HOME/tools/bin/sdkmanager
$ANDROID_HOME/tools/bin/avdmanager
```

**Comment by WilliamAntonRohm** [comment]
@PPartisan -- Tom, thank you for your follow-up.  I'm glad you found a solution.

**Comment by Alexs784** [comment]
this still seems to be an issue (I am facing the same). Is there anything missing in the docs that could be causing this indefinite hang when starting the emulator?

Ps: I did try using `/cmdline-tools/latest/`, which solves an exception related to some dependencies missing in Java 17, but doens't solve the emulator hanging and then getting a timeout.

**Comment by joaoantoniomartinsfilho** [comment]
Oi @Alexs784, how are you doing? 

Did you find a solution? I am facing the same problem 😕

**Comment by Alexs784** [comment]
@joaoantoniomartinsfilho no, the funny thing is I have the pipeline running daily but the emulator just hangs and I am out of options 😢

**Comment by ajay-se** [comment]
We too have the same issue, it just hands at launch emulator. The same script works fine on my Mac locally.

**Comment by mendesfelipe87** [comment]
Any news on that? testing the example code gave from the Microsoft documentation but after fixing the call for avdmanager, it freezes and the job give timeout

**Comment by Alexs784** [comment]
Although this doesn't fix the original issue (Azure emulator hanging) I did find an alternative: [gradle managed devices](https://developer.android.com/studio/test/gradle-managed-devices).
My setup is as simple as defining a device in the gradle setup (as shown in the docs) and then having a pipeline running:

```
# Accepting Android SDK licenses
  - script: |
      echo "Accepting Android SDK licenses"
      yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    displayName: Accept Android SDK licenses

# Running instrumented tests through a gradle managed device
  - task: Gradle@1
    displayName: Instrumented tests
    inputs:
      gradleWrapperFile: 'gradlew'
      publishJUnitResults: false
      failTaskOnFailedTests: true
      tasks: 'pixel4api30myFlavorMyVariant -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect'
```

Replace `pixel4api30myFlavorMyVariant` with your device + flavor + variant. Also not sure if the `gpu` flag is strictly needed, but it works in our case with it.

I figured out accepting SDK licenses are still needed in this case, hence the initial script.
