### ISSUE TITLE
Example in "Use a template parameter as part of a condition" is not clear

### ISSUE THREAD

**Issue by stewartadam** [MicrosoftDocs/azure-devops-docs#12449]
The example in the *Use a template parameter as part of a condition* section is not clear. It uses two code snippets, both with default value `true` for the parameter, then clarifies that the expected result is `true` - the lack of differentiation here makes the user liable to miss the point.
<details>
<summary>code snippets in question</summary>

```
# parameters.yml
parameters:
- name: doThing
  default: true # value passed to the condition
  type: boolean

jobs:
  - job: B
    steps:
    - script: echo I did a thing
    condition: and(succeeded(), eq('${{ parameters.doThing }}', 'true'))
```

```
# azure-pipeline.yml
parameters:
- name: doThing
  default: true 
  type: boolean

trigger:
- none

extends:
  template: parameters.yml
```

</details>

I recommend changing the default value in `azure-pipelines.yml` snippet to `false` to demonstrate the difference.

Furthermore, I would also add a new example clarifying that this does not affect *passing* parameters down from azure-pipelines.yml, rather only extending. The following code *does* work as expected, and would cause the job in the child template to be skipped:

<details>
<summary>recommended additional code snippet</summary>

```
# job-with-parameters.yml
parameters:
- name: doThing
  default: true # defaults to true but value from calling pipeline is used
  type: boolean

jobs:
  - job: B
    steps:
    - script: echo I did a thing
    condition: and(succeeded(), eq('${{ parameters.doThing }}', 'true'))
```

```
# azure-pipeline.yml
parameters:
- name: doThing
  default: false
  type: boolean

trigger:
- none

jobs:
  - template: 'job-with-parameters.yml'
    parameters:
      doThing: ${{ parameters.doThing }}
```

</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21e5cee4-eaae-3a96-db91-540ac759e83a
* Version Independent ID: 9bdc837c-ffe0-d999-f922-f3a5debc7f92
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
