### ISSUE TITLE
Error in YAML pipeline:  Deployment strategy: 'Rolling' is not supported for Environment scoped target.

### ISSUE THREAD

**Issue by bholman77** [MicrosoftDocs/azure-devops-docs#12485]
The site shows this example for a rolling deployment: 
jobs: 
- deployment: VMDeploy
  displayName: web
  environment:
    name: smarthotel-dev
    resourceType: VirtualMachine
  strategy:
    rolling:
      maxParallel: 5  #for percentages, mention as x%

However, when I run it, this error appears:  Deployment strategy: "'Rolling' is not supported for Environment scoped target."

It is worth noting that when I try the pipeline without environment it give this error: 
" 
Job ####: Environment is required."
Suggestions? 

Thanks,
Bill

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@bholman77 -- Bill, thank you for your feedback and question.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- Julia, please look into this issue.

**Comment by juliakm** [comment]
I've tried and can't reproduce this issue. Here's my working pipeline for reference. 

```yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:  
  - deployment: VMDeploy
    displayName: web
    environment:
      name: myVM
      resourceType: VirtualMachine
      tags: web1
    strategy:
      rolling:
        maxParallel: 5  #for percentages, mention as x%
        preDeploy:
          steps:
          - script: echo initialize, cleanup, backup, install certs
        deploy:
          steps:
            - script: echo my first deployment
        on:
          failure:
            steps:
            - script: echo Restore from backup! This is a failure
          success:
            steps:
            - script: echo Notify! This is a success
```
