### ISSUE TITLE
Outdated instruction for using output from different stage

### ISSUE THREAD

**Issue by devlie** [MicrosoftDocs/azure-devops-docs#12508]
This instruction in [Use outputs in a different stage](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-stage) does not seem to work:

> At the stage level, the format for referencing variables from a different stage is dependencies.STAGE.outputs['JOB.TASK.VARIABLE']

The only way I could get it to work is to use `stageDependencies` at stage level too.

```yaml
- stage: stage2
  dependsOn: stage1
  variables:
    finalResourceNamePrefix: $[ stageDependencies.stage1.jobA.outputs['prefixCalculator.FinalResourceNamePrefix'] ] # works
    finalResourceNamePrefix: $[ dependencies.stage1.outputs['jobA.prefixCalculator.FinalResourceNamePrefix'] ] # does not work
```

An outdated instruction, perhaps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
