### ISSUE TITLE
Pipeline Triggered from Multiple Other Pipelines

### ISSUE THREAD

**Issue by exwindchiller** [MicrosoftDocs/azure-devops-docs#12515]
The pipelines syntax implies multiple pipelines can trigger this pipeline, but I'm getting vague errors one subsequent pipeline elements.  Does it only support one?

resources:
  pipelines:
  - pipeline: securitylib # Name of the pipeline resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@exwindchiller -- thank you for your feedback and question.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@steved0x -- please look into this issue.

**Comment by steved0x** [comment]
@exwindchiller Sorry for the delay in triaging this issue. Pipeline completion triggers do support triggers on multiple pipelines, for example here is one of my test pipelines with multiple (albeit simple) triggers:

```
resources:
 pipelines:
   - pipeline: source-pipeline
     source: PipelineTriggerSource
     project: FabrikamFiber
     trigger: true
   - pipeline: other-project-pipeline
     source: PipelineTriggerFromOtherProject
     project: FabrikamRepo
     trigger: true

trigger: none # Only trigger with pipeline resource trigger

pool:
  vmImage: windows-latest

jobs:
- job: Test1
  steps:
  - bash: echo $(Resources.TriggeringAlias)
```

It sounds like you may have identified a product issue, if you can provide a simple pipeline to reproduce the issue, could you file a report here:
https://developercommunity.visualstudio.com/AzureDevOps
