### ISSUE TITLE
Functions missing in production slot after deploying to staging slot

### ISSUE THREAD

**Issue by ilantom** [MicrosoftDocs/azure-devops-docs#12537]
I have a function app with 2 slots - staging and production. Both staging and production slots have some functions.

I have the following YAML task to deploy to staging deployment slot:

```
- task: AzureFunctionApp@1
  displayName: 'deploy ${{ parameters.name }} function app (staging)'
  inputs:
    appType: 'functionapp'
    azureSubscription: sub
    appName: 'appname'
    Package: 'name.zip'
    deploymentMethod: 'runFromPackage'
    deployToSlotOrASE: true
    slotName: 'staging'
    resourceGroupName: 'rg' 
```

After deployment I see functions inside staging slot but I see NO functions (or ONLY one function with the same name as function app) inside production slot. What am I missing?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/S8Qh3.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d955bb83-fa46-22e0-de73-7700ae214af8
* Version Independent ID: 1f55672f-711e-24fa-e6bc-edc0ca723eba
* Content: [Azure Web App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-rm-web-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**
