### ISSUE TITLE
Example showing how to use Inline parameter would be useful

### ISSUE THREAD

**Issue by hvl71** [MicrosoftDocs/azure-devops-docs#12589]
It would be super helpful with a few more samples. I cannot read how to use the Inline parameter, so it becomes a bit trial and error instead of just reading the expected syntax and getting it right, right away.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcda4373-62ae-e1ae-c15d-63f441179b47
* Version Independent ID: 305f78c0-2e89-78f2-d2d1-89471602610c
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@hvl71 -- thank you for your feedback and suggestion.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by steved0x** [comment]
@hvl71 I'm adding a new example right now of how to use AzurePowerShell with an inline script.

```
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Placeholder Azure subscription connection'
    azurePowerShellVersion: LatestVersion
    ScriptType: 'InlineScript'
    Inline: |
      # You can write your azure powershell scripts inline here. 
      # You can also pass predefined and custom variables to this script using arguments
      Write-Host 'Hello'
      Write-Host 'World!'
```
