### ISSUE TITLE
Docker cache example - add CLI parameter

### ISSUE THREAD

**Issue by Mikaciu** [MicrosoftDocs/azure-devops-docs#12610]
Hello,

The docker example didn't restore the cache during my tests. For the docker cache to be used, the following argument must be provided to the `Docker@2` task :  `--cache-from $(repository):$(tag)`.

Example:

```yaml
  - task: Docker@2
    displayName: 'Build Docker'
    inputs:
      command: 'build'
      repository: '$(repository)'
      dockerfile: '$(dockerfilePath)'
      tags: |
        '$(tag)'
      build_arguments: '--cache-from $(repository):'$(tag)'
```

HTH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd39237-2778-c4f1-3ce4-bde343ecb59d
* Version Independent ID: e3daf460-128d-cb57-e899-ca0c841dff07
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
