### ISSUE TITLE
Example does not use cached packages

### ISSUE THREAD

**Issue by bpasha7** [MicrosoftDocs/azure-devops-docs#12647]
Example always downloads packages via http.
Working for me this variant.
```
- task: Cache@2
  displayName: 'NuGet Cache'
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
    restoreKeys: |
       nuget | "$(Agent.OS)"
    path: '$(NUGET_PACKAGES)'
    cacheHitVar: 'CACHE_RESTORED'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  condition: ne(variables.CACHE_RESTORED, 'true')
  inputs:
    restoreSolution: '$(solution)'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Version Independent ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Content: [Cache NuGet packages to reduce build time - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/caching-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/caching-nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
