### ISSUE TITLE
About the split expression

### ISSUE THREAD

**Issue by feliasson** [MicrosoftDocs/azure-devops-docs#12697]
The documentation does not clarify whether it is possible to use the split expression in any other scenario other than in each keyword, I would like for example to be able to split an Azure resource-id and then fetch index 8 which would be the resource-name, would that be possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops&source=docs#split)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by feliasson** [comment]
I managed to solve this! 

Example:
##### my-pipeline.yaml
```
  - template: /pipelines/monitoring/monitoring.base.azure-pipelines.yaml
    parameters:
      alerts: ${{ parameters.myalerts }}
      resourceIds: 
      - /subscriptions/<obfuscated>/resourceGroups/<obfuscated>/providers/Microsoft.Network/loadBalancers/kubernetes-internal
      - /subscriptions/<obfuscated>/resourceGroups/<obfuscated>/providers/Microsoft.Network/loadBalancers/kubernetes
```
##### monitoring.base.azure-pipelines.yaml
```
parameters:
  
  # Required
  alerts: []
  resourceIds: []

jobs:

- ${{ each resourceId in parameters.resourceIds }}:

  - ${{ each alert in parameters.alerts }}:

    - job: ${{ replace(split(resourceId, '/')['8'], '-', '_') }}_${{ alert.id }}
      
      steps:
      <my-tasks-here>
```
The result was unique job names based on my resourceIds input to monitoring.base.azure-pipelines.yaml
![image](https://user-images.githubusercontent.com/45947114/190633884-4781dd2b-3573-48e1-ade1-65b74959bdd2.png)

But you should really update your documentation, because most people will look at this expression to be able to generate unique job-names, rather to what is in the current example.

Also, why is it said [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#variables) that you can only call index on variables? I have not seen anything in the documentation mentioned what I did here for a parameter. 

Anyways, I'm happy, I just hope more people will find this so they can solve the same situation I had (since 1+ year back)
