### ISSUE TITLE
Document git repo branch behavior during build validation

### ISSUE THREAD

**Issue by rybal06** [MicrosoftDocs/azure-devops-docs#12703]
## Documentation Request

It would be really helpful to document how git branches and checkouts operate for build validation upon pull request.

It seems like a branch is created like "refs/pull/8468/merge" when build validation pipelines run upon a pull request being raised, which is used as the source branch for the build validation pipeline.

* Why is this?
* How can we interact with it (see Goal below)?
* What options are advisable when automating chores within the source branch upon pull request within ADO? Other CIs (such as GitHub actions) have an on PR trigger, but ADO seems to use the build validation feature to accomplish the same.

## Goal

Our goal is to have execute a pipeline upon on pull request to run a readme generator; and then update the PR source branch with and push back to branch which is triggering the pull request for a human to peer review.

This is so the user can confirm the readme generator did what they expected to provide an opportunity to make any additional changes to the readme generator's configuration templates (in repo). This also brings visibility into what the automated tool is doing rather than being invisible and behind the scenes.

### Implementation

I had this working via a standard yaml pipeline, but it fails to run on pull request via build validation pipelines because the source branch is not as expected, it is something named "refs/pull/8468/merge". The source branch for the PR is "testing-readme-gen".

```yaml
  - checkout: self
    path: SourceRepository
    persistCredentials: true

  - checkout: mysecondrepo
    
  - task: CmdLine@2
    displayName:  Generate README.md
    condition: always()
    inputs:
      script: |
        cd $(Pipeline.Workspace)/SourceRepository
        git config --global user.email "$(Build.RequestedForEmail)" && git config --global user.name "$(Build.RequestedFor)"
        git status
        git checkout $(Build.SourceBranchName)
        <Execute My Readme Generator>
        git add -A
        git commit -m "auto Updated README.md [skip ci]"
        git push -f
```

### Why this fails
The git checkout fails when run from a Pull Request using build validation; because the variable $(Build.SourceBranchName) is set to  "refs/pull/8468/merge" What is this branch?

I tried updating it to $(System.PullRequest.SourceBranch), which fails because it returns refs/heads/mybranchname. I should be able to split this string on the '/' to get the branch name and put it in the git checkout command to workaround that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47abb6d4-0fe9-ddd2-f48b-31fdc040eb7f
* Version Independent ID: a65b02a0-9885-c0e0-b829-e2e66aabbd91
* Content: [Git branch policies and settings - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#build-validation)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
