### ISSUE TITLE
Possible to do a split (and loop) on an output variable?

### ISSUE THREAD

**Issue by RobinZergiebel** [MicrosoftDocs/azure-devops-docs#12836]
We are creating a comma separated list of files as an output variable during one of our stages:

`- script: |
          set -ex
          cd ./packerlogs
          SUCCESSFUL_PACKERLOGS=$(echo $(grep -l "^ManagedImageSharedImageGalleryId:" ./packerlog-*cdh* | xargs -n1 basename) | tr ' ' ,)
          echo "##vso[task.setvariable variable=PackerlogList;isOutput=true]$SUCCESSFUL_PACKERLOGS"
        condition: and(succeeded(), ne(variables['CheckForExistingPackerlogs.ExistingPackerlogs'], 'false'))
        name: SetPackerlogList`

The value of the output variable will be something like "packerlog-cdh-xxx,packerlog-cdh-yyy,...". The amount of comma separated packerlogs is dynamic, not static.

We then want to loop over this output variable using the new split expression:

`- job: Terraform
    dependsOn: GetSubscriptionId
    displayName: terraform
    variables:
      PackerlogList: $[ stageDependencies.AnsibleGoldenImageBuild.AnsibleGoldenImageBuild.outputs['SetPackerlogList.PackerlogList'] ]
      TargetSubscriptionId: $[ dependencies.GetSubscriptionId.outputs['SetTargetSubscriptionId.TargetSubscriptionId'] ]

    pool:
      name: Agent Pool Linux VMSS

    steps:
      - ${{ each file in split(variables.PackerlogList, ',')}}:
        - script: |
            set -ex
            echo "List: $(PackerlogList)"
            echo "File: ${{ file }}"
          displayName: Display PackerlogList and current file value`

However, this unfortunately fails with the following error:

`2022-10-28T13:33:12.5568993Z + echo 'List: packerlog-cdh-xxx,packerlog-cdh-yyy'
2022-10-28T13:33:12.5570653Z /agent/_work/_temp/f9946e18-76ff-4001-9e99-b1dab8350344.sh: line 3: stageDependencies.AnsibleGoldenImageBuild.AnsibleGoldenImageBuild.outputs['SetPackerLogList.PackerlogList'] : syntax error: invalid arithmetic operator (error token is ".AnsibleGoldenImageBuild.AnsibleGoldenImageBuild.outputs['SetPackerLogList.PackerlogList'] ")
2022-10-28T13:33:12.5571897Z List: packerlog-cdh-xxx,packerlog-cdh-yyy
2022-10-28T13:33:12.5596137Z ##[error]Bash exited with code '1'.
2022-10-28T13:33:12.5629775Z ##[section]Finishing: Display PackerLogList and current file value`

So my question is basically: Is something like this even possible? If yes, what would the syntax be like?

Cheers,
Robin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@RobinZergiebel -- Robin, thank you for your question.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- Julia, please look into this issue.

**Comment by pulkitpatel95** [comment]
I have a similar requirement to loop on output variables.

@WilliamAntonRohm  @juliakm can you please confirm if this is possible or not?

**Comment by RobinZergiebel** [comment]
### For everyone running into the same problem (e.g. @pulkitpatel95):

As stated above, I doubt that this is possible due to the split and loop being rendered at compile time.

### We have found a different (though maybe less elegant) solution:

* Pipeline 1 writes a vars.yml file and commits it to Git
* Pipeline 2 triggers on the commit and runs the split and loop on the variable from the vars.yml

### Example code:
* Pipeline 1:
```
stages:
- stage: Commit
  displayName: Commit vars.yml

  jobs:
  - job: Commit
    displayName: Commit vars.yml
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self
        persistCredentials: true

      - script: |
          git config --global user.email robin@test.com & git config --global user.name "Robin Test"
        displayName: Configure git config
        workingDirectory: $(System.DefaultWorkingDirectory)

      - script: |
          git checkout -b auto/$(Build.BuildId)
          find $(System.DefaultWorkingDirectory) -name "vars.yml" -type f -exec sed -i -E "s/PackerlogList: .*/PackerlogList: $(TestList)/g" {} \;
          git add -A
          git commit -am "Pipeline $(Build.BuildId)"
          git push --set-upstream origin auto/$(Build.BuildId)
        displayName: Edit vars.yml and git push
        workingDirectory: $(System.DefaultWorkingDirectory)
```

* Pipeline 2:

```
trigger:
  branches:
    include:
    - auto/*

stages:
- stage: Split
  displayName: Test split

  jobs:
  - job: Split
    displayName: Test split
    variables:
    - template: vars.yml
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - ${{ each file in split(variables.PackerlogList, ',')}}:
        - script: |
            echo "File: ${{ file }}"
          displayName: Display current file value
```

* vars.yml:

```
# File: vars.yml
variables:
  PackerlogList: packerlog-cdh-aaa,packerlog-cdh-bbb
```
