### ISSUE TITLE
succeededOrFailed skips if all previous stages skipped

### ISSUE THREAD

**Issue by AzureMarker** [MicrosoftDocs/azure-devops-docs#12846]
Similar to #2896

The referenced issue got resolved after the bug was fixed, but I'm seeing similar behavior.

If a pipeline is run where the first stage is skipped due to a `condition` field and the second stage depends on the first (implicitly, if it matters) and uses the `succeededOrFailed` condition, the second stage gets skipped as well.

If the pipeline is queued so that only the second stage runs, it actually runs (doesn't get skipped).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@AzureMarker -- Mark, thank you for your detailed feedback and suggestions.  To vote to change the behavior of `succeededOrFailed()`, please add that here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

@juliakm -- Julia, please look into this potential documentation issue.

**Comment by juliakm** [comment]
Thank you for your detailed note. I apologize for the delay in responding. I think that this is a bug-type issue more than a documentation one. I'll make a note in the  `succeededOrFailed` section that `not(canceled())` may make more sense if you find that stages you wouldn't expect get skipped. 

Here's a pipeline for testing that demonstrates what you've described. When I switch to using `succeededOrFailed()` in job b, the second job gets skipped. 

```
jobs:
- job: a
  condition: false
  pool: 
    vmImage: ubuntu-latest
  steps:
  - script: printenv|sort
- job: b
  dependsOn: a
  #condition: succeededOrFailed()
  condition: not(canceled())
  pool: 
    vmImage: ubuntu-latest
  steps:
  - script: printenv|sort
- job: c
  dependsOn:
  - a
  - b
  condition: |
    and
    (
      in(dependencies.a.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'),
      in(dependencies.b.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    )
  pool: 
    vmImage: ubuntu-latest
  steps:
  - script: printenv|sort
```
