### ISSUE TITLE
YAML Won't accept feed/package names

### ISSUE THREAD

**Issue by thegreatpeon** [MicrosoftDocs/azure-devops-docs#12875]
I'm having a hard time getting this task to accept feed/package names rather than the IDs that you can only see from the Pipeline Editor in Azure DevOps. Every other task lets you do this so I'm assuming there's some proper syntax that I'm missing, but everything I've tried results in a "Cannot find the package '$(packagename)'" error or something similar.

Whether I use a variable or the name doesn't seem to matter, the only value it accepts is the ID.

**UPDATE**
So I took another look at things and found that Organization level feeds work just fine, but the Project feeds that I'm trying to access are the ones that are causing problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b934d9e8-d417-1f45-dc87-e0dc25219c97
* Version Independent ID: 14bbdf7d-0608-f517-3b10-26d0e83eca85
* Content: [Universal Package, download and publish task - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/package/universal-packages.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @arob98
* Microsoft Alias: **angrobe**

**Comment by WilliamAntonRohm** [comment]
@thegreatpeon -- Adam, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@arob98 -- Angela, please look into this potential documentation issue.

**Comment by thegreatpeon** [comment]
Update with some more context for you to work with. Both of these tasks work correctly as they are currently written. The first is pointing to an Organization scoped feed and the second is pointing to a Project scoped feed.

If I replace vstsFeed in Task 2 with the name of the feed, I get the following command and error:
```
C:\agent\_work\_tool\artifacttool\0.2.254\x64\ArtifactTool.exe universal download --feed SequoiaReadme@Release --service https://dev.azure.com/USNR-EWP/ --package-name dry-chain-readme --package-version 1.0.* --path "C:\agent\_work\6\a/Sequoia Sentry v2 DCS-Clean" --patvar UNIVERSAL_DOWNLOAD_PAT --verbosity Error --filter **
```
```
{"@t":"2022-11-10T23:29:56.9242153Z","@m":"The feed with ID 'SequoiaReadme' doesn't exist.","@i":"e06a1e2f","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2022-11-10 23:29:56.924Z"}
```
If I replace vstsFeedPackage in Task 2 with a variable that contains either the name or ID of the package, I get the following command and error:
```
C:\agent\_work\_tool\artifacttool\0.2.254\x64\ArtifactTool.exe universal download --feed 71425077-ffbf-4360-8f99-83574b284f1e --service https://dev.azure.com/USNR-EWP/ --package-name $(readmepackage) --package-version 1.0.* --path "C:\agent\_work\41\a\Sequoia Sentry v2 DCS-Debug" --patvar UNIVERSAL_DOWNLOAD_PAT --verbosity Debug --project 08da60ce-8eea-4a5f-892f-0bd7ee77bb1c
```
```
{"@t":"2022-11-10T23:30:07.5903571Z","@m":"ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 31b65051-1275-44aa-a6f1-4558df3f3952","@i":"50aac9d7","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2022-11-10 23:30:07.590Z"}

{"@t":"2022-11-10T23:30:07.7931181Z","@m":"ApplicationInsightsTelemetrySender did not correlate any events with X-TFS-Session 31b65051-1275-44aa-a6f1-4558df3f3952","@i":"ef542fb9","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2022-11-10 23:30:07.793Z"}

##[debug]Agent.Version=2.200.2

{"@t":"2022-11-10T23:30:07.7937974Z","@m":"Cannot find the package '$(readmepackage)' in feed '71425077-ffbf-4360-8f99-83574b284f1e'","@i":"9d7f4752","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2022-11-10 23:30:07.793Z"}
```

```
- task: UniversalPackages@0
      displayName: Download the INI files
      inputs:
        command: 'download'
        downloadDirectory: '$(download_location)'
        feedsToUse: 'internal'
        vstsFeed: 'Sequoia_Configuration_Files'
        vstsFeedPackage: '$(inifiles)'
        vstsPackageVersion: '$(inifilesversion)'
    - task: UniversalPackages@0
      displayName: Download the Readme files
      inputs:
        command: 'download'
        downloadDirectory: $(download_location)
        feedsToUse: 'internal'
        vstsFeed: '08da60ce-8eea-4a5f-892f-0bd7ee77bb1c/71425077-ffbf-4360-8f99-83574b284f1e'
        vstsFeedPackage: '87ca88e6-dc4e-4bd3-aa0b-4c53465eec12'
        vstsPackageVersion: '1.0.*'
```
