### ISSUE TITLE
Azure Devops Run time parameter support

### ISSUE THREAD

**Issue by DillyBabu** [MicrosoftDocs/azure-devops-docs#12870]
In Azure Devops, If I trigger a pipeline manually, the follow code successfully picks up my value and output is displayed. But if I trigger this pipeline by automatic(like pushing the code from vscode to branch) then it gives the following error:

**Error: "A value for the 'terraformAction' parameter must be provided."** 

I am not able to see any reference in Microsoft Document on how to send a run time parameters to the pipeline execution. Is this the normal behavior of YAML pipeline? 

Also, Kindly let me know if there is any work around for this. Thanks!

```
parameters:
  - name: terraformAction
    displayName: Apply/Destroy
    values:
      - Apply
      - Destroy

stages:
  - stage: TERRAFORM_APPLY
    condition: eq('${{ parameters.terraformAction }}', 'Apply')
      - job: 
        steps:
        - script: |
           echo "The Selected Action is ${{ parameters.terraformAction }} "

  - stage: TERRAFORM_DESTROY
    condition: eq('${{ parameters.terraformAction }}', 'Destroy')
    jobs:
      - job: 
        steps:
        - script: |
           echo "The Selected Action is ${{ parameters.terraformAction }} "
```
