### ISSUE TITLE
Example of kubectl in a script with an environment

### ISSUE THREAD

**Issue by m1o1** [MicrosoftDocs/azure-devops-docs#12892]
Please add an example showing how to use kubectl in a script using an environment with a kubernetes resource.

Currently facing an error where it seems the kubectl config is not set (all fields in `kubectl config view` are null or empty strings), even though I set it up to use the environment with access.

The docs say it should be possible in the [alternatives section](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/deploy?view=azure-devops#alternatives), but I don't know how to get the script to actually connect.

I set up a test pipeline like this:
```yaml
stages:
- stage: TestGetPodsAllNamespacesDev
  displayName: Get pods in all namespaces
  jobs:
  - deployment: 'GetAllPods'
    environment: 'test-cluster-dev'
    displayName: 'Get pods in all namespaces'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: none
          - task: Bash@3
            inputs:
              targetType: inline
              script: |-
                kubectl config view
                kubectl get pods --all-namespaces
```

I followed the instructions here to use an existing service account for my environment (I want to control the RBAC, not have it limited to one namespace):
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops#use-an-existing-service-account

I started by making a custom service account with a token:
```bash
kubectl create serviceaccount test-pipeline
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: test-pipeline-secret
  annotations:
    kubernetes.io/service-account.name: test-pipeline
type: kubernetes.io/service-account-token
EOF
kubectl create clusterrolebinding test-pipeline --clusterrole=view --serviceaccount=<my-namespace>:test-pipeline
```
I set the service account to reference the new secret. Then I copied the service account secret into the environment (using the generic provider).
Also did `kubectl config view` to get the endpoint.
I had to set it to allow untrusted certificates but ultimately the validation passed and I could see my workloads/services in the environment.

But now, when I try to run my pipeline, it has the issue described, where I guess it doesn't know where the kubectl config is stored that comes with the environment.

Any help is appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4b03aab-449c-0cc1-330f-e9b8c083468b
* Version Independent ID: d390143a-ec80-48ec-09ad-099c8de62382
* Content: [Deploy to Kubernetes - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/deploy?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/kubernetes/deploy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/kubernetes/deploy.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**
