### ISSUE TITLE
Repository Trigger - None Azure Repos

### ISSUE THREAD

**Issue by coolhome** [MicrosoftDocs/azure-devops-docs#12962]
I'm a bit confused by this statement because my code was triggered. Is this outdated or am I missing something?

`trigger:  # CI trigger for this repository, no CI trigger if skipped (only works for Azure Repos)`

```yaml
resources:
  repositories:
    - repository: SourceCode
      type: githubenterprise
      name: DevOps/Automation
      endpoint: GitHub Enterprise - DevOps
      trigger:
        branches:
          include:
            - refs/heads/master
        tags:
          include:
            - "*"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Define YAML resources for Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/resources.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
