### ISSUE TITLE
Inconsistent case in variable names

### ISSUE THREAD

**Issue by crowne** [MicrosoftDocs/azure-devops-docs#12989]
[Enter feedback here]

The sample code under heading [Publish packages to your pipeline](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/publish-maven-artifacts?view=azure-devops#publish-packages-to-your-pipeline)

shows two different cases for the same variable name $(build.artifactstagingdirectory) | $(Build.ArtifactStagingDirectory)
Are these variables case sensitive?

```yaml
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3861f31f-cee5-6df2-247a-bcceff91977d
* Version Independent ID: 3861f31f-cee5-6df2-247a-bcceff91977d
* Content: [Publish Maven artifacts - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/publish-maven-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/publish-maven-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/publish-maven-artifacts.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
