### ISSUE TITLE
Incorrect package name/path of a package using azure cache for Nuget.

### ISSUE THREAD

**Issue by maks200179** [MicrosoftDocs/azure-devops-docs#12985]
Hi folks. 
My cache config.

```
- task: Cache@2
  displayName: 'NuGet Cache'
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: '$(System.DefaultWorkingDirectory)\\project_name/packages'
    cacheHitVar: 'CACHE_RESTORED'
```

For example the correct path is packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets.
But after the cache restored using azure devops cache it appear under wrong path packages\microsoft.bcl.build\1.0.21\build\Microsoft.Bcl.Build.targets 
Then msbuild fail due package not found.
How can i change the package path ?

_Originally posted by @maks200179 in https://github.com/MicrosoftDocs/azure-devops-docs/issues/7572#issuecomment-1345784695_
