### ISSUE TITLE
Please document if and how the build name can be set within a yaml template

### ISSUE THREAD

**Issue by housten** [MicrosoftDocs/azure-devops-docs#13002]
Confusion over if this is possible has been discussed previously on [StackOverflow](https://stackoverflow.com/questions/59684253/how-to-set-build-name-build-buildnumber-in-an-azure-devops-build-pipeline-temp) without a clear resolution (no selected answer) and 13k views. There is still no clarification in the template documentation.
Can it be done? And if so, how?

USE CASE
To minimize (accidental) variation in build naming, as well as to have a central way to update naming conventions, we would like to define the build name in some of our templates, but on usage with an extends this causes the error `Unexpected value 'name'`. Below is an example of the top of the template file. Since we are including stages in the template, and name is a property of stages it seems logical for this to work.
```
parameters:
- name: 'NugetVersion'
  type: string
  default: 6.3.1

stages:
- stage: secure_buildstage

  pool:
    name: default

  name: '$(Build.DefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.rr)'

  variables:
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
