### ISSUE TITLE
How do you use this in a more complex pipeline

### ISSUE THREAD

**Issue by icfly2** [MicrosoftDocs/azure-devops-docs#13032]
The basic next step is for the module to be build and pushed to pypi.

However, it is not clear how this can be achieved as the usual build and publish steps would be run for each python version leading to pypi rejecting the upload after the first python version has succeeded, leading to the rest of the matrix failing 

```

trigger:
- add_pipeline

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10' 
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

- script: |
    pip install hatch
    hatch run cov  
  displayName: 'hatch'

- script: |
    hatch version $(Build.BuildId)
    hatch build
    hatch publish
  displayName: 'publish'
````

the publish script fails for all version of python but the first one to complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 545519f0-468e-e8cd-86e7-37f03ae82dc4
* Version Independent ID: d216e8fe-d5d6-f9e6-2115-37d32d03cf76
* Content: [Quickstart - Use Azure Pipelines to build and publish a Python app - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/python.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/python.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
