### ISSUE TITLE
The article wrongfully suggests to create a virtual environment that is ported to an Azure app service

### ISSUE THREAD

**Issue by LowerKees** [MicrosoftDocs/azure-devops-docs#13044]
The article suggests to create a virtual environment which is ported to the app service. However, the Python documentation on virtual environment portability is very clear: 

> [environments are inherently non-portable](https://docs.python.org/3/library/venv.html#how-venvs-work)

I believe this invalidates most of the article and I would suggest rewriting it to either leverage the ORYX build service or use Docker containers. 

Steps that underline my point:

The first step that creates the virtual environment is detailed in the following code block:

```yaml
steps:
    - task: UsePythonVersion@0
       inputs:
         versionSpec: '$(pythonVersion)'
         displayName: 'Use Python $(pythonVersion)'
    - script: |
         python -m venv antenv
         source antenv/bin/activate
         python -m pip install --upgrade pip
         pip install setup
         pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
       workingDirectory: $(projectRoot)
       displayName: "Install requirements"
```

Next, the virtual environment and all installed dependencies are archived in a zip file that is later used in a zip deploy step. These steps combined show that the article suggests to port the virtual environment created on a build agent and deploy this to an Azure app service.

This is also illustrated by the following code block:

```yaml
- task: ArchiveFiles@2
   inputs:
     rootFolderOrFile: '$(Build.SourcesDirectory)'
     includeRootFolder: false
     archiveType: 'zip'
     archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
     replaceExistingArchive: true
     verbose: # (no value); this input is optional
- publish: $(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip
   displayName: 'Upload package'
   artifact: drop
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 744eaf3c-85c6-2092-823a-8a709018b5f7
* Version Independent ID: 3ed6d4b4-334f-775b-f783-912b76124557
* Content: [Build and deploy Python web apps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/python-webapp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/python-webapp.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
