### ISSUE TITLE
Examples missing on how to checkout a commit using ref

### ISSUE THREAD

**Issue by ilantom** [MicrosoftDocs/azure-devops-docs#13058]
Please add examples on how to checkout a specific ref:

```
- checkout: git://MyProject/MyRepo@refs/tags/MyTag # checks out the commit referenced by MyTag.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checking-out-a-specific-ref)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/multi-repo-checkout.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@ilantom -- thank you for your suggestion.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@steved0x -- please look into this issue.

**Comment by steved0x** [comment]
@ilantom Thank you for providing an example of this:

The following example checks out the commit referenced by `MyTag`.

```yaml
resources:
  repositories:
  - repository: MyGitHubRepo
    type: github
    endpoint: MyGitHubServiceConnection
    name: MyGitHubOrgOrUser/MyGitHubRepo
    ref: refs/tags/MyTag

steps:
- checkout: MyGitHubRepo
```

This will go live in the docs later today. Thank you.
