### ISSUE TITLE
Clarify stage to stage dependency syntax

### ISSUE THREAD

**Issue by prayaas-a** [MicrosoftDocs/azure-devops-docs#13063]
Currently, output variables from stage-to-stage dependencies appear to be accessible in two distinct ways, only one of which is properly documented.

When used for a condition, the proper syntax is `dependencies.<stage>.outputs['<job>.<task>.<variable>']`. This is well documented.

However, to map such a variable to all jobs at the stage scope, one must instead use `stageDependencies.<stage>.<job>.outputs['<task>.<variable>']`. The Dependencies section has the following text (emphasis added):

> The context is called dependencies for jobs and stages and works much like variables. **Inside a job**, if you refer to an output variable from a job in another stage, the context is called stageDependencies.

The highlighted part appears to be false considering you need to use the `stageDependencies` syntax even at the stage scope when setting a variable. This language should be corrected. Further, on [this page](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-stage), there is a brief mention of the `stageDependencies` format being relevant at the stage level. However, the examples use it only in the context of a job, not a stage. In my opinion, an example (such as the one below) should be added to show that it is possible/required to use both syntaxes at the stage scope.

```
- stage: ExampleStage
  dependsOn: OtherStage
  condition: eq(dependencies.OtherStage.outputs['OtherJob.Task.BooleanVariable'], 'true')
  variables:
    otherString: $[stageDependencies.OtherStage.OtherJob.outputs['Task.StringVariable']]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
