### ISSUE TITLE
The example for conditional job running based output vars is broken

### ISSUE THREAD

**Issue by mhvelplund** [MicrosoftDocs/azure-devops-docs#13098]
This is the example:

```yaml
jobs:
- job: A
  steps:
  - script: "echo ##vso[task.setvariable variable=skipsubsequent;isOutput=true]false"
    name: printvar

- job: B
  condition: and(succeeded(), ne(dependencies.A.outputs['printvar.skipsubsequent'], 'true'))
  dependsOn: A
  steps:
  - script: echo hello from B
```

It "works", but only because `dependencies.A.outputs['printvar.skipsubsequent']` always evaluates to NULL. This is easy to demonstrate by changing the example to the logically equivalent:

```yaml
jobs:
- job: A
  steps:
  - script: "echo ##vso[task.setvariable variable=skipsubsequent;isOutput=true]false"
    name: printvar

- job: B
  condition: and(succeeded(), eq(dependencies.A.outputs['printvar.skipsubsequent'], 'false'))
  dependsOn: A
  steps:
  - script: echo hello from B
```

Now step B is skipped with the helpful message:

```
Started: Just now
Duration: 36s
Evaluating: and(succeeded(), eq(dependencies['A']['outputs']['printvar.skipsubsequent'], 'false'))
Expanded: and(True, eq(Null, 'false'))
Result: False
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95227592-b2a9-62be-59d1-fe8c7f4eae8e
* Version Independent ID: abf0c659-ce8c-b187-2784-22ddc061d69f
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/phases.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by mhvelplund** [comment]
I found the error in the example.

```yaml
script: "echo ##vso[task.setvariable variable=skipsubsequent;isOutput=true]false"
```
... echoes nothing, because '#' makes the rest of the line a comment.

Addeing single-quotes fixes it, so it works for the logical equivalent as well:

```yaml
jobs:
- job: A
  steps:
  - script: "echo '##vso[task.setvariable variable=skipsubsequent;isOutput=true]false'"
    name: printvar

- job: B
  condition: and(succeeded(), eq(dependencies.A.outputs['printvar.skipsubsequent'], 'false'))
  dependsOn: A
  steps:
  - script: echo hello from B
```
