### ISSUE TITLE
Poor examples which compare boolean parameter and 'true'

### ISSUE THREAD

**Issue by SBFrancies** [MicrosoftDocs/azure-devops-docs#13126]
There are examples in the code which show a comparison of a boolean parameter with a string, for example here: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

```
parameters:
- name: doThing
  default: true
  type: boolean

steps:
- script: echo I did a thing
  condition: and(succeeded(), eq('${{ parameters.doThing }}', 'true'))
```
This works as expected but only because `'true'` resolves to a truthy value. The following line would have the same effect:

`condition: and(succeeded(), eq('${{ parameters.doThing }}', 'false'))`

I don't think this would be expected by someone reading the docs. A better example can be found on this page: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

```
#azure-pipeline.yml
parameters:
- name: experimentalTemplate
  displayName: 'Use experimental build process?'
  type: boolean
  default: false

steps:
- ${{ if eq(parameters.experimentalTemplate, true) }}:
  - template: experimental.yml
- ${{ if not(eq(parameters.experimentalTemplate, true)) }}:
  - template: stable.yml
```

Note how `true` is not enclosed in quotes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21e5cee4-eaae-3a96-db91-540ac759e83a
* Version Independent ID: 9bdc837c-ffe0-d999-f922-f3a5debc7f92
* Content: [Conditions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml%2Cstages)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/conditions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
