### ISSUE TITLE
pipeline resource doesn't trigger for sibling pipelines unless project name is specified 

### ISSUE THREAD

**Issue by p-m-j** [MicrosoftDocs/azure-devops-docs#13142]
> project: FabrikamProject - If the triggering pipeline is in another Azure DevOps project, you must specify the project name. This property is **optional if both the source pipeline and the triggered pipeline are in the same project**. If you specify this value and your pipeline doesn't trigger, see the note at the end of this section.

This doesn't appear to be correct once a branch filter is added

## Broken
```yml
trigger: none

resources:
  pipelines:
  - pipeline: securitylib
    source: security-lib-ci
    trigger:
      branches:
        include:
        - develop

steps:
- bash: echo "app-ci runs after security-lib-ci completes"
```
## Working

```yml
trigger: none

resources:
  pipelines:
  - pipeline: securitylib
    project: demo-project # <--- This right here
    source: security-lib-ci
    trigger:
      branches:
        include:
        - develop

steps:
- bash: echo "app-ci runs after security-lib-ci completes"

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/pipeline-triggers.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
