### ISSUE TITLE
Please add an example for a variable used as a task condition in the same job as it is declared

### ISSUE THREAD

**Issue by Miles-Davies-HORIBA** [MicrosoftDocs/azure-devops-docs#13185]
This is generally an excellent piece of work with many good example of use cases.
It does seem to be missing the use case of a variable declared in a task used as a condition in a following task in the same job.
I think this would be helpful since this syntax isn't obvious to me.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92ad0d9b-2e51-de2e-a529-6cbe55692023
* Version Independent ID: 609b6196-cc6b-677a-c76f-f82bb7cce10a
* Content: [Set variables in scripts - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash#levels-of-output-variables)
* Content Source: [docs/pipelines/process/set-variables-scripts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/set-variables-scripts.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@Miles-Davies-HORIBA -- Miles, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- Julia, please look into this issue.

**Comment by juliakm** [comment]
@Miles-Davies-HORIBA Here's an example. The variable `isProd` is set to `false` in the `variables` section of the YAML pipeline. This variable is then used as a condition for the PublishBuildArtifacts task. The task does not run because the condition `eq(variables.isProd, true)` means that the task will only run if the value of the `isProd` variable is true.



```yaml
pool:
  vmImage: ubuntu-latest

variables:
  isProd: false

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - script: echo 'This is a build job.'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts'
    condition: eq(variables.isProd, true) # task skips because of isProd is false
```

I'll add a similar example to our docs.

**Comment by Miles-Davies-HORIBA** [comment]
> @Miles-Davies-HORIBA Here's an example. The variable `isProd` is set to `false` in the `variables` section of the YAML pipeline. This variable is then used as a condition for the PublishBuildArtifacts task. The task does not run because the condition `eq(variables.isProd, true)` means that the task will only run if the value of the `isProd` variable is true.
> 
> ```yaml
> pool:
>   vmImage: ubuntu-latest
> 
> variables:
>   isProd: false
> 
> jobs:
> - job: Build
>   displayName: 'Build job'
>   steps:
>   - script: echo 'This is a build job.'
>   - task: PublishBuildArtifacts@1
>     displayName: 'Publish build artifacts'
>     condition: eq(variables.isProd, true) # task skips because of isProd is false
> ```
> 
> I'll add a similar example to our docs.

Hi Julia, thanks for the quick reply. The example you propose is similar to other examples and doesn't address my feedback. I apologise if my feedback was not clear.

I would like an example of a task creating a variable using the logging commands and a following task using that variable as a condition. I think the syntax for this use case is complex and finding the solution was tricky for me. The proposed example doesn't cover my use case and is pretty simplistic. The example below covers my use case I think

`
steps:
  - powershell: |
      Write-Host "##vso[task.setvariable variable=ShouldRun;isoutput=true]$true"
    name: CheckShouldRunStep

  - powershell: |
      Write-Host "##[debug]Conditional step is being run"
   condition: |
       and(succeeded(), eq(variables['CheckShouldRunStep.ShouldRun'], 'true')
`

**Comment by juliakm** [comment]
@Miles-Davies-HORIBA Thanks for the clarification. Here's an updated example. 

```yaml
pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  displayName: 'Build job'
  steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Create a variable using the logging command
          echo '##vso[task.setvariable variable=isProd;isOutput=true]false'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      condition: eq(variables.isProd, true) # task skips because of isProd is false
```

There are some more detailed examples in our [conditions article](https://learn.microsoft.com/azure/devops/pipelines/process/conditions?source=recommendations&view=azure-devops&tabs=yaml%2Cstages#use-the-output-variable-from-a-job-in-a-condition-in-a-subsequent-job). I'll add a link to that article.
