### ISSUE TITLE
Formatting error on example step and invalid key

### ISSUE THREAD

**Issue by PontiusTheBarbarian** [MicrosoftDocs/azure-devops-docs#13213]
I think there are two problems with this example. One being that the `YAML` is invalid where `displayName:` and `script:` keys are on the same line. The second being that the docs for `AzurePowerShell@5`  [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) don't specify a 'script' key or alias, only a `ScriptType`, which contains a similar value. The 'script' key should also be nested in the `inputs` section.
```
- task: AzurePowerShell@5
  displayName: Azure PowerShell script: FilePath
  inputs:
    azureSubscription: '$(AzureSubscription)'
    ScriptPath: '$(Build.SourcesDirectory)\scripts\SetAzureFirewallRule.ps1'
    ScriptArguments: '-ServerName $(ServerName) -ResourceGroupName $(ResourceGroupName)'
    azurePowerShellVersion: LatestVersion
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81f4ee44-6500-b0e6-62d8-7a23e5b461fa
* Version Independent ID: 75bd021b-fed5-f258-315d-0ef8628fb887
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/targets/azure-sqldb.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-targets**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
