### ISSUE TITLE
Add details about lack of permissions for cross-project same-org repo templates

### ISSUE THREAD

**Issue by GarrettGeorge** [MicrosoftDocs/azure-devops-docs#13228]
Currently there's no documentation about how permissions for templates are managed. As an org or project administrator, I am under the impression that I can restrict read permission to my repo. However this is not the case as evidenced in the following pipeline:

```yaml
trigger: none

resources:
  repositories:
    - repository: common-templates
      type: git
      name: CommonAzureDevops/CommonAzureDevops
      ref: master

jobs:
  # track deployments on the environment
- job: Playground
  displayName: Pipeline used for testing new pipelines
  pool:
    name: azure

  steps:
  - template: templates/k8s-login.yaml@common-templates
    parameters:
      kubernetesServiceEndpoint: cluster-namespace
```
In this pipeline, for whatever reason, I'm technically able to read partial content from a repository and there's no way to restrict this. 

If I want to prevent cross-project repo reading, I can during the `steps.checkout` command because it's using the organization/project job scoped access token _but_ when I use `steps.template` there's no permission based check. I understand why this happens, because the template parser expands all templates server-side before even sending the eventual pipeline YAML to the agent. 

Some guidance would also be greatly appreciated on how we can deny pipelines in project A from using templates in project B's repo. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
