### ISSUE TITLE
Confusing phrase: "pass those parameters to a pipeline."

### ISSUE THREAD

**Issue by carlin-q-scott** [MicrosoftDocs/azure-devops-docs#13246]
The section on parameter passing says that I can "define parameters in a template and pass those parameters to a pipeline." The relationship is the reverse of that. I can pass parameters to a template. The example for parameter passing shows exactly this.

I was hoping that I could define pipeline parameters in a template that can be set at build time. But this doesn't seem to be supported, despite the quoted sentence indicating that it is. Basically, I want the equivalent of a variable template, but for build pipeline parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@carlin-q-scott -- Carlin, nice to hear from you again.

@juliakm -- Julia, please look into this issue.

**Comment by carlin-q-scott** [comment]
Sure @juliakm.

parameters.yaml
```yaml
parameters:
- name: buildConfiguration
  type: string
  default: Release
  values:
  - Release
  - Debug
- name: buildRuntime
  type: string
  default: Any CPU
  values:
  - Any CPU
  - x86
  - x64
```

azure-pipeline.yaml
```yaml
parameters:
- template: parameters.yaml@templates

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: >-
      --configuration ${{ parameters.buildConfiguration }}
      --runtime ${{ parameters.buildRuntime }}
```
