### ISSUE TITLE
How to use queue time variable in conditional insertion in a template?

### ISSUE THREAD

**Issue by AlfredWang01** [MicrosoftDocs/azure-devops-docs#13332]
Hi folks, 

I'm trying to set some variables in a task dynamically in a template, I need use a value from a queue time variable as condition.

1. First, I tried to use that queue time variable directly like followings, but cannot make it work:

```
  variables:
    ${{ if eq( variables.MyVariable, 'true' ) }}: 
      MyFlag: Good
    ${{ if ne( variables.MyVariable, 'true' ) }}: 
      MyFlag: Bad
```

2. Then, I tried to pass in a parameter to my template, and then use this parameter as condition to set my variable, the parameter can get the correct value, but I still cannot set my variable correctly, code like followings:

Use a template:
```
- template: templates/stage_build_sign_codeconnection_mac.yml
  parameters:
    MyParam: $(MyVariable)
```

Use parameter in conditional insertion in template:
```
parameters:
  - name: MyParam
    type: string
    default: ''

stages:

- stage: my_stage
  variables:
    ${{ if eq( parameters.MyParam, 'true' ) }}: 
      MyFlag: Good
    ${{ if ne( parameters.MyParam, 'true' ) }}: 
      MyFlag: Bad
```

I can get right value in template for displayName of task by compile time variable format:

`displayName: My param ${{ parameters.MyParam}}`

Could you give me a help on this?

Thanks.
