### ISSUE TITLE
Need example on consuming variables in lifecycle hooks

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/azure-devops-docs#13373]
[Enter feedback here]
- [Following the advice here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#support-for-output-variables), only examples are provided where there output variable is set as part of a deployment job.
- There needs an example of how to consume output variables from jobs (in the same stage), and pass them into a deployment job

**Why?**
- I'm currently getting null values passed through (from a job output var, to a deployment input var) and have no concrete examples to see if their are any syntax issues with my YAML, or if there is a bug, or if this feature is unsupported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/deployment-jobs.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@adriantorrie -- Adrian, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- Julia, please look into this issue.

**Comment by juliakm** [comment]
@adriantorrie Could you please provide a sanitized example of your YAML pipeline?

**Comment by juliakm** [comment]
Closing due to lack of response.

**Comment by juliakm** [comment]
@adriantorrie Here's a YAML that it's working. The trick for me was to add dependsOn. 

```yaml
trigger:
- '*'

jobs:
- job: A
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo "##vso[task.setvariable variable=myOutputVar;isoutput=true]this is from job A"
    name: passOutput

- deployment: B
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    myVarFromJobA: $[ dependencies.A.outputs['passOutput.myOutputVar'] ]  
  environment: staging
  dependsOn: A
  strategy:
    runOnce:
      deploy:
        steps:
        - bash: echo $(myVarFromJobA) #does render after adding dependsOn:A
```
