### ISSUE TITLE
Getting Validation Errorr: "Job : Step references task 'ManualValidation' at version '0.179.0' which is not valid for the given job target."

### ISSUE THREAD

**Issue by Turhan8** [MicrosoftDocs/azure-devops-docs#13382]
I am getting validation error for the release pipeline below:
```
name: $(Release.Artifacts._Yaml.BuildNumber)
trigger: none

variables:
  stagingPath: '\\staging\'
  testingPath: '\\testing\'
  productionPath: '\\production'

stages:
- stage: QA
  jobs:
  - job: ManualApproval
    displayName: Wait for external validation 
    pool: DataAnalyticsPool
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # job times out in 1 days
      inputs:
        notifyUsers: |
          turhan.ozen@edftrading.com
        instructions: "Please validate"
        onTimeout: reject
```

This is the validation error:
Job ManualApproval: Step references task 'ManualValidation' at version '0.179.0' which is not valid for the given job target.
