### ISSUE TITLE
wrong documentation sample

### ISSUE THREAD

**Issue by mortaelth** [MicrosoftDocs/azure-devops-docs#13399]
the following example of how to use variable groups does not work:

---
To reference a variable group, use macro syntax or a runtime expression. In the following example, the group my-variable-group has a variable named myhello.

```yaml
variables:
- group: my-variable-group
- name: my-passed-variable
  value: $[variables.myhello] # uses runtime expression

steps:
- script: echo $(myhello) # uses macro syntax
- script: echo $(my-passed-variable)
```
---
in order to make it work, I had to adjust it to this:

```yaml
variables:
- group: my-variable-group
- name: my-passed-variable
  value: $(myhello)
```

(myhello is variable inside the my-variable-group)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a872110-349f-1957-ae25-b2bf5275167c
* Version Independent ID: 4044ea34-94c6-a5eb-161d-c01b0b053aca
* Content: [Variable groups for Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/library/variable-groups.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**
