### ISSUE TITLE
Yaml parameter typing inconsistent when converting yaml object to JSON.

### ISSUE THREAD

**Issue by Erich-McMillan** [MicrosoftDocs/azure-devops-docs#13472]
## Issue:

Docs unclear on parameter typecast when using parameter to populate yaml object for template parameter.

## How to repro

1. Create a template which accepts an object parameter then converts to json in pwsh
    ```yaml
    # /templateA.yml
    parameters:
    - name: Configuration:
      type: object
      
    steps:
    - pwsh: |
          $jsonStr = @"
            ${{ convertToJson(parameters.Configuration) }}
          "@
          Write-Host "jsonStr is $jsonStr"
    ```

2. Create a calling template/pipeline where one value of the yaml obj param is hardcoded to boolean the other is populated from a boolean parameter

   ```yaml
   trigger: none

   parameters:
   - name: booleanParam
     default: true
     type: boolean

   ...
   - templateA.yml
     parameters:
        Configuration:
            parameterA: ${{ parameters.booleanParam }}
            parameterB: true
   ```

3. Run the output and observe the json string produced:

   ```json
   {
      "parameterA": "True",
      "parameterB": true
   }
   ```

Even though both should be boolean parameters I was expecting both to be `: true` not `: "True"` for one and `: true` for the other.

The output should be:

   ```json
   {
      "parameterA": true,
      "parameterB": true
   }
   ```

At least based on the docs https://learn.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script boolean should be `true` or `false`. So why does this end up as `"True"`.

Maybe I missed something in the docs somewhere?

Thanks :)

**Comment by juliakm** [comment]
I'm seeing the same thing. If I understand correctly, the `convertToJson()` expression returns what looks like a string version of "True" for when you set the value as a parameter and a boolean when the value in an object is set to `true`. I think that this may be a product issue and not a documentation one. I'll let the product team know but you may be able to get your issue resolved faster by posting in the [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps), which is actively monitored by the support team. 

Here are the pipelines I used to verify. 

```yaml
#azure-pipelines.yml

pool:
    vmImage: 'ubuntu-latest'

# trigger: none

parameters:
- name: booleanParam
  default: true
  type: boolean

steps:
- template: templateA.yml
  parameters:
    Configuration:
      parameterA: ${{ parameters.booleanParam }}
      parameterB: true
```

```yaml
# templateA.yml
parameters:
- name: 'pool'
  type: object
  default: {}
- name: 'Configuration'
  type: object
  default: {}
  
steps:
- pwsh: |
      $jsonStr = @"
        ${{ convertToJson(parameters.Configuration) }}
      "@
      Write-Host "jsonStr is $jsonStr"
```
