### ISSUE TITLE
Incorrect documentation dynamic build number variables

### ISSUE THREAD

**Issue by GooseLF** [MicrosoftDocs/azure-devops-docs#13508]
The documentation in [this](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&amp%3Btabs=yaml&tabs=yaml#how-can-i-set-the-build-number-dynamically-with-conditions) section is incorrect. When following the example and attempting to run in Azure DevOps, I was presented with the following error:

**Unexpected value "why".**

I believe the example code should read as follows:

```yaml
variables:
  - name: why
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: pr
    ${{ elseif eq(variables['Build.Reason'], 'Manual' ) }}:
      value: manual
    ${{ elseif eq(variables['Build.Reason'], 'IndividualCI' ) }}:
      value: indivci
    ${{ else }}:
      value: other
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&amp%3Btabs=yaml&tabs=yaml#how-can-i-set-the-build-number-dynamically-with-conditions)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/run-number.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
