### ISSUE TITLE
I have a question that is not on the FAQ, but I am surpised it is missing - How do I define my yml so my build only runs on the schedule and not other code changes?

### ISSUE THREAD

**Issue by austinledbetter** [MicrosoftDocs/azure-devops-docs#13561]
I have a pipeline that looks like this:

```
schedules:
- cron: "0 3 * * *"
  always: true
  displayName: Daily 3am build
  branches:
    include:
    - none

extends:
  template: ./_template_run_category_on_qa.yml
  parameters:
    testCategory: HomeHealthClaimsManager
```

Any time someone pushes a change on a branch or merges a change to the main branch, the pipeline starts to run.  I expected it to only run once a day at 3am based on my yaml file.  Why does it kick off for all this other activity?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#scheduled-triggers)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/scheduled-triggers.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
