### ISSUE TITLE
Documentation feedback/suggestion for the 'Combining trigger types' section

### ISSUE THREAD

**Issue by mail2pradeepc** [MicrosoftDocs/azure-devops-docs#13643]
Documentation feedback:

Section:
Combining trigger types

Link:
[https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops#combining-trigger-types](url)

Suggestion:
We could add example script as below for the example mentioned, so that users could relate it to  a script file:

In the below script, `trigger: none` in Pipeline B prevents it from triggering on a push to the repository. The `resources` block in Pipeline B sets up a pipeline completion trigger on Pipeline A. This means that when Pipeline A completes, it will trigger a new run of Pipeline B. This setup ensures that only one run of Pipeline B is triggered per completion of Pipeline A.

```
# Pipeline A
trigger:
  branches:
    include:
    - '*'

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - script: echo Building!

# Pipeline B
trigger: none

resources:
  pipelines:
  - pipeline: A
    source: PipelineA
    trigger:
      branches:
        include:
        - '*'

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - script: echo Building!
```
