### ISSUE TITLE
Provide useable Node/NPM pipeline cache example

### ISSUE THREAD

**Issue by joel1st** [MicrosoftDocs/azure-devops-docs#13655]
In the pipeline cache doc - the example is provided which has two major issues.
1. The script directly after the cache restoration, deletes the cache and reinstalls it (resulitng in the pipeline being slower than without any cache)!
2. The "restoreKeys" can lead to restoring a completely different cache, which will also require a `npm ci` to fix it.

This can be amended from:
```
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm

- script: npm ci
```

to this:

```
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  cache_hit: false 

steps:
- task: Cache@2
  inputs:
   key: 'npm | "$(Agent.OS)" | package-lock.json'
   cacheHitVar: cache_hit
   path: $(npm_config_cache)
  displayName: Cache npm
- task: Bash@3
  condition: and(succeeded(), eq(variables.cache_hit, false))
  displayName: 'Run NPM CI if no cache'
  inputs:
   targetType: 'inline'
   script: npm ci
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd39237-2778-c4f1-3ce4-bde343ecb59d
* Version Independent ID: e3daf460-128d-cb57-e899-ca0c841dff07
* Content: [Pipeline caching - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/caching.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
