### ISSUE TITLE
Referring to a specific commit

### ISSUE THREAD

**Issue by shurick81** [MicrosoftDocs/azure-devops-docs#13697]
The article says "If you want to pin a specific commit, first create a tag pointing to that commit, then pin to that tag". However, the easiest way to refer to a specific commit is using SHA:

```yaml
resources:
  repositories:
    - repository: templates_repo
      type: git
      name: pipeline-test-00/templates
      ref: f87406def01b44505687d0ff7928d6f0f6113132
```

Tested in this pipeline: https://dev.azure.com/sapozhkov/pipeline-test-00/_build/results?buildId=683&view=logs&j=8282e427-bffc-5a10-a8ab-7ce1defcccbe&t=70b0d9ad-f882-52ee-ffc2-2818d5f8e4b9

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#use-other-repositories)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
