### ISSUE TITLE
Github Advanced Security -Facing issue: Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again.

### ISSUE THREAD

**Issue by mazbur** [MicrosoftDocs/azure-devops-docs#13702]
Hi,

We are facing issue while enabling advanced security in azure devops. Only Dependency scanning task of advanced security is failing with this issue "Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again.". 

So we had added one environment variable   "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true" as the solution to resolve this issue.

 
```
- task: AdvancedSecurity-Dependency-Scanning@1
env:
     DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true- task: AdvancedSecurity-Dependency-Scanning@1
env:
     DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true
``` 

Below are the logs

```
Starting: AdvancedSecurityDependencyScanning

==============================================================================

Task         : Advanced Security Dependency Scanning

Description  : Scan for open source dependency vulnerabilities in your source code.

Version      : 1.1.177

Author       : Microsoft Corporation

Help         : Learn more about Advanced Security Dependency Scanning at https://aka.ms/advanced-security/dependency-scanning/detection

==============================================================================

Advanced Security Dependency Scanning Tool is starting up...

Advanced Security Dependency Scanning Tool v1.1.177 has started.

OS Platform: linux

OS Type: Linux

OS Arch: x64

OS Version: 6.2.0-1014-azure

Node Version: v16.20.2

.NET: Downloading and preparing .NET Core

.NET: Finished downloading and preparing .NET Core

/__w/_tasks/AdvancedSecurity-Dependency-Scanning_f97aace4-962a-441b-9141-b842d806b9c7/1.1.177/dotnet-6.0.9/dotnet /__w/_tasks/AdvancedSecurity-Dependency-Scanning_f97aace4-962a-441b-9141-b842d806b9c7/1.1.177/detection/Microsoft.AdvSec.Detection.dll scan --Verbosity Verbose --Timeout 300 --Output /__w/1/a --SourceDirectory /__w/1 --SourceFileRoot /__w/1/s --BuildIdentifier 1477323 --BuildDisplayType GHAzDO-broker-interface --Url https://governance.dev.azure.com/Specsavers/ --RequestorVsid 18c85fcc-2542-631b-936f-2915909431f9 --BuildType vsts://39b7d696-fa4d-4520-acdc-b928d40f0a94/9e743f0f-d236-4162-af3d-4fbf33e03a0b/4434/97cb8aaa-29c5-5e6e-4146-937419060251 --BuildDisplayIdentifier 20231010.2 --SourceType vsts://39b7d696-fa4d-4520-acdc-b928d40f0a94/9e743f0f-d236-4162-af3d-4fbf33e03a0b/f0541e3e-f620-4ea7-8602-c99fb10f47d1/feature/test_dso --SourceDisplayType feature/test_dso --SourceIdentifier 83791cce1de85303832fac26e58c76dd790f06c8 --SourceDisplayIdentifier 83791cce --ProdTaskPublisher true --PhaseDisplayName Build Docker image

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.

   at System.Environment.FailFast(System.String)

   at System.Globalization.GlobalizationMode+Settings..cctor()

   at System.Globalization.CultureData.CreateCultureWithInvariantData()

   at System.Globalization.CultureData.get_Invariant()

   at System.Globalization.CultureInfo..cctor()

   at System.Globalization.CultureInfo.get_InvariantCulture()
``` 

**Could you please let us know whether this solution won't break our existing flow and provide confirmation on this issue?**

**Comment by WilliamAntonRohm** [comment]
@mazbur -- thank you for your question.  Are you following a particular learn.microsoft.com article?  Meanwhile, please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by mazbur** [comment]
@WilliamAntonRohm -- Yes, we are following [this article](https://learn.microsoft.com/en-us/azure/devops/repos/security/configure-github-advanced-security-features?view=azure-devops&tabs=yaml#set-up-dependency-scanning)

We are using these four tasks to enable Github Advanced Security. Also we have some  maven build tasks in between codeql-init and codeql-analyse. This environment variable we are adding because we were getting the error mentioned above.

**We need your confirmation whether this environment variable (DOTNET_SYSTEM_GLOBALIZATION_INVARIANT) can be written under dependency-scanning task and wont hamper another code flow?**
```
- task: AdvancedSecurity-Codeql-Init@1
            inputs:
              languages: 'java'
              querysuite: 'security-extended'

 - task: AdvancedSecurity-Codeql-Analyze@1 

 - task: AdvancedSecurity-Dependency-Scanning@1
   env:
     	 DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

 - task: [AdvancedSecurity-Publish@1](mailto:AdvancedSecurity-Publish@1)
```
