### ISSUE TITLE
Clarify Runtime Expressions & Expression Functions

### ISSUE THREAD

**Issue by coolhome** [MicrosoftDocs/azure-devops-docs#13743]
Why can't you use `split()` + array access on output variables from another job? I was not able to find any documentation supporting or limiting functions in expressions setting a variable. There is an example using `$[eq(variables['Build.SourceBranch'], 'refs/heads/main')]` so naturally I would assume this would work. 
`
Example Code
```
jobs:
- job: A
  steps:
  - powershell: |
     Write-Host "##vso[task.setvariable variable=myOutputVar;isoutput=true]/sub/123/rg/456/test/test/test/test/test"
    name: passOutput
- job: B
  dependsOn: A
  variables:
    myVarFromJobA: $[ dependencies.A.outputs['passOutput.myOutputVar'] ]  
    myVarFromJobASplit: $[ split(dependencies.A.outputs['passOutput.myOutputVar'], '/')[2] ]
    myVarFromJobASplit2: $[ split(variables.myVarFromJobA, '/')[2] ]
  steps:
  - powershell: |
     Write-Host $(myVarFromJobA)
     Write-Host $(myVarFromJobASplit)
     Write-Host $(myVarFromJobASplit2)
```

In the documentation there are examples of using these functions but not with runtime variables dependencies/stageDependencies.
