### ISSUE TITLE
Service connections can be specified by variables.

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#13766]
[Enter feedback here]
Service connections can be specified by variables.

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/47343377/280c0917-afd3-4f72-8254-7831f1b7721d)

The note needs to be removed/modified to prevent confusion.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5284952-75a7-b6c1-69e6-be179bb94e02
* Version Independent ID: aac8216a-6c50-c614-540b-24a5f93cdb5a
* Content: [Service connections in Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/library/service-endpoints.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by juliakm** [comment]
I've confirmed that you can use variables in service connections. Example YAML use:

```yaml
- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: $(serviceconn)
    appType: 'functionAppLinux'
    appName: 'myawesomeapp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.9'
    deploymentMethod: 'auto'
```
