### ISSUE TITLE
Can we refer Pipeline template from Gitlab?

### ISSUE THREAD

**Issue by 13archit** [MicrosoftDocs/azure-devops-docs#13784]
I am trying to use Azure Devops Pipeline, but I want to fetch pipeline template from Gitlab private repo. Didn't find anything related to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@13archit -- Archit, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- Julia, please look into this issue.

**Comment by juliakm** [comment]
Azure DevOps support GitHub, GitHub Enterprise, and Bitbucket ([reference](https://learn.microsoft.com/azure/devops/pipelines/yaml-schema/resources-repositories-repository?view=azure-pipelines)) with the repository resource. One workaround would be to clone your GitLab repo inside of a `script` task. For example:

```yaml
stages:
- stage: Checkout
  jobs:
  - job: Build
    pool: 
      vmImage: 'Ubuntu-latest'
    steps:
    - checkout: none
    - script: | 
        git clean -ffdx
        git clone  https://username:password@gitlab.com/useraccount/reponame.git
         #if your password or username contain @ replace it with %40
```
Here's more information from [StackOverflow](https://stackoverflow.com/questions/61368533/is-it-possible-to-checkout-gitlab-repository-in-yml-which-sits-in-github). 

Here's a [Developer Community request](https://developercommunity.visualstudio.com/t/allow-using-yaml-build-pipelines-with-gitlab-repos/462450) for GitLab support.
