### ISSUE TITLE
Looping using "each" with variables doesn't work

### ISSUE THREAD

**Issue by chitturs** [MicrosoftDocs/azure-devops-docs#13791]
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#split has 2 examples of looping using parameters and variables.

Variables did not work in ADO build pipeline. The pipeline does not recognize ${{variable.xyz}}. However, parameters works as shown in the example.

Please investigate why variables looping doesn't work. I spent half a day on it with no success.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@chitturs -- Chittur, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- Julia, please look into this issue.

**Comment by juliakm** [comment]
The first `split()` example works for me. I updated the first example locally to make sure it ran without looking for a script. This should work. 

```yaml
trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'
  
variables:
- name: environments
  value: prod1,prod2 
steps:  
  - ${{ each env in split(variables.environments, ',')}}:
     - script: echo ${{ env }}
```
