### ISSUE TITLE
Please provide actual rather than theoretical steps.

### ISSUE THREAD

**Issue by vanderzielj** [MicrosoftDocs/azure-devops-docs#13807]
> When using Django, you typically want to migrate the data models using manage.py migrate after deploying the app code. You can add startUpCommand with post-deployment script for this purpose:

> `startUpCommand:  python3.7 manage.py migrate`

Where can I find the "post-deployment script" and the "startUpCommand"? Are you aware of the issue with Oryx described in this post?
[Python: Post build script fails, cannot open ODBC driver lib · Issue #1166 · microsoft/Oryx](https://github.com/microsoft/Oryx/issues/1166#issue-1062666240)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 744eaf3c-85c6-2092-823a-8a709018b5f7
* Version Independent ID: 3ed6d4b4-334f-775b-f783-912b76124557
* Content: [Build and deploy Python web apps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops#considerations-for-django)
* Content Source: [docs/pipelines/ecosystems/python-webapp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/python-webapp.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@vanderzielj -- thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- please look into this issue.

**Comment by juliakm** [comment]
Thanks for pointing this out. I'll clarify in the article that `startUpCommand` is a property of a task. 

```yaml
  - task: AzureWebApp@1
      displayName: 'Deploy Azure Web App : $(webAppName)'
      inputs:
        azureSubscription: $(azureServiceConnectionId)
        appName: $(webAppName)
        package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
        startUpCommand: 'python manage.py migrate'
```
