### ISSUE TITLE
Wrong documentation / sqlcmd

### ISSUE THREAD

**Issue by l33tCod-er** [MicrosoftDocs/azure-devops-docs#13815]
The documentation how to call "sqlcmd" under "Classic - YAML" clearly is wrong:

wrong:
``` yaml
- task: CmdLine@2
  displayName: Run Sqlcmd
  inputs:
    filename: Sqlcmd
    arguments: '-S $(ServerFqdn) -U $(AdminUser) -P $(AdminPassword) -d $(DatabaseName) -i $(SQLFile)'
```
correct:
``` yaml
- task: CmdLine@1
  displayName: Run Sqlcmd
  inputs:
    filename: sqlcmd
    arguments: '-S $(ServerFqdn) -U $(AdminUser) -P $(AdminPassword) -d $(DatabaseName) -i $(SQLFile)'
```

Not fully sure about the caps of "sqlcmd", but for us, only starting with lower case works.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81f4ee44-6500-b0e6-62d8-7a23e5b461fa
* Version Independent ID: 75bd021b-fed5-f258-315d-0ef8628fb887
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/targets/azure-sqldb.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-targets**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
