### ISSUE TITLE
Cache@2 task cacheHitVar set to inexact

### ISSUE THREAD

**Issue by CrommVardek** [MicrosoftDocs/azure-devops-docs#13828]
The documentation [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cache-v2?view=azure-pipelines) mentions that the task Cache@2 cacheHitVar is set to either 'true' or 'false' 

> The variable to set to true when the cache is restored (i.e. a cache hit). Otherwise, sets the variable to false.

However after running the following (only relevant parts...) 

```yml
- job: "Build"
    displayName: "Build job"
    pool:
      vmImage: ubuntu-latest
    variables:
      NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
      CACHE_RESTORED: 'false'
    steps:
      - task: UseDotNet@2
        displayName: "install dotnet sdk"
        inputs:
          packageType: "sdk"
          version: "6.x"
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: echo '$(CACHE_RESTORED)'
      - task: Cache@2
        displayName: 'NuGet Cache'
        inputs:
          key: 'nuget | "$(Agent.OS)" | $(Build.SourcesDirectory)/**/packages.lock.json,!$(Build.SourcesDirectory)/**/bin/**,!$(Build.SourcesDirectory)/**/obj/**'
          restoreKeys: |
            nuget | "$(Agent.OS)"
            nuget
          path: '$(NUGET_PACKAGES)'
          cacheHitVar: CACHE_RESTORED
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: echo '$(CACHE_RESTORED)'
      - task: DotNetCoreCLI@2
        displayName: "restore nugget packages"
        condition: ne(variables.CACHE_RESTORED, 'true')
        inputs:
          command: "restore"
          projects: |
            **/*.csproj
          feedsToUse: "config"
          nugetConfigPath: "nuget.config"
          restoreArguments: "--locked-mode"
```

The two Bash tasks output respectively `false` (expected) and `inexact` (unexpected). So this means that cacheHitVar is potentially set to something else than `true` or `false` ?

Or am I missing something ?

Also, the output of the Cache@2 task gave me this in the end : 

```
Expected size to be downloaded: 2,213.6 MB
Downloaded 0.0 MB out of 2,213.6 MB (0%).
Downloaded 27.4 MB out of 2,213.6 MB (1%).
Downloaded 327.9 MB out of 2,213.6 MB (15%).
Downloaded 1,095.9 MB out of 2,213.6 MB (50%).
Downloaded 2,074.0 MB out of 2,213.6 MB (94%).
Downloaded 2,458.7 MB out of 2,213.6 MB (111%).
```

Which was also unexpected. Note: there is NO cache miss.
