### ISSUE TITLE
##[error]Path does not exist: D:\a\1\s\$(Pipeline.ArtifactStagingDirectory)

### ISSUE THREAD

**Issue by Mark-Good** [MicrosoftDocs/azure-devops-docs#13937]
Documentation seems unclear.  

Yaml
```
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/CE.Starling.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
```

Result
PublishPipeLineArtifact
`##[error]Path does not exist: D:\a\1\s\$(Pipeline.ArtifactStagingDirectory)`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4959fc1-212b-7d6a-df73-b0b2993df561
* Version Independent ID: fcecb4fc-6b16-e432-8f4a-f043e222bb41
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/dotnet-core.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
