### ISSUE TITLE
indentation of YAML is incorrect

### ISSUE THREAD

**Issue by jasonwbarnett** [MicrosoftDocs/azure-devops-docs#13979]
Under the https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#number-of-retries-if-task-failed header, it currently reads:

```yaml
- task: <name of task>
   retryCountOnTaskFailure: <max number of retries>
   ...
```

It should be:

```yaml
- task: <name of task>
  retryCountOnTaskFailure: <max number of retries>
  ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac9c819c-d0d7-fa24-5fbf-f812c882acd3
* Version Independent ID: 428c9c9d-afc6-0f32-a9a0-1025faeda31c
* Content: [Build and Release Tasks - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/tasks.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
