### ISSUE TITLE
stageDependencies have implicit dependency (and can use variables defined in) the Stage immediatley preceding it, but not before

### ISSUE THREAD

**Issue by validis-ad** [MicrosoftDocs/azure-devops-docs#14009]
I haven't found this documented anywhere, but to elaborate on the title a bit:

`stageDependencies` have implicit dependency (and can use variables defined in) the immediately preceding Stage, but if you want to use variables from a Stage **before** the one immediately preceding the current Stage, you need an _explicit_ `dependsOn`.

So this works out of the box:

```
stages:                                                                            
- stage: branch_validation                                                         
  displayName: ADO Conformity Checks                                               
  jobs:
    - job: git_tag_cache
      displayName: Validating Branch Naming
      steps:                                                                       
        - script: |                                                                
            echo "This is a MOCK at the moment."
            ...SOME LOGIC HERE...
            echo "##vso[task.setvariable variable=relGitTag;isoutput=true]$RELTAG"
          displayName: Cache Relative Git Tag                                   
          name: cacheRelativeGitTag

- stage: build_and_push                                                         
  displayName: Build and Push Development Builds                                                                                      
  jobs:                                                                         
    - job: gradle_build                                                         
      variables:                                                                
        discoveredRelativeTag: $[ stageDependencies.branch_validation.git_tag_cache.outputs['cacheRelativeGitTag.relGitTag'] ]
        ...SOME USAGE OF THE ABOVE VARIABLE HERE...    
```

However, if you **have another stage between these two defined stages** then the implicit `dependsOn` of the previous stage, also means that variables defined in a stage prior to the one immediately before this one, have been forgotten.

To work around this, you need an explicit `dependsOn` like:

```
- stage: build_and_push                                                         
  displayName: Build and Push Development Builds                                
  dependsOn:                                                                    
    - branch_validation                                                           
  jobs:                                                                         
    - job: gradle_build                                                         
      variables:                                                                
        discoveredRelativeTag: $[ stageDependencies.branch_validation.git_tag_cache.outputs['cacheRelativeGitTag.relGitTag'] ]
...
```

If I've missed this in the documentation, I apologise, but I've just been banging my head against this for a while.
