### ISSUE TITLE
Use variables across stages at the stage level.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [MicrosoftDocs/azure-devops-docs#14038]
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch&source=docs#use-outputs-in-a-different-stage

The above documentation has a section on using variables across stages. However it only demonstrates the syntax to use the variables at the job level.

```
stages:
- stage: One
  jobs:
  - job: A
    steps:
    - task: MyTask@1  # this step generates the output variable
      name: ProduceVar  # because we're going to depend on it, we need to name the step

- stage: Two
  dependsOn:
  - One
  jobs:
  - job: B
    variables:
      # map the output variable from A into this job
      varFromA: $[ stageDependencies.One.A.outputs['ProduceVar.MyVar'] ]
    steps:
    - script: echo $(varFromA) # this step uses the mapped-in variable

- stage: Three
  dependsOn:
  - One
  - Two
  jobs:
  - job: C
    variables:
      # map the output variable from A into this job
      varFromA: $[ stageDependencies.One.A.outputs['ProduceVar.MyVar'] ]
    steps:
    - script: echo $(varFromA) # this step uses the mapped-in variable
```

This syntax does not work if you want to use the variable in a condition at the stage level.

This syntax _does_ work as a condition at the stage level

```
condition: or(succeeded('DeployInfraStage'), eq(dependencies.PlanStage.outputs['PlanJob.TerraformPlan.InfraState'], 'NoChange'))
```

However, even this only works if the variable was not defined in a deployment job. I have found no syntax at all that works to use a variable in a condition at the stage level if it was defined in a deployment job.

So how do I use a variable in a condition at the stage level if it was defined in a deployment job?
