### ISSUE TITLE
Better documentation for Test results files argument

### ISSUE THREAD

**Issue by chappers00** [MicrosoftDocs/azure-devops-docs#2914]
When using the PublishTestResults step in a YAML pipeline it's quite difficult to find the right syntax for specifying multiple files and using an exclude. We tried semicolons, commas and files with quotes.

We found this syntax worked:

- task: PublishTestResults@2
  displayName: Parse test results
  inputs:
    testResultsFiles: |
      **/TEST-*.xml
      !**/TEST-file.to.exclude.xml

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice and I will update the topic to include their recommendation.

**Comment by akinsolb** [comment]
@chappers00 @alexhomer1 can you confirm the separator between files? is it a new line or a pipe character to begin with? If its a new line, @alexhomer1 this isn't possible to do via the azure pipeline build configurator (website)

**Comment by chappers00** [comment]
@akinsolb below was the syntax which worked for me, essentially a combination of the pipe symbol and new lines for each pattern:

- task: PublishTestResults@2
  displayName: Parse test results
  inputs:
    testResultsFiles: |
      **/TEST-*.xml
      !* TEST-file.to.exclude.xml

**Comment by AjkayAlan** [comment]
I can confirm this is still existing. The following ways did not work:
```
    - task: PublishTestResults@2
      displayName: Publish Test Results **/test-*.xml
      inputs:
        testResultsFiles: '**/test-*.xml;**/junit.xml'
        failTaskOnFailedTests: 'true'
```

```
    - task: PublishTestResults@2
      displayName: Publish Test Results **/test-*.xml
      inputs:
        testResultsFiles: |-
          '**/test-*.xml'
          '**/junit.xml'
        failTaskOnFailedTests: 'true'
```

```
    - task: PublishTestResults@2
      displayName: Publish Test Results **/test-*.xml
      inputs:
        testResultsFiles: |
          '**/test-*.xml'
        failTaskOnFailedTests: 'true'
```
In any of the above ways, my build failed to recognize any test results

The only way that worked was when I had testResultsFiles with a pipe, and each item defined without any quotes (almost like quotes were being treated as part of the path). My VSCode seems angry at this format, but it works:
```
    - task: PublishTestResults@2
      displayName: Publish Test Results **/test-*.xml
      inputs:
        testResultsFiles: |
          **/test-*.xml
          **/junit.xml
        failTaskOnFailedTests: 'true'
```

**Comment by divais** [comment]
For multiple values you multi-line values without quotes will work. Use quotes only for single values. 
I shall add an example in the doc as well so to avoid confusion.

**Comment by PBoraMSFT** [comment]
@Additi - can you look into this?

**Comment by LarsWH** [comment]
The fix suggested by @AjkayAlan above does not work for me. I am trying to publish `**/surefire-reports/TEST-*.xml` and `**/failsafe-reports/TEST-*.xml` but without success. @divais - where can I find the updated documentation?

**Comment by Additi** [comment]
@larsWH the document is not yet updated. I'll get them updated and share the link.

**Comment by allantargino** [comment]
This is working for me:

```yaml
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: |
            **/surefire-reports/TEST-*.xml
            **/failsafe-reports/TEST-*.xml
          goals: 'package'
          codeCoverageToolOption: 'jaCoCo'
      - task: PublishTestResults@2
        displayName: Publish Test Results **/test-*.xml
        inputs:
          testResultsFiles: |
            **/surefire-reports/TEST-*.xml
            **/failsafe-reports/TEST-*.xml
          failTaskOnFailedTests: true
```

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by PBoraMSFT** [comment]
Adding @shashban

**Comment by sonnehansen** [comment]
hi @chappers00,
thank you for the solution :)

Took some time to because the docs still says semi-colon here +1 year later:
![image](https://user-images.githubusercontent.com/29034546/108852283-b1730d80-75e5-11eb-8d3c-aec4bfc45435.png)

**Comment by Rolf-Smit** [comment]
So I tried using the semicolon, but it seems that does not work. The pipe and multiple lines solution (without quotes) seems to work. Can the documentation please be updated? This is really frustrating especially since it is just a documentation issue.

**Comment by adrian-skybaker** [comment]
>Multiple paths can be specified, separated by a newline.

Please add a working example to the documentation, as using new lines is not intuitive in yaml.

**Comment by volkova-a-an** [comment]
Hi, it would be great to have a working example in the documentation or just here in the issue. I tried newline (as it is stated in docs), pipe as in the comment from [allantargino](https://github.com/allantargino) with and without quotes. Yet I can't figure it out.

**Comment by in-fke** [comment]
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/maven-v3?view=azure-pipelines
points to
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops
and there it says:

> A pattern is a string or list of newline-delimited strings.

But this page is independent of the fact that the string is to be specified in YAML.

so go to: https://yaml-multiline.info/

For me, the documentation seems consistent, yet it's the lacking the prominent example:

```
          testResultsFiles: |
            **/surefire-reports/TEST-*.xml
            **/failsafe-reports/TEST-*.xml
```

**Comment by in-fke** [comment]
Actually, this does seem broken. There is a discrepancy:

1. Documentation refers to "file-matching-patterns", and there, multline value is allowed
2. Task seems to prepend source folder erroneously, and maybe does not even support multiline in the first place

From Task, I got an error such as
```
No test result files matching /home/vsts/work/1/s/**/surefire-reports/TEST-*.xml
**/failsafe-reports/TEST-*.xml were found, so publishing JUnit test results is being skipped.

```
Note that the Task prepended the source folder only to the first line, not the second line.
Secondly, it looks like the pattern was not interpreted as multiline correctly (since it should have found some files) but I may have to do some more tests to verify that.

**Comment by in-fke** [comment]
Update, tried this:

```
parameters:
- name: maven_testResultsFiles
  type: string
  # specify both patterns in this manner
  # https://github.com/MicrosoftDocs/azure-devops-docs/issues/2914#issuecomment-560448579
  default: |
    $(System.DefaultWorkingDirectory)/**/surefire-reports/TEST-*.xml
    $(System.DefaultWorkingDirectory)/**/failsafe-reports/TEST-*.xml

...
- task: Maven@3
  displayName: 'Maven - Run Goal'
  inputs:
...
    testResultsFiles: ${{ parameters.maven_testResultsFiles }}

```
got this:
```
No test result files matching /home/vsts/work/1/s/**/surefire-reports/TEST-*.xml
/home/vsts/work/1/s/**/failsafe-reports/TEST-*.xml were found, so publishing JUnit test results is being skipped.

```

So I am getting the impression that the Maven Task does not support multi-line file pattern for collecting test results.
