### ISSUE TITLE
Grouped steps example is misleading

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#3314]
From the Phases section: 

```yaml
steps:
- script: |
    npm install -g bower
    npm install
    bower install
  displayName: 'Install dependencies'
- script: npm run build
- script: npm test
```

Here I get the impression that this functionally behaves the same as the example listed earlier:
```yaml
steps:
- script: npm install -g bower
- script: npm install
- script: bower install
- script: npm run build
- script: npm test
```

The problem is it doesn't, at least at the moment. The problem is with error handling. Each `- script:` task essentially checks the exit code of the last command, and importantly doesn't use `set -e`. This is important to realize, as in the grouped case, if `npm install -g bower` fails, then the other two commands will still run. And while here the whole task would still fail because `bower` wouldn't be available this is not a general assumption. For example, it may be that `bower install` could have been put in a subsequent step, and this would mean that the grouped task would have succeeded, even though the first command did fail. This issue would then only become apparent in subsequent steps, which may make debugging a bit harder.

Having said all that, the same kind of grouping with the same non-obvious effects can be done in Travis CI as well, and a typical work-around is to prepend the grouped script block with a `set -e`. The only difference to Travis CI is that such grouped commands can't be given a name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035d0e47-a927-1e99-34a4-181e34578af3
* Version Independent ID: ab6853d8-98cf-dd68-7425-4644cc7e0492
* Content: [Migrate from Travis to Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-travis?view=azure-devops#git-submodules)
* Content Source: [docs/pipelines/migrate/from-travis.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/migrate/from-travis.md)
* Product: **devops**
* GitHub Login: @ethomson
* Microsoft Alias: **ethomson**
