### ISSUE TITLE
How do we make Windows Containers run?

### ISSUE THREAD

**Issue by ctaggart** [MicrosoftDocs/azure-devops-docs#3815]
What is meant by "The agent must have permission to access the Docker daemon". The message was added with feedback in https://github.com/Microsoft/azure-pipelines-agent/issues/2082, but I don't think it is enough. What permissions do we change to make it work?

This `azure-pipelines.yml`:
``` yaml
jobs:

- job: Windows
  pool:
    vmImage: win1803
  container: 'mcr.microsoft.com/dotnet/core/sdk:2.2.105-nanoserver-1803'
  steps:
  - script: |
      dotnet --info
```

Fails with:
```
Exit code 1 returned from process: file name 'C:\Program Files\Docker\docker.EXE', arguments 'version --format '{{.Server.APIVersion}}''.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#requirements)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**
