### ISSUE TITLE
Availability of python developer packages

### ISSUE THREAD

**Issue by kenr** [MicrosoftDocs/azure-devops-docs#3851]
A use case we have for changing python versions is to compile Python extension modules (C). This requires header files, etc. Will this be supported anytime soon? If not, do you have a suggestion on how to do compilation of Python extension modules in Azure Devops?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e765cfad-8ab9-443a-1171-5af81a31252f
* Version Independent ID: 8ff69d93-0128-dbeb-9d63-45266ed73020
* Content: [Use Python Version task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-python-version.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **brcrista**

**Comment by brcrista** [comment]
Which image?  For Hosted Ubuntu, the header files are there, under the `include` directory where Python is installed.

You can set `name: xxx` on the task and then use `$(xxx.pythonLocation)` in later scripts to get the Python install directory.

If you run this YAML, you should see `include` there:

```yml
pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3
  name: python3

- script: |
    echo $(python3.pythonLocation)
    ls $(python3.pythonLocation)
  displayName: Test output variable
```
