### ISSUE TITLE
How to set environment variables?

### ISSUE THREAD

**Issue by amake** [MicrosoftDocs/azure-devops-docs#3874]
I have a secret I would like to supply to Gradle; per guidance elsewhere, I would prefer to do so by defining an [`ORG_GRADLE_PROJECT_foo=bar`-style environment variable](https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties) rather than supplying a command line argument. It doesn't seem like this is possible at the moment, or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00499395-fdc3-b150-3469-aee2f9fb7cbc
* Version Independent ID: 44e630e1-1689-2d2e-212b-3ce2baf8771f
* Content: [Gradle build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/gradle.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/gradle.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by krmeda** [comment]
We have been running a step prior to this with Bash setting the environment variable to accomplish same. Would really like if the variables can be exported as environment variables at runtime. 

```
  - bash: |
      export  ORG_GRADLE_PROJECT_foo=bar
  - task: Gradle@2
    displayName: 'Build and Test Gradle Project'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: $(ci.gradleTasks)
```

**Comment by vipulnewaskar7** [comment]
How can we edit the YAML of gradle task, so that we can add bash script to run before gradle task runs?
I see "View YAML", but can't edit that.

Also,
why the gradle task foolishly sets "**DOCKER_CONFIG**" environment variable and sets its value **<empty>**?
**Either don't set it, or set the right value as "~/.docker"**

**Comment by achimgrimm** [comment]
Hi,
I was able to set the environment variable (from a secret) using the `var` attribute. This is missing in this documentation. :-(

```
  - task: Gradle@2
    displayName: 'Build and Test Gradle Project'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: $(ci.gradleTasks)
    var:
      foo: $(mySecretVariable)
```
