### ISSUE TITLE
Missing information on setting this up in a YAML Pipeline, and using dotnet restore

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/azure-devops-docs#3884]
I haven't been having success getting my Azure Devops feed working in a YAML pipeline for a project that uses modern PackageRef in the .csproj (no packages.config, no project.json), so restore is via MSBuild and/or dotnet restore. All attempts I've made fail to authenticate or load the feed index.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78a9f20-b8d2-4aa7-c52d-a968ab87315d
* Version Independent ID: 3880a787-8f70-8c13-176e-c732b619fb06
* Content: [Restore Package Management NuGet packages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/packages/nuget-restore.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/packages/nuget-restore.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **amullans**

**Comment by nickstaggs** [comment]
Any movement on this? Or at least a work around?

**Comment by nickstaggs** [comment]
Never mind
```yaml
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '/<vsts-feed-guid>'
    includeNuGetOrg: true
```
Want me to open a PR?

**Comment by MichaelMcCoyTech** [comment]
Come on Microsoft.   Can someone respond here.

**Comment by elbatk** [comment]
Hi people, Azure Artifacts PM here. We're making some changes here that will help everyone out this quarter. To explain briefly, we're looking to create auth tasks that get you set up and then move out of your way and let you run custom commands like you would in a command line environment.

With that said, I'd like to get everyone fixed here. You have to set **feedsToUse** / **selectOrConfig** set to '_select_' and provide feeds, or set to '_config_' and point to the NuGet configuration. If you create a successful build step in the visual designer and convert it to YAML, it should be correct for you.

**Comment by dfoulk** [comment]
For anyone who needs to get a DevOps Artifacts NuGet Feed into their build...

We achieved this by adding the "vstsFeed" property to "NuGetCommand@X > inputs" and setting the value to our feed's GUID. To get this GUID, we did the following (hopefully there's an easier way, but I don't know of one):

1. Create a new Pipeline that used the "classic editor" (little link at the bottom of the "Where is your code?" page)
2. Continue with the creation of your Pipeline (Select a repo, branch, template, etc.)
3. Select the "NuGet restore" task
4. Select your DevOps Artifacts NuGet Feed from the "Feeds and authentication > Feeds to use > Use packages from this Azure Artifacts/TFS feed" dropdown
5. Click "View YAML"
6. Copy and paste the `vstsFeed: '1234abcd-1234-12ab-ab12-1234abcd1234'` line into the same "NuGetCommand@X > inputs" section in your azure-pipelines.yaml file

Here is what our azure-pipelines.yml file looked like after adding the feed:

```
# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'
    vstsFeed: '1234abcd-1234-12ab-ab12-1234abcd1234'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    jdkVersionOption: 1.8
    msbuildVersionOption: '16.0'
```

I hope this helps!
