### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by mboutet** [MicrosoftDocs/azure-devops-docs#4684]
How can we pass environment variables using the same syntax as for "script" jobs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad03c70-4014-135f-ffd3-245c08b3ce32
* Version Independent ID: 42a84b54-9ab7-89b2-00b1-efcfc6ba6eef
* Content: [SSH Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/ssh.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/ssh.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@davidstaheli for ssh task

**Comment by davidstaheli** [comment]
@mboutet are you using the SSH task with a script file, or inline script text?  We don't currently have a way to pass environment variables to the remote machine where the script executes unless you use inline script and set the variables dynamically in the script text.

**Comment by mboutet** [comment]
I was using an inline script like so (note: values modified with dummy values):

```
- job: Deploy
  displayName: Deploy
  variables:
  - group: SSH keys
  - name: API_IMAGE
    value: myiimage:latest
  - name: AZURE_AGENT_DOCKER_REGISTRY_USER
    value: azureagent
  - name: DOCKER_REGISTRY
    value: myorg.azurecr.io
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: SSH@0
    inputs:
      sshEndpoint: deploymentserver
      runOptions: inline
      inline: |
        docker login -u $AZURE_AGENT_DOCKER_REGISTRY_USER -p $AZURE_AGENT_DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
        # Deployment commands ommitted
        docker logout $DOCKER_REGISTRY
    env:
      AZURE_AGENT_DOCKER_REGISTRY_PASSWORD: $(AZURE_AGENT_DOCKER_REGISTRY_PASSWORD)
```

So if I use the following instead, it should work?

```
- job: Deploy
  displayName: Deploy
  variables:
  - group: SSH keys
  - name: AZURE_AGENT_DOCKER_REGISTRY_USER
    value: azureagent
  - name: DOCKER_REGISTRY
    value: myorg.azurecr.io
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: SSH@0
    inputs:
      sshEndpoint: deploymentserver
      runOptions: inline
      inline: |
        export AZURE_AGENT_DOCKER_REGISTRY_USER=$AZURE_AGENT_DOCKER_REGISTRY_USER
        export AZURE_AGENT_DOCKER_REGISTRY_PASSWORD=$AZURE_AGENT_DOCKER_REGISTRY_PASSWORD
        export DOCKER_REGISTRY=$DOCKER_REGISTRY
        
        docker login -u $AZURE_AGENT_DOCKER_REGISTRY_USER -p $AZURE_AGENT_DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
        # Deployment commands ommitted
        docker logout $DOCKER_REGISTRY
    env:
      AZURE_AGENT_DOCKER_REGISTRY_PASSWORD: $(AZURE_AGENT_DOCKER_REGISTRY_PASSWORD)
```
