### ISSUE TITLE
Provide a concrete worked example for Publish Python packages

### ISSUE THREAD

**Issue by haokanga** [MicrosoftDocs/azure-devops-docs#4820]
This page only contains fragmented steps and the author assumed the reader is an expert of twine.

This page failed to explain:
1. how many steps to implement an end to end pipeline to release Python packages, steps such as `python setup.py bdist_wheel` are missing and it requires the users to figure it out by checking the "Connect to feed" page in Azure Artifacts.
2. what is "{package path to publish}'" in "- script: 'twine upload -r {feedName/EndpointName} --config-file $(PYPIRC_PATH) {package path to publish}'"

Please, provide a fullest worked example similar to https://www.noelbundick.com/gists/consuming-packages-from-a-private-azure-pipelines-python-artifact-feed/ so that the document can be readable and actionable. Users can only rely on other online resources to find worked examples when examples are not provided officially.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 638243e7-cdd6-7573-aa6a-87c39da1bb3d
* Version Independent ID: d0046f56-ed26-7af2-3b8f-3dd5ab6ab892
* Content: [Publish packages to PyPI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml#install-twine)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pypi.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **elbatk**

**Comment by berndverst** [comment]
FYI @infin8x -- instructions for publishing to private PyPI-style package registry for Python are unclear / incomplete.

**Comment by ryotatomioka** [comment]
How about this? For me the confusing bit was both twine / pip authenticate expects <Project Name>/<Feed Name> but you only specify the <Feed Name> in twine upload...

```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Publish
  displayName: Publish my-hello-world
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      python -m pip install wheel twine
      python setup.py bdist_wheel
    displayName: Prepare for my-hello-world publishing
  # Python twine upload authenticate V1
  # See https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops#publish-python-distribution-to-azure-artifacts-feed
  - task: TwineAuthenticate@1
    displayName: 'Twine Authenticate'
    inputs:
      artifactFeed: MyProject/DemoFeed # <Project Name>/<Feed Name>
  - script: |
      python -m twine upload -r "DemoFeed" --skip-existing --config-file $(PYPIRC_PATH) ./dist/*.whl --verbose
    displayName: Publishing my-hello-world

- job: Consume
  displayName: Consume my-hello-world
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  # Python pip authenticate V1
  # See https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/pip-authenticate?view=azure-devops#download-python-distributions-from-azure-artifacts-feeds-without-consulting-official-python-registry
  - task: PipAuthenticate@1
    inputs:
      artifactFeeds: MyProject/DemoFeed # <Project Name>/<Feed Name>

  - script: |
      pip install my-hello-world
      python -c "import hello_world"
    displayName: Install my-hello-world
```

I think `UsePythonVersion` is not important.
