### ISSUE TITLE
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-v')   will not work

### ISSUE THREAD

**Issue by tdi** [MicrosoftDocs/azure-devops-docs#4951]
This condition will not work since it checks a branch name against the tag name - those will not match. The condition is good for matching branch names only. I suggest to change description to reflect it works for branch name comparison not to confuse.

If there is a way to have a condition matched on tag name, it would be nice to add that somewhere to the documentation. 

 `condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-v')`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b12d2c4-f871-1d14-0c16-91e58fb1130b
* Version Independent ID: 6b9e1d67-f303-7445-e573-830309ba49a4
* Content: [GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/github-release.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/github-release.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by Shazwazza** [comment]
Does anyone know of a way to achieve the above condition for tag names?

**Comment by tdi** [comment]
@Shazwazza you can get tag with git command and add it to a variable and then condition on this maybe?

**Comment by sitereactor** [comment]
If your build is triggered by a tag when you have ie.:
```
trigger:
  branches:
    include:
    - refs/heads/development
    - refs/heads/master
    - refs/tags/release-v*
    exclude:
```
then the `['Build.SourceBranch']` will be the name of the tag, ie.: `refs/tags/release-v1`

So the condition will work. I'm using it this way to only trigger a certain stage for commits, which are tagged.

**Comment by kyawza-sps** [comment]
How do you use this condition for the job if you could share the syntax?

**Comment by sitereactor** [comment]
@kyawza-sps I'm not sure if this is what you are looking for, but here is a stage where I use a condition for the Source Branch

```

  - stage: deploy_live
    displayName: Deploy code to Live  
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/release-'))
    variables:
      environment_name: live
      service_connection: "Live Connection"
    jobs:
      - template: deploy.yml
        parameters:
          environment_name: ${{ variables.environment_name }}
          service_connection: ${{ variables.service_connection }}
```
