### ISSUE TITLE
Making this work with JaCoCo

### ISSUE THREAD

**Issue by chaholl** [MicrosoftDocs/azure-devops-docs#5267]
Others have mentioned the need for clarification on the settings for JaCoCo. Here's a sample conflig:
```
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage results'
      inputs:
        codeCoverageTool: 'JaCoCo' 
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml' 
        pathToSources: '$(System.DefaultWorkingDirectory)'      
        additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/target/jacoco.exec'    
```
**Note:** The `pathToSources` value is required for JaCoCo since the HTML reports are now re-generated by the task. The HTML reports generated by JaCoCo are ignored (and in version 1.155 at least), cause an error if you try to use them.

Took a few hours of digging through source code etc. to piece this together. Hope it saves somebody some time!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by trajano** [comment]
Here's an example where I used a separate job
```
      - job: Build
        steps:
          - task: Maven@3
            displayName: 'Maven build'
            inputs:
              goals: org.jacoco:jacoco-maven-plugin:prepare-agent verify
              options: -B
          - publish: $(Pipeline.Workspace)
            artifact: build
      - job: Coverage
        displayName: Coverage Reports
        dependsOn: Build
        steps:
          - download: current
            artifact: build
          - script: |
              ls -lR '$(Pipeline.Workspace)/build'
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'JaCoCo'
              summaryFileLocation: '$(Pipeline.Workspace)/build/s/target/site/jacoco/jacoco.xml'
              pathToSources: '$(Pipeline.Workspace)/build/s'
              additionalCodeCoverageFiles: '$(Pipeline.Workspace)/build/s/target/jacoco.exec'
```

**Comment by AdrianSanguineti** [comment]
> **Note:** The `pathToSources` value is required for JaCoCo since the HTML reports are now re-generated by the task. The HTML reports generated by JaCoCo are ignored (and in version 1.155 at least), cause an error if you try to use them.

This comment saved my bacon, as I missed the finer detail in the `pathToSources` argument description. It would be great if @chaholl's example is added to documentation page, and perhaps an example for cobertura format as well.

**Comment by trajano** [comment]
Here's an example of using it with Gradle and SonarQube.  I opted not to use the Gradle@2 task because I wanted to keep the build file as close to what people can do if we change away from Azure DevOps

        - task: SonarQubePrepare@4
          inputs:
            SonarQube: 'devhaus-sonarqube'
            scannerMode: Other
          displayName: 'Prepare analysis on SonarQube'
        - bash: |
            echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
            echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)/bin:$(PATH)"
          displayName: "Set java version"
        - bash: |
            cat <<'EOT' > $(Agent.TempDirectory)/jacoco.gradle
            allprojects {
              buildscript  {
                repositories {
                  maven {
                    url "https://plugins.gradle.org/m2/"
                  }
                }
                dependencies {
                  classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.0"
                }
              }

              // After the project has been evaluated (and the dependency above has been added, apply the SonarQube plugin
              afterEvaluate { project ->
                if (project.getParent() == null && !project.plugins.hasPlugin('org.sonarqube')) {
                  //Add sonar plugin only to root projects, and only if it is not already applied
                  project.apply plugin: 'org.sonarqube'
                }      
              }

              apply plugin: 'java'
              apply plugin: 'jacoco'
              # apply plugin: 'org.sonarqube'
              jacocoTestReport {
                reports {
                  xml.enabled = true
                  html.enabled = true
                }
              }
              # check.dependsOn(sonarqube)
              check.dependsOn(jacocoTestReport)
            }
            EOT
          displayName: 'Create jacoco.gradle file'
        - bash: |
            sh ./gradlew -Prepo_username=$(REPO_USERNAME) -Prepo_password=$(REPO_PASSWORD) -I $(Agent.TempDirectory)/jacoco.gradle
          displayName: 'Build and Analyze'
        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: 'JaCoCo'
            summaryFileLocation: '$(Build.SourcesDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
            pathToSources: '$(Build.SourcesDirectory)/src/main/java'
            additionalCodeCoverageFiles: '$(Build.SourcesDirectory)/build/jacoco/*.exec'

**Comment by delor** [comment]
Without `task: UseDotNet@2` I was getting:
```
Starting: Publish code coverage
==============================================================================
Task         : Publish code coverage results
Description  : Publish Cobertura or JaCoCo code coverage results from a build
Version      : 1.160.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
##[warning]Please install dotnet core to enable automatic generation of Html report.
Reading code coverage summary from '/home/vsts/work/1/s/build/reports/jacoco/test/jacocoTestReport.xml'
Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Instruction- 7 of 22 covered.
 Line- 2 of 5 covered.
 Complexity- 2 of 4 covered.
 Method- 2 of 4 covered.
 Class- 1 of 3 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 1 files
Uploading 1 files
File upload succeed.
File upload succeed.
Published '/tmp/Code Coverage Report_466048' as artifact 'Code Coverage Report_466048'
Published '/tmp/Code Coverage Files_466048' as artifact 'Code Coverage Files_466048'
Async Command End: Publish code coverage
Finishing: Publish code coverage
```

After adding `task: UseDotNet@2` I get:
```
##[section]Starting: Publish code coverage
==============================================================================
Task         : Publish code coverage results
Description  : Publish Cobertura or JaCoCo code coverage results from a build
Version      : 1.160.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
[command]/__t/dotnet/dotnet /__w/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.160.4/netcoreapp2.0/ReportGenerator.dll -reports:/__w/1/s/build/reports/jacoco/test/jacocoTestReport.xml -targetdir:/__w/_temp/cchtml -reporttypes:HtmlInline_AzurePipelines -sourcedirs:/__w/1/s/src/main/kotlin
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
##[warning]Failed to generate Html report. Error: null
Reading code coverage summary from '/home/vsts/work/1/s/build/reports/jacoco/test/jacocoTestReport.xml'
##[section]Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Instruction- 7 of 22 covered.
 Line- 2 of 5 covered.
 Complexity- 2 of 4 covered.
 Method- 2 of 4 covered.
 Class- 1 of 3 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 1 files
Uploading 1 files
File upload succeed.
File upload succeed.
Published '/tmp/Code Coverage Report_466071' as artifact 'Code Coverage Report_466071'
Published '/tmp/Code Coverage Files_466071' as artifact 'Code Coverage Files_466071'
##[section]Async Command End: Publish code coverage
##[section]Finishing: Publish code coverage
```

**Comment by A830612** [comment]
> Others have mentioned the need for clarification on the settings for JaCoCo. Here's a sample conflig:
> 
> ```
>     - task: PublishCodeCoverageResults@1
>       displayName: 'Publish code coverage results'
>       inputs:
>         codeCoverageTool: 'JaCoCo' 
>         summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml' 
>         pathToSources: '$(System.DefaultWorkingDirectory)'      
>         additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/target/jacoco.exec'    
> ```
> 
> **Note:** The `pathToSources` value is required for JaCoCo since the HTML reports are now re-generated by the task. The HTML reports generated by JaCoCo are ignored (and in version 1.155 at least), cause an error if you try to use them.
> 
> Took a few hours of digging through source code etc. to piece this together. Hope it saves somebody some time!
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
> * Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
> * Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
> * Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
> * Product: **devops**
> * Technology: **devops-cicd**
> * GitHub Login: @PBoraMSFT
> * Microsoft Alias: **pbora**

Thanks the workaround worked for me

**Comment by maikefischer** [comment]
@chaholl this really does not work for me. I have debugged my pipeline to verify that the files are present and they are: 
        
- summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml' 
- pathToSources: '$(System.DefaultWorkingDirectory)'      
- additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/target/jacoco.exec'    

I still get a ##[warning]No code coverage results were found to publish.

**Comment by wimdeblauwe** [comment]
I can confirm that this works:

```
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
      pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java'
      additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/target/jacoco.exec'
```

With this in my `pom.xml`:

```
<project>
  <build>
    <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.7</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
    </plugins>
  </build>
</project>
```
