### ISSUE TITLE
Push services adds latest tag even if the setting is set to false

### ISSUE THREAD

**Issue by syonekura** [MicrosoftDocs/azure-devops-docs#5602]
Somewhere in my pipeline I have something like this:

```
    - task: DockerCompose@0
      displayName: 'Build Docker images'
      inputs:
        azureSubscription: ...
        azureContainerRegistry: ...
        projectName: ...
        dockerComposeFileArgs: TAG=mycustomtag
        dockerComposeCommand: build --build-arg SOME_ENV_VARS=$(ETC)

    - task: DockerCompose@0
      displayName: 'Push Docker images'
      inputs:
        azureSubscription: ...
        azureContainerRegistry: ...
        action: 'Push services'
        additionalImageTags: mycustomtag
        includeLatestTag: false
```

The thing is that `push services` adds the latest tag even if I specify `includeLatestTag: false`, making the build to fail:

```
[command]/usr/bin/docker push advancedanalyticsacr.azurecr.io/flex-optimizador-api:latest
The push refers to repository [advancedanalyticsacr.azurecr.io/flex-optimizador-api]
tag does not exist: advancedanalyticsacr.azurecr.io/flex-optimizador-api:latest
```

This build pipeline was working and hasn't been changed for a while now (a few months at least), but now fails, any suggestions about how can I prevent docker compose command to not include the latest tag when pushing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#push-service-images)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**
