### ISSUE TITLE
Deployment Job doesn't automatically check out sources

### ISSUE THREAD

**Issue by xtellurian** [MicrosoftDocs/azure-devops-docs#5647]
I think (and correct me if I'm wrong) that a deployment job doesn't automatically clone the source repo. This is different to the behaviour of regular jobs.

It would be useful to mention that on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by LarsCelie** [comment]
This confused me just now. The deployment job knew which template reference to use, but then couldn't find any source file.

What are the recommended tasks/steps to make sure the source repo is downloaded successfully in the same location as if it were a regular job?

**Comment by xtellurian** [comment]
@LarsCelie you can use this in your pipeline yaml

```yaml
steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: boolean  # if true, execute `execute git clean -ffdx && git reset --hard HEAD` before fetching
  fetchDepth: number  # the depth of commits to ask Git to fetch; defaults to no limit
  lfs: boolean  # whether to download Git-LFS files; defaults to false
  submodules: true | recursive  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules; defaults to not checking out submodules
  path: string  # path to check out source code, relative to the agent's build directory (e.g. \_work\1); defaults to a directory called `s`
  persistCredentials: boolean  # if 'true', leave the OAuth token in the Git config after the initial fetch; defaults to false
```

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout

**Comment by petr-stupka** [comment]
This works, thanks for advice!

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0

**Comment by henry-padilla** [comment]
I am finding that the deployment job (as of this post) downloads artifacts from earlier build job but it downloads them to D:\a\1\ as opposed to D:\a\1\a  ( the System.ArtifactsDirectory )
This makes using the files difficult.

**Comment by Happycoil** [comment]
@henry-padilla it downloads to the `Pipeline.Workspace` directory. You can work around that by defining a custom download artifact task.

```

steps:
- download: none
- task: DownloadBuildArtifacts@0
  inputs:
     artifactName: $(artifactName)
     buildType: 'current'
     downloadType: 'single'
     downloadPath: '$(System.ArtifactsDirectory)'
```
