### ISSUE TITLE
Please document how cache key fallback works.

### ISSUE THREAD

**Issue by vadimcn** [MicrosoftDocs/azure-devops-docs#5694]
Based on https://github.com/microsoft/azure-pipelines-tasks/issues/10842, I'm using Cache task like this:
```
  - task: CacheBeta@0
    inputs:
      key: ccache | $(Agent.OS) | $(Build.SourceVersion)
      path: $(Agent.BuildDirectory)/.ccache
      continueOnError: true
    displayName: ccache
    condition: always()
``` 
However each time it outputs `Information, There is a cache miss.` and no data is getting restored. 

I would have expected there to be a partial match on the first two key parts with cache from previous build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#feedback)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**
