### ISSUE TITLE
No one examples of join expression

### ISSUE THREAD

**Issue by tauke1** [MicrosoftDocs/azure-devops-docs#5737]
Hello! Can you give some examples with join expression?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by sasanmcp** [comment]
I need that too, please.

**Comment by rogersillito** [comment]
Yes - specifically I can't find any examples of how to create the array variable accepted as the 2nd parameter to `join`...

**Comment by orhanmaden** [comment]
An example should be nice

**Comment by Tetradeus** [comment]
Yes it just seems to not work. Please could you add an example?

**Comment by grummelf** [comment]
Even though it does not seem to match the operation explanation, this worked for me as an execution condition:

`and(succeeded(), startsWith(variables['Build.SourceBranch'], join('/refs/heads/', '${{ parameters.TRIGGER_BRANCH_PREFIX }}')))`

**Comment by winstonhenke** [comment]
Also need an example

**Comment by juliakm** [comment]
I apologize for the delay on this. I'm updating the docs now. In the meantime, here is a working example. 

```
parameters:
- name: myArray
  type: object
  default:
    - FOO
    - BAR
    - ZOO

variables:
   A: ${{ join(';',parameters.myArray) }} # outputs FOO;BAR;ZOO

steps:
  - script: |
      echo $A
```
