### ISSUE TITLE
Variable endpoint is not working

### ISSUE THREAD

**Issue by ANTPro** [MicrosoftDocs/azure-devops-docs#5790]
Sample:
 variables:
    Server: $[dependencies.Name.outputs['SetVariableJob.Server']]
- task: SSH@0
    inputs:
      sshEndpoint: '${Server}'
      runOptions: inline
      inline: 'echo ${Server}'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad03c70-4014-135f-ffd3-245c08b3ce32
* Version Independent ID: 42a84b54-9ab7-89b2-00b1-efcfc6ba6eef
* Content: [SSH Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/ssh.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/ssh.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@ANTPro  Thank you for the feedback, we're sorry your experiencing issues.

Instead of:

```
sshEndpoint: '${Server}'
runOptions: inline
inline: 'echo ${Server}'
```
...please try using:

```
sshEndpoint: '$(Server)'
runOptions: inline
inline: 'echo $(Server)'
```

And post the results.

**Comment by ANTPro** [comment]
What? Its eqal.

**Comment by ANTPro** [comment]
1.
variables:
Server: $[dependencies.Name.outputs['SetVariableJob.Server']] #Value = Server1
- task: SSH@0
inputs:
sshEndpoint: 'Server1'
runOptions: inline
inline: 'echo Server1'
2. - bug
variables:
Server: $[dependencies.Name.outputs['SetVariableJob.Server']] #Value = Server2
- task: SSH@0
inputs:
sshEndpoint: 'Server1'
runOptions: inline
inline: 'echo Server2'

**Comment by msebolt** [comment]
Just a similar issue earlier...  see https://github.com/MicrosoftDocs/vsts-docs/issues/5747.

Are there any additional errors in the output?

**Comment by ANTPro** [comment]
No errors

**Comment by msebolt** [comment]
This is probably better handled by the product team, please move the issue to [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues).

Our apologies for the inconvenience.

**Comment by ANTPro** [comment]
This is not task bug. Bug in Azure DevOps.

**Comment by msebolt** [comment]
Thank you, I'll assign the author to then.

**Comment by WilliamAntonRohm** [comment]
@ANTPro -- you may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

My apologies for the delay in responding.

**Comment by ANTPro** [comment]
This bug fixed?

**Comment by WilliamAntonRohm** [comment]
@RoopeshNair -- please look into this issue.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by jankytay** [comment]
I'm still having the same issue. DevOps refused to run a pipeline with variables in endpoint parameters.

Error message shown in DevOps portal:
> There was a resource authorization issue: "The pipeline is not valid. Job J2: Step SSH input sshEndpoint references service connection $(SSHENDPOINTFORHOSTING) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."


I've tested "SSH@0" and "CopyFilesOverSSH@0", and both of their `sshEndpoint` fields are not happy to accept variables as an input. The resource mentioned in the variable `SSHENDPOINTFORHOSTING` is authorized, and clicking the "Authorize Resources" button in the error box doesn't do anything.

Here's a simplified version of my pipeline:
```
stages:
- stage: S2
  jobs:
  - job: J2
    variables:
      SSHENDPOINTFORHOSTING: 'my_server'
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: '$(SSHENDPOINTFORHOSTING)'
        sourceFolder: 'foo'
        contents: |
          *.foo
          *.bar
        targetFolder: '/home/foo'
    - task: SSH@0
      inputs:
        sshEndpoint: '$(SSHENDPOINTFORHOSTING)'
        runOptions: 'inline'
        inline: |
          echo 'do something here'
        failOnStdErr: false
```
