### ISSUE TITLE
Buildandpush ignores ARGs

### ISSUE THREAD

**Issue by ChrisGibson1982** [MicrosoftDocs/azure-devops-docs#5865]
When you add arguments to a 'build and push' it presents a warning when the build runs, stating that it ignores arguments. Can we have an example of seperate build and push tasks that would allow you to add arguments to the build process please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by WilliamAntonRohm** [comment]
@ChrisGibson1982 -- Chris, you may find an example here:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

@shashankbarsin -- Shashank, please consider adding such an example to the documentation.

**Comment by ChrisGibson1982** [comment]
"Other commands and arguments" is there, but would be nice to have the push command as well

**Comment by benwk** [comment]
new to Azure pipelines and was misled for a long time

just for reference

```yaml
steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageRepository)'
      command: 'build'
      arguments: '--build-arg app=$(app)'
      Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  - task: Docker@2
    displayName: Push the image
    inputs:
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageRepository)'
      command: 'push'
```
