### ISSUE TITLE
build and run docker image without pushing to dockerhub

### ISSUE THREAD

**Issue by tashrifbillah** [MicrosoftDocs/azure-devops-docs#5949]
Hi, is it possible to build and run a docker image without pushing it and pulling back from dockerhub?

Specifically, I am using the following to build an image:

https://github.com/tashrifbillah/tbss_containers/blob/master/azure-pipelines.yml#L26

```
steps:
  - script: docker build -t $(imageName) -f Dockerfile.centos7 --build-arg USER=$(user) --build-arg CWD=$(wd) .
    displayName: 'Build a docker image'

```

Can I do the following:

```
steps:
  - script: docker build -t $(imageName) -f Dockerfile.centos7 --build-arg USER=$(user) --build-arg CWD=$(wd) .
    displayName: 'Build a docker image'
  - script: docker run --rm $(imageName)
    displayName: Run the docker image 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build an image - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/containers/build-image.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/containers/build-image.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**
