### ISSUE TITLE
Missing CocoaPods example

### ISSUE THREAD

**Issue by arnauddrain** [MicrosoftDocs/azure-devops-docs#6172]
An example to cache CocoaPods, especially the `~/.cocoapods` folder,  would be very useful for iOS developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by hewigovens** [comment]
we actually cache `Pods` folder and avoid `pod install` step, might be better than caching ~/.cocoapods

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by raosan** [comment]
Hi @hewigovens how did you cache the Pods folder? 
i try with this code but still get error in the post-job

```
 - task: Cache@2
      displayName: 'Cache CocoaPods'
      inputs:
        key: 'cocoapods | "$(Agent.OS)" | ios/Podfile.lock'
        path: '$(Pipeline.Workspace)/ios/Pods'
        cacheHitVar: 'PODS_CACHE_RESTORED'
```

Error: 
```
There is a cache miss.
tar: could not chdir to '/Users/runner/work/1/ios/Pods'
```
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/5974862/26b5373e-6ddf-49ce-b4b5-888032819560)

context: i'm working with React Native v0.70.6

**Comment by Pareshm24** [comment]
@raosan where you able to get this issue fixed?, we are facing the similar issue for some reason podfile.lock gets updated and we always get a cache miss due to that. I changed to below code and caching did succeed but getting build errors 
 ```
  - task: Cache@2
    inputs:
      key: 'pods | "$(Agent.OS)" | ios/Podfile | ios/Podfile.lock'
      path: 'ios/Pods'
      cacheHitVar: 'PODS_CACHE_RESTORED'
```

**Comment by raosan** [comment]
Yes I solved it @Pareshm24.
this is my full file if you want 

```
trigger:
  - main

pool:
  vmImage: 'macos-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

stages:
  - stage: Required
    jobs:
      - job: iOS
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Install Node.js'

        - task: Cache@2
          displayName: 'Cache Yarn packages'
          inputs:
            key: 'yarn | "$(Agent.OS)" | yarn.lock'
            restoreKeys: |
              yarn | "$(Agent.OS)"
              yarn
            path: $(YARN_CACHE_FOLDER)

        - script: yarn --frozen-lockfile
          displayName: 'Installing dependencies...'

        - task: Cache@2
          displayName: 'Cache CocoaPods'
          inputs:
            key: 'pods | "$(Agent.OS)" | ios/Podfile.lock'
            path: 'ios/Pods'
            cacheHitVar: 'PODS_CACHE_RESTORED'

        - task: CocoaPods@0
          displayName: 'Install CocoaPods...'
          condition: ne(variables.PODS_CACHE_RESTORED, 'true')
          inputs:
            workingDirectory: 'ios'

        - task: Xcode@5
          displayName: 'Building iOS app (debug)...'
          inputs:
            actions: 'clean build'
            configuration: 'Debug'
            sdk: 'iphoneos'
            xcWorkspacePath: 'ios/myapp.xcworkspace'
            scheme: 'myapp'
            packageApp: false
            exportPath: 'output'
            signingOption: 'nosign'
```

Sometimes, when the pods cache is corrupt and showing error again, i change the key, for example from this
```
key: 'pods | "$(Agent.OS)" | ios/Podfile.lock'
```
 to this
```
key: 'v2 | pods | "$(Agent.OS)" | Podfile.lock'
```
