### ISSUE TITLE
what does kubectl login do? its not an official k8s kubectl argument

### ISSUE THREAD

**Issue by bitsofinfo** [MicrosoftDocs/azure-devops-docs#6184]
what does kubectl login do exactly? its not an official k8s kubectl argument.... docs should provide clarity on this. I've tested the argument via this Task and it appears to enable any subsequent task to do kubectl commands (such as in bash) and have the local context setup properly? yet I don't see a ~.kube/config file........ but I do see this ENV var that is set?

KUBECONFIG=/home/vsts/work/_temp/kubectlTask/1572378635696/config

Please clarify your docs, sorely lacking this info that `login` can be used to setup your shell env for manual kubectl commands

---
#### Document Details

*Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Kubectl task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops#advanced)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by bitsofinfo** [comment]
to further clarify, this *KUBECONFIG* file is JSON and not YAML so it can't be used w/ kubectl. It has no context in it either.

Can we just get a legit ~/.kube/config file that is properly configured for the configured kubernetes service connection? I.e. w/ a legit context in it = the name of the k8s service connection?

**Comment by qwertoyo** [comment]
> Please clarify your docs, sorely lacking this info that login can be used to setup your shell env for manual kubectl commands

It's what I'm trying to achieve also. I'd need to run a small script which uses kubectl inside, how can I use that `kubectl login`?

**Comment by qwertoyo** [comment]
I tried with basic arguments and it worked, maybe the doc is already enough 😀

`- task: Kubernetes@1`
`  inputs:`
`    command: login`
`    connectionType: Kubernetes Service Connection`
`    kubernetesServiceEndpoint: [...]`

`- bash: kubectl get pv | grep Released [....]`

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by sonnyhcl** [comment]
Just find once I add `AzureKeyVault@2` task, the kubernetes login is not working anymore.
```
pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'xxx'
    KeyVaultName: 'babylon-xxx'
    SecretsFilter: '*'
    RunAsPreJob: true
    
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-xxx'
    command: 'login'

- bash: |
    env
    kubectl get pod
```
