### ISSUE TITLE
Using CacheBeta with NuGet is Failing Builds

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/azure-devops-docs#6281]
I followed the NuGet example in my [cross plaform build pipeline](https://dev.azure.com/schema-net/Schema.NET/_build/results?buildId=316&view=logs&j=b457fee1-24b5-5b05-276f-95f55538c81f&t=6e4d2787-11c9-490d-973b-abf8c18bce4d):

```yaml
    - task: CacheBeta@0
      displayName: Cache NuGet packages
      inputs:
        key: nuget | **/packages.lock.json
        path: $(Pipeline.Workspace)/.nuget/packages
```

However, this fails:

## Windows 

> Information, There is a cache miss.
> tar: could not chdir to 'd:\a\1\.nuget\packages'

## Mac

> Information, There is a cache miss.
> tar: could not chdir to '/Users/runner/runners/2.160.0/work/1/.nuget/packages'

## Linux

> Information, There is a cache miss.
> tar: /home/vsts/work/1/.nuget/packages: Cannot open: No such file or directory
> tar: Error is not recoverable: exiting now

Is the path `$(Pipeline.Workspace)/.nuget/packages` correct? Is the example incorrect? In my csproj files, I've added:

```xml
<RestorePackagesWithLockFile>true<RestorePackagesWithLockFile>
<DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#netnuget)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by uniquelau** [comment]
I see a similar issue.
My build is generating the same finger print each time "TKt7AYjs8qasLcl5a7VB3HUc4DyqY5tE1XEj1wiQmL8="
But each time I trigger the build I get a cache miss.

**Comment by oising** [comment]
Same problem with windows agent:
```
Information, There is a cache miss.
tar: could not chdir to 'd:\a\1.nuget\packages'
```

**Comment by oising** [comment]
I figured out the issue -- either the docs at https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#netnuget are wrong, or the windows-2019 build agent is misconfigured. I didn't try other agents.

I created a task to dump the nuget locals, and this is what I got:

```
http-cache: C:\Users\VssAdministrator\AppData\Local\NuGet\v3-cache
global-packages: C:\Users\VssAdministrator\.nuget\packages\
temp: C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch
plugins-cache: C:\Users\VssAdministrator\AppData\Local\NuGet\plugins-cache
```
The cache we're looking for, is `global-packages` (at least for .net core) -- the instructions on the docs say `$(Pipeline.Workspace)` but this does not resolve to the user's profile.

**Comment by oising** [comment]
Ah, I know why this happens -- I bet everyone here is using the GUI to create the pipeline, and not YAML. If you use YAML, the NUGET_PACKAGES variable from the example will implicitly create an environment variable and override the location from `~\.nuget\packages` to a the writeable location under `d:\a\1\` -- so the fix here is to create a pipeline variable for NUGET_PACKAGES to point to the new location, and then your pipeline will pick it up and the cache task will work.

**Comment by oising** [comment]
The docs should be made more clear for classic pipelines.

**Comment by kmadof** [comment]
@oising is it working for your YAML build as it is described in docs?

**Comment by GrimGadget** [comment]
The sample should definitely be more clear that if you change that variable name it will break the process.

**Comment by ramiMSFT** [comment]
@RehanSaeed Thank you for your feedback. @oising Thank you for your contribution.
The updated article will go live shortly.

**Comment by veuncent** [comment]
I was getting this error in a few of my many build pipelines, for no apparent reason.

Fixed it by adding a Powershell task to the top of my pipeline with the following inline script to create the directory if it does not exist:

`[System.IO.Directory]::CreateDirectory('$(NUGET_PACKAGES)')`

**Comment by rafek1241** [comment]
I used that in template:
```
parameters:
  - name: NUGET_PACKAGES
    default: $(Pipeline.Workspace)/.nuget/packages

jobs:
  - job: Testing
   steps:
      - task: Cache@2
        displayName: "Cache nuget packages"
        inputs:
          key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**'
          path: "${{parameters.NUGET_PACKAGES}}"
          restoreKeys: |
            nuget | "$(Agent.OS)"
```

and have the same issue:

```
There is a cache miss.
tar: /azp/agent/_work/5/.nuget/packages: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session ...............
```
