### ISSUE TITLE
Alternative to using the Checkout submodules option - not working

### ISSUE THREAD

**Issue by mmisztal1980** [MicrosoftDocs/azure-devops-docs#6292]
I'm in a situation where I'm trying to consume 2 submodules hosted in 2 separate projects within a single AzD organization - therefore I'm not eligible for `submodules: true | recursive` (commented out) so I have to resort to the alternative solution.

I've followed the steps from the title paragraph and got an empty output. I'm trying to get this to work in a YAML pipeline, resulting in

```
steps:
      - checkout: self
        clean: true
        #submodules: recursive
        persistCredentials: true         
      - task: Bash@3
        displayName: "[bash] git submodule"
        inputs:
          targetType: "inline"
          script: |
            PAT="pat:${{ parameters['Git.PAT'] }}"
            PAT_BASE64=`echo -n $PAT | base64`
            git -c http.https://dev.azure.com/cloud-technologies/cloud-technologies.net/_git/core-build.extraheader="AUTHORIZATION: basic ${PAT_BASE64}" submodule update --init --recursive
            git -c http.https://dev.azure.com/cloud-technologies/realm/_git/realm-core-infrastructure.extraheader="AUTHORIZATION: basic ${PAT_BASE64}" submodule update --init --recursive            
```

I've verified that the `$PAT_BASE64` is encoded correctly. However when trying to repro this locally in the checked-out repo, the outputs of the git commands are blank.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
