### ISSUE TITLE
Add PHP/Composer cache example

### ISSUE THREAD

**Issue by alexander-danilenko** [MicrosoftDocs/azure-devops-docs#6470]
I'm suggesting to add composer cache example to documentation as it's the most popular package manager for PHP apps. 

Just tested following solution and it works good, cache hits successfully: https://github.com/MicrosoftDocs/vsts-docs/pull/6471

```yaml
variables:
  COMPOSER_CACHE_DIR: $(Pipeline.Workspace)/.composer
steps:
  - task: Cache@2
    inputs:
      key: 'composer | "$(Agent.OS)" | composer.lock'
      restoreKeys: |
        composer | "$(Agent.OS)"
        composer
      path: $(COMPOSER_CACHE_DIR)
    displayName: Cache composer
  - script: composer install
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**
