### ISSUE TITLE
Stage parallelism does not seem to function with stage templates?

### ISSUE THREAD

**Issue by DrBushyTop** [MicrosoftDocs/azure-devops-docs#6475]
Hi,

According to the documentation, I should be able to specify parallelism by using
```
- stage: AcceptanceTest
  dependsOn: []    # this removes the implicit dependency on previous stage and causes this to run in parallel
```

**This does not seem to function when the stage is a template from another file**:
```
stages:
- template: build-api.yaml
  parameters:
    buildPlatform: $(buildPlatform)
    dependsOn: [] #tried with and without this on the first stage

- template: build-react.yaml
  parameters:
    buildPlatform: $(buildPlatform)
    dependsOn: []

- template: build-arm.yaml
  parameters:
    buildPlatform: $(buildPlatform)
    azureSubscription: $(azureSubscription)
    dependsOn: []
```

It also does not seem to work when specifying the two last stages to depend on the first one (so fan out).

```
- template: build-api.yaml
  parameters:
    buildPlatform: $(buildPlatform)

- template: build-react.yaml
  parameters:
    buildPlatform: $(buildPlatform)
    dependsOn: build-api.yaml

- template: build-arm.yaml
  parameters:
    buildPlatform: $(buildPlatform)
    azureSubscription: $(azureSubscription)
    dependsOn: build-api.yaml
```

Result in both cases is that they run one by one. 
![image](https://user-images.githubusercontent.com/22717844/69636238-cf5a6700-105e-11ea-8eb2-157dbd641501.png)

I have three microsoft hosted agents in the organization, and doing similar things with classic pipelines works just fine.

Am I missing something here or does it plain not work with stage templates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by DrBushyTop** [comment]
Turns out I had actually misunderstood the functionality under the hood.

My stage templates did not have the dependsOn parameter in them, and in my initial example I was just giving the empty array as a parameter to the template from where nothing was done with it. And also it turns out that this is not valid syntax:

```
- template: build-react.yaml
  parameters:
    buildPlatform: $(buildPlatform)
  dependsOn: []
```

So the way I got it working was just adding
```
stages:
- stage: build_api
  dependsOn: []
```
in all of the templates individually.

One thing that might be worth documenting though, is how would one give the "empty array" dependson value into a template as a parameter correctly? Is that currently doable?
