### ISSUE TITLE
Pipeline resource branch Build.SourceBranch

### ISSUE THREAD

**Issue by damienpontifex** [MicrosoftDocs/azure-devops-docs#6500]
The pipeline resource has "we will follow the same branch and commit on which the event is raised". When the pipeline is queued manually, on a specific branch, is there a way to have it also match the pipeline resources from that branch?

I tried setting `branch: $(Branch.SourceBranch)` but got an error and finding the default setting defined as `branch: string  # branch to pick the artifact, optional; defaults to all branches` we get the latest build artifacts across any branches, but we don't want to have it set to master in a scenario where someone wants to queue it for their unique branch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema&source=docs#resources)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@damienpontifex -- Damien, thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup with what you find out.  We hope to hear from you again.

**Comment by damienpontifex** [comment]
@WilliamAntonRohm I agree with it being an issue for me. Equally though, if I resolve it, maybe something I can add to the docs for clarification/large use cases.

Reading this note [in the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pipeline-resource)
> When you define the resource trigger, if the pipeline resource is from the same repo as the current pipeline, we will follow the same branch and commit on which the event is raised.

This is fine when the event is a trigger event from pipeline completion. But if the pipeline is queued manually this doesn't seem to be an event?
We have noticed queuing the pipeline manually on a branch, it pulls the resource from the latest successful build of any branch vs "following the same branch". 
Is manual queuing different from trigger events? 
And if so, could we improve the docs around this for now? and I can raise another support issue/feedback on Azure DevOps product to see if this could work more aligned in manual queuing scenarios

**Comment by WilliamAntonRohm** [comment]
@damienpontifex -- Damien, thank you for your follow-up.

@steved0x -- Steve, please look into this issue.

**Comment by damienpontifex** [comment]
CI Pipeline
```yaml
name: $(Date:yyyy.MM.dd)$(Rev:.rr)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Hello from $(Build.SourceBranch)" > branch.txt

- publish: branch.txt
  artifact: drop
```

CD Pipeline
```yaml
trigger: none

resources: 
  pipelines:
  - pipeline: CiPipeline
    source: SourceCiPipeline
    trigger:
      branches:  
        include:  
        - master

name: Release-$(Date:yyyy.MM.dd)$(Rev:.rr)

pool:
  vmImage: ubuntu-latest

steps:
- download: CiPipeline
  artifact: drop
  displayName: Download drop artifact

- script: echo "##vso[task.logissue type=error]$(cat $(Pipeline.Workspace)/CiPipeline/drop/branch.txt)"
  displayName: Display drop artifact contents
```

The master branch trigger works as describe in the docs triggering and getting those resources. 

Couple of scenarios I tried:
* Queue CI on branch feature/1 and wait until finish
* Manually Queue CD on branch feature/1
This CD run gets resources from feature/1

If I:
* Queue CI on branch feature/1 and wait until finish
* Queue CI on branch master and wait until finish
* Manually Queue CD on branch feature/1
This CD run gets resources from master

If I:
* Queue CI on branch feature/2 and wait until finish
* Manually Queue CD on branch feature/1
This CD run gets resources from feature/2

The docs suggest it will follow the same branch and commit, but I assume this is only if it get's automatically triggered. If manually triggered and no specific branch specified in the pipeline resource, it's always just the last successful build.

Is there a better way to describe this scenario in the docs?

And then a place I can submit for feature request? We commonly may re-run a CD pipeline for release, but this scenario of which artifacts it picks up means we would be guessing which CI artifacts it picks up if that same pipeline has CI enabled for other branches and PR requests etc
