### ISSUE TITLE
Clarify use of variables in template expressions

### ISSUE THREAD

**Issue by MarkKoz** [MicrosoftDocs/azure-devops-docs#6513]
While it could be extrapolated from the statement that the expression variables are evaluated before the job runs, it should be clarified that variables cannot be used in template expressions, with the exception being predefined variables. Also worth mentioning that variables cannot be passed as parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by csuzw** [comment]
This limitation on the use of variables with templates in pipelines is really limiting and frustrating.  Is there any intention to change this behaviour to something sensible?

**Comment by julie-ng** [comment]
We can also just document the existing behavior (eval at compile or runtime) better, for example:

```yaml
jobs:
- job: build
  variables:
  - foo: bar 
  steps:
    - bash: |
        echo $(foo)            # This will be bar
        echo '##vso[task.setvariable variable=foo]baz'
        echo $(foo)            # This will also be bar, $(foo) expands before the step
    - bash: echo $(a)        # This will be baz. The variable is expanded just before the step
```

Source: https://adamtheautomator.com/azure-devops-variables-complete-guide/

After understanding this difference, everything worked for me.
