### ISSUE TITLE
Defining Resources inside a Template 

### ISSUE THREAD

**Issue by JoeBrockhaus** [MicrosoftDocs/azure-devops-docs#6533]
Today I discovered it's not possible to ~use~ _**define**_ Resources inside a Template. 
It would probably be valuable to include this caveat here, and if reasonable, some expected guidance for how this would be handled. 

---

_A similar [Suggestion](https://developercommunity.visualstudio.com/idea/832840/templated-resources.html) exists (Resource Templates). Some improvements around this experience would be welcomed from a composition + abstraction standpoint. I'll describe my scenario + workaround(s) below._

### Issue

I have a Pipeline _(`pipeline.yml`)_ that references a Template _(`local-template.yml`)_, which itself references a Template _(`templates/remote_template.yml`)_ in another Repository _(`github/my/repo_2`)_. Because only `local-template.yml` knows or cares about the Remote Repository, it defines a `resources` section with the relevant dependent Repository. 

- `Repository1`: 
  - `local-template.yml`:
      ```yaml
  
        resources:
          repositories:

            - repository: repo_2
              type: github
              name: my/repo_2
              endpoint: myCreds

        stages:
        - stage: stage_1
          displayName: stage 1 
 
          jobs: 
          - job: job_1
            steps:
            - template: templates/remote_template.yml@repo_2
      ```

  - `pipeline.yml`:
    
      ```yaml

      stages: 
      - template: ../local-template.yml

      ```

However, this is not supported, resulting in the following: 

> _**Pipeline configuration error:**_
> _**`/local-template.yml (Line: xx, Col: xx): Unexpected value 'resources'`**_

### Possible Options

Assuming the Resource is added to the top-level Pipeline + removed from `local-template`: 
1. Add a Template Parameter for the dependent Repository name.
1. Do not add a Parameter; assume the caller knows it must add the Resource and it must be named specifically. 

Of these choices, the first is better, and ultimately gives the most control to the author. but it adds some hidden dependency + cruft the consumer would otherwise not need. OTOH, I can appreciate the level of complexity such support would introduce. _(ie: Templates which define the same resource multiple times for different repos, vice versa, etc.)_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#using-other-repositories)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
