### ISSUE TITLE
Missing documentation on variable redefinition within the same scope

### ISSUE THREAD

**Issue by kevinhartman** [MicrosoftDocs/azure-devops-docs#6632]
If a variable is defined twice within the same scope (e.g. there are two entries within a Stage's `variables` map, each with a different value), what is the behavior? Does the last entry in the map prevail? Is this an error case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@kevinhartman Thank you for the question.

This is a duplicate of https://github.com/MicrosoftDocs/vsts-docs/issues/1142.  Please refer there for any additional questions or comments.

**Comment by actual-size** [comment]
@msebolt #1142 may technically be a duplicate, but nothing on it answers this issue's question. What happens when the same variable is declared twice *within* a scope?

**Comment by kevinhartman** [comment]
Yeah, I meant to reopen this. #1142 doesn't answer my question, which is: "what happens if you re-declare a variable in the *same* scope?"

For example, consider the following variable template:
```yml
parameters:
  uid: '' # unique environment ID (e.g. 'prod', 'staging', 'test', 'e2e')

variables:
  deployVars.terraform.skipDeploy: true

  ${{ if eq(parameters.uid, 'prod') }}:
    deployVars.terraform.skipDeploy: false
```

If I instantiate this template with `uid: prod`, what will be the value of `deployVars.terraform.skipDeploy`?

Technically, `deployVars.terraform.skipDeploy` is redeclared with a different value in that case. Is the result well-defined? Does lexical order define the precedence?

**Comment by juliakm** [comment]
@kevinhartman The last defined value in the scope will win out if the variables are defined in the same scope and there are no other definitions that take higher priority. I'll clarify this in the docs. Here's a simplified example:

```yaml
trigger: none

stages:
- stage: one
  displayName: Stage One
  variables: 
    - name: a
      value: alpha
    - name: a
      value: beta
  jobs: 
  - job: I
    displayName: Job I
    variables:
      - name: b
        value: uno
      - name: b
        value: dos
    steps: 
    - script: echo $(a) #outputs beta
    - script: echo $(b) #outputs dos
```

**Comment by kevinhartman** [comment]
Thanks @juliakm. I tried this this morning and unfortunately I get the error `deployVars.terraform.skipDeploy is already defined`.

Could this be a product bug or a recent behavior change?

**Comment by kevinhartman** [comment]
@PRMerger17 guessing you're a bot, but this issue should not be closed.

**Comment by georgesymonds** [comment]
I am also seeing the same error and don't understand why this issue has been closed. It is clearly unresolved.

**Comment by msebolt** [comment]
Please note only documentation changes can be made here.

All product-related issues are to be submitted [here](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) to solicit feedback for further guidance from the **Azure DevOps community**.

**Comment by juliakm** [comment]
@kevinhartman I'm not sure your exact scenario but something like this may work. Could you please open an issue in the [Developer Community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) if it does not? 

```yaml
parameters:
  - name: uid # unique environment ID (e.g. 'prod', 'staging', 'test', 'e2e')
    default: "prod"
    type: string

variables:
  ${{ if eq( parameters.uid, 'prod' ) }}: 
    skipDeploy: false 
  ${{ if ne( parameters.uid, 'prod' ) }}: 
    skipDeploy: true


steps:
- script: echo $(skipDeploy)
```
