### ISSUE TITLE
dotnet core packing with NuGetCommand@2

### ISSUE THREAD

**Issue by aserowy** [MicrosoftDocs/azure-devops-docs#6703]
Hi,

it should be mentioned, that core and standard packages should get packed with:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack $(buildConfiguration)'
  inputs:
    command: pack

Otherwise you will get a System.InvalidCastException: Unable to cast object of type 'System.String' to type 'NuGet.Frameworks.NuGetFramework'.

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@aserowy Thank you for the feedback, assigning this to the author for review.

**Comment by shadargee1982** [comment]
Package versioning -> YAML

Add Note:
DotNetCore and DotNetStandard packages should be packaged with the `DotNetCoreCLI@2` task to avoid System.InvalidCastExceptions
```
task: DotNetCoreCLI@2
displayName: 'dotnet pack $(buildConfiguration)'
inputs:
    command: pack
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
     patchVersion: '$(Patch)'
```
