### ISSUE TITLE
Pipeline trigger not working as expressed in documentation

### ISSUE THREAD

**Issue by Exodus** [MicrosoftDocs/azure-devops-docs#6753]
I am running a test for a recently added feature (https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-159-update#cd-capabilities-for-your-multi-stage-yaml-pipelines), this is not working as expressed in the documentation (https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pipeline-triggers-1).

Per the documentation, I am running the following test:

I have two files in the same repo (Azure Repo):

```
#azure-pipelines-a.yml
jobs:
  - job: A
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: Bash@3
        displayName: Test
        inputs:
          targetType: inline
          script: |
            echo "Running testa"
            sleep 10
```
and
```
#azure-pipelines-b.yml
resources:
  pipelines:
    - pipeline: ci
      source: testa
      trigger:
        branches:
          - master

jobs:
  - job: B
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            echo "Running testb"
```
Both pipelines are added to an Azure DevOps project.

From the documentation:

"""
When you specify both CI triggers and pipeline triggers, you can expect new runs to be started every time (a) an update is made to the repository and (b) a run of the upstream pipeline is completed. Consider an example of a pipeline B that depends on A. Let us also assume that both of these pipelines use the same repository for the source code, and that both of them also have CI triggers configured. When you push an update to the repository, then:

A new run of A is started.
At the same time, a new run of B is started. This run will consume the previously produced artifacts from A.
As A completes, it will trigger another run of B.
To prevent triggering two runs of B in this example, you must remove its CI trigger or pipeline trigger.
"""

Expected Result

azure-pipelines-a.yml should trigger azure-pipelines-b.yml after it has completed it's tasks.

Actual Result

Both pipelines run at the same time. Pipeline 'b' is not being triggered by pipeline 'a'.

Addition Information

These pipelines do not specify CI triggers, that said, the default behavior of CI triggers is to run; the documentation of pipeline triggers seems to indicate this behavior would be overwritten by the existence of the resource pipeline code, this is not the case.

Nor is the case when I have disabled CI triggers using:

trigger: none
In this case, the pipeline 'b' simply does not run in any automated fashion.

I have also tried a different configuration of the pipeline resource as such:
```
resources:
  pipelines:
    - pipeline: ci
      source: testa
      trigger: true
```
Using `trigger: true` in this case. This has also been unsuccessful in running as I understand the documentation indicates.

Having this feature would be ideal in cases where we want to separate the CI from the CD and allow independent executions of a deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pipeline-triggers-1)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by junyzheng** [comment]
running into the same issue, please considering update the documentation

**Comment by epernst** [comment]
Ahh, this explains why I could not get it working. Spent quite some time on it before I saw this post.

Thanks for pointing it out and Microsoft please update the docs.

**Comment by rmaziarka** [comment]
I am struggling with this behavior as well. Pipelines triggers in YAML don't work as expected. 2 pipelines are triggered together and the second is not raised when first is finished. 

Please share how we should approach these pipelines - is it a mistake in docs or bug inside the Azure DevOps.

**Comment by panoschatz** [comment]
Same problem here. Can't get a pipeline to be triggered by the completion of another no matter what I've tried in the resources block. Also, the example provided isn't particularly clear. Can we get an update on this please?

**Comment by wolszakp** [comment]
I was running into the same issue. 
I found solution over here:
https://developercommunity.visualstudio.com/content/problem/864701/pipeline-trigger-not-working-as-expressed-in-docum.html?childToView=897210#comment-897210

In shortcut, when I've changed defaultBranch in my dependent pipeline to my working branch 
triggering start working.:
You need to go: Edit -> Triggers (3 dots in right upper corner) -> YAML -> Get sources -> Default branch for manual and scheduled builds
Over there put a branch in which your yaml pipeline you are taking.
This helps me to work

**Comment by StarbuckSapien** [comment]
That solution is <less than ideal>. No one would ever think that you'd have to go into the repo settings for a pipeline to change its default branch, when the pipeline was created on another branch.

**Comment by panoschatz** [comment]
That eventually worked for me.

Say local pipeline and (repo name) : pipe-A
remote pipeline (and repo): pipe-B

```
resources:
  pipelines:
  - pipeline: pipe-A (the one to be triggered)
    source: pipe-B (the remote)
    trigger: 
      branches:
      - master (or whatever other branch)
```
However when I have multiple pipelines on master of repo A they are all triggered at the same time as a result of pipe-B completing.

Problem is I can't rename the actual pipeline and Azure DevOps simply gives it the name 'pipe-A (1)' if I have multiple pipeline yml files in the same branch which gives me headaches..
