### ISSUE TITLE
artifactName is optional, and it's default is NOT drop

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-devops-docs#6765]
The way the docs read today it looks like artifactName is optional (which it is) and the default value is drop..which it is not. It seems like the default name is constructed from the stage and job that called the task. _ are removed and the two items are concatenated with a .

the docs needs to be updated to indicate the correct default name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by rom1gal** [comment]
@drdamour : actually drop is the default name, just experienced it

**Comment by drdamour** [comment]
Its not in my pipeline, maybe its related to how its used

**Comment by abatishchev** [comment]
The following YAML:

```yml
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.ArtifactsDirectory)
```

confirms that the default value for `artifactName` is `Job`:

![image](https://user-images.githubusercontent.com/351644/81621851-5fd5fb00-93a4-11ea-9703-9b365e47ee88.png)


Because change the YAML to this:

```yml
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.ArtifactsDirectory)
    artifactName: 'drop'
```

produces this:

![image](https://user-images.githubusercontent.com/351644/81621827-4af96780-93a4-11ea-8153-1c531e31644c.png)
![image](https://user-images.githubusercontent.com/351644/81621867-69f7f980-93a4-11ea-9fa5-e12f795f6533.png)

@rom1gal, please update the doc.

/cc @vijayma.
