### ISSUE TITLE
Provide a working YAML example for building and testing an iOS app.

### ISSUE THREAD

**Issue by apacha** [MicrosoftDocs/azure-devops-docs#6766]
Can you please provide a full WORKING example for iOS? 

I've seen examples for Android, but I'm building also an iOS app and there seems to be no proper documentation. Note that there are some instructions that actually work (https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/xcuitest), but the [Azure DevOps step](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/app-center-test?view=azure-devops) is fundamentally different. Or at least the documentation is not at all helpful. For example, should I provide an IPA file or a app file? The appcenter-cli requires the app from the DerivedData directory, but the documentation of the build steps requires:
* App IPA to test
* Test IPA file
* Build directory

which is confusing as hell!

I've tried something like:

```
- task: Xcode@5
  inputs:
    actions: 'build-for-testing'
    configuration: 'Debug'
    sdk: 'iphoneos'
    xcWorkspacePath: 'MyProject/MyProject.xcworkspace'
    scheme: 'MyProject'
    packageApp: false
    args: '-derivedDataPath $(build.artifactStagingDirectory)/DerivedData'

- task: AppCenterTest@1
  inputs:
    appFile: '$(build.artifactStagingDirectory)/DerivedData/Build/Products/Debug-iphoneos/MyProject.app'
    artifactsDirectory: '$(build.artifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'xcuitest'
    xcUITestBuildDirectory: '$(ProjectDir)/Build/Products/Debug-iphoneos'
    xcUITestIpaFile: '$(build.artifactStagingDirectory)/DerivedData/Build/Products/Debug-iphoneos/MyProjectUITests-Runner.app'
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'MyCustomer AppCenter Deployment'
    appSlug: 'MyCustomer/MyProject-iOS'
    devices: 'iphoneDevices'
    localeOption: 'en_US'
    skipWaitingForResults: true
```

but all I'm getting is that the paths are incorrect. Something similar to `##[error]Error: Cannot find any file based on /Users/runner/runners/2.163.1/work/1/a/DerivedData/Build/Products/Debug-iphoneos/MyProject.app`.

And what's with this the artifactsDirectory? I expected this step to only upload the build to AppCenter and kick off the tests. What artifacts is it producing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0bff55-744d-06c4-d6da-595e6d5d6e94
* Version Independent ID: 4fc5c777-ec33-38fd-0c56-6c6038e9ac40
* Content: [App Center Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/app-center-test?view=azure-devops#q--a)
* Content Source: [docs/pipelines/tasks/test/app-center-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/app-center-test.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**
