### ISSUE TITLE
add an example of how to reference a pipeline variable vs repeating the same expression

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-devops-docs#6769]
I'd like to have an example added that shows how to reference a pipeline level variable expression

IE
in pipeline top something like it

variables:
  - name: isMaster
    value: eq(variables['Build.SourceBranch'], 'refs/heads/master')

then for a stage condition uses that isMaster:

condition: and(variables.isMaster, succeeded())

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by drdamour** [comment]
@WilliamAntonRohm how do i find out the changeset related to this

**Comment by WilliamAntonRohm** [comment]
@drdamour -- the updated article is live.  Here is the new YAML code example:

```
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
steps:
  - script: echo Hello!
    condition: and(variables.isMain, succeeded())
```

**Comment by drdamour** [comment]
@WilliamAntonRohm  yeah i saw that,  BUT that's not what was asked for.  that is a JOB condition and the request was a STAGE condition. they seem to work differently.  can we re-open?

also just wondering where we can see the commit changeset for this ticket...somehow pr merger knew to close this...but it doesn't link the commits and i wanted to see if there was a way to find em

**Comment by WilliamAntonRohm** [comment]
@drdamour -- thank you for clarifying.  The PRs are created in a private internal document repo, then merged into master (this repo) which is periodically published live.

@juliakm -- please look into this issue.

**Comment by juliakm** [comment]
Here's an updated example that will be live shortly. 

```yaml
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
- stage: A
  jobs:
  - job: A1
    steps:
      - script: echo Hello Stage A!

- stage: B
  condition: eq(variables.isMain, true)
  jobs:
  - job: B1
    steps:
      - script: echo Hello Stage B!
      - script: echo $(isMain)

```
