### ISSUE TITLE
Template reference syntax is not documented when using multiple repos

### ISSUE THREAD

**Issue by mtaylorfsmb** [MicrosoftDocs/azure-devops-docs#6894]
With the support for multiple repos we can now use `checkout` to check out a template repo. When using the `resource`  syntax we reference templates using the resource name.

```yaml
resources:
  repositories:
    - repository: templates
       type: git
      name: build-tools

steps:
- template: my-build.yml@templates
```

But this doesn't appear to work with the `checkout` syntax.

```yaml
- checkout: git://build-tools
   path: templates

steps:
- template: my-build.yml@templates
```
Provide documentation on the correct syntax for this. It seems like it would be just prefixing the template path with the path used in `checkout` but that doesn't work either.

```yaml
- checkout: git://build-tools
   path: templates

steps:
- template: templates/my-build.yml
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#template-references)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
