### ISSUE TITLE
Parameter expansion does NOT happen before conditions are considered in a template.

### ISSUE THREAD

**Issue by NickDrouin** [MicrosoftDocs/azure-devops-docs#6896]
Above, the sentence:
["Parameter expansion happens before conditions are considered, so you can embed parameters inside conditions."](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#use-a-template-parameter-as-part-of-a-condition)

Is not true when you pass a parameter to template: the parameter is NULL in the template at the time the condition is evaluated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@NickDrouin Thank you for the feedback, assigning this to the author for review.

If this issue is product-related, a ticket should to be filed with the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by fluffy-cakes** [comment]
i have been doing my nut in trying to figure out what's going wrong.

my pipeline variable `terraformDestroy` = `yes`

```
stages:
- template: /.pipelines/library/stages/base-ms.yml
  parameters:
    terraformBackendContainerName: $(TERRAFORM_BACKEND_CONTAINER_NAME)
    terraformBackendKeyName: $(ENVIRONMENT_NAME)/base-ms.tfstate
    terraformBackendStorageName: $(TERRAFORM_BACKEND_STORAGE_NAME)
    terraformDestroy: ${{ variables['terraformDestroy'] }}
    terraformRootFolder: "modules/compliance_core"
```

will fail when parameters and variables are evaluated at the same time:
```
    - script: |
        cd $SYSTEM_DEFAULTWORKINGDIRECTORY/${{ parameters['terraformRootFolder'] }}
        echo "I'm going to destroy!"
        echo ${{ parameters.terraformDestroy }}
        echo $(terraformDestroy)
      condition: eq('${{ parameters['terraformDestroy'] }}', 'yes')
      displayName: "Terraform - Destroy ~${{ parameters['terraformRootFolder'] }}"
```

it will be blank: `eq('', 'yes')` which evaluates to `False`

however, if i change the condition to `condition: eq(variables['terraformDestroy'], 'yes')` it will work, but it's not pulling in the variable via parameters. which sucks
