### ISSUE TITLE
Dotnet Run

### ISSUE THREAD

**Issue by Norrch2** [MicrosoftDocs/azure-devops-docs#6947]
This article indicates that it supports the "Run" command but does not provide any examples. Please provide examples to use this command-line argument. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@Norrch2 Thank you for the feedback.

Assigning this to the author for further review.

**Comment by babelshift** [comment]
```
- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
```
