### ISSUE TITLE
This documentation page needs A LOT of work

### ISSUE THREAD

**Issue by ahelwer** [MicrosoftDocs/azure-devops-docs#6967]
Many parameters missing documentation, unclear how to use various commands.
This task is a mess. It should be split up into a bunch of smaller tasks (one for pack, one for push, etc.) - as is, it's very difficult to figure out which parameters are required and which are optional for any given command.
Documentation is inconsistent between this page and others, for example here: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml
I have to try 5-10 times before I brute-force the correct way to use this command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@ahelwer Thank you for providing feedback to Microsoft!

Assigning this to the author for further review.

**Comment by estensen** [comment]
Is there any progress on this? Is `allowPackageConflicts` still only available for Windows agents as stated here?

**Comment by satbai** [comment]
Ways to improve the current [NuGet ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)docs:
I think we need more examples with the various options we have. There are currently some examples of restore, pack and push commands but we should add one for custom as well. E.g.
"Custom command can be used to run any other nuget command, such as
```
- task: NuGetCommand@2
  displayName: 'NuGet locals all -clear'
  inputs:
    command: custom
    arguments: 'locals all -clear -verbosity Detailed'
```
Change the following:

![image](https://user-images.githubusercontent.com/24945574/82711746-266e7c80-9c3b-11ea-9fc0-9dec28995534.png)
We should add to the above that the string here must be either 'select' or 'config' as seen in the examples in the docs.

![image](https://user-images.githubusercontent.com/24945574/82711907-9250e500-9c3b-11ea-9da1-d3f4156bf0ff.png)
Add: Default: true and equired when feedsToUse == Select

Add example of using externalFeedCredentials:
```
- task: NuGetCommand@2
  displayName: 'NuGet restore NuGet.config external feed'
  inputs:
    restoreSolution: 'Example.sln'
    feedsToUse: config
    nugetConfigPath: ./nuget.config
    externalFeedCredentials: 'Canary@CodeSharing-SU0 (Artifacts)'
    noCache: true
  continueOnError: true
```
And add to the explanation that it needs to be the name of the [service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml) here: 
![image](https://user-images.githubusercontent.com/24945574/82712038-f673a900-9c3b-11ea-9a83-343895210fa8.png)
https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml
 


Updates to the [publish to nuget feed](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops) docs:
