### ISSUE TITLE
Resource Group Deployment Task Blows Up DevOps Deploy With AKS + CosmosDB.

### ISSUE THREAD

**Issue by dhmorrison** [MicrosoftDocs/azure-devops-docs#6968]
Out of the box the DevOps Project created by Azure Portal contains a DevOps Deployment task that invokes this product.

```
steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'Azure Deployment:Create AKS cluster'
  inputs:
    azureSubscription: 'wfdss-az-do-poc-001 - Azure'
    resourceGroupName: 'wfdss-az-do-poc-001-rg'
    location: 'East US'
    csmFile: '$(System.DefaultWorkingDirectory)/**/aks-template.json'
    overrideParameters: '-clusterName "myClusterName" -dnsPrefix "myPrefix" -appInsightsLocation "myLocation" -clusterLocation "myLocation" -servicePrincipalClientId "$(ServicePrincipalId)" -servicePrincipalClientSecret "$(ServicePrincipalKey)" -agentCount 3 -agentVMSize Standard_DS2_v2 -kubernetesVersion 1.13.12 -omsLocation "myLocation" -clusterTags $(clusterTags) -omsWorkspaceName "myName" -databaseAccountId mydbName -databaseAccountLocation myLocation -httpApplicationRoutingEnabled true'
    deploymentOutputs: deploymentOutputs
```
Here's the Error:

```
Starting: Azure Deployment:Create AKS cluster
==============================================================================
Task         : Azure resource group deployment
Description  : Deploy an Azure Resource Manager (ARM) template to a resource group and manage virtual machines
Version      : 2.162.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
==============================================================================
Checking if the following resource group exists: myaksParameter-rg.
Resource group exists: true.
Creating deployment parameters.
The detected encoding for file '/home/vsts/work/1/s/ArmTemplates/aks-template.json' is 'utf-8'
Starting Deployment.
Deployment name is aks-template-20200117-032050-2419
There were errors in your deployment. Error code: InvalidTemplateDeployment.
##[error]The template deployment 'aks-template-20200117-032050-2419' is not valid according to the validation procedure. The tracking id is 'ddca30fa-54ac-4953-ae1e-06d707808310'. See inner errors for details.
##[error]Details:
##[error]PropertyChangeNotAllowed: Provisioning of resource(s) for container service myaksParameter in resource group myaksParameter-rg failed. Message: {
  "code": "PropertyChangeNotAllowed",
  "message": "Changing property 'servicePrincipalProfile.secret' is not allowed.",
  "target": "servicePrincipalProfile.secret"
 }. Details: 
##[error]Task failed while creating or updating the template deployment.
Finishing: Azure Deployment:Create AKS cluster
````
If I remove the stuff about the servicePrinciple then I get a different error complaining about the "servicePrinciple stuff" is missing.  Seems to be a catch 22.  Since this is an out of the box deployment created by Azure, I'm feeling a bit discouraged.  It's not optimal behavior, a demo install/deployment from Azure to show off some functionality, straight up not working.  But that's where we are here.

How do I fix this template deployment task so the Cosmos stuff gets deployed and the servicePrinciple requirement is fulfilled, and my AKS cluster is deployed to?

Thanks for the help.

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**
