### ISSUE TITLE
YML "Show Assistant" Seems to Provide Different .Net Core Publish Code than the Forked Repo

### ISSUE THREAD

**Issue by DanJ210** [MicrosoftDocs/azure-devops-docs#6994]
Long story as to why I've got a new project which is a project that I already have on Azure Dev ups with CI/CD setup to automatically build and release to Azure but I am. I've created a pipeline but the build doesn't seem to be publishing or producing any artifact so the release does not pick it up. When viewing the pipeline .yml file and clicking "Show Assistant" if I click .Net Core and select publish -&gt; add it adds some additional code that the .yml file flags as duplicates. So I don't understand how that tool is supposed to be assisting me. All I want is to create a build task that publishes an artifact when done.

I'm using this doc to try to understand something that I already had setup once a while back. What's confusing me and why I'm reporting this here is the first set of steps, "Create Pipeline" after step 6 where you're revieweing the .yml file. The code from the branch that I forked above has this in the .yml file
```
steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
```
But when using the assistant and adding the selected .Net Core publish choices it adds
```
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
```

What's right and why is there a difference? The docs don't seem to cover what Azure Dev Ops is providing to the user while the repo training tool is providing something entirely different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@DanJ210 -- Daniel, you may find some answers here:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

@chcomley -- please look into this issue.

**Comment by DanJ210** [comment]
I've been reading around profusely so I'll continue to do so. I'll keep an ear open in case something comes up here. Thank you.

**Comment by juliakm** [comment]
@DanJ210 If you haven't seen it already, this [section](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#publish-artifacts-to-azure-pipelines) goes into more details. 

You can run `dotnet publish --output $(Build.ArtifactStagingDirectory)` or `DotNetCoreCLI@2` and `PublishBuildArtifacts@1` to produce a release artifact. 

Here's the YAML I tested with:
```
# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'myWebsiteName'
```
