### ISSUE TITLE
Difference between AzureResourceManagerTemplateDeployment and AzureResourceGroupDeployment

### ISSUE THREAD

**Issue by fgheysels** [MicrosoftDocs/azure-devops-docs#7122]
There seem to be 2 similar tasks available for deploying Azure resources.

Unfortunately, I cannot find any documentation regarding the `AzureResourceManagerTemplateDeployment` although this `AzureResourceManagerTemplateDeployment` task can be choosen from the Yaml pipeline editor in Azure Devops:

```yaml
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
```

On the other hand, I cannot find the `AzureResourceGroupDeployment` task in the Yaml pipelines editor in Azure Devops.  What are the differences between these 2 tasks ?  Where can I find the documentation regarding the `AzureResourceManagerTemplateDeployment` task and how come I cannot find the `AsureResourceGroupDeployment` task in the Yaml editor in Azure Devops ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**
