### ISSUE TITLE
Notes about how to use azure key vault secrets

### ISSUE THREAD

**Issue by mikehachen** [MicrosoftDocs/azure-devops-docs#7123]
Obviously, you can't use values from a variable group directly if they are secrets from an Azure Key Vault. There is no detailed description or examples of how such values can be used in a yml pipeline.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ChendrayanV** [comment]
I don;t see any challenge in it! In my case I have TenantID, ClientID and ClientSecret in a Az Key Vault as secrets. I created a variable group and followed the steps for authorization. 

Below YAML is working as expected. 
```YAML
trigger:
  branches:
    include:
      - 'master'

stages:
  - stage:
    variables:
      - group: 'Azure Automation'
      - name: 'Azure Automation'
    pool: 
      name: 'AZ-Automation'
    jobs:
      - job: 
        steps:
          - task: PowerShell@2
            inputs:
              targetType: filePath
              filePath: 'src\Microsoft.Azure.Billing.ps1'
              arguments: '-TenantId $(TenantId) -ClientId $(ClientId) -ClientSecret $(ClientSecret)'
```

My PowerShell Script  (To Generate Bearer Token)

```PowerShell
param (
    $TenantId,

    $ClientId,

    $ClientSecret
)
$Result = Invoke-RestMethod -Uri https://login.microsoftonline.com/$TenantID/oauth2/token?api-version=1.0 `
    -Method Post `
    -Body @{
    "grant_type" = "client_credentials"; "resource" = "https://management.core.windows.net/"; "client_id" = "$ClientId"; "client_secret" = "$ClientSecret" 
}
$Authorization = "{0} {1}" -f ($result.token_type , $result.access_token)
$Authorization
```
