### ISSUE TITLE
Document variable usage syntax

### ISSUE THREAD

**Issue by Lectem** [MicrosoftDocs/azure-devops-docs#7210]
It seems that using the familiar syntax

`variables.Build.SourceBranch` expands to `variables['Build']['SourceBranch']` which is not the same as `variables['Build.SourceBranch']` ?

This should be mentionned as it is misleading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
I apologize for the delay on this. The variable syntax `variables['Build.SourceBranch']` should work. Here is an example YAML. The variables variables['Build.SourceBranch'] processes as variables['Build']['SourceBranch'] but this should happen behind the scenes. 

```yaml
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isMainTwo: $[eq(variables['Build']['SourceBranch'], 'refs/heads/master')]

steps:
 - script: echo $(isMain) # True
 - script: echo $(isMainTwo) # False
```
