### ISSUE TITLE
Pipeline triggers based on stage not supported

### ISSUE THREAD

**Issue by chatelain-io** [MicrosoftDocs/azure-devops-docs#7234]
Documentation state that we can set pipeline triggers on specific stage but when I do so I get "Stage filters in pipeline resource pipeline_name" is not supported.

The resource pipeline is a bitbucket repository, is it a limitation based on the repository type or the feature isn't deployed yet.

In any case, the documentation should describe what is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by chatelain-io** [comment]
Pipeline stage filters should be removed from the documentation.

I was in communication with the Support team and they confirmed this feature is not yet available.

Response on 2020-02-21

Hope you are doing well.
I got an update from the product team that we don't have stage filter support yet. Initially, we built it, that's why you see it in the documents. However, there is a significant improvement we have to do on this and our developers are working on this to improve it in the future.

**Comment by socrplaycj** [comment]
I'm having the same issue.

**Comment by alanwales** [comment]
We are also eager to use this feature and were disappointed to see the documentation does not reflect what is actually supported. Please let us know when it's available, thanks!

**Comment by moonrockfamily** [comment]
Without stage 'approvals' in pipeline releases, we attempted to use the 'stages' filter to ensure the production release (GEOR) was 'approved'/manually initiated!  We are using a 'tag to release' process that has worked well for us.

```yaml
name: Release
# Disable Source repository Trigger
trigger:
  - none

# The resources this pipeline depends on.
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#schema
resources:
  pipelines:
    - pipeline: BuildPipeline  # Name of this pipeline resource
      source: Build # Name of the triggering pipeline
      trigger: # See pipelineResourceTrigger definition
        branches:
          include:
            - refs/tags/deploy*
        stages: # automatically trigger the 'test' stages.
          - GSB1
          - GSB3
          - GSB5
          - GSB6

stages:
  - stage: GEOR
    displayName: Production Release
    condition: startsWith(variables['build.SourceBranchName'], 'deployGEOR')
    dependsOn: GSB1
    variables:
      - group: database-variables-geor
      - template: variablesTemplate-JobSubService.yml
        parameters:
          bannerExe: 'c:\Banner\GEOR\general\exe' 
    jobs:
      - template: jobsTemplate-MigrateDatabase.yml
      - template: jobsTemplate-DeployBannerJobs.yml
      - template: jobsTemplate-RestartJobSubService.yml

  - stage: GSB1
    condition: >
      or(
        startsWith(variables['build.SourceBranchName'], 'deployGSB1'),
        startsWith(variables['build.SourceBranchName'], 'deployGEOR')
      )
    dependsOn: [] # no dependency
    variables:
      - group: database-variables-gsb1 
      - template: variablesTemplate-JobSubService.yml
        parameters:
          bannerExe: 'c:\Banner\gsb1\general\exe' 
    jobs:
      - template: jobsTemplate-MigrateDatabase.yml
      - template: jobsTemplate-DeployBannerJobs.yml
      - template: jobsTemplate-RestartJobSubService.yml

  - stage: GSB3
    condition: startsWith(variables['build.SourceBranchName'], 'deployGSB3')
    dependsOn: [] # no dependency
    variables:
      - group: database-variables-gsb3
      - template: variablesTemplate-JobSubService.yml
        parameters:
          bannerExe: 'c:\Banner\gsb3\general\exe' 
    jobs:
      - template: jobsTemplate-MigrateDatabase.yml
      - template: jobsTemplate-DeployBannerJobs.yml
      - template: jobsTemplate-RestartJobSubService.yml

  - stage: GSB5
    condition: startsWith(variables['build.SourceBranchName'], 'deployGSB5')
    dependsOn: [] # no dependency
    variables:
      - group: database-variables-gsb5 
      - template: variablesTemplate-JobSubService.yml
        parameters:
          bannerExe: 'c:\Banner\gsb5\general\exe' 
    jobs:
      - template: jobsTemplate-MigrateDatabase.yml
      - template: jobsTemplate-DeployBannerJobs.yml
      - template: jobsTemplate-RestartJobSubService.yml

  - stage: GSB6
    condition: startsWith(variables['build.SourceBranchName'], 'deployGSB6')
    dependsOn: [] # no dependency
    variables:
      - group: database-variables-gsb6
      - template: variablesTemplate-JobSubService.yml
        parameters:
          bannerExe: 'c:\Banner\gsb6\general\exe' 
    jobs:
      - template: jobsTemplate-MigrateDatabase.yml
      - template: jobsTemplate-DeployBannerJobs.yml
      - template: jobsTemplate-RestartJobSubService.yml
```

### Side Note
You might also notice our pipeline trigger uses a hack `branches` `include` node , vs using the `tags` node.  This hack was necessary because the pipelineResourceTrigger-tags node only supports a sequenceOfNonEmptyString and a value of `deploy*` was not matched/did not trigger the pipeline.

```yaml
resources:
  pipelines:
    - pipeline: BuildPipeline  # Name of this pipeline resource
      source: Build # Name of the triggering pipeline
      trigger: # See pipelineResourceTrigger definition
        branches:
          include:
            - refs/tags/deploy*
        stages: # automatically trigger the 'test' stages.
          - GSB1
          - GSB3
          - GSB5
          - GSB6
```
vs desired:
```yaml
resources:
  pipelines:
    - pipeline: BuildPipeline  # Name of this pipeline resource
      source: Build # Name of the triggering pipeline
      trigger: # See pipelineResourceTrigger definition
        tags:
          include:
            - deploy*
        stages: # automatically trigger the 'test' stages.
          - GSB1
          - GSB3
          - GSB5
          - GSB6
```

tried but didn't trigger:
```yaml
resources:
  pipelines:
    - pipeline: BuildPipeline  # Name of this pipeline resource
      source: Build # Name of the triggering pipeline
      trigger: # See pipelineResourceTrigger definition
        tags:
          - deploy*
```
Notice the absence of the non-supported `stages` node!

**Comment by moonrockfamily** [comment]
Trying the following work-around:
```yaml
resources:
  pipelines:
    - pipeline: BuildPipeline  # Name of this pipeline resource
      source: Build # Name of the triggering pipeline
      trigger: # See pipelineResourceTrigger definition
        branches:
          include:
            - refs/tags/deploy*
        # The following depends on a fix for https://github.com/MicrosoftDocs/azure-devops-docs/issues/7234
        # stages: # automatically trigger the 'test' stages.
        #   - GSB1
        #   - GSB3
        #   - GSB5
        #   - GSB6

stages:
  - stage: GEOR
    displayName: Production Release
    condition: startsWith(variables['build.SourceBranchName'], 'deployGEOR')
    dependsOn: 
      - GSB1
      - MustManuallyRunThisStageOfThePipeline
    variables:
      - group: database-variables-geor
      - template: variablesTemplate-JobSubService.yml
        parameters:
          bannerExe: 'c:\Banner\GEOR\general\exe' 
    jobs:
      - template: jobsTemplate-MigrateDatabase.yml
      - template: jobsTemplate-DeployBannerJobs.yml
      - template: jobsTemplate-RestartJobSubService.yml
```

**Comment by moonrockfamily** [comment]
Nice try, no luck:
`Stage GEOR depends on unknown stage MustManuallyRunThisStageOfThePipeline.`

**Comment by 24mu13** [comment]
Sprint 172 July, 9 - "These features will roll out over the next two to three weeks"
:thinking:

**Comment by yashv** [comment]
(Piggybacking on this discussion)

I stumbled upon this thread while facing a peculiar problem:

My triggered pipeline looks like this:
```yml
trigger: none

resources:        # types: pipelines | builds | repositories | containers | packages
  pipelines:
  - pipeline: YVPlayStarter  # identifier for the resource used in pipeline resource variables
    source: TestBuilds/YV Play Starter # Name of the triggering pipeline
    trigger: 
      branches:
        include:
          - users/yv/bring-together
      stages:
        - Stg1
        - Stg2

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

```

My Triggering pipeline has three stages, and triggered pipeline is running twice: once when the mentioned stages (Stg1, Stg2) complete and once when the all the stages complete in the triggering pipeline.
