### ISSUE TITLE
Accessing output variables from earlier lifecycle hooks

### ISSUE THREAD

**Issue by arnoschuring** [MicrosoftDocs/azure-devops-docs#7294]
It appears there is no way to access variables defined earlier in the current deployment, or if there is, it deserves a mention in the documentation.

As a simple example, how is this designed to work:

```
  strategy:
    runOnce:
      preDeploy:
        steps:
        - powershell: echo "##vso[task.setvariable variable=myLocalVar;isOutput=false]local variable"
          name: setvarStep
        - powershell: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]output variable"
          name: outvarStep
        - powershell: echo 'Both $(myLocalVar) and $(outvarStep.myOutputVar) are available here'
      deploy:
        steps:
        - powershell: echo 'Neither $(myLocalVar) nor $(outvarStep.myOutputVar) are available here'
```

I was hoping that the fixes in release 164 would cover this, but it appears they only cover consuming output variables in dependent jobs, not in subsequent hooks within the same job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops&source=docs#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
