### ISSUE TITLE
More than one Deployment Job in a single Stage?

### ISSUE THREAD

**Issue by mgeorgebrown89** [MicrosoftDocs/azure-devops-docs#7347]
Is this possible? I haven't had success so far. Even just with this example:

```
- stage: Deploy
    dependsOn: Test
    jobs:
    - deployment: Infrasctructure_Development
      displayName: Infrastructure
      environment: Development
      strategy:
        runOnce:
          deploy:
            pool: 
              vmImage: windows-2019
            steps:
              - task: PowerShell@2
                inputs:
                  targetType: inline
                  script: echo hello                  
    - deployment: Applications_Development
      displayName: Applications
      environment: Development
      strategy:
        runOnce:
          deploy:
            pool: 
              vmImage: windows-2019
              steps:
                - task: PowerShell@2
                  inputs:
                    targetType: inline
                    script: echo hello
```

I get an error saying the `Deployment Life cycle hook of type Deploy must contain steps to be run as part of the hook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@mgeorgebrown89 -- Michael, thank you for your question.  You may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

@juliakm -- Julia, please look into this issue.

**Comment by brent-robinson** [comment]
@mgeorgebrown89 - It looks like your second deployment is indented incorrectly. In the sample you've provided, `steps` is appearing under `pool`, whereas it should be under `deploy` (similar to your first deployment).

```
- stage: Deploy
    dependsOn: Test
    jobs:
    - deployment: Infrasctructure_Development
      displayName: Infrastructure
      environment: Development
      strategy:
        runOnce:
          deploy:
            pool: 
              vmImage: windows-2019
            steps:
              - task: PowerShell@2
                inputs:
                  targetType: inline
                  script: echo hello                  
    - deployment: Applications_Development
      displayName: Applications
      environment: Development
      strategy:
        runOnce:
          deploy:
            pool: 
              vmImage: windows-2019
            steps: # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< here
              - task: PowerShell@2
                inputs:
                  targetType: inline
                  script: echo hello
```

**Comment by juliakm** [comment]
Thanks @brent-robinson! 

@mgeorgebrown89 Here's an updated YAML that runs for me. I'm closing this issue because it doesn't appear to be a documentation bug. 

```
stages:
- stage: Deploy
  jobs:
    - deployment: Infrasctructure_Development
      displayName: Infrastructure
      environment: Development
      strategy:
        runOnce:
          deploy:
            pool: 
              vmImage: windows-2019
            steps:
              - task: PowerShell@2
                inputs:
                  targetType: inline
                  script: echo hello                  
    - deployment: Applications_Development
      displayName: Applications
      environment: Development
      strategy:
        runOnce:
          deploy:
            pool: 
              vmImage: windows-2019
            steps:
              - task: PowerShell@2
                inputs:
                  targetType: inline
                  script: echo hello
```
