### ISSUE TITLE
appSettings field using linked variable set

### ISSUE THREAD

**Issue by 1TheMuffinMan** [MicrosoftDocs/azure-devops-docs#7348]
I have variable sets defined that don't necessarily belong to any specific release pipeline. Once I link a variable set into a pipeline it doesn't appear there is a way to bind that to the appSettings field (I have to type them out manually). Is there a way to achieve this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by WilliamAntonRohm** [comment]
@1TheMuffinMan -- Nicholas, thank you for your feedback.  You may find answers here:

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

@azooinmyluggage -- Atul, please look into this potential documentation issue.

**Comment by bennypowers** [comment]
I'm accomplishing this like so:
```yaml

- task: AzureAppConfiguration@3
  inputs:
    azureSubscription: $(azureSubscription)
    ConfigstoreName: $(appConfigName)
    KeyFilter: '*'
    Label: ${{ parameters.deploymentEnvironment }}
  displayName: Get config values from Azure App Configuration

- task: AzureFunctionApp@1
  displayName: Deploy Server to Azure Functions
  inputs:
    azureSubscription: $(azureSubscription)
    appType: functionAppLinux
    appName: $(GRAPHQL_FUNCTION_APP_NAME)
    appSettings: >-
      -AUTH0_CLIENT_ID "$(AUTH0_CLIENT_ID)"
      -AUTH0_DOMAIN "$(AUTH0_DOMAIN)"
      -GRAPHQL_HOST "$(GRAPHQL_HOST)"
    configurationStrings: --always-on true
    package: $(Pipeline.Workspace)/server/$(Build.BuildId)-server.zip
    resourceGroupName: $(resourceGroup)
```

As OP mentioned, this is less maintainable than I would have hoped.
Some API like
```yaml
apiSettingsFromConfig: true
```
which would forward the variables from the previous config step would be pleasant.
