### ISSUE TITLE
Documentation should contain a "Build a Xamarin.Forms app" section

### ISSUE THREAD

**Issue by dfoulk** [MicrosoftDocs/azure-devops-docs#7356]
It would be great to see some recommendations here for Xamarin.Forms developers. Some questions that should maybe be addressed in this doc:

1) Do we just add a .NET Standard step to the Xamarin.Android/iOS template in x2 Pipelines?
2) Does it make sense to create x1 Pipeline with x2 agents?
    - Agent 1 (Android)
        - .NET Core (build task)
        - Xamarin.Android (build task)
    - Agent 2 (iOS)
        - .NET Core (build task)
        - Xamarin.iOS (build task)

Basically, what do you recommend we do to setup Pipelines for our Xamarin.Forms projects?

Extra Credit: Microsoft should add a Xamarin.Forms template to Pipelines :)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54533c61-9265-2908-c92d-f49285b24333
* Version Independent ID: 004ded47-21ee-94a7-51fe-2b835e124b55
* Content: [Build Xamarin apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xamarin?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/ecosystems/xamarin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/xamarin.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by chowarth** [comment]
There is no difference when building a Xamarin.Forms app because you have multiple platforms to build for, each with their own unique pipeline requirements. As per your thoughts, 2. makes most sense. Here's a rough example of what I use:

- Job1
  - windows-latest
  - Build and run Unit tests
- Job2
  - Depends on Job1
  - macosx-latest
  - Tasks for building iOS project
- Job3
  - Depends on Job1
  - macosx-latest
  - Tasks for building Android project
- Job4
  - Depends on Job1
  - windows-latest
  - Tasks for building UWP project

The tasks you run for each project can be totally different depending on what you want to do with your pipeline e.g. Versioning requires different files to be updated depending on the platform.

**Comment by dfoulk** [comment]
@chowarth Thank you for your response. That is what I was looking for in the documentation. I haven't been able to find any instructions on how to setup a Xamarin.Forms Pipeline. My first attempt at setting up an Azure Pipeline was a Xamarin.Forms app. I never did get it working. I'll be trying again this week.

I would really love to see a Pipelines template for Xamarin.Forms so that people like myself (unfamiliar with Pipelines) can get up and running as easily as a .NET MVC developer. Those guys have it made- templates and documentation all over the place!

Anyways, thank you for your help.Derek

**Comment by CalvinAllen** [comment]
@dfoulk Did you figure out your pipeline for the Xamarin.Forms app?  I have a working one I can put in a gist, if so.

**Comment by dfoulk** [comment]
@CalvinAllen I did get one created- after much pain and suffering lol. Thank you; I would love to compare what I have to yours. Plus, I'm sure someone will appreciate us posting them here! I'll post mine here today.

**Comment by CalvinAllen** [comment]
@dfoulk Here's what mine looks like currently for building the iOS project.  Note that we have our provisioning profile / etc., stored in the Library as a variable group with `p12Filename`, `p12Password`, and `provisioningProfile` variables, and the files stored in the Secure Files area.

```
variables:
- name: buildConfiguration
  value: Release
- group: codesign_and_provisioning

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: UseDotNet@2
  displayName: 'Configure .NET SDK...'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_6_1
  displayName: 'Select Xamarin SDK Version...'
  enabled: true

- script: sudo xcode-select -s /Applications/Xcode_11.3.1.app/Contents/Developer
  displayName: 'Select Xcode Version...'
  enabled: true
  
- task: InstallAppleCertificate@2
  displayName: 'Install Certificate [$(p12FileName)]...'
  inputs:
    certSecureFile: '$(p12FileName)'
    certPwd: '$(p12Password)'
    keychain: 'temp'
    deleteCert: true  

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Provisioning Profile [$(provisioningProfile)]...'
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(provisioningProfile)'
   removeProfile: true
   
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore Packages...'
  inputs:
    restoreSolution: '**/*.sln'

- task: ios-bundle-version@1
  displayName: 'Set Version...'
  inputs:
    sourcePath: 'src/StarLeasing.Inspection.IOS/Info.plist'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    versionName: '2.0.0'
    printFile: false
      
- task: XamariniOS@2
  displayName: 'Build iOS Application...'
  inputs:
    solutionFile: '**/*.IOS.csproj'
    configuration: '$(buildConfiguration)'
    packageApp: true
    buildForSimulator: false
    runNugetRestore: false
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'
    
- task: CopyFiles@2
  displayName: "Archive IPA file..."
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifacts..."
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
```
