### ISSUE TITLE
Including KeyVault secrets inside a template

### ISSUE THREAD

**Issue by devedse** [MicrosoftDocs/azure-devops-docs#7390]
Hi all,

I've created a build and release pipeline. The release basically kicks of a template and provides one variable: 'ENVIRONMENT':

```
- stage: "Release_Development"
  jobs:
  - template: build-release-pipeline-release-template.yml
    parameters:
      ENVIRONMENT: 'dev'
```

What I want to do is based on this environment variable, use the right variables from the key vault. Currently I've simply placed this at the top of the parent YAML:

```
variables:
  - group: akv-userprov-dev-001
```

This works because inside the library tab I've created a variable group that's connected to the Keyvault.

However since the secrets have the same name in the key vault for TEST and PROD we can't distinguish them during the release.

Is there a way to pass variables of a specific key vault connection to a template? (Or obtain them inside the template itself based on a variable group name)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by devedse** [comment]
Currently I'm using a workaround to just use the Azure DevOps task to load all secrets from the Keyvault as variables inside the build/release.

**Comment by WilliamAntonRohm** [comment]
@devedse -- Devedse, thank you for your feedback and research.  You may find answers to your questions here:

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 


 
@juliakm -- Julia, please look into this issue.

**Comment by rhoffpauir** [comment]
I've got the same question/problem. I love the integration between Azure Devops Variable Groups and KeyVault, but would really like to be able to consume the variable groups dynamically by a variable that indicates the Environment.

**Comment by devedse** [comment]
I've since resolved this issue as follows:

```
- stage: "Release_Development"
  condition: and(succeeded(), and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest')))
  variables:
    - group: CoolApp-dev
  jobs:
  - template: infra-pipeline-release-template.yml
    parameters:
      ENVIRONMENT: 'dev'

 - stage: "Release_Test"
   condition: and(succeeded(), and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest')))
   variables:
     - group: CoolApp-test
   jobs:
   - template: infra-pipeline-release-template.yml
     parameters:
       ENVIRONMENT: 'test'

 - stage: "Release_Production"
   condition: and(succeeded(), and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest')))
   variables:
     - group: CoolApp-prod
   jobs:
   - template: infra-pipeline-release-template.yml
     parameters:
       ENVIRONMENT: 'prod'
```

This allows you to pass a variable group (from the library)
