### ISSUE TITLE
Missing mandatory hostName

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-devops-docs#7401]
I followed the example in this page, yet the pipeline fails with:

```
Starting: Install SSH key
==============================================================================
Task         : Install SSH key
Description  : Install an SSH key prior to a build or deployment
Version      : 0.156.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/install-ssh-key
==============================================================================
##[error]Error: Input required: hostName
Finishing: Install SSH key
```

The correct YAML (working in my case) is:

```
# Install SSH key
# Install an SSH key prior to a build or deployment
- task: InstallSSHKey@0
  inputs:
    hostName: 
    sshPublicKey: 
    #sshPassphrase: # Optional
    sshKeySecureFile: 
```

Where `hostName` is the name of the host to connect (not the full line of `known_hosts` as the Git example suggests).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops#open-source)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
