### ISSUE TITLE
Lack of documentation when using SSH with git

### ISSUE THREAD

**Issue by LordGordonQ** [MicrosoftDocs/azure-devops-docs#7404]
Using SSH with git is mandatory if your repository has submodules. I spent many hours trying to figure out how clone such repository using SSH in a Pipeline. 

Here a minimal example.

Steps:
 1. create locally a new SSH key
 1. add the public key to your Azure DevOps to allow it to access the repository
 1. add the private key in the Library (Azure DevOps Pipeline)
 1. make sure the user `Project Collection Build Service (yourname)` has at least the following permissions with the repositories (main and submodules): `Contribute`, `Create Branch`, `Create tag`, `Read`.

**YAML**
```
variables:
  ssh_public_key: 'ssh-rsa xxxxx'

resources:
  repositories:
  - repository: self

jobs:
  - job: YourJobName
    pool:
      vmImage: 'ubuntu-latest'
    workspace:
      clean: all
    steps:
      - checkout: none

      - task: InstallSSHKey@0
        inputs:
          hostName: 'ssh.dev.azure.com'
          sshPublicKey: $(ssh_public_key)
          sshKeySecureFile: 'private_key_name_as_in_the_library'
        displayName: "Install SSH key"
      
      - script: git clone --recurse-submodules git@ssh.dev.azure.com:v3/xxx
        workingDirectory: $(Agent.BuildDirectory)
      - script: |
          git submodule foreach 'git checkout master'
          git submodule foreach 'git status'
          git status
        workingDirectory: $(Agent.BuildDirectory)/mainrepo
      
      - script: |
          git config --global user.email "noreply@mydomain.com"
          git config --global user.name "Azure DevOps Pipeline"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 024e4ed9-cf8d-155f-5e4a-73c2effaaed8
* Version Independent ID: f19c0538-4aae-b3b4-82b9-422e76723b01
* Content: [Run Git commands in a script - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/scripts/git-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/git-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**
