### ISSUE TITLE
Minimatch patterns do not work as expected in DownloadPipelineArtifact

### ISSUE THREAD

**Issue by ian-craig** [MicrosoftDocs/azure-devops-docs#7432]
The `patterns` argument is described as one or more patterns which "limit which files get downloaded". The docs link to https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops for examples of how to use.

As a test I have the following
```
  - task: DownloadPipelineArtifact@2
    inputs:
      targetPath: $(Agent.TempDirectory)/foo
      artifactName: 'myArtifactName'
      patterns: |
        **
        !__tests__/**
        !rush.json

  - script: dir
    workingDirectory: $(Agent.TempDirectory)/foo
```
The download task logs that it is using the patterns:
`Information, Minimatch patterns: [**,!__tests__/**,!rush.json]`

However it appears to just ignore the patterns and download the files anyway.
```
 Directory of D:\a\_temp\foo

02/27/2020  05:12 PM    <DIR>          .
02/27/2020  05:12 PM    <DIR>          ..
02/27/2020  05:12 PM               169 .gitignore
02/27/2020  05:12 PM    <DIR>          apps
02/27/2020  05:12 PM    <DIR>          common
02/27/2020  05:12 PM             3,276 package.json
02/27/2020  05:12 PM               960 rush.json
02/27/2020  05:12 PM    <DIR>          __tests__
```

According to the linked documentation, my pattern should have excluded the `rush.json` file and the `__tests__` directory. "Leading ! changes the meaning of an include pattern to exclude. You can include a pattern, exclude a subset of it, and then re-include a subset of that: this is known as an "interleaved" pattern."

It's possible that I'm using `patterns` incorrectly, but there are very few examples to go on in the linked documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
