### ISSUE TITLE
Powershell Core?

### ISSUE THREAD

**Issue by mmisztal1980** [MicrosoftDocs/azure-devops-docs#7434]
The documentation does not specify whether or not the task supports Powershell Core and / or how to enable it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by koushik984** [comment]
Just confirming that core works on azure powershell task :) 

I am able to use flag as below
```
task: AzurePowerShell@4
          displayName: 'az ps: test core'
          inputs:
            azureSubscription: $(serviceconnection_name)
            pwsh: true
            scriptType: inlineScript
            inline: Get-ChildItem $(System.DefaultWorkingDirectory)
            azurePowerShellVersion: 'latestVersion'
```
