### ISSUE TITLE
Problems with ReviewApp

### ISSUE THREAD

**Issue by mmisztal1980** [MicrosoftDocs/azure-devops-docs#7445]
I'm attempting to configure the reviewApp flow to verify that the dynamic env creation works as expected.

This is a fragment of a stage that contains the deployment job
```yaml
stages:
  - stage: deployment_stage_cluster_${{ parameters['Kubernetes.Namespace'] }}
    displayName: "deploy to ${{ parameters['Kubernetes.Cluster'] }}"
    dependsOn: []    
    jobs:      
      - deployment: DeployPullRequest
        displayName: Deploy Pull request
        condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
        pool:
          vmImage: ${{ parameters['Agent.Pool'] }}
        environment: azureday2020-demo-aks.test
        strategy:
          runOnce:
            deploy:
              steps:
                - reviewApp: test
                - task: KubectlInstaller@0
                  displayName: "kubectl installer"
                  inputs: 
                    kubectlVersion: ${{ parameters['Kubernetes.Kubectl.Version'] }}
                - task: HelmInstaller@1
                  displayName: "helm installer"
                  inputs: 
                    helmVersionToInstall: ${{ parameters['Kubernetes.Helm.Version'] }}
                - task: Kubernetes@1
                  displayName: 'Create a new namespace for the pull request'
                  inputs:
                    command: apply
                    useConfigurationFile: true
                    inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "test" }}'
```

Problems encountered:
- Attempts of running a pipeline containing the above template yield an immediate error: `Job Deployment: Resource test does not exist in environment azureday2020-demo-aks`
  - This appears to work differntly than advertised? I was under the impression that both the environment and the resource were to be provisioned automatically?
- When attempting to use template parameters to define the environment name : `environment: '${{ parameters['ClusterName] }}.${{ parameters['Namespace] }}'` I'm getting consistent failures stating that `environmentName` is invalid/missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-in/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops#setup-review-app)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
