### ISSUE TITLE
Versioning NPM packages

### ISSUE THREAD

**Issue by ThomasVandenbon** [MicrosoftDocs/azure-devops-docs#7469]
The [Build, test, and deploy JavaScript and Node.js apps](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops)-page briefly mentions versioning of NPM packages, but redirects you to a different page:

> For more information about versioning and publishing npm packages, see [Publish npm packages](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/npm?view=azure-devops&tabs=yaml).

However, the [Publish npm packages](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/npm?view=azure-devops&tabs=yaml)-page doesn't talk about NPM versioning at all.

In my opinion, a good versioning strategy of an NPM package is the hardest part of a release-pipeline. But as far as I can tell, it doesn't seem to fit into the idea of publishing build artifacts in a build pipeline to later release them in a release pipeline. I would have thought versioning would be done at the release step, but this seems impossible.

Some clarification (documentation) on this topic would be very helpful.

_Note: I am aware that [Publish a module to a npm registry](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops#publish-a-module-to-a-npm-registry) lists a very simple solution, but it's not a very practical approach at all._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b2fdca-9125-9720-3d03-3c6dd336f100
* Version Independent ID: b2a24e28-9858-fe1c-4527-745f1f387e4e
* Content: [Build and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/javascript.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@ThomasVandenbon I'm still working on a cleaner example for the docs but one thing you can do is use [npm version](https://docs.npmjs.com/cli/version) for versioning and then update your git repo. Here's an example of part of the YAML. 

````yaml

# log into repo
- checkout: self
  persistCredentials: true
  clean: true

# this is a truncated version
- script: |
    npm --version
    npm version minor --force # not sure if you need to force
    npm publish --access public

# push changes back to git
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email "youremail@email.com"
      git config --global user.name "Azure Pipeline"
      git add package.json
      git commit -a -m "Test Commit from Azure DevOps"
      git push -u origin HEAD:master
```
