### ISSUE TITLE
Build.Reason documented incorrectly for triggered pipeline

### ISSUE THREAD

**Issue by michaelstaszewski** [MicrosoftDocs/azure-devops-docs#7492]
The predefined pipeline vars topic says Build.Reason would be "BuildCompletion" when a pipeline is triggered by another, but I'm seeing "ResourceTrigger" as the actual value.

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

My triggered pipeline triggers block is as follows...

```
trigger:
  branches:
    exclude:
    - '*'

pr:
  branches:
    exclude:
    - '*'

resources:
  pipelines:
  - pipeline: pipeline-alias
    source: pipeline-name
    trigger:
      branches:
        include:
          - master
```
