### ISSUE TITLE
Variable expansion with deployment job and environment tags

### ISSUE THREAD

**Issue by jimjim91** [MicrosoftDocs/azure-devops-docs#7518]
When setting an output variable from a deployment job, and in that deployment job you have referenced environment tags, the pipeline sets the System.JobName variable to include the environment resource name: "JobName_environmentResource_lifecyclehook", this wasn't immediately clear from the documentation, however this made it clearer for me: https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/preview/outputvariable.md

**Comment by jimjim91** [comment]
Example, Imagine in the environment there is a VM called "VM1", and another called "VM2", the VM1 has a tag called "tag1", VM2 has a tag called "tag2"
`stages:
- stage: MyStage
  jobs:
  - deployment: deployment1
    displayName: AnyDeploy
    pool:
      vmImage: 'ubuntu-latest'
    environment:
      name: env1
      resourceType: virtualmachine
      tags: tag1
    strategy:
      runOnce:
       deploy:
        steps:
        - task: Bash@3
          displayName: 'Setting output variable'
          inputs:
            targetType: 'inline'
            script: |
              token=Some_Value
              echo "##vso[task.setvariable variable=token;isOutput=true]$token"
              echo $token
          name: setvarStep

  - deployment: deployment2
    dependsOn: deployment1
    pool:
      vmImage: 'ubuntu-latest'
    environment:
      name: env1
      resourceType: virtualmachine
      tags: tag2
    variables:
      myToken: $[ dependencies.deployment1.outputs['deployment1_VM1_Deploy.setvarStep.token'] ]
    strategy:
      runOnce:
       deploy:
        steps:
        - task: Bash@3
          displayName: 'Checking if output variable was passed'
          inputs:
            targetType: 'inline'
            script: |
              echo My docker token = $(myToken)`

**Comment by WilliamAntonRohm** [comment]
@jimjim91 -- thank you for your feedback.


@TingluoHuang -- please look into this issue.  You are welcome to re-assign this issue or return it to me.

**Comment by TingluoHuang** [comment]
@WilliamAntonRohm I am no longer work for Azure DevOps. :)

**Comment by WilliamAntonRohm** [comment]
@TingluoHuang -- Tingluo, thank you for the update.

**Comment by juliakm** [comment]
@jimjim91 I apologize for the delay in responding. I'm finding that `System.JobName` gets set to `Deploy_vmname`. I'll update the docs to make that clearer. 

Here's your YAML with a few changes:
```yaml
stages:
- stage: MyStage
  jobs:
  - deployment: deployment1
    displayName: AnyDeploy
    pool:
      vmImage: 'ubuntu-latest'
    environment:
      name: env1
      resourceType: virtualmachine
      tags: tag1
    strategy:
      runOnce:
       deploy:
        steps:
        - task: Bash@3
          displayName: 'Setting output variable'
          inputs:
            targetType: 'inline'
            script: |
              token=Some_Value
              echo "##vso[task.setvariable variable=token;isOutput=true]$token"
              echo $token # outputs Some_Value
              echo $(System.JobName) # outputs Deploy_vmsfortesting
          name: setvarStep

  - deployment: deployment2
    dependsOn: deployment1
    pool:
      vmImage: 'ubuntu-latest'
    environment:
      name: env1
      resourceType: virtualmachine
      tags: tag2
    variables:
      myToken: $[ dependencies.deployment1.outputs['Deploy_vmsfortesting.setvarStep.token'] ]
    strategy:
      runOnce:
       deploy:
        steps:
        - task: Bash@3
          displayName: 'Checking if output variable was passed'
          inputs:
            targetType: 'inline'
            script: |
              echo My docker token = $(myToken) # outputs My docker token = Some_Value
              echo $(System.JobName) # outputs Deploy_vmsfortesting
```
