### ISSUE TITLE
Combination of Microsoft hosted and self hosted agents

### ISSUE THREAD

**Issue by heing** [MicrosoftDocs/azure-devops-docs#7595]
The example should cover a combination of Microsoft hosted, e.g. Ubuntu 18.04, and self hosted agents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5552e8c4-b0c2-f3ff-c69a-607166afb611
* Version Independent ID: 8e73c13c-9b2b-0eac-45ec-4bd3a8d01bb1
* Content: [Create a multi-platform pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=azure-devops)
* Content Source: [docs/pipelines/get-started-multiplatform.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-multiplatform.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@heing Good idea, I am taking a look.

**Comment by steved0x** [comment]
@heing I'm adding an example to the document right now, basically it looks like this, you specify a blank `vmImage` for the self-hosted agent

```
strategy:
  matrix:
    microsofthosted:
      poolName: Azure Pipelines
      vmImage: ubuntu-latest

    selfhosted:
      poolName: FabrikamPool
      vmImage:

pool:
  name: $(poolName)
  vmImage: $(vmImage)

steps:
- checkout: none
- script: echo test
```
