### ISSUE TITLE
Example needed for installing packages from a feed in another devops organization

### ISSUE THREAD

**Issue by jrummell** [MicrosoftDocs/azure-devops-docs#7621]
How do you configure npm install to use a feed in a different devops organization? I've done the following:

- added a .npmrc file to my project:

```
@scop-name:registry=https://pkgs.dev.azure.com/account/_packaging/project/npm/registry/

always-auth=true
```

- added an npm service connection using a PAT with Packaging read and write scopes ( I tried both the generated PAT and a base64 encoded PAT)
- added a build task:

```
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    customRegistry: useNpmrc
    customEndpoint: 'service connection name'
    verbose: true
```

I get the following error in the build on a local agent:

```
3185 verbose stack Error: Unable to authenticate, need: Basic realm="https://pkgsprodeus21.pkgs.visualstudio.com/", Bearer, TFS-Federated
3185 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:94:17
3185 verbose stack     at runMicrotasks (<anonymous>)
3185 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
3186 verbose statusCode 401
3187 verbose pkgid @scope-name/package@^1.0.21
3188 verbose cwd E:\VSTS\agent\_work\12\s\project\app
3189 verbose Windows_NT 10.0.17134
3190 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3191 verbose node v12.14.1
3192 verbose npm  v6.13.4
3193 error code E401
3194 error Unable to authenticate, your authentication token seems to be invalid.
3195 error To correct this please trying logging in again with:
3195 error     npm login
3196 verbose exit [ 1, true ]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c00d3b8-64c1-9f1b-83f8-62d8cf07817b
* Version Independent ID: 5fcdebed-cfb8-c5a6-d807-1315b2db5e57
* Content: [npm task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/npm.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@jrummell -- John, thank you for your question.  You may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

@vijayma -- Vijay, please look into this issue.

**Comment by ox4** [comment]
@WilliamAntonRohm , @vijayma I was wondering whether there are any updates on this issue? I took the same steps @jrummell mentioned and got exactly the same result. 
Unfortunately I had no luck finding anything related on StackOverflow.

**Comment by afi-itree** [comment]
Exactly the same behaviour for me... Double checked the PAT, also tried to base64 encode the PAT with no success. I also use scoped registry, like @jrummell.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by dinesh-chander** [comment]
I have a similar setup and facing this issue. Is there any example that we can look into?

**Comment by dinesh-chander** [comment]
Yeah, I have posted it on the dev community also. Here's the link https://developercommunity.visualstudio.com/t/npm-service-connection-doesnt-work-with/1520661

**Comment by robmaas** [comment]
I've been struggling with this as well. The documentation isn't clear and the provided examples are not working.
After a while I found another (unexplained, undocumented) snippet in a unrelated example that seems to fix the issue. It is about setting the `NPM_CONFIG_USERCONFIG` to the correct `.npmrc` after setting up the npm authentication.

The configuration is **very fragile**, these are some of the issues that I found:
- The PAT should have **Package Read** Permissions in the correct organization scope.
- Make sure your registry URL located in your `.npmrc` matches with the URL in your Service Connection (it differs between Project-scoped and Organization-scoped feeds). Also take into account the old/new URL's of the DevOps organizations and make sure you use the same URL in both locations.
- Set the pipeline `NPM_CONFIG_USERCONFIG` after running the npm authentication (see script below).
- Do NOT use the `NPM@1` task to install packages, it just doesn't work. Use `script: npm ci` instead, otherwise the npm authentication is not respected/applied. That is probably a bug in the `Npm@1` task.

A complete working yaml flow looks like this:
```
- task: NodeTool@0
  displayName: Use Node.js $(nodeVersion)
  inputs:
      versionSpec: $(nodeVersion)

- task: npmAuthenticate@0
  displayName: NPM auth
  inputs:
      workingFile: '$(someVariableWorkingDir)/.npmrc'
      customEndpoint: 'serviceconnectionname'
    
- script: echo ##vso[task.setvariable variable=NPM_CONFIG_USERCONFIG]$(someVariableWorkingDir)/.npmrc
  displayName: NPM set user config
      
- script: npm ci
  displayName: NPM ci
  workingDirectory: '$(someVariableWorkingDir)'
      
#- task: Gulp@1 / NPM / 
# Your build script/runner
```
