### ISSUE TITLE
Add example for publishfeedcredentials

### ISSUE THREAD

**Issue by robertlarkins** [MicrosoftDocs/azure-devops-docs#7628]
Can an example be added for publishfeedcredentials that shows what the NuGet service connection containing credentials should look like? It would be good to know what this structure looks like for publishing to a private non-Azure Artifacts server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by babelshift** [comment]
Here's an example that I figured out from: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-nuget

You first need to set up a NuGet Service Connection in your Project settings. Then reference the name of that Service Connection in the publishFeedCredentials line.

```
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'
```
