### ISSUE TITLE
Documentation mismatch for single jobs and templates

### ISSUE THREAD

**Issue by gthvidsten** [MicrosoftDocs/azure-devops-docs#7783]
At the top the documentation says:

> In the simplest case, a pipeline has a single job. In that case, you do not have to explicitly use the job keyword. You can directly specify the steps in your YAML file.

This is not completely true, because if you are using a template (using the `extends` keyword) that only has a single job this template *must* have a stage and a job.

If you do the following in a template:

```
parameters:
  - name: someParameter
    default: ''
    type: string

pool:
  name: Hosted Ubuntu 1604

steps:
- task: SomeTask@1
- task: OtherTask@2
- task: DifferentTask@3
```

You will get the following message:
> your-template.yml (Line: 6, Col: 1): Unexpected value 'pool'

So maybe the documentation should specify that this is only valid for standalone pipelines, not for pipelines that includes templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
