### ISSUE TITLE
Trigger fails when pipeline name contains whitespace

### ISSUE THREAD

**Issue by seanjmalone** [MicrosoftDocs/azure-devops-docs#7787]
Both the pipeline name input and the YAML editor allow whitespace, but our pipeline trigger was failing because our value for 'source:' had a space in it. As far as I can tell this isn't documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**

**Comment by WilliamAntonRohm** [comment]
@seanjmalone -- Sean, thank you for your feedback.

@ashokirla -- Ashok, please review [private PR 1188](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1188).

**Comment by ashokirla** [comment]
Thanks for the feedback. We will investigate the issue on priority.

**Comment by ashokirla** [comment]
@seanjmalone I am not able to reproduce this issue. Can you share the YAML snippet with resource triggers. And do you have any other resources added in YAML. Also, can you try enclosing the CI pipeline with spaces in quotes and try it.

**Comment by seanjmalone** [comment]
@ashokirla we no longer have pipeline names with whitespace and our pipeline triggers are running fine, although I believe at the time we had two, with `resources` sections like:
```yaml
resources:
  pipelines:
  - pipeline: PortalServicesPipeline
    source: Portal.Services
    trigger: 
      branches:
        include:
          - master
```
And:
```yaml
resources:
  pipelines:
  - pipeline: PortalServicesPipeline
    source: Portal Services
    trigger: 
      branches:
        include:
          - master
```
I was seeing the one with a space not triggering, although it had also been recently created. Could it be possible that there is sometimes a delay between the YAML file being updated to add the trigger, and the trigger becoming active when the pipelines are run? That could also explain what I was seeing. Having a similarly named pipeline with a dot instead of a space, that triggered on the first build after it was added, could have led me to believe the whitespace was to blame.

**Comment by kasubram** [comment]
I couldn't reproduce it either. There is a background job which picks up the trigger filter detail and store them for later reference but its generally runs instant. There shouldn't be any delay. If you have your yaml file in github or any other repo other than TfsGit may be we never received the event that there is a change in the yaml which has trigger enabled.

Please let us know in which repository your yaml file resides in? If this is the case, if you make another edit to the yaml file, if you simply add a comment it will generate a commit event and notify the background job on the azuredevops side to process the trigger detail.

This yaml just works fine for me.
```
trigger: none
resources:
  pipelines:
  - pipeline: PortalServicesPipeline
    source: Portal Services
    trigger: 
      branches:
        include:
          - master
jobs:
- job: Job1
  pool: default

  steps:
    - checkout: none
    - download: PortalServicesPipeline
````
