### ISSUE TITLE
Is it possible to pass a variable as a parameter to the template

### ISSUE THREAD

**Issue by AnujSehgall** [MicrosoftDocs/azure-devops-docs#7901]
I'm trying to pass a variable from one task as a parameter to a template which is being called at the next task and using it in a condition in the template. Condition is failing due to empty value of the parameter.

Here is an example

azure-pipeline.yaml

````
variables:
  - name: experimentalTemplate
    value: true
jobs:
  - template: build-template.yaml
    parameters:
      templateState: $experimentalTemplate
````

build-template.yaml

```
parameters:
- name: templateState
  type: boolean
  default: false
jobs:
  - job: TemplateDecision
    steps:
      - ${{ if eq(parameters.templateState, true) }}:
        <do-something>
      - ${{ if eq(parameters.templateState, false) }}:
        <do-soemthing>
```

In the above template, the flow ignores this condition and move forward with further tasks.
Maybe because "parameters.templateState" is empty at the run-time. Is there any solution for this?
