### ISSUE TITLE
Pipeline resource syntax for Azure DevOps Server 2019?

### ISSUE THREAD

**Issue by tbergstedt** [MicrosoftDocs/azure-devops-docs#7922]
I am trying to set up a pipeline resoure in our on-premises Azure DevOps Server 2019 installation. I'm fillowing the documentation at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops-2019&tabs=yaml. Basically copying the example, I try:
```
resources:
  pipelines:
  - pipeline: rs_artifacts
    source: RS-Artifacts
    trigger: 
      branches:
        include: 
        - master
```
As you can see, it is nearly identical to the example given in documentation. Yet when I try to trigger a build for a pipeline containing this, I receive syntax error:
`/buildtools/definitions/buitlds/test/int-test.yml (Line: 7, Col: 5): Unexpected value 'trigger'`

It is as if the keyword `'trigger'` doesn't work here? Just to make sure, I have tried pasting the resource example from documentation above directly into my pipeline definition, and even then the syntax check reacts on the `'trigger'` statement.

We are using version 17.153.29207.5 (AzureDevOps2019.Update1).
