### ISSUE TITLE
Kubernetes annotation in deployment not valid

### ISSUE THREAD

**Issue by magandrez** [MicrosoftDocs/azure-devops-docs#7926]
On the deployment manifest linked above [1] there is a Kubernetes annotation for API version not valid with latest supported AKS version.

`apiVersion: apps/v1beta1` 

This needs to be corrected to `apiVersion: apps/v1` for the pipeline to be successful.
[1] https://github.com/Microsoft/azure-pipelines-yaml/blob/master/templates/resources/k8s/deployment.yml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbceb1f5-05c3-487d-6e21-dc1b4936a55c
* Version Independent ID: 35355737-9ad9-9df5-b612-806d9df2462b
* Content: [Deploy to Azure Kubernetes Service - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/kubernetes/aks-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/kubernetes/aks-template.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by WilliamAntonRohm** [comment]
@azooinmyluggage -- Atul, please review [PR 486](https://github.com/microsoft/azure-pipelines-yaml/pull/486).

**Comment by deeproute** [comment]
Also there is a missing selector on the deployment. The correct yaml should be this:
**apiVersion : apps/v1**
kind: Deployment
metadata:
  name: deeproutepipelinesjavascriptdocker 
spec:
  replicas: 1
  **selector:
    matchLabels:
      app: deeproutepipelinesjavascriptdocker**
  template:
    metadata:
      labels:
        app: deeproutepipelinesjavascriptdocker 
    spec:
      containers:
        - name: deeproutepipelinesjavascriptdocker 
          image: acraksdevops.azurecr.io/deeproutepipelinesjavascriptdocker
          ports:
          - containerPort: 8080

**Comment by eduardopvilca** [comment]
I try to use this api version of k8s but the tag of my deployment image doesn't catch the parameter of container input.

```
- task: KubernetesManifest@0
   displayName: Deploy to Kubernetes cluster
   inputs:
      action: deploy
      kubernetesServiceConnection: $(aksServiceConnectionDev)
      namespace: $(aksNamespace)
      manifests: $(Pipeline.Workspace)/manifests/deployment.yml
       containers: acreuc00201.azurecr.io/miles:1.0.0
```
```
apiVersion: apps/v1 ##change
kind: Deployment
metadata:
  name: miles-deployment
  labels:
    component: miles
spec:
  replicas: 1
  ##add
  selector:
    matchLabels:
      component: miles
  ##end
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: miles
    spec:
      containers:
        - name: miles
          image: acreuc00201.azurecr.io/miles
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "768Mi"
```
