### ISSUE TITLE
Accessing output variables within Deployment Jobs from earlier lifecycle hooks

### ISSUE THREAD

**Issue by akokskis** [MicrosoftDocs/azure-devops-docs#7933]
As mentioned in #7294 (which refers to the documentation on the deployment jobs page), the documentation regarding output variables being accessed within deployment jobs from previous lifecycle hooks is totally lacking.

It would be good to understand the details and syntax of how to access these variables. 

```
strategy:
  runOnce:
    preDeploy:
      steps:
      - bash: |
          echo "##vso[task.setvariable variable=myLocalVar;isOutput=false]local variable"
        name: setvarStep
      - bash: |
          echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]output variable"
        name: outvarStep
      - bash: |
          echo 'Both $(myLocalVar) and $(outvarStep.myOutputVar) are available here'
    deploy:
      steps:
      - bash: |
          echo 'Neither $(myLocalVar) nor $(outvarStep.myOutputVar) are available here'
```
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
