### ISSUE TITLE
Conditions do not cast parameters to Boolean while evaluating

### ISSUE THREAD

**Issue by ferrata** [MicrosoftDocs/azure-devops-docs#7953]
When pipeline definition has the following YAML:

```yaml
variables:
  isSourceBranchMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isSourceBranchDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  publishArtifacts: $[ or( variables.isSourceBranchMaster, variables.isSourceBranchDevelop ) ]
```

Variable `publishArtifacts` is not evaluated according to this documentation. Here is the output:

```
  isSourceBranchMaster:
    Parsing expression: &lt;eq(variables['Build.SourceBranch'], 'refs/heads/master')&gt;
    Evaluating: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    Expanded: eq('refs/heads/feature/update-file', 'refs/heads/master')
    Result: 'False'
  isSourceBranchDevelop:
    Parsing expression: &lt;eq(variables['Build.SourceBranch'], 'refs/heads/develop')&gt;
    Evaluating: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
    Expanded: eq('refs/heads/feature/update-file', 'refs/heads/develop')
    Result: 'False'
  publishArtifacts:
    Parsing expression: &lt;or( variables.isSourceBranchMaster, variables.isSourceBranchDevelop )&gt;
    Evaluating: or(variables['isSourceBranchMaster'], variables['isSourceBranchDevelop'])
    Expanded: or('False', variables['isSourceBranchDevelop'])
    Result: 'True'
```

`publishArtifacts` variable evaluation result should be `'False'`
I am using Azure DevOps Server Version 17.143.28912.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by ferrata** [comment]
Potential workaround is to define the variable as following:

```
publishArtifacts: $[ or( eq(variables.isSourceBranchMaster, true), eq(variables.isSourceBranchDevelop, true) ) ]
```

But documentation then should be updated to do not confuse developers.

**Comment by drdamour** [comment]
does that workaround work? i'd expect it to have to be eq(xx, 'True')

**Comment by ferrata** [comment]
> does that workaround work? i'd expect it to have to be eq(xx, 'True')

Using just `true` (vs `'True'`) works. Probably because it is a valid [literal](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#literals).

**Comment by drdamour** [comment]
@ferrata id be careful since “False” evaluates to true since its non empty string

**Comment by ferrata** [comment]
@drdamour, 

> id be careful since “False” evaluates to true since its non empty string

Yes, you are correct. It breaks if first argument is of a `boolean` type. According to the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#eq) `eq` converts second argument to match type of the first one. It works in my case above because it seems like variables always resolve to `string`, even if expression should return `boolean`.

Did some more digging. Here is what I understand happens:

```yaml
variables:
  compareTrueToBoolean: $[eq(true, false)] # 'False', both arguments have same type (boolean)
  compareTrueToString: $[eq(true, 'false')] # 'True', second argument is treated as boolean True because it is non-empty string

  evaluatedTrue: $[eq('a', 'a')]
  compareEvaluatedTrueToBoolean: $[eq(variables.evaluatedTrue, false)] # 'False', second (boolean) argument gets converted to string
  compareEvaluatedTrueToString: $[eq(variables.evaluatedTrue, 'false')] # 'False', both arguments have same type (string)
```
