### ISSUE TITLE
Creating/Updating ConfigMap from file

### ISSUE THREAD

**Issue by dannyyy** [MicrosoftDocs/azure-devops-docs#7957]
The description of the ConfigMap parameters are not clear nor the goal it should achieve.
I intented to use the `useConfigMapFile` and `ConfigMapFile` to update a given ConfigMap with each deployment. The content of the ConfigMap origins from a folder or file of the current Git checkout (That's what is selectible also in the GUI for non YAML builds).
The output of this task is always 'success' no matter what kind of crap I configure for the task inputs. Even with proper configuration nothnig happen despice getting 'success'. Highly unsuable or totally wrong explained in the docs. 

What I use:
```
            - task: Kubernetes@1
              displayName: 'Create ConfigMap for /data'
              inputs:
                kubernetesServiceEndpoint: 'cluster-test'
                namespace: 'mynamespace-test'
                forceUpdateConfigMap: true
                useConfigMapFile: true
                configMapFile: $(Build.SourcesDirectory)/data/FirewallRuleRequest_ExcelTemplate.xlsx
```
What I expect is, that with each deployment the key `FirewallRuleRequest_ExcelTemplate.xlsx` will be replaced by the content the respective file. Actually it's a delete and create command as explained for the `forceUpdateConfigMap` argument.

So is there a technical issue or a documentation issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Kubectl task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**
