### ISSUE TITLE
System Variables do not seem to be available in the template condition despite what this documentation page claims

### ISSUE THREAD

**Issue by ferrata** [MicrosoftDocs/azure-devops-docs#7980]
Hey,

This [page](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#context) claims that:

> Template expressions
> ...
> Additionally, you have access to the variables context that contains all the variables specified in the YAML file plus the [system variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables).

I have a hard time trying to make it work. Consider the following pipeline definition. It uses template expression where it checks a value from `System.PullRequest.PullRequestId` system variable:

```yaml
variables:
  systemVariableCondition: $[lt(0, variables['System.PullRequest.PullRequestId'])]
  ${{ if lt(0, variables['System.PullRequest.PullRequestId']) }}:
    dependentVariable: "some value"
  
phases:
- phase: Build
  displayName: Build
  steps:
  - powershell: |  
      Write-Host "dependentVariable: $(dependentVariable)"
```

Run-time variable `systemVariableCondition` is in this definition just to confirm that system variable in question has expected value.

Here is the output from the "Prepare job" step, please note that expected variable `dependentVariable` was *not* introduced:

```
##[section]Starting: Prepare job Build
Variables:
  systemVariableCondition:
    Parsing expression: &lt;lt(0, variables['System.PullRequest.PullRequestId'])&gt;
    Evaluating: lt(0, variables['System.PullRequest.PullRequestId'])
    Expanded: lt(0, '335')
    Result: 'True'
ContinueOnError: False
TimeoutInMinutes: 60
CancelTimeoutInMinutes: 5
Execution:
##[section]Finishing: Prepare job Build
```

So the step fails:

```
+ Write-Host "dependentVariable: $(dependentVariable)"
+                                  ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dependentVariable:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
 
##[error]PowerShell exited with code '1'.
```

Please elaborate what exactly this page means by stating that one has access to system variables in a template expression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@ferrata -- Alexander, thank you for your feedback.  Please look here as well:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @juliakm for awareness

**Comment by ferrata** [comment]
@WilliamAntonRohm,

Hey, can you please explain why you have closed the issue and what is the answer to my question?

Thanks

**Comment by WilliamAntonRohm** [comment]
@ferrata -- Alexander, I may have misunderstood your initial request.

@juliakm -- Julia, please look into this issue.

**Comment by szymon3** [comment]
I have the same issue.

**Comment by MarioAllegro** [comment]
Hi @ferrata,

I think you faced the same problem as me currently. Could it be that you are currently not on an pull request build but an automated CI build?
It seems, that if your are not on a PR you do not have access to the variable in this context and you will get the aforementioned error. Just add a condition as shown below to make sure you are on a PR:
`- job: Database
condition: eq(variables['Build.Reason'], 'PullRequest')`

**Comment by abelal83** [comment]
System variables do not seem to expand. I have this issue

```yml
parameters:
  CheckoutDirectory: $(System.DefaultWorkingDirectory)

  - ${{ if eq(parameters.Type, 'terraform') }}:
    - template: ${{ parameters.CheckoutDirectory}}/builds/${{ parameters.Type }}/build.yml
```

it error complaining it's unable to find /$(System.DefaultWorkingDirectory/builds/terraform/build.yml

This si extremely frustrating, I've tried so many hacks to get this to work but it appears if any system variables are used it will not expand but anything else is fine.
