### ISSUE TITLE
This document is no longer the "comprehensive list of system variables" it is said to be in other areas of documentation

### ISSUE THREAD

**Issue by JGCreator** [MicrosoftDocs/azure-devops-docs#8014]
In reviewing the documentation for Define Variables &gt; System Variables section, this page is linked to directly and is said to be a "comprehensive list of system variables", yet later in the Define Variables &gt; Set Variables Using Expressions section of that same document there is a reference to a variable `pipeline.startTime` in an example for creating a counter that resets daily. This document has no definition for the `pipeline.startTime` variable although it is a valid variable and can be used in pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@JGCreator Variables that start with `pipelines` are a special class that only work in expressions. I'll add more context to the example on the expressions page for this. 

To see this in action, you can try this pipeline. The values for `$(a)` and `$(b)` render but `$(b)` does not. 

```yaml
jobs:
- job:
  variables:
    a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
    b: $[pipeline.startTime]
    c: $(pipeline.startTime)

  steps:
  - bash: echo $(a) #outputs 102
  - bash: echo $(b) #outputs 2020-05-11 16:36:13-05:00
  - script: echo $(c) #outputs echo $(pipeline.startTime)
```
