### ISSUE TITLE
Usage of expressions in build number format

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/azure-devops-docs#8034]
Hi, I'd like my build number format to change depending on the `[build.reason](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables)`.

For example for GitHub PR triggers I can use:
```
$(System.PullRequest.PullRequestNumber)$(Rev:.r)
```

But if the build reason is anything other than pull request then I get a malformed build number.

Ideally I'd like to use an expression or some way to set a variable depending on the build reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by StephenHodgson** [comment]
Right, I'm saying the documentation is lacking about how to specify a build number format using an expression

**Comment by StephenHodgson** [comment]
Figured it out:

```
name: ${{ coalesce( variables['System.PullRequest.PullRequestNumber'], '$(Build.SourceBranchName)', '$(Date:yyyyMMdd)') }}$(Rev:.r)
```

**Comment by StephenHodgson** [comment]
Opened https://github.com/MicrosoftDocs/azure-devops-docs/pull/8058 to properly document usage of expressions in docs

**Comment by WilliamAntonRohm** [comment]
@StephenHodgson -- Stephen, thank you for your contribution.

@dracorp -- Piotr, thank you for your followup.

@juliakm -- Julia, please look into this potential documentation issue.

**Comment by juliakm** [comment]
@StephenHodgson Here's a sample pipeline that uses an if/elseif/else condition to set the build number. I'll update the docs with a similar example tomorrow. We also have a more in-depth article on using conditions in the works. 

```yaml
variables:
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    why: pr
  ${{ elseif eq(variables['Build.Reason'], 'Manual' ) }}:
    why: manual
  ${{ elseif eq(variables['Build.Reason'], 'IndividualCI' ) }}:
    why: indivci 
  ${{ else }}:
    why: other

name: $(TeamProject)_$(SourceBranchName)_$(why)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(why)
- script: echo $(Build.Reason)
- script: echo '$(Build.BuildNumber)'
```
