### ISSUE TITLE
multi-job output variable named Foo.Bar

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#8081]
It is explained in this section how to grab a variable output from one job, in another job: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable

However the variable name is simply "myOutputVar" in your example, and you access it like this:
```
myVarFromJobA: $[ dependencies.A.outputs['setvarStep.myOutputVar'] ]
```

However in my case, the variable I need to access is set by an executable and it's named "GitVersion.SemVer".

How do I access that using this syntax? I tried this, but the extra "." in the property name doesn't seem to work:

myVarFromJobA: $[ dependencies.A.outputs['setvarStep.GitVersion.SemVer'] ]

I have tried to guess other ways and they all failed:

myVarFromJobA: $[ dependencies.A.outputs['setvarStep.variables['GitVersion.SemVer']]' ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@dazinator Thank you for the question, assigning this to the author for further review.

In the meantime, please refer to the following:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by dazinator** [comment]
Think this issue is still present..?

**Comment by mijacobs** [comment]
@dazinator : For a faster answer to you question, check these resources:
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm Can you take a look?

**Comment by vtbassmatt** [comment]
I had no issues including a period in the variable name.

```yaml
jobs:
  # Set an output variable from job A
  - job: A
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - script: echo "##vso[task.setvariable variable=myOutput.Var;isOutput=true]this is the value"
      name: setvarStep
    - script: echo $(setvarStep.myOutput.Var)
      name: echovar
  
  # Map the variable into job B
  - job: B
    dependsOn: A
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      myVarFromJobA: $[ dependencies.A.outputs['setvarStep.myOutput.Var'] ]  # map in the variable
                                                                            # remember, expressions require single quotes
    steps:
    - script: echo $(myVarFromJobA)
      name: echovar
```
