### ISSUE TITLE
Can parameters be set based on variables?

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#8101]
For example some of my jobs are only relevent for PR's. At the moment I use variables and a condition on the Job that enables the job based on that variable.
However the job still shows up in the UI even when it is skipped.
With Runtime parameters - If I could set a parameter called "IsPR" based on the variables available, then I could use:

- ${{ if eq(parameters.IsPr, true) }}:

To only include jobs for PR.

In order to do this kind of thing I need to know whether I can set parameters to values based on the build variables - rather than a user having to supply them through the UI when running the pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by akempe** [comment]
I've been tearing my hair out with this exact problem for a few days now. The bad news is that I don't think it's possible because parameters get expanded into their values and validated at compile time - when variables are not "fully" available. I say "fully", because it appears that the location where the variable is defined *may* influence its availability for *some* usage at compile time. Again, *may* and *some* are used here because the docs on this are so thin, convoluted, spread out, and when they do exist you have to read between the lines.  If anything helps, after all my experimentation I gave up and just used variables.

**Comment by cubikca** [comment]
Yes, you can try something like:

```yaml
steps:
  - template: job.yml
  - parameters:
      IsPr: $(IsPr)
```

This will template the steps within job.yml setting the IsPr parameter to the value of the build variable IsPr.

**Comment by akempe** [comment]
@cubikca please can you provide a full example showing your variable declarations and assignment as this doesn’t work for me.

**Comment by cubikca** [comment]
Yes it seems you are correct. I was thinking of a multi-stage deployment where the stages were selected:

```yaml
stages:
  - template: 'deploy-stage.yml'
    parameters:
      environment: 'QA1'
  - template: 'deploy-stage.yml'
    parameters:
      environment: 'QA2'
  - template: 'deploy-stage.yml'
    parameters:
      environment: 'QA3'
  - template: 'deploy-stage.yml'
    parameters:
      environment: 'UAT1'
  - template: 'deploy-stage.yml'
    parameters:
      environment: 'Production'
```

And then in deploy-stage.yml:

```yaml
stages:
  - stage: ${{ parameters.environment }}
    jobs:
      - deployment: deployment1
        environment: ${{ parameters.environment }}
        condition: eq(parameters.environment, 'SomeValue')
        variables:
          - ${{ if startswith(parameters.environment, 'UAT') }}:
            - template: deploy-vars-UAT.yml
          - ${{ if and(not(startswith(parameters.environment, 'UAT')), ne(parameters.environment, 'Production')) }}:
            - template: deploy-vars-Test.yml
           - ${{ if eq(parameters.environment, 'Production') }}:
             - template: deploy-vars-Production.yml
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy-job1.yml
                  parameters:
                    environment: ${{ parameters.environment }}
```

This general idea seems to be very flexible. But you are right that the syntax provided does not work because the templating engine runs before build variable replacement. I believe the syntax `${{ variables.IsPr }}` might work here because the variable should be *defined* before the templating engine runs. That's not abundantly clear from the documentation however. What you are asking is probably common enough, and an example of how to achieve it would save a lot of grief.

**Comment by akempe** [comment]
> Overall I agree with you, and I personally tore my hair out trying to achieve this multi-stage build.

This is why I cry... it is exactly what pipelines should be making easy!

>The key is understanding the timing of templating versus execution, and when a variable is "in scope". This will probably take some pain and experimentation.

And this is **exactly** where there is a total lack of clarity and consistency across all the docs. Each doc references a slightly different variable syntax and never includes details about how the variable was declared/set - which from experimentation **is critical**. There isn't clear documentation of scope. What worries me most, is I've seen multiple GitHub issues where MS employees have to backtrack on themselves when their initial suggestion to a problem doesn't work. Not even they have a clear view of this.

**Comment by pdesantis** [comment]
Were you able to get it to work? I'm trying to set a parameter based off a variable like so:

variables:
  - name: needsManualApproval
     value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

(then later in one of my jobs):
- template: deploy.yml
  parameters: 
    deploy: ${{ eq(variables.needsManualApproval, false) }}

**Comment by akempe** [comment]
@pdesantis nope, and I’m pretty sure it’s impossible with the current parameter functionality offered by pipelines. I gave up using parameters entirely in favour of variables. Unless someone from MS provides a concrete working example, I wouldn’t waste more time on this.

**Comment by cubikca** [comment]
I did eventually get a working pipeline based off the new YAML, but it was so aggravating and unclear that I am really hoping "Classic" pipelines and releases don't go away any time soon.

**Comment by vtbassmatt** [comment]
Parameters are expanded really early in processing. We give an overview in the [Runs](https://docs.microsoft.com/azure/devops/pipelines/process/runs) topic. In general many variables are not available, but happily for your scenario, one is! You can do this:

```yaml
steps:
- script: echo I run always
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - script: I run only if Build.Reason == PullRequest
- script: echo I again run always
```

The variables which are available in templates are documented in the table of [predefined variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables#build-variables-devops-services). You sometimes have to scroll the table over to see that column.

Yes, unfortunately, we have too many ways to use variables 😞 This is the cost of trying to maintain backwards compatibility _and_ continue making forward progress. There's a reasonable introduction to the various syntaxes, and when you'd use them, in [this section](https://docs.microsoft.com/azure/devops/pipelines/process/variables#understand-variable-syntax). IF you have suggestions on making that clearer, please open a new issue (seriously, we would love the feedback).

Classic RM and classic build aren't going anywhere, they simply aren't receiving any new features.

@juliakm I'm marking this one "ready for doc" because perhaps we could give some kind of scenario-based example as I did above.
