### ISSUE TITLE
Should I use resources in the defined template?

### ISSUE THREAD

**Issue by BuddyJoker** [MicrosoftDocs/azure-devops-docs#8118]
I've seen the official docs about [template](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#use-other-repositories)
And I wanna define a template like this:

**build-test.yml**
```yaml
resources:
  repositories:
    - repository: templates
      type: git
      name: org/template

jobs:
  - template: dir/build.yml@templates
```
then the **pipeline-build.yml** is:
```yaml
trigger:
- master

jobs:
  - template: build-test.yml
```
but it does not work when i run this pipeline,the error is:

> /pipelines/build-test.yml (Line: 1, Col: 1): Unexpected value 'resources'

so how can i create a template include resources or have another way to solve this problem?
