### ISSUE TITLE
Checkout path clarify

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8136]
As we see in doc:

> Multiple repositories: Your source code is checked out into directories named after the repositories as a subfolder of s in (Agent.BuildDirectory). If (Agent.BuildDirectory) is C:\agent\_work\1 and your repositories are named tools and code, your code is checked out to C:\agent\_work\1\s\tools and C:\agent\_work\1\s\code.

This mean 'name' property of repository?

```
resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps - this one?
      ref: yaml

```
 or repository name itselft?

```
resources:
  repositories:
    - repository: templates - this one?
      type: git
      name: DevOps
      ref: yaml
```

So after next step:

```
- checkout: templates
  name: CheckoutDevOps
  displayName: 'Checkout DevOps repo'
```

I would use it like this: 

```
- task: PowerShell@2
  displayName: 'Deploy something'
  inputs:
    targetType: 'filePath'
    filePath: 'DevOps\BuildTemplates\DoStuff.ps1' - here DevOps
    workingDirectory: '$(Build.SourcesDirectory)'
```

or this?

```
- task: PowerShell@2
  displayName: 'Deploy something'
  inputs:
    targetType: 'filePath'
    filePath: 'templates\BuildTemplates\DoStuff.ps1' - here templates
    workingDirectory: '$(Build.SourcesDirectory)'
```

PS: Actually I tried both and it doesn't work both:

```
##[debug]Microsoft.PowerShell.Commands.WriteErrorException: Invalid file path 'C:\DeployAgent\_work\10\s\DevOps\BuildTemplates\DoStuff.ps1'. A path to a .ps1 file is required.
##[error]Invalid file path 'C:\DeployAgent\_work\10\s\DevOps\BuildTemplates\DoStuff.ps1'. A path to a .ps1 file is required.
##[debug]Processed: ##vso[task.logissue type=error]Invalid file path 'C:\DeployAgent\_work\10\s\DevOps\BuildTemplates\DoStuff.ps1'. A path to a .ps1 file is required.

```

Checkout debug log does not tell where it checked out. Every time I using yaml I think 'what the hell is going on?'. I forced to spent on DevOps actions more time than I would spent for doing same thing manually. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#repository-declared-using-inline-syntax)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
