### ISSUE TITLE
Need Azure DevOps Pipeline expression function to access a numbered item in an array

### ISSUE THREAD

**Issue by couven92** [MicrosoftDocs/azure-devops-docs#8171]
If you have an array-typed object in a template expression (e.g. passed by parameters), you can only iterate over that array with today's syntax. There is no way to access a specific (i.e. indexed) item from that array.

Consider the following example, where a template is invoked with a defaults object that contains a list of default object specifications coming from different sources. By using a filtered-array expression it is easy to access the `item` property of each array-element. But there is no way to access, the first or last item (which would be very useful in this scenario).

I propose to add three new function expressions:

* `item(index, array)`
   Returns the element in `array` that is located at position `index` (0-based), or returns `null` if the index was out of bounds. `array` can be a filtered-array expression, or a YAML sequence object obtained from a parameter or variable in the current context.
   If `array` is a string, the `item` returns the character located at `index`.
   If `array` is neither an array, nor a string, then coerce the value into a string following normal type-casting rules.
* `first` works like `item` with the `index` parameter set to `0` to obatin the first item.
* `last` works like `item` with the `index` parameter set to the length of `array` minus 1, to get the last item in the sequence.

```yml
parameters:
- name: defaults
  type: object
  default:
    - item: default1
    - item: default2
    - item: default3
steps:
- pwsh: 'Write-Host ${{ item(1, parameters.defaults.*.item) }}'
  # Writes: default2
- pwsh: 'Write-Host ${{ first(parameters.defaults.*.item) }}'
  # Writes default1
- pwsh: 'Write-Host ${{ last(parameters.defaults.*.item) }}'
  # Writes default3
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
