### ISSUE TITLE
How to auto trigger pipeline B

### ISSUE THREAD

**Issue by kenakamu** [MicrosoftDocs/azure-devops-docs#8177]
The document says "To prevent triggering two runs of B in this example, you must remove its CI trigger or pipeline trigger." However, if I remove pipeline trigger, then B won't be triggered at all. How can I trigger B only after A compiled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**

**Comment by kenakamu** [comment]
Actually, if I remove pipeline trigger, it uses implicit trigger so it's triggered once which is even worse.

**Comment by msebolt** [comment]
@kenakamu  Thank you for the question.

Assigning this to the author for further review to see if the documentation requires an update.

If this is product-related and is not yet currently feasible, please refer to **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback from the product team.

Or, for additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
@thomps23 Temporarily assigned.

@ashkir  Doesn't appear as a valid alias.

**Comment by billybraga** [comment]
@kenakamu Try `trigger: none` in your pipeline yaml

**Comment by kenakamu** [comment]
Thanks @billybraga. Is there anyway to trigger only previous pipeline completed?

**Comment by billybraga** [comment]
@kenakamu Yes. Edit pipline > Menu > Triggers > Build completion > + Add > Choose build

**Comment by mohammednaseem** [comment]
@billybraga 
is there a way to trigger a "Release" pipeline based on previous pipeline completed?
what is you said above is about tying about build pipelines together or sequencing them right?

**Comment by kenakamu** [comment]
In addition to what @mohammednaseem mentioned, is there any way to define the trigger in yaml rather than using GUI of ADO which may stay in projects?

**Comment by the-mod** [comment]
Tried `trigger:none` in my CD Pipeline and import the CI Pipeline via resources, but CD Pipeline gets not triggered after CI Build was successfull

**Comment by the-mod** [comment]
`trigger: none` works now for me

**Comment by XREvo** [comment]
@the-mod Can you show us a sample of you yaml file? I've set up `trigger: none` and a CI Pipeline via resources, but it still don't work.

**Comment by the-mod** [comment]
Hi @XREvo,

this is working for me.
Maybe you have an Issue with the Name of the referenced Pipeline.
It should be the same Name as the pipeline is stored at Azure.

`trigger: none

resources:
  pipelines:
  - pipeline: 'service-build-pipeline'
    source: 'service-build'
    trigger: 
     branches:
      include: 
        - master`

**Comment by XREvo** [comment]
Thanks @the-mod for your response and for the sample.  

Does the pipeline triggers only works on `master` ?

I'll explain myself :
- I created a `ci.yml` file on `master` (you'll find it at the end of my comment).
- Then i registered it as a pipeline named `ci` on Azure DevOps.
- Then i created a branch `setup/cd` from `master`. 
- I create a `cd.yml` file on `setup/cd` (you'll find it at the end of my comment).
- At commit, `ci` pipeline start automatically 🎉.
- Then i registered a pipeline named `cd` on Azure DevOps, from the `cd.yml` file.
- Finally, i updated the `README.md`
- At commit, `ci` pipeline start automatically 🎉.
- At the end of `ci` pipeline nothing happens 😐.
- I created a PR to merge `setup/cd` into `master`.
- At merge completion, `ci` pipeline start automatically 🎉.
- At the end of `ci` pipeline, `cd` pipeline start automatically 🤔.

That's why i'm asking if pipeline triggers only works on `master` ?

Here is my `ci.yml` file, register as `ci` pipeline into AzDO :
```
pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - master
      - setup/*

steps:
  - task: CopyFiles@2
    displayName: Copying
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      cleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    displayName: Publishing
    inputs:
      artifactName: 'app'
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
```


Here is my `ci.yml` file, register as `ci` pipeline into AzDO :
```
pool:
  vmImage: 'ubuntu-latest'

trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: ci
      trigger:
        branches:
          - master
          - setup/*

steps:
  - download: ci
    artifact: app
```
