### ISSUE TITLE
VMs matching tags: "any" or "all" ?

### ISSUE THREAD

**Issue by JoeGaggler** [MicrosoftDocs/azure-devops-docs#8202]
Please update the "Reference VM resources in pipelines" section to indicate whether the VM resource must match ALL of the tags or ANY of tags. The linked reference document (YAML Schema) does not even define "tags" as an option for "environment".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by juliakm** [comment]
@JoeGaggler It will match when ALL tags are met. You can use a comma-separated syntax. Here's an example pipeline. I'll update the docs to make this clearer. 

```yaml
trigger: 
- master

pool: 
   vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: ContosoDeploy
    resourceType: VirtualMachine
    tags: ubuntu,extra # target VMs that have both these tags
  strategy:
   runOnce:
     deploy:   
      steps:
        - script: echo "Hello world"
```
