### ISSUE TITLE
Incorrect documentation and sample code from Azure

### ISSUE THREAD

**Issue by IRLeif** [MicrosoftDocs/azure-devops-docs#8208]
I can't get the recommended approach to work based on the examples provided.

After spending the better part of two days reading countless blog posts, StackOverflow issues, documentation pages, etc. I still haven't been able to identify the root cause.

I suspect a different `.pypirc` might be loaded from the wrong location on the virtual machine in the Azure DevOps Pipeline, but I haven't been able to confirm this.

**Error message in full, copied from Azure DevOps Pipeline:**

```
Starting: Publish Package
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
twine upload -r myserver --config-file /home/vsts/work/_temp/twineAuthenticate/JmhwYF/.pypirc dist/*
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/c10c2098-a9bc-4913-8490-c401e7bc117a.sh
InvalidConfiguration: Missing 'myserver' section from the configuration file
or not a complete URL in --repository-url.
Maybe you have a out-dated '/home/vsts/work/_temp/twineAuthenticate/JmhwYF/.pypirc' format?
more info: https://docs.python.org/distutils/packageindex.html#pypirc

##[error]Bash exited with code '1'.
Finishing: Publish Package
```

The link referenced in the error message does not provide any useful information.

**My project structure:**

```
.
├── .pypirc
├── LICENSE
├── README.md
├── example_pkg
│   └── __init__.py
├── pipelines
│   └── publish_package.yml
├── setup.py
└── tests
```

**Contents of my `.pypirc`:**

Note that this was copied directly from the Azure Feeds "Connect to feed"-tutorial, i.e. this is the sample file provided by Microsoft within Azure.

```pypirc
[distutils]
Index-servers =
  myserver

[myserver]
Repository = https://pkgs.dev.azure.com/myorg/myproject/_packaging/myfeed/pypi/upload
```

I have tried changing to lower-case `index-servers` and `repository` without any luck.

**Contents of my `publish_package.yml`:**

```yaml
name: Publish Package
trigger:
  - master
pool:
  vmImage: ubuntu-18.04
steps:
- task: UsePythonVersion@0
  displayName: Set Python Version
  inputs:
    versionSpec: 3.8.2
- script: |
    pip install setuptools==46.1.3
    pip install wheel==0.34.2
    pip install twine==3.1.1
  displayName: Install Dependencies
- script: |
    python setup.py sdist bdist_wheel
  displayName: Build Artefact
- task: TwineAuthenticate@0
  inputs:
    artifactFeed: myfeed
  displayName: Authenticate Twine
- script: |
    twine upload -r myserver --config-file $(PYPIRC_PATH) dist/*
  displayName: Publish Package
```

**Side-note:** I had to change `artifactFeeds`(as recommended by the documentation) to `artifactFeed`(singular) to get the the task `TwineAuthenticate@0` to work.

I have also tried variations of the twine upload command without any luck:

```
twine upload -r myserver dist/*
twine upload -r myproject/myserver dist/*
'twine upload -r myserver --config-file $(PYPIRC_PATH) dist/*'
twine upload -r myproject/myserver --config-file $(PYPIRC_PATH) dist/*
python -m twine upload -r myserver --config-file $(PYPIRC_PATH) dist/*
'python -m twine upload -r myserver --config-file $(PYPIRC_PATH) dist/*'
```

All variants result in the same error as mentioned above.

Note that all the other tasks and scripts in the Azure Pipeline (including Authenticate Twine) seems to be working correctly. Only the last script with the display name _Publish Package_ is failing.

The code in this documentation and within Azure Feeds seems to be incorrect.

What is the correct approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 638243e7-cdd6-7573-aa6a-87c39da1bb3d
* Version Independent ID: d0046f56-ed26-7af2-3b8f-3dd5ab6ab892
* Content: [Publish packages to Azure Artifacts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pypi.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by IRLeif** [comment]
I found a hint in [this comment](https://github.com/MicrosoftDocs/azure-devops-docs/issues/2586#issuecomment-601597960):

"I used feed/endpoint as the artifactFeed. But the feed is project/feed. And there is no validation on the artifactFeed so if it is invalid there is no error shown to the user."

That was part one of the problem.

Also, I was using version `0` of the `TwineAuthenticate` task (as copied from older Microsoft documentation). I had to change to version `1`.

That was the second part of the problem.

More specifically, I had to change this:

```yaml
- task: TwineAuthenticate@0
  inputs:
    artifactFeed: myfeed
  displayName: Authenticate Twine
```

To this:

```yaml
- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'my project/myfeed'
  displayName: Authenticate Twine

```

Note that my project name has spaces in it, so I needed to enclose it in single quotes. Double quotes would also have worked, but then I would have to escape the `/`

Everything is working fine after making those two changes.

For good measure, I also changed this script:

```yaml
- script: |
    twine upload -r myserver --config-file $(PYPIRC_PATH) dist/*
  displayName: Publish Package
```

To this:

```yaml
- script: |
    python -m twine upload -r myserver --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: Publish Package
```

That last script change was probably not necessary, but I changed it to match the example shown in [this Microsoft documentation page](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops). Just for consistency.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by oynek** [comment]
This problem is definitely still relevant. It took me several hours to figure out where the problem is. Thanks for sharing.

**Comment by Madaditya** [comment]
I am still seeing this problem.

twine is unable to identify my configuration

**Error :** `InvalidConfiguration: Missing 'myproject-artifacts' section from the configuration file`

my pipeline.yaml

```
steps:
- task: UsePythonVersion@0
  inputs:
    # versionSpec: '$(python.version)'
    versionSpec: '3.6'
    addToPath: true
  displayName: 'Use Python $(python.version)'

- task: CmdLine@2
  displayName: 'Install Dependencies'
  inputs:
    script: |
      pip install wheel
      pip install twine

- task: CmdLine@2
  displayName: 'Build Package'
  inputs:
    script: |
      python setup.py sdist bdist_wheel
    workingDirectory: 'module/package'
    # failOnStderr: true

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'myorg/myproject-artifacts'
- task: CmdLine@2
  displayName: 'Publish Package'
  inputs:
    script: |
      cat $PYPIRC_PATH
      python -m twine upload -r myproject-artifacts --config-file $(PYPIRC_PATH) dist/*.whl
    workingDirectory: 'module/package'
    failOnStderr: true
```

Not sure what is wrong.

**Comment by luigibrancati** [comment]
This issue is still relevant, here is my pipeline
```
trigger:
  tags:
    include:
    - 'package-*'
    exclude:
    - '*.dev'

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python3.7:
      python.version: '3.7'
    
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    cd $(package-dir)
    python -m pip install --upgrade pip setuptools wheel
    python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd $(package-dir)
    python -m pip install -r test_requirements.txt
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
  displayName: 'pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'project/myfeed'

- script: |
    cd $(package-dir)
    python -m pip install wheel twine
  displayName: "Install twine and wheel"

- script: |
    cd $(package-dir)
    python setup.py bdist_wheel
  displayName: "Create the wheel"

- script: |
    cd $(package-dir)
    python -m twine upload -r myfeed dist/* --config-file $(PYPIRC_PATH)
  displayName: "Install the artifact"
```

This gives me the error `InvalidConfiguration: Missing 'myfeed' section from /home/vsts/work/_temp/twineAuthenticate/1qfoCS/.pypirc.`. An interesting thing is that this exact pipeline works if i change `vmImage: ubuntu-latest` to `vmImage: vs2017-win2016`, without touching naything else.
