### ISSUE TITLE
Distinguish why Build.Repository.Name results in Null and Build.SourceBranch does not result in Null

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/azure-devops-docs#8217]
When declaring
```
variables:
  BuildRepoName: $[ variables['Build.Repository.Name'] ]
  BuildSourceBranch: $[ variables['Build.SourceBranch'] ]
```
The documentation states it is an agent scoped variable.  Perhaps there should be more clarification on what that means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by trajano** [comment]
A better enhancement would be to show **how** to get the value in case it is needed.

## How to extract agent-scoped variables for use in [places that do not allow it]

Since agent-scoped variables cannot be used without being run in an agent, the most common cases being `condition`s in `stage`s, `job`s and `step`s, they need to be set from an agent and set as a variable.

This can be done through [ a link that points to the task.setvariable ] that is executed in the initial stages.  For example
```yaml
stages:
  - stage: bootstrap
    displayName: Bootstrap build pipeline
    jobs:
      - job: exposeAgentScopedVariables 
        displayName: Expose agent-scoped variables
        steps:
          - bash: |
                echo "##vso[task.setvariable variable=X.Build.Respository.Name]$(Build.Repository.Name)"
                echo "##vso[task.setvariable variable=X.Build.Respository.Uri]$(Build.Repository.Uri)"
            displayName: Expose agent-scoped variables
```

Then in future stages it can be accessed as

```
condition: and(succeeded(), ne(variables['X.Build.Respository.Name'], 'specialName'))
```
