### ISSUE TITLE
Type casting

### ISSUE THREAD

**Issue by Thilas** [MicrosoftDocs/azure-devops-docs#8242]
The type casting section is really helpful. It is just missing a couple of cases. What is the expected behavior when casting the values `[]` and `{}` to booleans? `true` or `false`?

IMHO, it should return `false` but it seems not. Could you confirm and document the expected behavior please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#type-casting)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@Thilas I apologize for the delay in responding. Can you explain your use case here? When I use `[]` or `{}` in an expression, I'm getting an error response.

**Comment by Thilas** [comment]
@juliakm, my use case is that on some parameters, I want to define the default value as `[]` or `{}`. Then if I want to know if we have an empty list or object, the only way I know of is: `${{ if parameters.myParam }}`. But it returns `true`.

May be there is an other way to do that?

**Comment by juliakm** [comment]
@Thilas Here's an example you may find helpful:

```yaml
parameters:
- name: foo
  type: object
  default: []

- name: bar
  type: object
  default: {"one":"two"}
pool: { vmImage: ubuntu-latest }

steps:
- checkout: none
- ${{ if eq(length(parameters.foo), 0) }}:
  - script: echo Foo is empty
    displayName: Foo is empty
```
