### ISSUE TITLE
Schema documentation suggests pool can be specified at pipeline level but pipeline run doesn't reflect this

### ISSUE THREAD

**Issue by mustafaoral** [MicrosoftDocs/azure-devops-docs#8261]
[YAML schema reference](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pool) suggests that the pool can be specified "at the pipeline, stage, or job level". With the exception of stages, which are not possible to configure using classic build pipelines, this mirrors the classic build pipelines where the pool can be specified at the pipeline or job level.

When I set up a simple pipeline using this YAML:

```yaml
name: $(Date:yyyyMMdd)$(Rev:.r)
pool:
  vm-image: windows-2019
steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      arguments: -c Release
```

and run it, the output indicates that the agent wasn't provisioned with Windows Server 2019 with Visual Studio 2019 as per `vm-image: windows-2019`:

```
Pool: Azure Pipelines
Image: Ubuntu16
Agent: Hosted Agent
Started: Today at 14:14
Duration: 15s
```
If it's not possible to specify the pool at the pipeline level, then the documentation should either not suggest so, or if there are any gotchas, these should be made explicit.
