### ISSUE TITLE
Document "resources" usage in templates that use "extends"

### ISSUE THREAD

**Issue by beatcracker** [MicrosoftDocs/azure-devops-docs#8288]
It seems that you can have multiple `resources` definitions if you use new [extends](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates#extend-from-a-template) keyword. This works:

- azure-pipelines.yml
```yml
resources:
   containers:
      - container: node_latest
        image: node:latest

extends:
  template: template.yml
```

- template.yml
```yml
resources:
  containers:
    - container: node_lts
      image: node:lts

jobs:
- job:
  pool:
    vmImage: ubuntu-latest
  steps:
    - bash: node --version
      target: node_latest

    - bash: node --version
      target: node_lts
```

The rendered template will look like this and the pipeline will run without issues:

```yml
resources:
    containers:
    - container: node_lts
    image: node:lts
    - container: node_latest
    image: node:latest
stages:
- stage: __default
    jobs:
    - job: ''
    pool:
        vmImage: ubuntu-latest
    steps:
    - task: Bash@3
        target:
        container: node_latest
        inputs:
        targetType: inline
        script: node --version
    - task: Bash@3
        target:
        container: node_lts
        inputs:
        targetType: inline
        script: node --version
```

Unfortunately this is not documented anywhere. Similar issues:

* [Defining Resources inside a Template
](https://github.com/MicrosoftDocs/azure-devops-docs/issues/6533) (#6533)
* [Using a Step Template within a Phase Template (nested templates](https://github.com/Microsoft/azure-pipelines-yaml/issues/49)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
