### ISSUE TITLE
runtime expression	$[variables.var] renders as is when not found

### ISSUE THREAD

**Issue by pallxk** [MicrosoftDocs/azure-devops-docs#8342]
while the doc says it renders empty string.

Example pipeline:

```yml
steps:
- bash: echo '$[variables.var]'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
I wonder if you ran into a bug. Can you test out this YAML? If it doesn't work as expected, please ask a question in our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). The Developer Community is actively monitored by the engineering team. 

```yaml
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo '$[variables.var]' #output $[variables.var]
- script: echo '$[variables.var]' #output $[variables.var]
```
