### ISSUE TITLE
Documentation is not clear! AzureWebApp failed due to error "No package found with specified pattern: d:\a\1\s\**\*.zip<br/>"

### ISSUE THREAD

**Issue by dylanw-oss** [MicrosoftDocs/azure-devops-docs#8360]
I followed [this document](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml) to create a pipeline for .NET Core web APP.

I use vmImage: 'windows-latest'

```yaml
  # download the artifact drop from the previous job
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: drop

  # deploy to Azure Web App production
  - task: AzureWebApp@1
    inputs:
      azureSubscription: '<prod Azure service connection>'
      appName: '<name of prod web app>
```

This won't work, I got below error message:

> ##[error]Error: No package found with specified pattern: d:\a\1\s\**\*.zip<br/>Check if the package mentioned in the task is published as an artifact in the build or a previous stage and downloaded in the current job.
> Finishing: AzureWebApp

And finally I figured out that the task "DownloadBuildArtifacts" will download files to destination  $(System.ArtifactsDirectory) by default.
And if you follow [the same document](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml#deploy-a-web-deploy-package-aspnet), add package path to task "AzureWebApp@1"
It still won't work, because the downloaded path from task "DownloadBuildArtifacts@0"  is different than this package reference path in task "AzureWebApp@1".
```yaml
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Azure service connection>'
    appName: '<Name of web app>'
    package: $(System.DefaultWorkingDirectory)/**/*.zip
```

To fix it, you have to explicitly declared the download path and package reference path, like this:

```yaml
  # download the artifact drop from the previous job
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: drop
      downloadPath: '$(System.DefaultWorkingDirectory)'

  # deploy to Azure Web App staging
  - task: AzureWebApp@1
    inputs:
      package: $(System.DefaultWorkingDirectory)/**/*.zip  
      azureSubscription: '<prod Azure service connection>'
      appName: '<name of prod web app>
      slotName: staging

```

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by michaelbuller** [comment]
This is still relevant, I am starting from the example actions for how to deploy a node app to azure web apps.  I used the example template and it dies on this step.

**Comment by mizrael** [comment]
I was having exactly the same issue. I have to test, build and deploy (to multiple environments and subscriptions) a Function App.
I (sort of) managed to make it work by following the steps outlined here: https://joeblogs.technology/2020/07/multi-stage-pipelines-and-yaml-for-continuous-delivery-azure-devops/

basically, my pipeline now looks something like this:

```
- stage: Build 
  displayName: Build  

  jobs:
  - job: build_APIs
    displayName: Build APIs

    steps:        
    - task: DotNetCoreCLI@2
      displayName: Build Release
      inputs:
        command: 'build'
        projects: |
          $(functionAppDirectory)/*.csproj
        arguments: --output $(publishOutputDirectory) --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(publishOutputDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  jobs:
    - deployment: Deploy   
      environment: 'UAT'   
      strategy:
        runOnce:
          preDeploy:
            steps:
            - download: current
              artifact: drop
              displayName: Download artifact            
          deploy:
            steps:            
            - task: AzureWebApp@1    
              displayName: Deploy to UAT
              inputs:                
                azureSubscription: '..............'
                appType: 'functionApp'
                appName: '.............'
                package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
```
