### ISSUE TITLE
Poor documentation about objects and repetition constructs

### ISSUE THREAD

**Issue by cubikca** [MicrosoftDocs/azure-devops-docs#8385]
The documentation is incredibly unclear as to how to process an "object". I really only want a list of strings, but I am stuck passing it as an object because a list of strings doesn't exist (in a template language? really??).

Just for a concrete example, I'm trying to deploy to multiple instances simultaneously. Depending on which environment we are running in, we have 1 or more instances for 1 or more components. The stage YAML looks like this:

```yaml
parameters:
  - name: environment
    type: string
    default: 'None'
  - name: service1instances
    type: object
    default:
     - 1: true
  - name: web1instances
    type: object
    default:
      - 1: true
  - name: web2instances
    type: object
    default:
      - 1: true
  - name: web3instances
    type: object
    default:
      - 1: true
  - name: oauthinstances
    type: object
    default:
      - 1: true
  - stage: ${{ parameters.environment }}
    pool: 'Azure Pipelines'
    dependsOn: []
    variables:
      - ${{ if ne(parameters.environment, 'Production') }}:
        - group: QA
      - ${{ if eq(parameters.environment, 'Production') }}:
        - group: Production-New
      - group: 'Certificate Thumbprints'
    jobs:
      - deployment: dbmigrate
        displayName: 'Migrate databases to latest version'
        pool:
          name: Build-${{ parameters.environment }}
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - template: jobs/deploy-dbmigrate-job.yml
      - deployment: servicex86
        dependsOn: [dbmigrate]
        displayName: 'Deploy ServiceX86'
        pool:
          name: Deploy-${{ parameters.environment }}-ServiceX86
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - template: jobs/deploy-servicex86-job.yml
                  parameters:
                    environment: ${{ parameters.environment }}
      - ${{ each instance in parameters['serviceinstances'] }}:
        - ${{ each pair in instance }}:
          - deployment: service${{ pair.key }}
            displayName: 'Deploy Service1 (${{ pair.key }})'
            condition: eq(pair.value, true)
            environment: ${{ parameters.environment }}
            pool:
              name: Deploy-${{ parameters.environment }}-Service1-${{ pair.key }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: jobs/deploy-service-job.yml
                      parameters:
                        environment: ${{ parameters.environment }}
      - deployment: systemtx
        displayName: 'Deploy Service2'
        environment: ${{ parameters.environment }}
        pool:
          name: Deploy-RSP-${{ parameters.environment }}-SystemTx
        strategy:
          runOnce:
            deploy:
              steps:
                - template: jobs/deploy-systemtx-job.yml
                  parameters:
                    environment: ${{ parameters.environment }}
      - ${{ each instance in parameters['web1instances'] }}:
        - ${{ each pair in instance }}:
          - deployment: paragon${{ pair.key }}
            displayName: 'Deploy Web1 (${{ pair.key }})'
            condition: eq(pair.value, true)
            environment: ${{ parameters.environment }}
            variables:
              - ${{ if startswith(parameters.environment, 'UAT') }}:
                - template: deploy-vars-UAT.yml
              - ${{ if and(not(startswith(parameters.environment, 'UAT')), ne(parameters.environment, 'Production')) }}:
                - template: deploy-vars-Test.yml
              - ${{ if eq(parameters.environment, 'Production') }}:
                - template: deploy-vars-Production.yml
            pool:
              name: Deploy-${{ parameters.environment }}-Web1-${{ pair.key }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: jobs/deploy-web1-job.yml
                      parameters:
                        environment: ${{ parameters.environment }}
      - ${{ each instance in parameters['web2instances'] }}:
        - ${{ each pair in instance }}:
          - deployment: web2${{ pair.key }}
            displayName: 'Deploy Web2 (${{ pair.key }})'
            condition: eq(pair.value, true)
            environment: ${{ parameters.environment }}
            variables:
              - ${{ if startswith(parameters.environment, 'UAT') }}:
                - template: deploy-vars-UAT.yml
              - ${{ if and(not(startswith(parameters.environment, 'UAT')), ne(parameters.environment, 'Production')) }}:
                - template: deploy-vars-Test.yml
              - ${{ if eq(parameters.environment, 'Production') }}:
                - template: deploy-vars-Production.yml
            pool:
              name: Deploy-${{ parameters.environment }}-Web2-${{ pair.key }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: jobs/deploy-web2-job.yml
                      parameters:
                        environment: ${{ parameters.environment }}
      - ${{ each instance in parameters['oauthinstances'] }}:
        - ${{ each pair in instance }}:
          - deployment: oauth${{ pair.key }}
            displayName: 'Deploy OAuth (${{ pair.key }})'
            condition: eq(pair.value, true)
            environment: ${{ parameters.environment }}
            variables:
              - ${{ if startswith(parameters.environment, 'UAT') }}:
                - template: deploy-vars-UAT.yml
              - ${{ if and(not(startswith(parameters.environment, 'UAT')), ne(parameters.environment, 'Production')) }}:
                - template: deploy-vars-Test.yml
              - ${{ if eq(parameters.environment, 'Production') }}:
                - template: deploy-vars-Production.yml
            pool:
              name: Deploy-${{ parameters.environment }}-OAuth-${{ pair.key }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: jobs/deploy-oauth-job.yml
                      parameters:
                        environment: ${{ parameters.environment }}
      - ${{ each instance in parameters['web3instances'] }}:
        - ${{ each pair in instance }}:
          - deployment: web3${{ pair.key }}
            displayName: 'Deploy Web3 (${{ pair.key }})'
            condition: eq(pair.value, true)
            environment: ${{ parameters.environment }}
            variables:
              - ${{ if startswith(parameters.environment, 'UAT') }}:
                - template: deploy-vars-UAT.yml
              - ${{ if and(not(startswith(parameters.environment, 'UAT')), ne(parameters.environment, 'Production')) }}:
                - template: deploy-vars-Test.yml
              - ${{ if eq(parameters.environment, 'Production') }}:
                - template: deploy-vars-Production.yml
            pool:
              name: Deploy-${{ parameters.environment }}-Web3-${{ pair.key }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: jobs/deploy-web3-job.yml
                      parameters:
                        environment: ${{ parameters.environment }}
```
The included jobs are pretty straightforward, and it was working as expected before attempting to add the repetition construct, so I doubt that there are syntax errors there. In any case, I get no useful error message. All that Azure Pipelines says is "Unable to load pipeline stages". Of course, maybe what I'm doing is overkill and there's a simpler way to execute a job on multiple pools. But, I still need to know how many instances there are to programmatically generate the pool names.

I'd really like to see some more documentation on YAML objects and how to use them effectively. Specifically, I'd like to know how to use a list of strings as a parameter. If necessary, show how to have a list of strings masquerade as an object.

Somewhat unrelated, but is there any way to pre-validate the YAML? The tweak/push/CI/CD cycle is quite cumbersome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
