### ISSUE TITLE
Add example of caching Docker images

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/azure-devops-docs#8397]
I added this a while back https://developercommunity.visualstudio.com/idea/703669/caching-of-docker-images-between-builds.html but I found a way of doing it within the existing system.  Though when I pasted my example the formatting broke, so I am adding it here

```
# Azure pipeline template for loading the Docker cache
parameters:
  - name: cacheImages
    type: string
    default: tomcat:8.5.45-jdk11-openjdk mysql:latest

steps:
  - task: Cache@2
    inputs:
      key: docker | **/Dockerfile | "${{ parameters.cacheImages }}"
      path: $(Pipeline.Workspace)/docker
      cacheHitVar: DOCKER_CACHE_RESTORED
    displayName: Cache Docker images
  - script: |
      gunzip -c $(Pipeline.Workspace)/docker/cache.tar.gz | docker load
    displayName: Restore Docker image cache
    condition: and(not(canceled()), eq(variables.DOCKER_CACHE_RESTORED, 'true'))
  - script: |
      mkdir -p $(Pipeline.Workspace)/docker
      for fn in ${{ parameters.cacheImages }}
      do
        docker pull -q $fn
      done
      docker save ${{ parameters.cacheImages }} | gzip -9c &gt; $(Pipeline.Workspace)/docker/cache.tar.gz
    displayName: Populate docker image cache
    condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_RESTORED, 'true')))
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
