### ISSUE TITLE
Determine triggering pipeline

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/azure-devops-docs#8399]
Hi team. Since a pipeline can be triggered by multiple other pipelines, is there any mechanism that exists to identify which exact pipeline was the trigger? My purpose is to control what happens in the triggered pipeline based on which pipeline triggered it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**

**Comment by msebolt** [comment]
@damienestewart Thank you for the question.

Please see if the build variables in [this table](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#how-are-the-identity-variables-set) solves this issue, else add some further details below.

**Comment by msebolt** [comment]
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).

**Comment by brichins** [comment]
I don't think the docs cover this correctly.  It appears that only external (Jenkins) "builds" but not "pipelines" create the `Build.TriggeredBy.*` variables.  In my case I have defined a pipeline that can be triggered from either of two upstream pipelines.  When I dump the env vars, I can see information for both the dev and qa pipelines, but it doesn't indicate which one triggered it.  I'm guessing it's the difference between a `ResourceTrigger` vs a `BuildTrigger`. 

```yaml
  pipelines:
    - pipeline: baseInfraDev
      source: dev-hack
      project: EXAMPLE
      trigger: true
    - pipeline: baseInfraQA
      source: qa-hack
      project: EXAMPLE
      trigger: true
```

The `triggerInfo` section of the pipeline from the API contains the information, so I'm guessing it's not being mapped into the env vars.  I don't want to have to query the API but can if there aren't any more options.

```
triggerInfo:
  alias: baseInfraQA
  artifactType: Pipeline
  pipelineId: '1775074'
  pipelineTriggerType: PipelineCompletion
  projectId: someUidNotShownHere
  source: qa-hack
  version: '20200629.5'
```

**Comment by Resousse** [comment]
@brichins, hello, did you find a way to retrieve the pipeline name of the pipeline which triggered the pipeline? 
Thanks,

**Comment by steved0x** [comment]
@Resousse @brichins You should be able to use the `Resources.TriggeringAlias` variable if the pipeline is triggered by a pipeline resource trigger (which it appears to be from your example), for example:

```
resources:
 pipelines:
   - pipeline: source-pipeline
     source: PipelineTriggerSource
     project: FabrikamFiber
     trigger: true
   - pipeline: other-project-pipeline
     source: PipelineTriggerFromOtherProject
     project: FabrikamRepo
     trigger: true

trigger: none # Only trigger with pipeline resource trigger

pool:
  vmImage: windows-latest

jobs:
- job: Test1
  steps:
  - bash: echo $(Resources.TriggeringAlias)
```

https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines#pipeline-resource-metadata-as-predefined-variables
