### ISSUE TITLE
pipeline triggers are not activating when examples are followed - request for updated documentation

### ISSUE THREAD

**Issue by PaulCharlton** [MicrosoftDocs/azure-devops-docs#8435]
with repo 1, a pipeline named `admin_web_api`

in repo 2
```
resources:
  pipelines:
    - pipeline: 'admin_web_api'
      source: 'admin_web_api'
      project: 'foobar'
      trigger:
        branches:
          - master-foobar
```

pipeline for repo 1 builds.   pipeline for repo 2 does not run.

I have triggered pipeline 1 both manually and via a commit to the `master-foobar` branch

repo 1 and repo 2 are in the same `visualstudio.com` project

ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml

**Comment by PaulCharlton** [comment]
it may be a documentation issue at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml since the example there does not conform to the schema at: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-pipelines

===
update:
adding `include:` in the trigger block allows the repo 2 pipeline to trigger ... when a commit is made to repo 1, which is before the repo 1 pipeline COMPLETES.     Is there another incantation for repo 2 to start its pipeline after the repo 1 pipeline completes?

```
resources:
  pipelines:
    - pipeline: 'admin_web_api'
      source: 'admin_web_api'
      project: 'footer'
      trigger:
        branches:
          include:
          - master-foobar
```
