### ISSUE TITLE
Need additional info about when macro syntax variables can be used

### ISSUE THREAD

**Issue by cb55555** [MicrosoftDocs/azure-devops-docs#8445]
According to the section titled "Understand variable syntax", macro variables can be used on the right side of a pipeline definition:

> Macro variables are only expanded when they are used for a value, not as a keyword. Values appear on the right side of a pipeline definition. The following is valid: key: $(value). The following isn't valid: $(key): value.

There's also a note about where in the YAML the variables are expanded:

> Variables are only expanded for stages, jobs, and steps. You cannot, for example, use macro syntax inside a resource or trigger.

However, I found that you cannot use macro variables for the display name of a job if naming the job inline. For example this fails:

```
variables:
- name: jobName
  value: MyJob

jobs:
- job: $(jobName)  #Error: Job $(jobName) has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number.
  steps:
  - script: echo 'fred'
```

You must use the displayName property like this:

```
variables:
- name: jobName
  value: MyJob

jobs:
- job:
  displayName: $(jobName)  #This works file
  steps:
  - script: echo 'fred'
```

If you must name the job inline, you have to use the template expression syntax like this:

```
variables:
- name: jobName
  value: MyJob

jobs:
- job: ${{ variables.jobName }}
  steps:
  - script: echo 'fred'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
