### ISSUE TITLE
workspace: clean: all doesn't work for deployment jobs

### ISSUE THREAD

**Issue by akempe** [MicrosoftDocs/azure-devops-docs#8452]
The docs regarding cleaning a workspace don't work for deployment jobs. Either the docs are wrong or this is a bug. See [these other people](https://developercommunity.visualstudio.com/content/problem/614016/there-is-no-way-how-to-clean-workspace-in-deployme.html) also having problems. Please update appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#agent-phase)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@akempe Can you go into more detail on what isn't working? I'm able to run the following YAML with a previous job. If this is possibly a bug, please post on the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). That space is actively monitored by the engineering team. 

In the issue you linked to, there was a bug that should be fixed now. The documentation was also updated. 

```yaml
jobs:
  # track deployments on the environment
- deployment: DeployWeb
  displayName: deploy Web App
  pool:
    vmImage: 'Ubuntu-16.04'
  workspace:
   clean: all
  # creates an environment if it doesn't exist
  environment: 'smarthotel-dev'
  strategy:
    # default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment
```

**Comment by akempe** [comment]
Mine was on windows with a `IISWebAppDeploymentOnMachineGroup` task.
Note: my conditions DO pass, because it works when I have manual scripts steps to delete the artefacts. 

Please see this [other issue](https://developercommunity.visualstudio.com/content/problem/959548/yaml-pipeline-deployment-job-workspace-clean-all-d.html) where it's been closed, but there are a load of comments on the solution saying it still doesn't work. Hence my confusion re. the docs being wrong or it actually being a bug still.

```
- deployment: mydeploy
  workspace:
    clean: all
  pool:
    vmImage: 'windows-latest'
  displayName: deploy Web App
  dependsOn: mybuild	# a higher up buildstep
  condition: and(succeeded(), and(eq(variables.xxx, 'yyy'), eq(variables.aaa, 'bbb')))
  environment: myenv.myvm
  strategy:
    runOnce:
      deploy:
        steps:
	- task: IISWebAppDeploymentOnMachineGroup@0
        ......
```
