### ISSUE TITLE
Which versions of pipeline artifacts are used?

### ISSUE THREAD

**Issue by lukeschlather** [MicrosoftDocs/azure-devops-docs#8470]
In this example, I have a few questions around multi-stage pipelines.

```
# Download artifacts from a specific branch with a tag
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'FabrikamFiber'
    pipeline: 12
    runVersion: 'latestFromBranch'
    runBranch: 'refs/heads/master'
    tags: 'testTag'
```

What is the "latest" or "latestFromBranch" ? 

Example set up:

* I have two pipelines each with two stages. Call them Pipeline A and B, with stages A1, A2, B1, B2.
* Stage A1 generates some artifacts, Stage A2 runs some tests. 
* Stages B1 and B2 consume artifacts from Stage A1.

Assume that there is a run of Pipeline A which generated artifacts A-artifact1, and A2 completed successfully.
Assume there is a second run of Pipeline A in progress, which has generated an artifact A-artifact2.

My hope is that:

* If B1 consumes A-artifact1 that same pipeline run will always use A-artifact1, even if A-artifact2 is fully available before stage B2 begins.
* Pipeline B will not consume A-artifact2 unless the entire pipeline A has completed successfully.

Is that accurate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
