### ISSUE TITLE
example in the documentation for stageDependencies in conditions

### ISSUE THREAD

**Issue by stephenmoloney** [MicrosoftDocs/azure-devops-docs#8486]
# Issue:

The code below comes from the [documentation](https://github.com/MicrosoftDocs/azure-devops-docs/blame/5703a9bae7f894e0d1d64daf883b5ea5d2751077/docs/pipelines/process/expressions.md#L480-L497) 
```yaml
stages:
- stage: A
  jobs:
  - job: A1
    steps:
     - script: echo "##vso[task.setvariable variable=skipsubsequent;isOutput=true]false"
       name: printvar
- stage: B
  condition: and(succeeded(), ne(stageDependencies.A.A1.outputs['printvar.skipsubsequent'], 'true'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo hello from Stage B
```

But `stageDependencies` inside the condition doesn't seem to be supported as of `29/May/2020`.

The error returned is as follows:

```txt
An error occurred while loading the YAML build pipeline. Unrecognized value: 'stageDependencies'. Located at position 21 within expression: ...
```
Has this feature been rolled out yet in Azure Devops or do we need to wait?
