### ISSUE TITLE
Potential mistake in the naming of an agent variable

### ISSUE THREAD

**Issue by simontjell** [MicrosoftDocs/azure-devops-docs#8514]
I the instance of Azure DevOps 2019, I'm accessing, the variable listed here as **Agent.MachineName** does in fact seem to be named **Agent.ComputerName**.

I might be confused, but it looks like a mistake.

Best regards,
Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@simontjell Which version of 2019 are you using? Are you on a Windows server?

This is what I found during testing on DevOps Server 2019.1:

```yaml
steps:
- script: |
    echo "Hello world"
- powershell: Write-Host $(Agent.MachineName) #Resolves to 2019-1-SERVER
- powershell: Write-Host $(Agent.ComputerName) #Fails

```
