### ISSUE TITLE
Great docs! How do you use length() for Arrays such as stepLists?

### ISSUE THREAD

**Issue by raboley** [MicrosoftDocs/azure-devops-docs#8521]
I'm trying to make it so that I can skip an entire job if there are no steps sent to that job. I want to check that the step list is empty, which I assume length is the best way to do it? Based on the doc it sounds like it should be able to count an array, but I get an error when I try to use length() on the steplist. 

Using the condition:

```yaml
condition: gt(length(${{ parameters.validateParallelSteps }}), 0)
```

`Unable to convert from Array to String. Value: Array`

This is going to be used as a pipeline template hence the parameters syntax.

I am using

```yaml
parameters:
  - name: validateParallelSteps
    type: stepList
    default: []
(...)
    - job: PR_Parallel
      condition: gt(length(${{ parameters.validateParallelSteps }}), 0)
      steps:
```

And the referencing template I am testing with does not include this parameter in it which should default it to []

Basically it doesn't seem like length() is working, or other things on a step list even though errors indicate it is treating it like an array, but not really.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@raboley Thank you for the feedback.

Please see if using `join` as mentioned [here](https://developercommunity.visualstudio.com/content/problem/879845/pipeline-template-echo-array-parameter-fails-with.html) fixes the issue.

Otherwise, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback on this from the product team.

For additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by Davesmall28** [comment]
The solution to the above is to move the length expression inside the curly braces:

`condition: gt(${{length(parameters.validateParallelSteps)}}, 0)`

**Comment by raboley** [comment]
Ty! I figured it out eventually but forgot about this thread, hope it is able to help someone in the future!

**Comment by toothpasteBeforeOj** [comment]
> @raboley - Hope this helps you, 2 years later 😄
> 
> The solution to the above is to move the length expression inside the curly braces:
> 
> `condition: gt(${{length(parameters.validateParallelSteps)}}, 0)`

Wow, I was struggling with this only today and you just posted yesterday. Thank you so much for sharing!!

**Comment by russellboley-uipath** [comment]
I just googled this again today so I can see how poorly it sticks in my head. Thanks again @Davesmall28  😆

**Comment by hammady** [comment]
Thanks for the solution. If you want to skip few steps rather than the whole job, you can do the following:
```yaml
        - ${{ if gt(length(parameters.some_param), 0) }}:
          - step1: ...
          - step2: ...
          - template: tpl.yaml
            parameters: {}
```

Or for some variables:

```yaml
  variables:
    - group: My mandatory group
    - ${{ if gt(length(parameters.some_param), 0) }}:
      - group: My optional group
      - name: another_var
        value: my_value
```
