### ISSUE TITLE
Stage template reference - file not found error

### ISSUE THREAD

**Issue by roofiq** [MicrosoftDocs/azure-devops-docs#8531]
Hello,
I wanted to reference a Stage template from my core yaml template.
Below example is basically what I was trying to achieve. Unfortunately, I got an error message saying: **common.yml not found in repository...**

```
# Repo: Contoso/LinuxProduct
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: templates
      type: github
      name: Contoso/BuildTemplates

stages:
- template: common.yml@templates  # Template reference
```
Just to add, both repositories are in the same project in my example.
Is it possible to reference a whole stage like this or it only works on job and steps level?

Thanks!
Rafal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
