### ISSUE TITLE
Extra spaces in YAML example

### ISSUE THREAD

**Issue by errollw** [MicrosoftDocs/azure-devops-docs#8533]
In the YAML example below for **Download python distributions from Azure Artifacts feeds consulting official python registry first**, there are two additional spaces before `onlyAddExtraIndex` which should not be there, I think.

```
- task: PipAuthenticate@1
  displayName: 'Pip Authenticate'
  inputs:
    # Provide list of feed names which you want to authenticate.
    # Project scoped feeds must include the project name in addition to the feed name.
    artifactFeeds: project1/myTestFeed1, myTestFeed2
    # Setting this variable to "true" will force pip to get distributions from official python registry first and fallback to feeds mentioned above if distributions are not found there.
      onlyAddExtraIndex: true

# Use command line tool to 'pip install'.
- script: |
     pip install HelloTestPackage
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77227c6d-c042-d4b9-9801-ecb3547e1c33
* Version Independent ID: af8571a9-604a-6cf7-43ea-a714c42b95e7
* Content: [Python Pip Authenticate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/pip-authenticate?view=azure-devops&viewFallbackFrom=vst)
* Content Source: [docs/pipelines/tasks/package/pip-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/pip-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
