### ISSUE TITLE
Incorrect path causes function to not work even though pipeline succeeds

### ISSUE THREAD

**Issue by lgaud** [MicrosoftDocs/azure-devops-docs#8542]
When following this sample, I got to a state where the pipeline succeeded but the function did not appear in the Functions UI and could not be called. If you look in <yourapp>.scm.azurewebsites.net you'll see the .jar, host.json, annd HttpTrigger-Java folder deployed to site/wwwroot/javafunctions when it needs to be just site/wwwroot

To fix this, update the properties section of pom.xml to match your app's details (particularly functionAppName)
```
<functionAppName>javafunctions</functionAppName>
        <functionAppRegion>westus</functionAppRegion>
        <stagingDirectory>${project.build.directory}/azure-functions/${functionAppName}</stagingDirectory>
        <functionResourceGroup>java-functions-group</functionResourceGroup>
```
and add /$(appName) to the final deploy step to deploy the contents of the directory and not the directory itself
```
- task: AzureFunctionApp@1
  displayName: Azure Function App deploy
  inputs:
    azureSubscription: $(serviceConnectionToAzure)
    appType: functionApp
    appName: $(appName)
    package: $(build.artifactstagingdirectory)/$(appName)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e576b8-a378-a985-33cb-8adb9d7d7957
* Version Independent ID: d1b99713-8e01-23d9-47b7-1a9b5c98d5ca
* Content: [Build and deploy a Java web app to Azure Functions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java-function?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/java-function.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/java-function.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
