### ISSUE TITLE
DevOps Server 2019 does not support this

### ISSUE THREAD

**Issue by csnemes** [MicrosoftDocs/azure-devops-docs#8554]
Per 
https://developercommunity.visualstudio.com/content/problem/941173/facing-a-sequence-was-not-expected-when-applying-y.html
So please mention it in the documentation,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#parameters)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vtbassmatt** [comment]
This is correct. Azure DevOps 2019 only supported:

```yaml
parameters:
  key: value
  key2: value2
```

while 2020+ and the service prefer:

```yaml
parameters:
- name: key
  default: value
- name: key2
  default: value2
```
