### ISSUE TITLE
How to define build number?

### ISSUE THREAD

**Issue by brechtvhb** [MicrosoftDocs/azure-devops-docs#8556]
I use gitversion to create a build number.

Here's an example task:

```
        - task: gittools.usegitversion.gitversion-task.UseGitVersion@5
          displayName: GitVersion
          inputs:
            versionSpec: 5.x
            useConfigFile: true
            configFilePath: GitVersion.yml
```

In the pipelines tab the build number is being replaced but in the enviroments tab see this kind of output:

Deployment by $(GitVersion.SemVer)
#4949 on xxxx targeting test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
