### ISSUE TITLE
Pipelines secrets: inconsistent documentation

### ISSUE THREAD

**Issue by Lectem** [MicrosoftDocs/azure-devops-docs#8572]
The secret variable examples are not consistent.

It says:

> 
> ```yml
> variables:
>  GLOBAL_MYSECRET: $(mySecret) # this will not work because the variable needs to be mapped as env
>  GLOBAL_MY_MAPPED_ENV_VAR: foo # this will not work because the variable needs to be mapped as env
> 
> steps:
> 
> - powershell: |
>     # Using an input-macro:
>     Write-Host "This works: $(mySecret)"
> 
>     # Using the env var directly:
>     Write-Host "This does not work: $env:MYSECRET"
> 
>     # Using the env var through the variables mapping will not work:
>     Write-Host "This does not work either: $env:GLOBAL_MYSECRET"
> 
>     # Using the global var mapped in the pipeline. It is not a secret var:
>     Write-Host "This works: $env:GLOBAL_MY_MAPPED_ENV_VAR" 
> 
>     # Using the mapped env var:
>     Write-Host "This works: $env:MY_MAPPED_ENV_VAR"    # Recommended
> 
>   env:
>     MY_MAPPED_ENV_VAR: $(mySecret) # right way to map to an env variable
> ```

should result into 

> ```
> This works: ***
> This does not work:
> Global does not work either:
> This works: someValue
> This works: ***
> ```

Shouldn't `This works: someValue` be `This works: foo` ?

And the next example simply contradicts the previous one, as it uses `variables` and not `env`, which should not be working:

> 
> This example shows how to use secret variables $(vmsUser) and $(vmsAdminPass) in an Azure file copy task.
> ```yml
> variables:
>   VMS_USER: $(vmsUser)
>   VMS_PASS: $(vmsAdminPass)
> 
> pool:
>   vmImage: 'ubuntu-latest'
> 
> steps:
> - task: AzureFileCopy@4
>   inputs:
>     SourcePath: 'my/path'
>     azureSubscription: 'my-subscription'
>     Destination: 'AzureVMs'
>     storage: 'my-storage'
>     resourceGroup: 'my-rg'
>     vmsAdminUserName: $(VMS_USER)
>     vmsAdminPassword: $(VMS_PASS)
> ```

It should probably be this instead ?

```yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureFileCopy@4
  inputs:
    SourcePath: 'my/path'
    azureSubscription: 'my-subscription'
    Destination: 'AzureVMs'
    storage: 'my-storage'
    resourceGroup: 'my-rg'
    vmsAdminUserName: $(VMS_USER)
    vmsAdminPassword: $(VMS_PASS)
  env:
    VMS_USER: $(vmsUser)
    VMS_PASS: $(vmsAdminPass)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
