### ISSUE TITLE
Deployment Pipeline not trigger when build pipeline complete

### ISSUE THREAD

**Issue by szaroubi** [MicrosoftDocs/azure-devops-docs#8590]
Both my build and deployment pipelines are yaml based.
I want the deployment pipeline to trigger when the build pipeline has completed.
I have added the following block to my deployment pipeline yaml file

```yaml
### DISABLE RUN ON Commit
trigger: none

### ENABLE RUN WHEN THE BUILD PIPELINE RunS
resources:
  pipelines:
  - pipeline: buildPipelnie # Name of the pipeline resource
    source: 'Name of my Build Pipeline' # Name of the triggering pipeline
    trigger: 
      branches:
      - prefix-*
```

I am not sure I am doing it right or not, but I am following the doc.

I have also tried disabling the `trigger: none`
```yaml
### DISABLE RUN ON Commit
##trigger: none

### ENABLE RUN WHEN THE BUILD PIPELINE Run
resources:
  pipelines:
  - pipeline: buildPipelnie # Name of the pipeline resource
    source: 'Name of my Build Pipeline' # Name of the triggering pipeline
    trigger: 
      branches:
      - prefix-*
```

And didn't work.
I have also tried the `include/exclude` syntax of the `branches.prefix` block.
And it didn't work either.

Any suggestions would be greatly appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**

**Comment by szaroubi** [comment]
Got it work work:
Branch names should be prefixed with: `refs/heads/` 
in the example about, it should be `refs/heads/prefix-*`

**Comment by msebolt** [comment]
@szaroubi Thank you for the feedback and for posting a solution, the documentation has been updated and is pending review.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute).

**Comment by roofiq** [comment]
Hey, I'm having issues with running it.

My 'CI' pipeline:
```
trigger:
- branch-name
steps:
- script: echo 'Im  a trigger'
- publish: $(System.DefaultWorkingDirectory)
  artifact: WebApp
```

My 'CD' pipeline:
```
resources:
  pipelines: 
  - pipeline: _pipeline
    source: pipeline-name
    trigger: 
      branches: 
      - refs/heads/branch-name
trigger: none
```
It's not triggering 'CD' pipeline at all. Am I missing something?

Thanks,
Rafal
