### ISSUE TITLE
Variable parameters not expanding in template: ${{ }}

### ISSUE THREAD

**Issue by abelal83** [MicrosoftDocs/azure-devops-docs#8615]
When I use this code to conditionally run template it works fine

```yml 
parameters:
  Type: <valuefedfrompipeline.yml> # value is terraform

 - ${{ if eq(parameters.Type, 'terraform') }}:
    - template: /builds/${{ parameters.Type }}/build.yml
```

However, when I do this and attempt to run

```yml 
parameters:
  CheckoutDirectory: '$(System.DefaultWorkingDirectory)'
  Type: <valuefedfrompipeline.yml> # value is terraform

 - ${{ if eq(parameters.Type, 'terraform') }}:
    - template: ${{ parameters.CheckoutDirectory }}/builds/${{ parameters.Type }}/build.yml
```
I get this error

/build.yml: File /$(System.DefaultWorkingDirectory)/builds/terraform/build.yml not found in repository....

It appears if any variables are used for CheckoutDirectory value template is not able to expand the value. 

From my testing the problem appears to be ${{ }} is unable to expand any values that contain $(somevar) as their value.  Is this expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
