### ISSUE TITLE
Coverlet sample does not work

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/azure-devops-docs#8644]
The example code

```
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
    publishTestResults: true
    projects: '**/test-library/*.csproj' # update with your test project directory

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml
```

results in a error

> ##[warning]No code coverage results were found to publish.

My test project references `<PackageReference Include="coverlet.collector" Version="1.2.0" />`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#run-your-tests)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
