### ISSUE TITLE
Examples for passing arguments to powershell script are incorrect

### ISSUE THREAD

**Issue by dakimaz** [MicrosoftDocs/azure-devops-docs#8704]
I wanted to change my `inline` powershell task to `filepath` task instead.
In the documentation it is stated that arguments are used like so:

> (Optional) Arguments passed to the Powershell script.
> For example, -Name someName -Path -Value "Some long string value"
> 
> Note: unused when Type is inline.

I made the following powershell script to update the source path of a code coverage file:

```
param ($filename, $newpath)
$xml=New-Object XML
$xml.Load($filename)
$sourceNode = $xml.GetElementsByTagName('source').Item(0);
$sourceNode.innerText = $newpath
$xml.Save($filename)
```

Called it like this in the pipeline:

```
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\ci\scripts\update_code_cov_source_path.ps1
        arguments: |
          -filename "$(System.DefaultWorkingDirectory)\code_coverage\CoverageResults.xml"
          -newpath "$(System.DefaultWorkingDirectory)\project\src"
      displayName: 'Update Path For Project Code Coverage'
```

And I get the following error when executing the pipeline:

> -newpath : The term '-newpath' is not recognized as the name of a cmdlet, 
> function, script file, or operable program. Check the spelling of the name, or 
> if a path was included, verify that the path is correct and try again.
> At D:\builds\a2\_temp\95478eee-657b-412a-a701-4dd1d0711597.ps1:3 char:1
> + -newpath "D:\builds\a2\8\s\project\src"

Calling the powershell script locally:

`PS C:\work\ci\scripts> .\update_code_cov_source_path.ps1 -filename "C:\work\CoverageResults.xml" -newpath "woo"`
Works.

Also, changing the pipeline task to:

```
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\ci\scripts\update_code_cov_source_path.ps1
        arguments: |
          "$(System.DefaultWorkingDirectory)\code_coverage\CoverageResults.xml"
          "$(System.DefaultWorkingDirectory)\project\src"
      displayName: 'Update Path For Project Code Coverage'
```
~~Fixes the issue~~. The task didn't fail, but it produced empty files. 

It appears that you cannot use the pipe symbol `|` for arguments the same way you can with the `script` task. That's too bad since "one-linening" it can become pretty unreadable.

This works:

```
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\ci\scripts\update_code_cov_source_path.ps1
        arguments: -filename $(System.DefaultWorkingDirectory)\code_coverage\CoverageResults.xml -newpath $(System.DefaultWorkingDirectory)\project\src
      displayName: 'Update Path For Project Code Coverage'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This is related to how YAML deals with different forms of multiline strings. You could use `>` instead of `|` to have YAML ignore the inline newlines:

```yaml
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\ci\scripts\update_code_cov_source_path.ps1
        arguments: >
          -filename "$(System.DefaultWorkingDirectory)\code_coverage\CoverageResults.xml"
          -newpath "$(System.DefaultWorkingDirectory)\project\src"
      displayName: 'Update Path For Project Code Coverage'
```
