### ISSUE TITLE
Example showing how to use secret variables is confusing

### ISSUE THREAD

**Issue by plastikfan** [MicrosoftDocs/azure-devops-docs#8710]
[Enter feedback here]

I'm trying to figure out how to correctly define secret variables (from Library groups) and use them in a pipeline. The eamples shown here are too confusung because they include code that does work with code that does not work, all mixed together in the same example. Please consider re-writing and making it clear.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@plastikfan Thanks for your feedback. Could you point to which secret variable examples you are having trouble getting working?

**Comment by plastikfan** [comment]
The following quoted from your page:

```
variables:
 GLOBAL_MYSECRET: $(mySecret) # this will not work because the variable needs to be mapped as env
 GLOBAL_MY_MAPPED_ENV_VAR: foo # this will not work because the variable needs to be mapped as env

steps:

- powershell: |
    # Using an input-macro:
    Write-Host "This works: $(mySecret)"

    # Using the env var directly:
    Write-Host "This does not work: $env:MYSECRET"

    # Using the env var through the variables mapping will not work:
    Write-Host "This does not work either: $env:GLOBAL_MYSECRET"

    # Using the global var mapped in the pipeline. It is not a secret var:
    Write-Host "This works: $env:GLOBAL_MY_MAPPED_ENV_VAR" 

    # Using the mapped env var:
    Write-Host "This works: $env:MY_MAPPED_ENV_VAR"    # Recommended

  env:
    MY_MAPPED_ENV_VAR: $(mySecret) # right way to map to an env variable
```

is too confusing.

Please split this out into a full example with all code the works and an another example with error scenarios. This is just a mess as it stands
