### ISSUE TITLE
Can resource triggers be used for Pull Request builds?

### ISSUE THREAD

**Issue by sonofhammer** [MicrosoftDocs/azure-devops-docs#8712]
I'm trying to trigger one pipeline after another for ALL branch builds, including Pull request builds.

my pipeline looks like this
``` yml
resources:
  pipelines:
  - pipeline: product
    source: ProductsCI
    branch: master
    trigger:
      branches:
        include:
        - '*'
```

And this triggers on `master` and other branches successfully. But it does not trigger on any pull request builds.

Is there a way to trigger one pipeline after another on a pull request build?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**
