### ISSUE TITLE
runOnce YAML snippet includes a pool vmImage, but no azure-agent pool is used.

### ISSUE THREAD

**Issue by VictorioBerra** [MicrosoftDocs/azure-devops-docs#8720]
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/deploy-linux-vm?view=azure-devops&tabs=java#define-cd-steps-to-deploy-to-the-linux-vm

> Below is an example YAML snippet for runOnce :

```yaml
jobs:
- deployment: VMDeploy
  displayName: web
  pool: # <-----------------------------------
    vmImage: 'Ubuntu-16.04' # <-----------------------------------
  environment:
    name: <environment name>
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment
```

Unless I am misunderstanding, `environment:` will deploy to VM resources defined in the environment, these exist as deployment pool agents behind the scenes right? Then what is the purpose of `vmImage: 'Ubuntu-16.04'`?

Can someone correct me if I am wrong? `- script: echo my first deployment` will not run on 'Ubuntu-16.04'. The echo statement will run on whatever azagent lives on whatever pool is attached to whatever environment named `<environment name>`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61d73b50-b26b-3e9e-e8c2-37669424793c
* Version Independent ID: ebde85d2-1f0a-afa8-0597-d084c2b64870
* Content: [Deploy to a Linux VM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/deploy-linux-vm?view=azure-devops&tabs=java)
* Content Source: [docs/pipelines/ecosystems/deploy-linux-vm.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/deploy-linux-vm.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by juliakm** [comment]
Hi @VictorioBerra. You're right and I've updated that example. The update should be live shortly. 

For virtual machines, you do not need to define a pool. Any steps that you define in a deployment job with a virtual machine resource will run against that virtual machine and not against the agent in the pool. For other resource types such as Kubernetes, you do need to define a pool so that tasks can run on that machine.

This code example comes from a working pipeline. 

```yaml
  - deployment: VMDeploy
    displayName: web
    environment:
      name: <environment name>
      resourceType: VirtualMachine
      tags: web1
    strategy:
      runOnce:
         deploy:
           steps:
           - script: echo my first deployment
```
