### ISSUE TITLE
Is System.Debug Available in templates

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/azure-devops-docs#8740]
For System.Debug it is not defineid if this variable is Available in templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@ChrisBlankDe Thank you for the question.

Use of the term `many pre-defined variables` is used in the [templates](https://docs.microsoft.com/azure/devops/pipelines/process/templates?view=azure-devops) article is unfortunately somewhat vague when referring to variable [System.Debug](https://docs.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemdebug).

Assigning this to the author for further clarification.

Its use has previously been described in [this post](https://developercommunity.visualstudio.com/content/problem/862950/systemdebug-variable-seems-to-evaluate-to-null-whe.html), however please contact the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html) if there are any issues with its use.

**Comment by juliakm** [comment]
I apologize for the delay in answering this question. You can add `system.debug` to a template. Here's an example parameters.yml YAML:

```yaml
# parameters.yml
parameters:
- name: doThing
  default: true # value passed to the condition
  type: boolean

variables:
  system.debug: 'true'

jobs:
  - job: B
    steps:
    - script: echo I did a thing
    condition: and(succeeded(), eq('${{ parameters.doThing }}', 'true'))
```

And, here's the azure-pipelines.yml file. 
parameters:
- name: doThing
  default: true # will not be evaluated in time
  type: boolean

extends:
  template: parameters.yml
```
I'll make this clearer in the article.

**Comment by karpikpl** [comment]
@juliakm I'm not sure if your answer shows how to use `system.debug` in templates.

Something like this should (?) work when "diagnostics" checkbox is checked, but it doesn't:

```yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- ${{ if eq(lower(variables['system.debug']), 'true') }}:
  - script: echo 'Debug is true'
    displayName: Debug with variables['system.debug']

- ${{ if eq(lower(variables['SYSTEM_DEBUG']), 'true') }}:
  - script: echo 'Debug is true'
    displayName: Debug with variables['SYSTEM_DEBUG']

- ${{ if eq(variables.SYSTEM_DEBUG, 'true') }}:
  - script: echo 'Debug is true'
    displayName: Debug with variables.SYSTEM_DEBUG

- ${{ if eq(coalesce(variables.SYSTEM_DEBUG, 'false'), 'true') }}:
  - script: echo 'Debug is true'
    displayName: Debug with variables.SYSTEM_DEBUG with coalesce
```
