### ISSUE TITLE
PIP_EXTRA_INDEX_URL from PipAuthenticate@1

### ISSUE THREAD

**Issue by jeanveau** [MicrosoftDocs/azure-devops-docs#8750]
[Enter feedback here]
Hello Devops team,

I have an issue about consuming uploaded python package from artifacts.

The package is installed by `pip install <packagename>`, as the artifact is private, I tried to generate my PAT in azure, and pass it to pip by add `--extra-index-url https://{name}:{PAT}@pkgs.dev.azure.com/abakame/Abaka/_packaging/<organization_name>/pypi/simple` and everything was fine, the authentication succeed and the package was installed correctly.

But when I try it within the pipeline by using task `PipAuthenticate@1`, I can't find the package anymore, while `PipAuthenticate@1` worked but the PIP_EXTRA_INDEX_URL returned by the task was not what I expected.

The generated url is on domain `<organization_name>.pkgs.visualstudio.com` instead of `dev.azure.com`.

I'm not sure if the problem was caused by domain name, but it's the only difference I can found so far.

here is my pipeline:
```yaml
        steps:
          - task: PipAuthenticate@1
            displayName: pip authentication
            inputs:
             artifactFeeds: $(artifactFeed)
             onlyAddExtraIndex: True
          - task: Docker@2
            displayName: building image
            inputs:
              containerRegistry: $(containerRegistrySerivce)
              repository: $(imageName)
              tags: $(RELEASE_VERSION)
              command: build
              Dockerfile: $(dockerfile)
              arguments: --build-arg PIP_EXTRA_INDEX_URL=$(PIP_EXTRA_INDEX_URL)
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
```

In the setting of my artifact feed, the user Project Build Collection Service has permission contributor
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77227c6d-c042-d4b9-9801-ecb3547e1c33
* Version Independent ID: af8571a9-604a-6cf7-43ea-a714c42b95e7
* Content: [Python Pip Authenticate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/pip-authenticate?view=azure-devops#versions)
* Content Source: [docs/pipelines/tasks/package/pip-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/pip-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
