### ISSUE TITLE
Add sample using variable group in a deployment stage

### ISSUE THREAD

**Issue by tomkuijsten** [MicrosoftDocs/azure-devops-docs#8755]
I am trying for 8 hours now and I can't get the variable group working on deployment level. In short:

This doesn't work:

```yaml

# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: $(Build.Repository.Name) $(GitVersion.FullSemVer)

variables:
 - name: appResourceName
   readonly: true
   value: 'LonWeuConHub'

<other stuff>

.....

 - stage: deploy_to_azure_staging
   variables:
    - group: deployment-staging # DOESN'T WORK
    displayName: 'Deploy to Azure Staging'
    dependsOn: build_and_test
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: azure_deploy_staging
        displayName: Deploy to staging
        environment: Staging
        strategy:
          runOnce:
            deploy:
              steps:
                - template: azure-pipelines-deploy.yml
                  parameters:
                    subscriptionName: '$(subscriptionName)'
                    appResourceName: '$(appResourceName)'
```
However, if I move the  variable group up to the root level, like this:

```yaml
# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: $(Build.Repository.Name) $(GitVersion.FullSemVer)

variables:
 - group: deployment-staging # UP HERE IT WORKS
 - name: appResourceName
   readonly: true
   value: 'LonWeuConHub'

<other stuff>

 - stage: deploy_to_azure_staging
    displayName: 'Deploy to Azure Staging'
    dependsOn: build_and_test
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: azure_deploy_staging
        displayName: Deploy to staging
        environment: Staging
        strategy:
          runOnce:
            deploy:
              steps:
                - template: azure-pipelines-deploy.yml
                  parameters:
                    subscriptionName: '$(subscriptionName)'
                    appResourceName: '$(appResourceName)'
```

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**
