### ISSUE TITLE
"Push/Publish a package to a feed in the same organization you define in the task" YAML sample throws warnings in console.

### ISSUE THREAD

**Issue by VictorioBerra** [MicrosoftDocs/azure-devops-docs#8767]
```yaml
# Push a project
- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'select'
    vstsFeed: 'my-project/my-project-scoped-feed'
    publishVstsFeed: 'myTestFeed'
```

Results in:

`##[warning]Required argument (Feed) is missing.`

![image](https://user-images.githubusercontent.com/2934507/86391403-5e67d700-bc5f-11ea-9e24-182aef62a6a4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
