### ISSUE TITLE
How to trigger pipeline on dockerhub push?

### ISSUE THREAD

**Issue by tehho** [MicrosoftDocs/azure-devops-docs#8831]
"An error occurred while loading the YAML build pipeline. 'image' key is not defined for Docker hub container resource: argocd"
Trying to trigger a azure devops pipeline from an external dockerhub repositiory.

```yaml
resources:
  -containers:
    - container: tools
      type: ACR
      azureSubscription: example
      resourceGroup: containerRegistry
      registry: crExample
      repository: tools
      trigger:
        tags:
          include:
          - "*"

    - container: argocd
      type: Docker
      azureSubscription: argoproj
      registry: argoproj
      repository: argocd
      trigger:
        tags:
          include:
            - "v*"
```
First container works and triggers the pipeline correctly but the second does not.
How to fix? Could you also make an example on this site.

Use case:
We append our tools to the argocd image in a custom dockerfile. Would like to automate the release for when argocd does a release or when we rebuild our tools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
