### ISSUE TITLE
Schema for object parameters

### ISSUE THREAD

**Issue by pinkfloydx33** [MicrosoftDocs/azure-devops-docs#8870]
Is it possible to set the schema/data types for object parameters? It is possible to set a default value, but is there a way to suggest the shape of the object? 

Take the example from the documentation:

```yaml
- name: myObject
  type: object
  default:
    foo: FOO
    bar: BAR
    things:
    - one
    - two
    - three
```

I would envision something like this:

```yaml
- name: myObject
  type: object
  default:
  - name: foo
    type: string
    default: FOO
  - name: bar
    type: string
    default: BAR
  - name: things
    type: string
    values:
    - one
    - two
    - three 
    default:
    - one
    - two 
    - three 
```
I realize this won't work though as the parser wouldn't know if you were definining the schema or if this was the exact object that should be the default of `myObject` (ie that object now includes a sequence of `name`/etc objects). 

Is there a way to do this, and if so can the docs be updated to reflect? Many of my parameters are objects with sub settings. I do this for organizational purposes but it also makes it easier to override only specific *groups* of settings (ie pass-thru an object of the same schema from a calling template). 

The one thing preventing me from switching to typed parameters is that it's not going to gain me much in most places if I cannot define the schema for an object type. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
