### ISSUE TITLE
Docker Daemon Running?

### ISSUE THREAD

**Issue by poochwashere** [MicrosoftDocs/azure-devops-docs#8916]
I followed the instructions detailed on this page to a T. My VMSS agent pool is up and running with the latest agents installed. However, when I run my pipeline builds and I hit a stage that uses `docker` such as the task below, I get the error `docker: command not found`.  I am not attempting to run "docker in docker" as I trying to run docker on the VM with the agent installed. 

What am I missing here? Is docker installed along with the agent or is that an additional process? 

Cheers!

```
- task: Docker@2
            displayName: "Build and Push PR image"
            inputs:
              containerRegistry: myrepo
              command: "buildAndPush"
              Dockerfile: "Dockerfile"
              repository: "$(repo)"
              tags: "$(tag)"
            condition: succeeded()
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
