### ISSUE TITLE
Loop through values from parameters?

### ISSUE THREAD

**Issue by spowser** [MicrosoftDocs/azure-devops-docs#8945]
```
parameters:
- name: services
  type: string
  default: service1
  values:
  - service1
  - service2
  - service3
  - service4

trigger: none

jobs: 
- job: PrintServices
  steps:
  - ${{ each service in parameters.services.values }} #not sure what to do here?
    - powershell: |
        Write-Host "Service Name: ${{ service }}"
```

Using the above as an example, is there valid syntax to loop through the allowed values in a parameter?  I have a use case where a user can select 1 service but the default will be to run all the services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
