### ISSUE TITLE
Example does not work - colon is missing

### ISSUE THREAD

**Issue by raspe88** [MicrosoftDocs/azure-devops-docs#8962]
At https://docs.microsoft.com/en-us/azure/devops/pipelines/security/templates?view=azure-devops#use-extends-templates
in the first example it is written:

``` yml
# template.yml
parameters:
- name: usersteps
  type: stepList
  default: []
steps:
- ${{ each step in parameters.usersteps }}
  - ${{ step }}
```

This will not work because the line `- ${{ each step in parameters.usersteps }}` is missing a colon at the end. The example should be:

``` yml
# template.yml
parameters:
- name: usersteps
  type: stepList
  default: []
steps:
- ${{ each step in parameters.usersteps }}:
  - ${{ step }}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f721e2df-f7e4-8db7-08cc-eab779477c99
* Version Independent ID: 95014030-e9eb-6425-2990-8f9fa2452e7e
* Content: [Security through templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/security/templates?view=azure-devops)
* Content Source: [docs/pipelines/security/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/security/templates.md)
* Product: **devops**
* Technology: **devops-cicd-security**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
