### ISSUE TITLE
WorkingDirectory in gulp@1 taks doesn't working as expected

### ISSUE THREAD

**Issue by bpelikan** [MicrosoftDocs/azure-devops-docs#8980]
I'm trying use `workingDirectory` in `gulp@1` taks:
```yml
- task: gulp@1
  displayName: 'Run gulp tasks'
  inputs:
    workingDirectory: $(workingDirectory)
```
but I always get this error:
```bash
Starting: Run gulp tasks
==============================================================================
Task         : gulp
Description  : Run the gulp Node.js streaming task-based build system
Version      : 1.166.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/gulp
==============================================================================
##[error]Unhandled: Not found gulpFile: /home/vsts/work/1/s/gulpfile.js
Finishing: Run gulp tasks
```
This looks like `workingDirectory` was not taken into account, because there should be `/home/vsts/work/1/s/$(workingDirectory)/gulpfile.js`
Instead using this is working fine:
```yml
- task: gulp@1
  displayName: 'Run gulp tasks'
  inputs:
    gulpFile: '$(workingDirectory)/gulpfile.js'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f19b029-4ee8-9a2f-10b2-55d691c89e69
* Version Independent ID: 69566433-f3be-a902-082d-2ed935cb2b63
* Content: [Gulp build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gulp?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/gulp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/gulp.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
