### ISSUE TITLE
Pipelines erroneously execute based on tag creation in dependent resource repositories

### ISSUE THREAD

**Issue by hoffmanntravis** [MicrosoftDocs/azure-devops-docs#9003]
Hello,

This is in regards to the documentation below with regard to triggers, and a deviation of expected behavior as documented:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-repositories

Expected behavior as stated in documentation:
trigger:  # CI trigger for this repository, no CI trigger if skipped (only works for Azure Repos)
I would expect no triggered release / run

Actual behavior:
When a tag is created in the dependent repository, all pipelines that reference that repository create erroneous 'releases' that point at the commit hash of the dependent repository (and naturally does not exist in the pipeline linked repository).  This creates a series of failed and pointless 'releases / runs'.  The trigger cause is cited as 'Individual CI for' [tagname] [commithash]

Code we have defined.  Note the absence of any trigger reference:

```
resources:
  repositories:
    - repository: Automation.Templates
      type: git
      name: Automation.Templates
      ref: refs/tags/Deploy/v1.0.0

```
Thanks,
Travis
