### ISSUE TITLE
stageDependencies example is incorrect

### ISSUE THREAD

**Issue by johncrim** [MicrosoftDocs/azure-devops-docs#9050]
I wasted a bunch of time because this stageDependencies example is incorrect:

```yaml
- stage: B
  condition: and(succeeded(), ne(dependencies.A.A1.outputs['printvar.skipsubsequent'], 'true'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo hello from Stage B
  - job: B2
    condition: ne(stageDependencies.A.A1.outputs['stagevar.stageexists'], 'true')
    steps:
     - script: echo hello from Stage B2
```

Fortunately this github comment provides excellent info about what works and doesn't:
https://github.com/microsoft/azure-pipelines-tasks/issues/4743#issuecomment-643469964

Bottom line - it should be:

```yaml
- stage: B
  condition: and(succeeded(), ne(dependencies.A.outputs['A1.printvar.skipsubsequent'], 'true'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo hello from Stage B
  - job: B2
    condition: ne(stageDependencies.A.outputs['A1.stagevar.stageexists'], 'true')
    steps:
     - script: echo hello from Stage B2
```

Note that I was able to make the `stageDependencies.StageName.JobName.outputs(StepName.VariableName)` syntax work for a job condition, but not for a stage condition.

For a stage condition, but syntax is: `stageDependencies.StageName.outputs(JobName.StepName.VariableName)`. Fortunately the new docs help explain this structure (thanks!), but this leftover example is still incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
