### ISSUE TITLE
Pass tags (with spaces) to an ARM template using Azure Devops Pipeline

### ISSUE THREAD

**Issue by brucedkyle** [MicrosoftDocs/azure-devops-docs#9051]
I am using Azure DevOps Pipelines to deploy an ARM template. How do you pass tags into AzureResourceManagerTemplateDeployment@3

The long story is:

My template has a tags parameter that I pass into the pipeline using AzureResourceManagerTemplateDeployment@3.

My ARM template has a value in parameters section as an object:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "resourceTags": {
            "type": "object",
            "defaultValue": {
                "application": "coolapp",
                "owner": "Bill Contoso"
            }
        }
```
I am using ubuntu-latest for my pool. Tags may have spaces.

In my pipeline for simplicity, I set the tags to a variable.
```
pool:
  vmImage: 'ubuntu-latest'
variables:
  - name: tags
    value: ("Location Region=West US 2" "Environment=${{ parameters.environment }}")
```
When I call the template deployment, I am passing in the tags as an overrideParameters
```
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: "Deploy my templateaccount"
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'ResourceManager-connection'
      subscriptionId: ${{ parameters.subscriptionid }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'
      location: '${{ parameters.location }}'
      templateLocation: 'Linked artifact'
      csmFile: 'mytemplatelocation/azuredeploy.json'
      overrideParameters: '-location ${{ parameters.location }} -resourceTags $(tags)'
      deploymentMode: 'Incremental'
      deploymentOutputs: resourceOutput
  - pwsh: Write-Output '$(resourceOutput)'
```
So far I have not understood how AzureResourceManagerTemplateDeployment@3 on Ubuntu is expecting the tags to be sent.

In each case, the template fails to deploy.

Is this scenario supported in Azure DevOps Pipeline?

**Comment by ToMakeSense** [comment]
You should firstly verify the ARM template in visual studio, then try to get the resource deployed in a dev/sandbox eqnvironment via visual studio, if failed, figure out the error message in the outputs. when it pass, try to get the next resource deployed(it may also be ARM deployment or other, let's say, powershell), when all your deployment in your local environmnet done, try to migrate and link the same tasks in Azure DevOps. it saves most of your time.

Jump to this question, you need first get the ARM template deployed in your local environtment to figure out the tag related failure. if it works well in local deployment, it turns to Azure DevOps's problem.

**Comment by brucedkyle** [comment]
Thanks so much for your quick answer Kevin. I think I need an example that is clearer.
My question What does `AzureResourceManagerTemplateDeployment@3` expect for me to pass in `overrideParameters`  to  deploy a tag?

Try the following example template. Save as `example.azuredeploy.json`

```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "resourceBaseName": {
      "type": "string",
      "metadata": {
        "description": "Specifies the name of the resource, including its prefix."
      }
    },
    "resourceTags": {
      "type": "object",
      "defaultValue": {
        "Cost Center": "Admin"
      }
    }
  },
  "resources": [
    {
      "apiVersion": "2019-06-01",
      "kind": "StorageV2",
      "location": "[resourceGroup().location]",
      "name": "[parameters('resourceBaseName')]",
      "properties": {
        "supportsHttpsTrafficOnly": true
      },
      "sku": {
        "name": "Standard_LRS"
      },
      "type": "Microsoft.Storage/storageAccounts",
      "tags": "[parameters('resourceTags')]"
    }
  ]
}
```
The deployment works as expected in PowerShell

```
New-AzResourceGroup  -Name myResourceGroup   -Location "Central US"
$templateFile = ".\example.azuredeploy.json"
$tags = @{ "Cost Center" = "DevTest"; "Location"="West US 2" }
New-AzResourceGroupDeployment  -Name StorageAccountExample  -ResourceGroupName myResourceGroup  -TemplateFile $templateFile -resourceName "abcdef738920" -resourceTags $tags
```
However when I run the following AzDevOps Pipeline, the deployment fails.

```
parameters:
  - name: 'subscriptionID'
    displayName: 'Subscription ID (a GUID)'
    type: string
    default: '9f241d6e-16e2-4b2b-a485-cc546f04799b'
  - name: 'resourceGroupName'
    displayName: 'Resource Group Name'
    type: string
    default: "myResourceGroup"

pool:
  vmImage: 'ubuntu-latest'
variables:
  - name: tags
    value: ("Location Region=West US 2" "Environment=dev")
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'ResourceManager-connection'
    subscriptionId: ${{ parameters.subscriptionid }}
    location: 'west us 2'
    templateLocation: 'Linked artifact'
    csmFile: 'storageaccount/example.azuredeploy.json'
    overrideParameters: '-resourceName abcie3777032 -resourceTags ${{ variables.tags }}'
    deploymentMode: 'Incremental'
```
Error is ##[error]Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Object'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.

What is the right syntax for me to pass in `tabs` into my Ubuntu build machine?
And failing that.. what is the work around?

Many thanks.

**Comment by ToMakeSense** [comment]
@brucedkyle I would like to use **ARM template** + multiple **ARM template parameter** files for deployment(see screenshot below). it's much simple to edit JSON than get it work via terminal. more important, it's persistent and you can use it over and over again. you can refer [Add parameter files](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-tutorial-use-parameter-file?tabs=azure-powershell#add-parameter-files) and [Example 1: Use a custom template and parameter file to create a deployment](https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azresourcegroupdeployment?view=azps-4.5.0#example-1--use-a-custom-template-and-parameter-file-to-create-a-deployment) for this kind of deployment.
![image](https://user-images.githubusercontent.com/6244148/90155367-ce6c8f80-ddbd-11ea-95a9-320b2676c512.png)

The parameter file sample that matches your ARM template
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "resourceName": {
      "value": "myResourceGroup"
    },
    "resourceTags": {
      "value": {
        "Cost Center": "DevTest",
        "Location": "West US 2"
      }
    }
  }
}
```

I used classical UI for Azure resource deployment, In this mode,  you are able to select your ARM template and template file from your source Repo.  and you can see the YAML content in the right top of this page. **It's also possible to override template parameters**. 
![image](https://user-images.githubusercontent.com/6244148/90159373-e1ce2980-ddc2-11ea-9a97-5d00958f8a42.png)

The YAML file should look like this(see the `overrideParameters` part).

```
steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Subscription scope'
  inputs:
    deploymentScope: Subscription
    azureResourceManagerConnection: 'XXXXXXXXXXXXXXXXXX'
    subscriptionId: 'XXXXXXXXXXXXXXXXXX'
    location: west
    csmFile: Deployment/azuredeploy.json
    csmParametersFile: Deployment/azuredeploy.parameters.json
    overrideParameters: '-resourceName abcie3777032 -resourceTags {"Cost Center":"DevTest","Location":"West US"}'
```

**Comment by ToMakeSense** [comment]
In your second YAML example(the Azure DevOps pipeline), I see you use [Azure DevOps Variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) to pass the  ARM template parameters, it should be used like below I think (not 100% sure, for some reason, I can't run my Azure DevOps with Azure subscription, and I am not doing the deployment work for period of time, can't remember all the details).

```json
variables:
  tags: '{ "Cost Center": "DevTest", "Location": "West US 2" }'
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    XXXXXXXXXXX
    overrideParameters: '-resourceName -resourceTags $(tags)'
```

**Comment by brucedkyle** [comment]
YES. YES YES. 

Thanks to @ToMakeSense!!! Here's the full answer:

The format for the tags that worked in Azure DevOps pipeline `AzureResourceManagerTemplateDeployment@3` is to use JSON for your ARM Template objects, such as tags.

- Left curly bracket, colon separating the key value pairs, and comma separating the tags.
- Each key and the value in my case worked with quotes.
- A right curly bracket.

But following templates works by passing in a JSON object: `{"Cost Center":"DevTest","Location":"West US"}` as your template parameter. In context this looks like:

```
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ResourceManager-connection'
    subscriptionId: 'XXXXX'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-wus2-exampletest'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'storageaccount/example.azuredeploy.json'
    csmParametersFile: 'storageaccount/azuredeploy.parameters.json'
    overrideParameters: '-resourceName oweruhsow -resourceTags {"Cost Center":"DevTest","Location":"West US"}'
    deploymentMode: 'Complete'
```

This Pipeline module is expecting JSON objects, not the same format used elsewhere with PowerShell (https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resource) to deploy from the command line. 

Also as a side note, other posts suggested that you name use something other than `tags` for your tags parameter. The one that worked for me is `resourceTags`. Here is my ARM template:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "resourceName": {
      "type": "string",
      "metadata": {
        "description": "Specifies the name of the resource"
      }
    },
    "location": {
      "type": "string",
      "defaultValue": "[resourceGroup().location]",
      "metadata": {
        "description": "Location for the resources."
      }
    },
    "resourceTags": {
      "type": "object",
      "defaultValue": {
        "Cost Center": "Admin"
      }
    }
  },
  "resources": [
    {
      "apiVersion": "2019-06-01",
      "kind": "StorageV2",
      "location": "[parameters('location')]",
      "name": "[parameters('resourceName')]",
      "properties": {
        "supportsHttpsTrafficOnly": true
      },
      "sku": {
        "name": "Standard_LRS"
      },
      "type": "Microsoft.Storage/storageAccounts",
      "tags": "[parameters('resourceTags')]"
    }
  ]
}

```

If you want to set your template object as a the variable, you then can pass it in using the DevOps variable such as `$(tags)`:

```
variables:
  tags: '{"Cost Center":"DevTest","Location":"West US"}'
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ResourceManager-connection'
    subscriptionId: 'XXXXXX
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-wus2-exampletest'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'storageaccount/example.azuredeploy.json'
    csmParametersFile: 'storageaccount/azuredeploy.parameters.json'
    overrideParameters: '-resourceName oweruhso11w -resourceTags $(tags)'
    deploymentMode: 'Complete'
```

Also (as a side note), and THANK YOU @ToMakeSense,  for some reason, the module needed to have a `csmParametersFile` or it would just fail with something about failing with `RESOURCEGROUP` in all caps. The param file is not needed to deploy from the command line, but Pipelines modules does seem to require it.
A `csmParamters` file that can have just about nothing in it, but it seems to be needed.

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": { }
  }
```

This also works using the `pool` `image: windows-latest` too.

THANK YOU!!! You unblocked me.
