### ISSUE TITLE
Can task DownloadPackage@1 be used to download dependency from Maven ?

### ISSUE THREAD

**Issue by neshant** [MicrosoftDocs/azure-devops-docs#9061]
https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-package.md

I am trying to download a dependency from Maven during the build phase. I am using DownloadPackage@1 task.

  ```
- task: DownloadPackage@1
    displayName: 'Download Datadog Agent'
    inputs:
      packageType: 'maven'
      feed: 'internal-azure-feed-name'
      definition: 'com.datadoghq:dd-java-agent'
      version: '0.59.0'
      files: '*.jar'
      downloadPath: '$(Build.SourcesDirectory)/datadog'
```

The artifact is not present in the feed so I am assuming it should try get it from upstream global maven.

https://repo.maven.apache.org/maven2/com/datadoghq/dd-java-agent/0.59.0/

Is that assumption correct?

However I get the following error in the pipeline.

> (node:3420) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Package with name com.datadoghq:dd-java-agent not found.

I am trying to figure out the right task for this job. Is DownloadPackage@1 the right thing to use for this? 
Or should I try something like UniversalPackage@0 ?
