### ISSUE TITLE
Parameter references are not expanded/resolved in variablesTemplate

### ISSUE THREAD

**Issue by moonrockfamily** [MicrosoftDocs/azure-devops-docs#9070]
variablesTemplate-JobSubService.yml
```yaml
parameters:
  - name: bannerExe
    type: string

variables:
  bannerExe: ${{ parameters.bannerExe }}
  bannerExeStage: ${{ join(parameters.bannerExe, 'Stage') }}
  bannerExeBackup: ${{ join(parameters.bannerExe, 'Backup') }}
```

pipeline-release.yml:
```yaml
name: Release
# Disable Source repository Trigger
trigger:
  - none

# The resources this pipeline depends on.
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#schema
resources:
  pipelines:
    - pipeline: BuildPipeline  # Name of this pipeline resource
      source: Build # Name of the triggering pipeline
      trigger: # See pipelineResourceTrigger definition
        branches:
          include:
            - refs/tags/deploy*

  - stage: GSB1
    condition: startsWith(variables['build.SourceBranchName'], 'deployGSB1')
    dependsOn: [] # no dependency
    variables:
      - group: database-variables-gsb1 
      - template: variablesTemplate-JobSubService.yml
        parameters:
          bannerExe: 'c:\Banner\gsb1\general\exe' 
    jobs:
      - template: jobsTemplate-MigrateDatabase.yml
      - template: jobsTemplate-DeployBannerJobs.yml
      - template: jobsTemplate-RestartJobSubService.yml
```

### Actual Template Expansion result snippet
```yaml
- stage: GSB1
  condition: >
    or(
      startsWith(variables['build.SourceBranchName'], 'deployGSB1'),
      startsWith(variables['build.SourceBranchName'], 'deployGEOR')
    )
  dependsOn: []
  variables:
  - group: database-variables-gsb1
  - name: bannerExe
    value: c:\Banner\gsb1\general\exe
  - name: bannerExeStage
    value: Stage
  - name: bannerExeBackup
    value: Backup
...
```
### Expected Template Expansion result snippet
```yaml
- stage: GSB1
  condition: >
    or(
      startsWith(variables['build.SourceBranchName'], 'deployGSB1'),
      startsWith(variables['build.SourceBranchName'], 'deployGEOR')
    )
  dependsOn: []
  variables:
  - group: database-variables-gsb1
  - name: bannerExe
    value: c:\Banner\gsb1\general\exe
  - name: bannerExeStage
    value: c:\Banner\gsb1\general\exeStage
  - name: bannerExeBackup
    value: c:\Banner\gsb1\general\exeBackup
...
```

**Comment by moonrockfamily** [comment]
### Work-around attempt

**Idea**: Nested template expansion.

#### variablesTemplate-JobSubService.yml
```yaml
#Caution: This likely isn't working as per https://github.com/MicrosoftDocs/azure-devops-docs/issues/9070
parameters:
  - name: bannerExe
    type: string

variables:
  bannerExe: ${{ parameters.bannerExe }}
  bannerExeStage: ${{ join('${{ parameters.bannerExe }}', 'Stage') }}
  bannerExeBackup: ${{ join('${{ parameters.bannerExe }}', 'Backup') }}
```

### Download logs archive
#### initializeLog.txt snippet
```yaml
Begin load: variablesTemplateReference
Begin evaluating template '/ci/azure/variablesTemplate-JobSubService.yml'
Evaluating: parameters['bannerExe']
Result: 'c:\Banner\GEOR\general\exe'
Evaluating: join('${{ parameters.bannerExe }}', 'Stage')
Result: 'Stage'
Evaluating: join('${{ parameters.bannerExe }}', 'Backup')
Result: 'Backup'
Begin transform: variables
Evaluating: value
Result: Object
Evaluating: pair['key']
Result: 'bannerExe'
Evaluating: pair['value']
Result: 'c:\Banner\GEOR\general\exe'
Evaluating: pair['key']
Result: 'bannerExeStage'
Evaluating: pair['value']
Result: 'Stage'
Evaluating: pair['key']
Result: 'bannerExeBackup'
Evaluating: pair['value']
Result: 'Backup'
End transform: variables
```
#### azure-pipelines-expanded.yml snippet
```yaml
  variables:
  - group: database-variables-gsb1
  - name: bannerExe
    value: c:\Banner\gsb1\general\exe
  - name: bannerExeStage
    value: Stage
  - name: bannerExeBackup
    value: Backup
```
