### ISSUE TITLE
Issue to trigger a pipeline when an update is pushed to repository declared as resource

### ISSUE THREAD

**Issue by dielenko** [MicrosoftDocs/azure-devops-docs#9095]
Greetings Team,

I am not able to use multi-repo triggers in Azure Pipelines. I am following the official documentation here: 
- https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#triggers
 
## Example of simple Azure Pipeline:
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: MultiCheckoutRepo
    type: git
    name: ProjectName/RepoName
    ref: main
    trigger:
    - main

variables:
 - group: 'Variable_Group_Name'

parameters:
  - name: System.Debug
    displayName: "Run System Debug"
    type: boolean
    default: True

stages:
- stage: Multi_Checkout_repo_Stage
  displayName: Multi Checkout Repo Stage

  pool:
    vmImage: 'ubuntu-latest'

  jobs:
    - job: List_Azure_Repos
      displayName: List Azure Repos

      steps:
      - checkout: self
      - checkout: MultiCheckoutRepo

      - script: dir $(Build.SourcesDirectory)
        displayName: 'Run dir to list sources'

    - job: One_line_script_Job
      displayName: One-line script Job

      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

    - job: Multi_line_script_Job
      displayName: Multi-line script Job
      dependsOn:  One_line_script_Job

      steps:
      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
          echo Get the variable value for Azure Resource Group from the ADO Library: $(Azure.ResourceGroupName)
        displayName: 'Run a multi-line script'
```
When I am pushing commit in the Azure Repo (all repos are in one project) described in the resource section of the YAML file nothing happens. According to the official documentation after a code change and push in that repository, the Azure Pipeline situated in self repo should trigger a new run.
I found that this feature was planned to be available to everyone by the end of July 2020. This is the Roadmap item:
- https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1454026

From my experience with this feature It is still not available.
May I ask for some assistance and information about that issue.
Thanks in advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Use multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
