### ISSUE TITLE
Purpose of 'pool' property in deployment job

### ISSUE THREAD

**Issue by Sidewinder53** [MicrosoftDocs/azure-devops-docs#9123]
I'm trying to grasp the concept behind the pool tag in deployment jobs for environments.

On which machine are steps inside a deployment job executed, when you specific both the environment and pool property?
For example, when deploying to a virtual machine, why would you want to specific the pool property in the first place? 
After all, deployment steps should be executed in the environment, not in the agent pool.

The documentation doesn't really explain any of that, and it appears that in practice, you must declare deployment jobs in the more extensive syntax to deploy to virtual machines:

Documentation suggests, that deployment jobs to environments should look like this:
```
- stage: Deploy
  jobs:
  - deployment: DeployApp
    environment: '<environment name>'
    strategy:
      runOnce:
        deploy:
        [...]
```
This tries to deploy to an unspecified agent:

> ##[warning]No valid image label found in agent specification.
> ,##[error]The remote provider was unable to process the request.
> Pool: Azure Pipelines

When using more extensive syntax, and additionally, specifying the resource type, deployments will be made to the correct environment:
```
environment:
  name: '<environment name>'
  resourceType: 'virtualMachine'
```

I would suggest to explain the purpose of the pool property inside deployment jobs and add examples how to deploy to environments with virtual machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Rereading and it looks like the pool may also be used for lifecycle hooks. I'm working on getting more information on this.

**Comment by juliakm** [comment]
@Sidewinder53 For virtual machines, you do not need to define a pool. Any steps that you define in a deployment job with a virtual machine resource will run against that VM and not against the agent in the pool. For other environments such as Kubernetes, you do need a pool because tasks run on that machine. I'll update the documentation to make this clearer. In the meantime, here's an example you can use for testing. Add a virtual machine to your test environment, `myenv` that is not Ubuntu 20.04 (the current version for the `ubuntu-latest` agent). 

```yaml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: myenv 
    resourceType: 'virtualMachine'
  strategy:
    runOnce:
      deploy:
       steps:
       - script: echo "Hello world!!"
       - script: cat /etc/lsb-release #outputs the Ubuntu version
```
