### ISSUE TITLE
Spaces are not handled as documented in PipAuthenticate@1/artifactFeeds

### ISSUE THREAD

**Issue by howardjones** [MicrosoftDocs/azure-devops-docs#9212]
The first example does not work as given. A space between the comma-separated feed names ends up in the feed URL.

```yaml
- task: PipAuthenticate@1
            displayName: Authenticate with artifact feed
            inputs:
              artifactFeeds: Platform/python-api-client, Platform/python-authentication-client
              onlyAddExtraIndex: false

- script: |
    echo $PIP_INDEX_URL
    echo $PIP_EXTRA_INDEX_URL
```

results in:

```
https://build:***@pkgs.dev.azure.com/MyOrg/Platform/_packaging/python-api-client/pypi/simple
https://build:***@pkgs.dev.azure.com/MyOrg/%20Platform/_packaging/python-authentication-client/pypi/simple
```

Note the %20 in the second URL!

Spaces should probably be trimmed by the task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77227c6d-c042-d4b9-9801-ecb3547e1c33
* Version Independent ID: af8571a9-604a-6cf7-43ea-a714c42b95e7
* Content: [Python Pip Authenticate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/pip-authenticate?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/pip-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/pip-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@howardjones  Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

A similar issue was reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/8533, an update to the documentation is pending review.

**Comment by steved0x** [comment]
I'm fixing this, the Task assistant puts single quotes around it, like this, and I have updated the documentation to address this.

```
- task: PipAuthenticate@1
  inputs:
    artifactFeeds: 'FabrikamFiber/DotnetDocsTools, fabrikam-tailspin'
    onlyAddExtraIndex: true
```
