### ISSUE TITLE
Missing npm file path in target folder

### ISSUE THREAD

**Issue by MarkAPhillips** [MicrosoftDocs/azure-devops-docs#9221]
How can I version my npm packages as part of the build process?

```
- task: CopyFiles@2
  inputs:
      contents: '*.tgz'
      targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy archives to artifacts staging directory'
```

should be:

```
- task: CopyFiles@2
  inputs:
      contents: '*.tgz'
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy archives to artifacts staging directory'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b2fdca-9125-9720-3d03-3c6dd336f100
* Version Independent ID: b2a24e28-9858-fe1c-4527-745f1f387e4e
* Content: [Build and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops&tabs=code)
* Content Source: [docs/pipelines/ecosystems/javascript.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/javascript.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
