### ISSUE TITLE
There should be an AzureCLI@2 file example

### ISSUE THREAD

**Issue by samsmithnz** [MicrosoftDocs/azure-devops-docs#9226]
There is only one, inline example. There should be a file example too:

```
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: <Name of the Azure Resource Manager service connection>
    scriptType: ps
    scriptLocation: 'MyScript.ps1'
    scriptPath: '$(build.artifactstagingdirectory)'
    arguments: '-myVariable myValue'

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by vromantp** [comment]
The following structure worked for me:

```
- task: AzureCLI@2  
  inputs:  
    azureSubscription: '<Name of the Azure Resource Manager service connection>'  
    scriptType: pscore  
    scriptLocation: scriptPath  
    scriptPath: '<Full path to .ps1 script>'
```
