### ISSUE TITLE
Stage to stage dependencies output fails

### ISSUE THREAD

**Issue by lmmarsano** [MicrosoftDocs/azure-devops-docs#9231]
The interface
```json
"dependencies": {
  "<STAGE_NAME>" : {
    "result": "Succeeded|SucceededWithIssues|Skipped|Failed|Canceled",
    "outputs": {
        "jobName.stepName.variableName": "value"
    }
  },
  "...": {
    // another stage
  }
}
```
presented for [stage to stage dependencies](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#stage-to-stage-dependencies) is incorrect.
This pipeline
```yaml
trigger:
- master

stages:
- stage: S0
  jobs:
  - job: J0
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: echo '##vso[task.setvariable variable=crosser;isOutput=true]'true
      name: output
- stage: S1
  variables:
    rtStage: $[dependencies.S0.outputs['J0.output.crosser']]
  jobs:
  - job: J0
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        echo output'
        'variable rtStage $(rtStage)'
        'environment rtStage $RTSTAGE
      name: jobAcrossStages
```
outputs nothing for the variables.
[Pipeline run log](https://dev.azure.com/humana-test/DevOps/_build/results?buildId=4087&view=results)
Variable expansion
```
Job preparation parameters
Variables:
  rtStage:
    Parsing expression: <dependencies.S0.outputs['J0.output.crosser']>
    Evaluating: dependencies['S0']['outputs']['J0.output.crosser']
    Expanded: Null
    Result: ''
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#stage-to-stage-dependencies)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cveld** [comment]
For us we would like to read out the result of a stage to store it into a state store. Currently we are not able to read out the stage results, we are only able to read out job results.

The following variable mounts:
```
variables:
      Result1: $[stageDependencies.mystage.result]
      Result2: $[stageDependencies.mystage.myjob.result]
      Result3: $[dependencies.mystage.result]
```

yield:
```
<null>
Succeeded
<null>
```

**Comment by lmmarsano** [comment]
> $(rtStage)

Thinking about this a bit more, I think a missed a subtlety of [macro expansion](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables#macro-syntax-variables).
Macro expansion gets
> processed before a task executes during runtime

by replacing
> the expression with the contents of the variable

its literal text I'm guessing.
In that case, at execution the pipeline replaces `$(rtStage)` & evaluates
```yaml
    steps:
    - bash: |
        echo output'
        'variable rtStage $[dependencies.S0.outputs['J0.output.crosser']]'
        'environment rtStage $RTSTAGE
      name: jobAcrossStages
```
a [job to job dependency across stages](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#job-to-job-dependencies-across-stages), which requires a different expression: no wonder it fails!
In that's so, perhaps Microsoft could clarify the variable documentation, because I didn't exactly get why we had 2 runtime syntaxes (`$()` and `$[]`) until now.
[Though this table might seem to say it](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#runtime-expression-syntax), setting a clear distinction between
- macro: expression/text **expansion**
- runtime expression: expression **execution**

would send it home for me.
