### ISSUE TITLE
How to access a variable defined in matrix strategy in expression?

### ISSUE THREAD

**Issue by congkun-ck** [MicrosoftDocs/azure-devops-docs#9255]
I want to define a new variable based on values defined in matrix strategy. However it looks neither compile time nor runtime expression could get the value correctly.

The following snippet wants to define two booleans exp1/exp2 based on whether 'configuration' is 'Release'. 'configuration' is defined in the matrix strategy.

``` 
- job: WindowsSampleApp
  displayName: 'Sample'
  strategy:
    matrix:
      Release x64:
        configuration: 'Release'
        platform: 'x64'
    maxParallel: 8
  continueOnError: false
  pool:
    vmImage: "windows-2019"
  workspace:
    clean: all
  timeoutInMinutes: 240
  variables:
    exp1: ${{ eq(variables.configuration, 'Release') }}
    exp2: $[ eq(variables.configuration, 'Release') ]
    raw1: ${{ variables.configuration }}
    raw2: $[ variables.configuration ]
    raw3: $(configuration)
  steps:
  - task: PowerShell@2
    displayName: 'Dump variable'
    inputs:
      targetType: inline
      script: |
        Write-Host "exp1:" $env:exp1
        Write-Host "exp2:" $env:exp2
        Write-Host "raw1:" $env:raw1
        Write-Host "raw2:" $env:raw2
        Write-Host "raw3:" $env:raw3

      errorActionPreference: 'stop'
      failOnStderr: true
```
Output:
```
exp1: False
exp2: False
raw1: 
raw2: 
raw3: Release
```

Any idea what is the right way to do this except also defining exp1/exp2 in matrix strategy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@congkun-ck Thank you for the question.

Note the support options in this forum are limited to documentation samples only.

Please cite an example below, otherwise move this issue to one of the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by brandonaut** [comment]
I think this is a documentation issue, since the docs don't specify what kind of variable is created in the [matrix build strategy](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#matrix):

```yaml
strategy:
  matrix: { string1: { string2: string3 } }
  maxParallel: number
```
> For each occurrence of string2, a variable called string2 with the value string3 is available to the job.

Is `string2` a compile-time variable, or a runtime variable?

**Comment by juliakm** [comment]
You can use macro syntax to access the variables within tasks in your pipeline. The value of the variables will change depending on where you are your matrix strategy.  I'm closing this issue again since the variables page has more information no accessing variables and this seems like an implementation issue. Here's an example YAML that references the `imageName` field in a matrix strategy. 

```yaml
pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SampleApp
  displayName: 'Sample'
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      windows: 
        imageName: 'windows-latest'

  steps:
  - script: |
      echo $(imageName)
```
