### ISSUE TITLE
Inconsistent examples for Yarn

### ISSUE THREAD

**Issue by sachinahya** [MicrosoftDocs/azure-devops-docs#9261]
The examples under [Key input](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#key-input) and [Restore keys](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#restore-keys) suggest adding `yarn` as one of the restore keys. 

```yaml
- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
       yarn
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages
```

This caused our builds to fail when we had multiple platforms as the CLI packages get built and cached for a specific OS and don't work when the cache is moved to a different OS.

The example in [Node.js/Yarn](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsyarn) section only has `yarn | "$(Agent.OS)"` which gets around this, as it ensures there is a cache entry for each OS and its platform-specific packages. I think the other two examples should be updated to match this.

```yaml
steps:
- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
