### ISSUE TITLE
Stage can be set to run based on a variable output in a previous stage.

### ISSUE THREAD

**Issue by ivanakcheurov** [MicrosoftDocs/azure-devops-docs#9306]
[Enter feedback here]

> You cannot currently specify that a stage run based on the value of an output variable set in a previous stage.

It is not true.
You **can** specify that a stage run based on the value of an output variable set in a previous stage.

```yaml
- stage: FirstStage
  jobs:
  - job: decide_what_to_run
    steps:
    - task: PowerShell@2
      name: trigger_stages
      inputs:
        targetType: 'inline'
        script: |
          Write-Output "##vso[task.setvariable variable=SecondStage_should_run;isOutput=true]true" 
- stage: SecondStage
  condition: eq(dependencies.FirstStage.outputs['decide_what_to_run.trigger_stages.SecondStage_should_run'], 'true')
  jobs:
  - job: do_something
    steps:
    - powershell: |
        Write-Output "I have been run" 
```

Please also check #8486 and #8366 and [Sprint-168-Update which states it is possible now](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-168-update#jobs-can-access-output-variables-from-previous-stages)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322215c-8025-4f21-0700-7dfa7dc5c46e
* Version Independent ID: 141fcdbb-8394-525b-bb29-eff9a693a9c4
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
