### ISSUE TITLE
Possible typo in sample scripts

### ISSUE THREAD

**Issue by Ozzian** [MicrosoftDocs/azure-devops-docs#9343]
Possible typo in sample scripts?

In windows sample, the AZURE_DEVOPS_CLI_PAT is not used in the script itself, but the $(System.AccessToken) is used...

```
- script: echo $(System.AccessToken) | az devops login
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
  displayName: 'Login Azure DevOps Extension'
```

vs on the linux and mac versions

```
- script: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
  displayName: 'Login Azure DevOps Extension'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9480b69-ca1f-55bc-8505-49c51d9f205e
* Version Independent ID: 03df29bf-108d-6ffc-bb3e-b29fb8a1e46c
* Content: [Azure DevOps CLI in Azure Pipeline YAML - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops)
* Content Source: [docs/cli/azure-devops-cli-in-yaml.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/azure-devops-cli-in-yaml.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@steved0x - could you take a look at this issue and resolve if possible?

**Comment by steved0x** [comment]
@Ozzian I am updating this article to use bash and a single pipeline vs the template approach that is there now. For the example that you mention, the correct yaml would be as shown in the following example, with the difference being the `%` vs `$` in the other examples, because `script` on Windows agents uses command line, vs bash on the other agent types.

```
- script: echo %AZURE_DEVOPS_CLI_PAT% | az devops login
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
  displayName: 'Login Azure DevOps Extension'
```
