### ISSUE TITLE
Predefined variables for repository resource trigger

### ISSUE THREAD

**Issue by sukoneck** [MicrosoftDocs/azure-devops-docs#9389]
When a pipeline is triggered by a [repository resource trigger ](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-repositories) I need to be able to determine metadata about the triggering repository (such as repo name and branch). 

It [sounds like these variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#variables) should be set during a pipeline run that was triggered by a repository resource; however, their values are empty when I do an `env | sort`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-pipelines)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by sukoneck** [comment]
FWIW, the predefined variables for `Build.Repository.Name` and `Build.SourceBranchName` now work as expected when used with a repository trigger. So, I'm no longer in need of `resources.triggeringAlias` and `resources.triggeringCategory`. However, [this section of this doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#variables) is still inaccurate.

**Comment by winstonhenke** [comment]
@sukoneck, I stumbled across this thread because I was having issues with the `resources.triggeringAlias` variable too. My issue ended up being something else with how I was using it and was able to use it like this to set a variable value conditionally

```yaml
variables:
  ${{ if eq( variables['resources.triggeringAlias'], 'gen-central-usa' ) }}: 
    myVar: 'some value'
  ${{ if ne( variables['resources.triggeringAlias'], 'gen-central-cdn' ) }}: 
   myVar: 'some other value'
```

**Comment by bruceharrison1984** [comment]
I'd also like to note that `variables['resources.triggeringCategory']` is not available when trying to define a root variable such as

```yml
  - name: TRIGGERED_BY_PIPELINE
    value: ${{ eq(variables['resources.triggeringCategory'], 'pipeline') }}
```
the `resources.triggeringCategory` is always null, and the value isn't set until you enter in to a job/stage

**Comment by mijacobs** [comment]
@juliakm, can you take a look at the doc and see if we should add additional explanation for resources.triggeringAlias and resources.triggeringCategory? 

variables:
  ${{ if eq( variables['resources.triggeringAlias'], 'homer' ) }}: 
    myVar: 'some value'
  ${{ if eq( variables['resources.triggeringAlias'], 'simpson' ) }}: 
   myVar: 'some other value'

**Comment by juliakm** [comment]
@winstonhenke Thanks for the example!

 @sukoneck `resources.triggeringAlias` and and `resources.triggeringCategory` are only set when your pipeline run initiates because of a resources trigger. Otherwise, those values will be blank even if you are using a resource in your pipeline. To test this, we can set up two pipelines where one triggers the other one. 

### First Pipeline: learn-triggers

Start a new pipeline from Azure Repos or GitHub. 

```yaml
# pipeline that will be triggered 
steps:
- script: printenv
- script: echo $(resources.triggeringAlias)
- script: echo $(resources.triggeringCategory) 
```

### Second Pipeline: resources

Create a second pipeline in a different repository. This is the pipeline that gets triggered

```yaml
resources:
  pipelines:
  - pipeline: testfromresources
    source: learn-triggers
    trigger:
      branches:
      - master 

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
```

When you run the `resources` pipeline, it will trigger the `learn-triggers` pipeline.  Open the learn-triggers pipeline after your run, and you should see the value `pipeline` for `triggeringCategory` and `testfromresources` for `triggeringAlias`. 

I'll work on getting a similar example in the docs.
