### ISSUE TITLE
Extends template does not render parameters

### ISSUE THREAD

**Issue by dduleep** [MicrosoftDocs/azure-devops-docs#9416]
I have tried to insert runtime param from simple-param.yml file same as [MS DOC](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters), 
The **"yesNo"** parameter in simple-param.yml file not render/view() into AzureDevOps 

![Azure DevOps Build pipeline](https://user-images.githubusercontent.com/14990589/95014918-d674dd00-0652-11eb-9cc8-0776f153a6ed.png)

```
# File: simple-param.yml
parameters:
  - name: yesNo # name of the parameter; required
    type: boolean # data type of the parameter; required
    default: false

steps:
  - script: echo ${{ parameters.yesNo }}

```

```
# File: azure-popelines.yml
name: DEMO

parameters:
  - name: demo-name# name of the parameter; required
    type: string # data type of the parameter; required
    default: xxx

extends:
  template: simple-param.yml
  parameters:
    yesNo: false # set to a non-boolean value to have the build fail
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
