### ISSUE TITLE
Mapped name for System.AccessToken

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/azure-devops-docs#9453]
For use of System.AccessToken in YAML, does the token need to be mapped to SYSTEM_ACCESSTOKEN, or can the name be customized?

For example, is the following form required?

```
steps:
  - powershell: Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

Or can we use a different environment variable name as follows?

```
steps:
  - powershell: Write-Host "This is a script that could use $env:MY_SPECIAL_TOKEN"
    env:
      MY_SPECIAL_TOKEN: $(System.AccessToken)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#server-jobs)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
