### ISSUE TITLE
Clarify when template parameters are actually parsed

### ISSUE THREAD

**Issue by PaulVrugt** [MicrosoftDocs/azure-devops-docs#9459]
The documentation doesn't state when template parameters are actually replace in the template. I always assumed they would be replace compile time (since inside the template the parameter expression (`${{`) is used) and for this type of expression the documentation states they are replaced compile time.

But recently I ran into a weird issue. I needed to pass a value to a template that is defined in a variable group. Now since the following works:

**Example 1:**
```
trigger: none

variables:
- name: VariablesTest
  value: "value1"

jobs:
 - template: TestTemplate.yaml
   parameters:
     parameter1: ${{ variables.VariablesTest }}
```

I would assume that the following also works:

**Example 2:**
```
trigger: none

variables:
- group: PaulTest #this contains the `VariablesTest` variable

jobs:
 - template: TestTemplate.yaml
   parameters:
     parameter1: ${{ variables.VariablesTest }}
```

However, this causes the parameter value to be empty. Strangely enough, the following DOES work:

**Example 3:**
```
trigger: none

variables:
- group: PaulTest #this contains the `VariablesTest` variable

jobs:
 - template: TestTemplate.yaml
   parameters:
     parameter1: $(VariablesTest)
```
I was under the impression that you could not use `$(` variables as parameter values, because they were expanded compile time, and `$(` variables are expanded at runtime. So I don't understand the rules here, and the documentation doesn't state anything about this. And if this last example works (which it does), why doesn't the second example also work? Since the documentation states you can use variables in template expressions as long as these variables are present when the pipeline is compiled, which, looking at the 3rd example, is also the case when they are added via a variable group.

I'm really confused as to how this all works, and the docs don't help me. Please explain it to me (and hopefully update the docs)

**Edit:**
I found [this doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline) stating:

> It also answers another common issue: why can't I use variables to resolve service connection / environment names? Resources are authorized before a stage can start running, so stage- and job-level variables aren't available. Pipeline-level variables can be used, but only those explicitly included in the pipeline. <ins>**Variable groups are themselves a resource subject to authorization, so their data is likewise not available when checking resource authorization**</ins>.

But this simply doesn't seem to be true, given that example 3 works. So now I'm even more confused

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
