### ISSUE TITLE
Incorrect schema for pipeline resource triggers

### ISSUE THREAD

**Issue by rcdailey** [MicrosoftDocs/azure-devops-docs#9484]
The schema for pipeline resources shows up as this:

```yml
resources:
  pipelines:
  - pipeline: string  # identifier for the pipeline resource
    project:  string # project for the build pipeline; optional input for current project
    source: string  # source pipeline definition name
    branch: string  # branch to pick the artifact, optional; defaults to all branches
    version: string # pipeline run number to pick artifact, optional; defaults to last successfully completed run
    trigger:     # optional; triggers are not enabled by default.
      branches:
        include: [string] # branches to consider the trigger events, optional; defaults to all branches.
        exclude: [string] # branches to discard the trigger events, optional; defaults to none.
```

The documentation concerning `trigger:` is incorrect based on errors I observe. Since everything under `trigger` is documented as optional, I attempted this:

```yml
resources:
  pipelines:
    - pipeline: my_resource
      source: My Pipeline
      branch: master
      trigger:
```

What I expected was:

* `trigger.branches.include` defaults to `refs/heads/*` (or however you've implemented it to "default to all branches").
* `trigger.branches.exclude` to default to empty (exclude no branches).

However, once I pushed this YAML change, the pipeline showed a parsing error:

```
/build/pipeline/my-pipeline.yml (Line: 10, Col: 19): Unexpected value ''
```

I researched this and found various discussions ([here][1], [here][2]) that show others have had the same or similar problem.

When I did the following, it worked, so at the very least `trigger.branches.include` is *not* an optional property and must be present if `trigger` is specified.

```yml
resources:
  pipelines:
    - pipeline: my_resource
      source: My Pipeline
      branch: master
      trigger:
        branches:
          include:
            - refs/heads/*
```

I prefer this be resolved by allowing these to be omitted, as the schema seems to indicate is permitted. Short of that, I'd be fine with the documentation not showing these as optional.

[1]: https://developercommunity.visualstudio.com/content/problem/587484/unexpected-value-trigger-using-resource-triggers-i.html
[2]: https://developercommunity.visualstudio.com/content/problem/954120/pipeline-trigger-unexpected-value-trigger.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#resources)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
