### ISSUE TITLE
Unclear on how to authenticate when using KubectlInstaller@0

### ISSUE THREAD

**Issue by BrunoZell** [MicrosoftDocs/azure-devops-docs#9487]
I want to run `kubectl apply --validate=true --dry-run=client -f=deployment.yaml` from an existing PowerShell script in my Azure DevOps pipeline. My job looks like this:

```yaml
- job:
  displayName: Verify Kubernetes configuration
  steps:
  - task: KubectlInstaller@0
  - task: PowerShell@2
    inputs:
      filePath: $(Build.SourcesDirectory)/verify-configuration.ps1
      failOnStderr: true
```

With fails on the command described above with the output:

```
##[error]mkdir: cannot create directory ‘/run/user/1001’: Permission denied
##[error]The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

I suspect that this is due to the newly installed kubectl not being connected to my cluster. I already have an existing Kubernetes Environment registered in Azure DevOps, but I only see examples of how to use it with the pipeline task `Kubernetes@1`, not when running kubectl from the command line via `KubectlInstaller@0`.

How do I authenticate kubectl with the cluster registred in Azure DevOps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efef7470-b172-c5f9-924a-f66ec84adc43
* Version Independent ID: 3c951d4f-51c5-ed67-8ee0-521770a4ae35
* Content: [Kubectl installer task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/kubectl-installer?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/tool/kubectl-installer.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/tool/kubectl-installer.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**
