### ISSUE TITLE
Use the OAuth token to access the REST API examples does not work as-is

### ISSUE THREAD

**Issue by CZEMacLeod** [MicrosoftDocs/azure-devops-docs#9488]
The example for `Use the OAuth token to access the REST API` does not work as-is

[Here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemaccesstoken) it mentions that you have to explicitly map in SYSTEM_ACCESSTOKEN to a task so I think the example needs to but updated to the following and a reference added.

```yaml
- task: PowerShell@2
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
   targetType: inline
   script: |
      $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/build/definitions/$($env:SYSTEM_DEFINITIONID)?api-version=5.0"
      Write-Host "URL: $url"
      $pipeline = Invoke-RestMethod -Uri $url -Headers @{
          Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
      }
      Write-Host "Pipeline = $($pipeline | ConvertTo-Json -Depth 100)"
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acfc2d3a-e665-f90d-bf3c-c2e81f0e72aa
* Version Independent ID: ea7dcfb7-cc63-43d6-939e-62b657b567d8
* Content: [Use PowerShell scripts to customize pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/powershell?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/scripts/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
