### ISSUE TITLE
Missing example for using multiple patterns

### ISSUE THREAD

**Issue by ThomasPiskol** [MicrosoftDocs/azure-devops-docs#9518]
Please provide an example how to use multiple patterns. 
You have added a [link to another page explaining the file matching pattern](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops), but even this page does not show how to use correctly multiple pattern.

This seems to work:
 ```yaml
- task: DownloadPipelineArtifact@2
    inputs:    
        patterns: |
            **/*.txt
            SomeOtherPattern/*.pdb
            A/Third/Pattern/**/*.dll
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**
