### ISSUE TITLE
Pipeline Trigger on Stage Completion needs more info

### ISSUE THREAD

**Issue by itsjusth** [MicrosoftDocs/azure-devops-docs#9551]
I am trying to trigger a pipeline on the completion of a stage:

```
resources:
  pipelines:
  - pipeline: MyPipelineResource
    source: 'My Pipeline'
    trigger:
      stages:
      - Release_To_Production
```

I am expecting this to trigger this pipeline anytime the Release_To_Production stage completes in 'My Pipeline'.  There is no other triggers block in my YAML.

The pipeline currently is triggering on other events in this repository that are not expected.  How can I make this work in the way I am expecting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-pipelines)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
