### ISSUE TITLE
Using custom docker image for Microsoft-hosted agents pool

### ISSUE THREAD

**Issue by matlion** [MicrosoftDocs/azure-devops-docs#9560]
In a pipeline without stages I can specify custom docker images:

```
resources:
  containers:
  - container: customUbuntu
    image: my.azurecr.io/my-agent:1
    endpoint: my_azure_registry
```

How can I specify custom images in my pool configuration when using stages?
I only find documentation on specifying given images.
E.g.

```
pool:
  vmImage: 'ubuntu-latest'

```

Specifying the container and referencing in the pool does not work:

```
resources:
  containers:
  - container: customUbuntu
    image: my.azurecr.io/my-agent:1
    endpoint: my_azure_registry

pool:
  vmImage: customUbuntu
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by matlion** [comment]
I've found the documentation here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops

So the solution is to specify container: inside the job spec:

```
resources:
  containers:
  - container: customUbuntu
    image: my.azurecr.io/my-agent:1
    endpoint: my_azure_registry

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: A
    container: customUbuntu
    steps:
    - bash: echo "A"
```
