### ISSUE TITLE
Conditions based on resources

### ISSUE THREAD

**Issue by Thibaultce** [MicrosoftDocs/azure-devops-docs#9579]
I have 2 Git repositories: one with the source code of the application, one for the DevOps pipelines.

For the second stage of the pipeline, I want to check if the branch that triggered the pipeline is master.
But the problem is the variable **Build.SourceBranchName** has the information of the DevOps repository, not the repository containing the source code (repository named _hidden_).

I don't see any variable that can be used for that purpose.
```
resources:
  repositories:
  - repository: 'hidden'
    type: git
    name: 'hidden/hidden'
    trigger:
    - master
    - develop

trigger: none

stages:
- stage: Build
  displayName: Build stage

  variables:
  - name: BuildConfiguration
    value: 'Release'
  - name: ApiSolution
    value: 'Company.WebApi.csproj'

  jobs:
  - job: BuildAPI
    displayName: 'Build API'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
    - checkout: hidden

    - script: dir $(Build.SourcesDirectory)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'env | sort'
[...] 

- stage: DeployDev
  displayName: 'Deploy dev stage'

  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))

  jobs:
  - deployment: DeployServiceApp
    displayName: 'Deploy system to the dev environment job'

    workspace:
      clean: all
      
    environment: 
      name: 'xyz'
      resourceType: 'VirtualMachine'

    strategy:
      runOnce:
        deploy:
          steps:
[...]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
