### ISSUE TITLE
stageDependencies syntax in 'Define Variables' incorrect

### ISSUE THREAD

**Issue by ian-craig** [MicrosoftDocs/azure-devops-docs#9622]
The [Use outputs in a different stage](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-stage) section describes the use of `stageDependencies` syntax for accessing output variables from another stage.

This syntax doesn't seem to work at all, and instead there is a different way of accessing other stage outputs.

**Documented format** (always undefined)
```yaml
stageDependencies.StageOne.JobA.outputs['StepA.MyVar']
```

**What actually works**
```yaml
dependencies.StageOne.outputs['JobA.StepA.MyVar']
# or 
stageDependencies.StageOne.outputs['JobA.StepA.MyVar']
```

Related to #8366

It would also be great if instead of calling stages, jobs and steps all "A", "B", "C" you used names like "StageA", "JobB" and "StepC" so that we don't need to constantly reference the rest of the file to be able to read it. ☺

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by chris-codeflow** [comment]
I tested this today and have confirmed that the _currently_ documented syntax is correct and that the proposed syntax didn't work.

The job evaluation for the first job in the second stage of the pipeline correctly evaluated and mapped the output variable from a job in the previous stage.

Snippet from pipeline:

```yaml
- stage: B
  dependsOn: A
  variables:
    semVer: $[ stageDependencies.A.CalculateVersion.outputs['Version.SemVer'] ]
  jobs:
  - job: UseVersion
    steps:
    - script: |
        echo "SemVer: $(semVer)"
```

Output from the Azure Pipelines run:

```text
Job preparation parameters
Variables:
  semVer:
    Parsing expression: <stageDependencies.A.CalculateVersion.outputs['Version.SemVer']>
    Evaluating: stageDependencies['A']['CalculateVersion']['outputs']['Version.SemVer']
    Result: '1.0.0-rc1'
```

**Comment by ian-craig** [comment]
I did a little more digging and it seems that the syntax which works depends on where you use it. 
- The _current_ syntax does not work in conditions, but does work in variables.
- The _proposed_ syntax works in conditions but not in variables. 

This is extremely confusing as a user.

Here's a much longer example which shows both.
```yml
trigger: none

stages:
- stage: StageA
  jobs:
  - job: JobA1
    steps:
    - checkout: none
    - script: echo "##vso[task.setvariable variable=Var;isOutput=true]X"
      name: StepA1

- stage: ConditionCurrentSyntax
  condition: and(succeeded(), eq(stageDependencies.StageA.JobA1.outputs['StepA1.Var'], 'X'))
  dependsOn: StageA
  jobs:
  - job:
    steps:
    - checkout: none
    - script: echo hello from Stage B

- stage: ConditionAlternateSyntax
  condition: and(succeeded(), eq(stageDependencies.StageA.outputs['JobA1.StepA1.Var'], 'X'))
  dependsOn: StageA
  jobs:
  - job:
    steps:
    - checkout: none
    - script: echo hello from Stage C

- stage: AlwaysRun
  dependsOn: StageA
  variables:
    CurrentVar: $[ stageDependencies.StageA.JobA1.outputs['StepA1.Var'] ]
    AlternateStageDepVar: $[ stageDependencies.StageA.outputs['JobA1.StepA1.Var'] ]
    AlternateDepVar: $[ dependencies.StageA.outputs['JobA1.StepA1.Var'] ]
  jobs:
  - job:
    steps:
    - checkout: none
    - script: |
        echo "Current: $(CurrentVar)"
        echo "AlternateStageDep: $(AlternateStageDepVar)"
        echo "AlternateDep: $(AlternateDep)"
```

Example run:
![image](https://user-images.githubusercontent.com/2031632/99620872-478e0b00-29db-11eb-923d-771a236aadf2.png)

Variables from the last stage:
```
Current: X
AlternateStageDep: 
AlternateDep:
```

**Comment by chris-codeflow** [comment]
Thanks @ian-craig for looking into this further.  I read the [dependencies](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies) documentation and tried different combinations in a pipeline and came to the following conclusions:
- for job to job _conditions_ and _variable mappings_, use syntax `dependencies.<jobName>.outputs['<stepName>.<variableName>']`
- for stage to stage _conditions_, use syntax `dependencies.<stageName>.outputs['<jobName>.<stepName>.<variableName>']`
- for stage to stage _variable mappings_, use syntax `stageDependencies.<stageName>.<jobName>.outputs['<stepName>.<variableName>']`

I completely agree with you that the syntax is confusing and what I found invalidates the following statement in [Stage to stage dependencies](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#stage-to-stage-dependencies) for the `dependencies` syntax:

> Use this form of dependencies to map in variables or check conditions at a stage level.

**Comment by cveld** [comment]
Then how can we map a stage result into a variable?
Neither stageDependencies.MyStage.result nor dependencies.MyStage.result seem to work.

**Comment by chris-codeflow** [comment]
You can use stage to stage variable mappings using the syntax `stageDependencies.<stageName>.<jobName>.outputs['<stepName>.<variableName>']` and ensure you refer to the dependency in the `dependsOn` array.

Example:

```yaml
stages:
- stage: A
  jobs:
  - job: J1
    steps:
    - script: |
        echo "##vso[task.setvariable variable=Test.Id;isOutput=true]0903760e-de41-493c-88a9-6467dc5f7c3f"
      name: SetID
      displayName: Set output 'Test.Id'

- stage: B
  dependsOn: A
  jobs:
  - job: J2
    variables:
      id: $[ stageDependencies.A.J1.outputs['SetID.Test.Id'] ]
    steps:
      - checkout: none
      - script: |
          echo "ID from S1: $(id)"
```

**Comment by cveld** [comment]
@chris-codeflow But how to work with the result of a stage? I understand how to reach out to output variables. But I still need to learn how to fetch the result of a stage.

The following variable mounts:
```
variables:
      Result1: $[stageDependencies.mystage.result]
      Result2: $[stageDependencies.mystage.myjob.result]
      Result3: $[dependencies.mystage.result]
```

yield:
```
<null>   # expected: Succeeded
Succeeded
<null>   # expected: Succeeded
```

**Comment by chris-codeflow** [comment]
@cveld .  I did some testing and concluded that you CANNOT map stage results to variables, but you can map job results to variables, as follows:

```yaml
- stage: s2
  # You can use a dependent stage's result in a condition.
  condition: in(dependencies.s1.result, 'Succeeded', 'SucceededWithIssues')
  dependsOn: s1
  jobs:
    - job: Test
      variables:
        lastResult: $[ stageDependencies.s1.j1.result ]
      steps:
        - script: |
            echo "Last job result: $(lastResult)"
```

This seems logical as you would naturally use _conditions_ for checking the result of a previous stage. I can't see an obvious use case for mapping a stage result to a variable.
