### ISSUE TITLE
How to push *.symbols.nupkg

### ISSUE THREAD

**Issue by LukePammant** [MicrosoftDocs/azure-devops-docs#9628]
I'm trying to publish the symbols for my nuget package but I don't see how to do so. The docs state: 

'To publish symbols for NuGet packages, include the preceding task in the build pipeline that produces the NuGet packages. Then the symbols will be available to all users in the Azure DevOps organization.'

But there is no 'preceding task'.

In the build pipeline I am running `dotnet pack` followed by `dotnet push` but get the follow errors:

``` sh
nuget push /home/vsts/work/1/a/MyPackage.1.0.20311.1.nupkg
nuget push /home/vsts/work/1/a/MyPackage.1.0.20311.1.symbols.nupkg
error: Response status code does not indicate success: 409 (Conflict - The feed already contains 'MyPackage 1.0.20311.1'.
```

I'm looking to the documentation to help me figure out where to push the symbols.nupkg. 

Here is my current pipeline:

``` yml
 - task: DotNetCoreCLI@2
      displayName: dotnet pack
      inputs:
          command: pack
          packagesToPack: *.csproj
          includesymbols: true
          includesource: true

    - task: DotNetCoreCLI@2
      displayName: dotnet push
      inputs:
        command: push
        searchPatternPush: $(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.Tests.nupkg
        feedPublish: MyVSTS
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb2bfcb-0a0c-ce90-fa49-ad2e7fbaa57a
* Version Independent ID: 1a295877-ff8f-f8c2-0349-76a69a0f5cfc
* Content: [Publish symbols for debugging - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**
