### ISSUE TITLE
Incorrect code sample for yaml branch & path filters

### ISSUE THREAD

**Issue by JimBlizzard** [MicrosoftDocs/azure-devops-docs#9656]
The indentation in this example code is incorrect:  

```
trigger:
  branches:
    include:
    - master
    - releases/*
    - feature/*
    exclude:
    - releases/old*
    - feature/*-working
  paths:
    include:
    - '*' # same as '/' for the repository root
    exclude:
    - 'docs/*' # same as 'docs/'
```

It should be: 
```
trigger:
  branches:
    include:
      - master
      - releases/*
      - feature/*
    exclude:
      - releases/old*
      - feature/*-working
  paths:
    include:
      - '*' # same as '/' for the repository root
    exclude:
      - 'docs/*' # same as 'docs/'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
