### ISSUE TITLE
List contents in GitHub repository instead of Main repository

### ISSUE THREAD

**Issue by lipalath-ms** [MicrosoftDocs/azure-devops-docs#9672]
I have yaml file in Main repository with the following content: 
```
 resources: 

  repositories:
  - repository: test-build
    type: github
    endpoint: GithubTest
    name: lipalath-ms/test-build
    ref: master
 
stages:

- template: build-services.yml@test-build
```
1st step in build-services.yml is to list contents of directory in GitHub repository:- 

```
-  script: dir
   workingDirectory:
   displayName: Contents within dir
```

On running the build, I see the contents in my main repository:

```
Directory of D:\a\1\s 
 
11/13/2020 06:43 PM <DIR> . 

11/13/2020 06:43 PM <DIR> .. 

11/13/2020 06:43 PM 2,581 .gitattributes 

11/13/2020 06:43 PM 3,032 .gitignore 

11/13/2020 06:43 PM 119 README 

11/13/2020 06:43 PM 995 vsts-cicd.yml
```
How can I update this step to list the contents in GitHub repository?

Please let me know. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
