### ISSUE TITLE
UseDotNet path issue

### ISSUE THREAD

**Issue by mikeblakeuk** [MicrosoftDocs/azure-devops-docs#9690]
Given we are using Microsoft Agents:
    ubuntu:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

When we want to ensure an SDK exists we use the following YAML

```yaml
- powershell: dotnet --info
  displayName: 'dotnet info before'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 3.1 (again)'
  inputs:
    version: 3.1.x

- powershell: dotnet --info
  displayName: 'dotnet info tools path'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 5.0 (until Dec2020)'
  inputs:
    version: 5.0.x

- powershell: dotnet --info
  displayName: 'dotnet info after'
```

But some agents already have .net 3.1 already install so, on windows-latest, wastes upto 2 minutes installing it again

before (note the path)
![image](https://user-images.githubusercontent.com/1986660/99451003-780d7080-2919-11eb-8ef4-ef6e7b179ac4.png)

after:
![image](https://user-images.githubusercontent.com/1986660/99451026-80fe4200-2919-11eb-95e1-53772c2cb839.png)

Q. How can we ensure the SDKs are installed and only if install them they are missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [Use .NET Core task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by vtbassmatt** [comment]
None of the tool installer tasks are really designed for this use case. Though, I can see why you'd want it. The best workaround I can think of would involve using a script to test the currently-installed .NET Core version, set a variable to "true" or "false" depending on whether you want to execute a change of version, then use that variable as a condition in the `UseDotNet` task.

Roughly:

```yaml
steps:
- script: |
    (check .NET version, only run the next line if it's not 3.1.x)
    echo "##vso[task.setVariable variable=updateNetVersion]true"
- task: UseDotNet@2
  condition: eq(variables.updateNetVersion, true)
  inputs:
    version: 3.1.x
```

To request a change, you can file a feature request through our support web site: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
