### ISSUE TITLE
Variables in Variable Group not accessible when declared at stage level

### ISSUE THREAD

**Issue by obeyda** [MicrosoftDocs/azure-devops-docs#9729]
I have defined a variable group and set permissions to all pipelines,
And I updated my pipeline to something like this: 

```
- stage: DeployStage
    displayName: Deploy
    dependsOn:
      - SetupStage
      - BuildStage
    variables:
      - group: Dev
     jobs:
      - deployment: DeployAzureFunctions
        strategy:
          runOnce:
            deploy:
              steps:
<...>
                - task: AzureFunctionApp@1
                  displayName: "Deploy Function App"
                  inputs:
                    azureSubscription: $(azureSubscription)
<...> 
```
I have the variable `azureSubscription` defined in the variable group, but I get this error

```
There was a resource authorization issue: "The pipeline is not valid. Job DeployAzureFunctions: Step input azureSubscription references service connection $(azureSubscription) which could not be found. 
The service connection does not exist or has not been authorized for use. For authorization details, 
refer to https://aka.ms/yamlauthz.

```

However, when I add the variable group at the root level of my pipeline (before `Stages`) everything works fine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#expansion-of-variables)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
