### ISSUE TITLE
Explain what is inside resources.repositories context

### ISSUE THREAD

**Issue by kmadof** [MicrosoftDocs/azure-devops-docs#9768]
This is somehow related to [Getting ref of non-self repo causes exception](https://github.com/MicrosoftDocs/azure-devops-docs/pull/9758) but it touches the issue from broader context. It would be good if someone explain what information and how can we get from  `resources.repositories` context as the example given in docs produces error on validatin pipeline.

**Comment by kmadof** [comment]
@msebolt I just wonder if there is a chance to reach someone who may help with this. I'm keen to write documentation, however there is no public knowledge about this areas. I was trying to figure out what is avialable in this context, but

```yaml
- script: env | sort
```

gave me nothing. Ideally it would be to get info like [this regarding dependencies](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies):

```json
"dependencies": {
  "<STAGE_NAME>" : {
    "result": "Succeeded|SucceededWithIssues|Skipped|Failed|Canceled",
    "outputs": {
        "jobName.stepName.variableName": "value"
    }
  },
  "...": {
    // another stage
  }
}
```

**Comment by steved0x** [comment]
@kmadof I am looking into this (and also your related PR) - I was able to successfully run the example, here is my sample pipeline that worked. I am reading the ref from:

* An Azure Repos git repository in the same project
* An Azure Repos git repo in a different project in the same org
* An Azure Repos Git in a different org (using a service connection)
* A GitHub repo using a service connection

Looking at my sample pipeline, I can't see anything different than what you have, can you spot a difference? That might help us to figure out why it is failing for you.

```
resources:
  repositories:
  - repository: dotnettools # In a different organization
    endpoint: contoso-ltd3
    type: git
    name: MyFirstProject/contoso-demo
    trigger:
    - '*'
  - repository: ff
    type: git
    name: FabrikamFiber/FabrikamFiber # same project
    trigger:
    - '*'
  - repository: FabrikamRepoAccessTest
    type: git
    name: FabrikamRepoAccessTest/FabrikamRepoAccessTest # different project same org
    trigger:
    - '*'

  - repository: pipelines-xamarin
    endpoint: github.com-xamarin-pipelines
    type: github
    name: MicrosoftDocs/pipelines-xamarin

variables:
  ff.ref: $[ resources.repositories['ff'].ref ]
  dt.ref: $[ resources.repositories['dotnettools'].ref ]
  px.ref: $[ resources.repositories['pipelines-xamarin'].ref ]
  fr.ref: $[ resources.repositories['FabrikamRepoAccessTest/FabrikamRepoAccessTest']. ref]
  isMain: $[eq(resources.repositories['FabrikamRepoAccessTest/FabrikamRepoAccessTest'].ref, 'refs/heads/master')]


# run!!
trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: dotnettools
- checkout: FabrikamRepoAccessTest
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- bash: | 
    echo "FF version: $FF_REF"

- bash: |
    echo "DT version: $PX_REF"

- bash: |
    echo "PX version: $DT_REF"

- bash: | 
    echo "FR version: $FR_REF"

- bash: |
    echo "IsMain: $ISMAIN"
```
