### ISSUE TITLE
expressions in $[ ] reqire spacing, some example don't have it

### ISSUE THREAD

**Issue by dave-yotta** [MicrosoftDocs/azure-devops-docs#9782]
There are examples like `myVar:$[eq(1,2)]` on this page.

However, the expression I have written:
```
$[replace(variables['System.CollectionUri'],'https://dev','https://pkgs.dev')]
```
is not evaluated unless it is written with spaces like this: 
```
$[ replace(variables['System.CollectionUri'],'https://dev','https://pkgs.dev') ]
```

This is probabbly true across the board for compile and runtime expressions and all functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vtbassmatt** [comment]
I feel like I've seen this before, but I can't repro it. If you see it again, please file a bug with the specifics here: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

My example:

```yaml
pool:
  vmImage: 'ubuntu-20.04'

variables:
  PKG_URL: $[replace(variables['System.CollectionUri'],'https://dev','https://pkgs.dev')]
  PKG_URL2: $[ replace(variables['System.CollectionUri'],'https://dev','https://pkgs.dev') ]

steps:
- checkout: none
- script: |
    echo $PKG_URL
    echo $PKG_URL2
```

Result:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/714283/102236700-cdf61980-3ec1-11eb-9e05-2d7158260f6d.png">
