### ISSUE TITLE
PR trigger configuration doesn't  work as expected

### ISSUE THREAD

**Issue by JavidSalmanov** [MicrosoftDocs/azure-devops-docs#9864]
Hi,
Pipeline configured as bellow:

```
pr:
  branches:
    include:
    - master
  drafts: false
  paths:
    include:
    - terraform
```
Repo location: Github
Connection to Github: azurepipeline app
If push branch to the remote repo, it automatically starts the pipeline without even being part of any PR.
The pipeline was created based on information from the official documentation:
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers
