### ISSUE TITLE
Resource repository - trigger doesn't work

### ISSUE THREAD

**Issue by roofiq** [MicrosoftDocs/azure-devops-docs#9893]
Hello,

I'm having issues with setting up automatic resources repository trigger.
After each commit to repoA, I want my pipeline in other repository to trigger, but somehow it doesn't want to start.

repoA is in the same project as the one, that I'm configuring pipeline.
Here is simple example of my YAML:
```
resources:
  repositories:
  - repository: repoA
    type: git
    name: repoA
    trigger:
    - branchName # tested 'refs/heads/branchName' as well or '*'
```
Can there be any other things that determine, that it's not working correctly?

Edit: Does the reason might be that my organization is in 'old' DevOps website? We are using {orgName}.visualstudio.com

Thanks,
Rafal
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by roofiq** [comment]
Hey, so to give a small update. I have opened similar issue here on [developercommunity.visualstudio.com](https://developercommunity.visualstudio.com/content/problem/1297955/unable-to-trigger-pipeline-by-specifyng-resources.html).

I have tried placing my yaml templates in default branch of the repository and it worked as expected.
There is for sure some issue with this functionality as it should work regardless this setting.

**Comment by DavidFeldhoff** [comment]
I have the same issue and I tested it with two new repositories which only have one branch (so that default and compare branch are always the "main" branch). But I also wasn't able to get it running as well.. Any update in the meantime?

**Comment by DavidFeldhoff** [comment]
Based on the https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#triggers
article I tried as well this syntax: Again without success. The trigger for testdfe (=self) works, but testdfe2 triggers nothing. And as I said it has nothing to do with the compare branch in my case as "testdfe" and "testdfe2" just have one branch each. Repository "testdfe" consists of the files "readme.md" and "azure-pipelines.yml" while repository "testdfe2" consists only of the "readme.md"  file.

```
resources:
  repositories:
  - repository: testdfe2
    type: git
    name: Development/testdfe2
    ref: main
    trigger:
    - main
  - repository: self
    type: git
    name: Development/testdfe
    trigger:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
```

**Comment by inuvano-labs** [comment]
I too am experiencing the issue in my ADO org - based on the docs the following yml should work:

```yml
resources:
  repositories:
  - repository: Y
    type: git
    name: Company/Y
    trigger: 
     - main
  - repository: Z
    type: git
    name: Company/Z
    trigger: 
     - main


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script
```

Repo's Y and Z are newly created, contain just application code - the yml template above is in Repo X associated to a pipeline in ADO. Commits to either Y or Z do not trigger a build.

Looking online, it appears this feature has been in development for some time. But difficult to determine whether it is GA - the docs suggest so, but there are alot of posts suggesting otherwise.

It would be good if someone from MS can confirm whether this is a bug or whether it hasn't been rolled out. If it's not GA then it should be highlighted in the docs as such.
