### ISSUE TITLE
Example not working for variable name with dot

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#9925]
Using this example:

```
jobs:
# Set an output variable from job A
- job: A
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the value"
    name: setvarStep
  - script: echo $(setvarStep.myOutputVar)
    name: echovar

# Map the variable into job B
- job: B
  dependsOn: A
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    myVarFromJobA: $[ dependencies.A.outputs['setvarStep.myOutputVar'] ]  # map in the variable
                                                                          # remember, expressions require single quotes
  steps:
  - script: echo $(myVarFromJobA)
    name: echovar
```

Note that, the output variable in the example given is `myOutputVar` which doesn't contain any dot.
My output variable is named `DetectMergedPullRequest.IsMergedPr` so it does contain a dot.
I can use this output variable within the same job.
However the example doesn't seem to work (i.e using it from another job) for my variable name that contains a "."
For example this combination not work:

"##vso[task.setvariable variable=DetectMergedPullRequest.IsMergedPr;isOutput=true]True"
and
$[ dependencies.A.outputs['A.setvarStep.DetectMergedPullRequest.IsMergedPr'] ]

How should I deal with this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**
