### ISSUE TITLE
Continuous deployment triggers clarification

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#9935]
The doc reads:

> Continuous deployment triggers allow you to create a release every time a new build artifact is available.

Suppose a build pipeline has a step to publish an artifact:

```
  - task: PublishBuildArtifacts@1
    displayName: Upload build artifact
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'info'
```

Then suppose after this step, the build pipeline fails on another step.

The overall result of the build pipeline was that it failed, but it failed after the build asset was published.

Suppose you have a classic release pipeline with a Continuous deployment trigger for that build asset.

Does the trigger still fire? Based on the docs I am guessing that it should still fire, because the asset was published, even though the build pipeline failed - it doesn't matter? Or does it matter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70217fc0-8411-04b1-d448-d013398c5ac8
* Version Independent ID: ed92b98e-2d6f-8dfb-9319-85c825b2cb30
* Content: [Classic release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**
