### ISSUE TITLE
How to reference a VM in an Environment?

### ISSUE THREAD

**Issue by sandersaares** [MicrosoftDocs/azure-devops-docs#9956]
The page on registering VMs into Environments speaks about the registration but nowhere do I see any examples of how my commands being run against my environment are supposed to reference the "current" VM they are supposed to run against. This sounds like some vital missing information.

If I register N virtual machines in an Environment, I expect to be able to reference them in my steps. In fact, I expect to be able to execute my steps on those virtual machines. At the moment, how to do this and whether this is even possible remains unclear.

The feature is very vaguely described, so it is possible I misunderstand how it is meant to be used and what I say above makes no sense. In that case, the feature should be described more clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@sandersaares  I'm working on an update to this article now. You don't reference the virtual machines directly and instead reference the environment. The exception to this is that if you want to target a specific VM, you can tag that VM with a specific tag and reference the tag. Here's an example where I am only running code on the VM associated with an environment that has a `windows` tag. 

```yaml
trigger: 
- master

pool: 
   vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: ContosoDeploy
    resourceType: VirtualMachine
    tags: windows # only deploy to virtual machines with this tag
  strategy:
   runOnce:
     deploy:   
      steps:
        - script: echo "Hello world"
```
